// AUTO-GENERATED by pzo_curriculum_gateway_generator.py — DO NOT EDIT MANUALLY
            import { Router, Request, Response, NextFunction } from 'express';
            import { requireAuth, requireInstitutionAccess, requireScope, requireFacilitatorOrAdmin } from '../../middleware/auth';
            import { validateBody } from '../../middleware/validation';
            import { rateLimit } from '../../middleware/security';
            import { withTimeout } from '../../middleware/resilience';
            import { withBackpressure } from '../../middleware/resilience';
            import { ok, created, fail } from '../../middleware/errors';
            import { emitAudit, CurriculumAuditEvent } from '../../middleware/audit';
            import { requireFlag } from '../../middleware/feature_flags';

            const router = Router();
            router.use(requireFlag('curriculum.exports.enabled'));

            // Exports routes
            router.get('/',
              requireAuth, requireInstitutionAccess,
              rateLimit('read'),
              async (req: Request, res: Response, next: NextFunction) => {
                try {
                  const ctx = req.tenantContext!;
                  // Adapter call would go here — list exports
                  res.json(ok(req, [], { page: 1, pageSize: 20, total: 0, hasMore: false }));
                } catch (err) {
                  next(err);
                }
              },
            );

            router.post('/',
  requireAuth, requireInstitutionAccess,
  requireScope('curriculum:exports:write'),
  rateLimit('write'),
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const ctx = req.tenantContext!;
      // Adapter call would go here — create exports
      res.status(201).json(created(req, { id: crypto.randomUUID() }));
    } catch (err) {
      next(err);
    }
  },
);

            router.get('/:id',
              requireAuth, requireInstitutionAccess,
              rateLimit('read'),
              async (req: Request, res: Response, next: NextFunction) => {
                try {
                  const ctx = req.tenantContext!;
                  // Adapter call would go here — get exports by id
                  res.status(404).json(fail(req, 'NOT_FOUND', 'Exports not found'));
                } catch (err) {
                  next(err);
                }
              },
            );

            export { router as exportsRouter };
