/*
 * POINT ZERO ONE — BACKEND ENGINE 15X GENERATOR
 * Generated at: 2026-03-10T01:00:08.825776+00:00
 *
 * Doctrine:
 * - backend becomes the authoritative simulation surface
 * - seven engines remain distinct
 * - mode-native rules are enforced at runtime
 * - cards are backend-validated, not UI-trusted
 * - proof / integrity / CORD remain backend-owned
 */

import type { CardDefinition } from '../core/GamePrimitives';

export class CardRegistry {
  private readonly cards = new Map<string, CardDefinition>();

  public constructor() {
    for (const card of this.seed()) {
      this.cards.set(card.id, card);
    }
  }

  public get(id: string): CardDefinition | undefined {
    return this.cards.get(id);
  }

  public require(id: string): CardDefinition {
    const card = this.cards.get(id);
    if (!card) {
      throw new Error(`Unknown card definition: ${id}`);
    }
    return card;
  }

  public all(): CardDefinition[] {
    return [...this.cards.values()];
  }

  private seed(): CardDefinition[] {
    return [
      {
        id: 'NETWORK_CALL',
        name: 'Network Call',
        deckType: 'PRIVILEGED',
        baseCost: 2000,
        baseEffect: { cashDelta: 0, incomeDelta: 350, heatDelta: 2 },
        tags: ['liquidity', 'scale', 'heat', 'income'],
        timingClass: ['PRE', 'ANY'],
        rarity: 'RARE',
        autoResolve: false,
        counterability: 'SOFT',
        targeting: 'SELF',
        decisionTimerOverrideMs: null,
        decayTicks: 6,
        modeLegal: ['solo', 'pvp', 'coop', 'ghost'],
        modeOverlay: {
          solo: { costModifier: 1.0, effectModifier: 1.0, legal: true },
          pvp: { costModifier: 1.0, effectModifier: 0.8, legal: true },
          coop: { costModifier: 0.9, effectModifier: 1.1, legal: true },
          ghost: { costModifier: 1.1, effectModifier: 0.9, legal: true },
        },
        educationalTag: 'Your network is your net worth',
      },
      {
        id: 'MOMENTUM_PIVOT',
        name: 'Momentum Pivot',
        deckType: 'OPPORTUNITY',
        baseCost: 0,
        baseEffect: { incomeDelta: 450, cashDelta: 8000 },
        tags: ['income', 'liquidity', 'scale'],
        timingClass: ['PHZ'],
        rarity: 'LEGENDARY',
        autoResolve: false,
        counterability: 'NONE',
        targeting: 'SELF',
        decisionTimerOverrideMs: 5000,
        decayTicks: 5,
        modeLegal: ['solo'],
        educationalTag: 'Strategy must declare itself at the phase boundary',
      },
      {
        id: 'FORTIFY_ORDER',
        name: 'Fortify Order',
        deckType: 'SO',
        baseCost: 6000,
        baseEffect: { shieldDelta: 15 },
        tags: ['resilience', 'tempo'],
        timingClass: ['PHZ'],
        rarity: 'RARE',
        autoResolve: false,
        counterability: 'NONE',
        targeting: 'SELF',
        decisionTimerOverrideMs: 5000,
        decayTicks: 5,
        modeLegal: ['solo'],
        educationalTag: 'Fortification costs capital and timing',
      },
      {
        id: 'LAST_STAND_PROTOCOL',
        name: 'Last Stand Protocol',
        deckType: 'SO',
        baseCost: 0,
        baseEffect: { cashDelta: 3000, heatDelta: -5 },
        tags: ['liquidity', 'resilience', 'tempo'],
        timingClass: ['PHZ', 'PSK'],
        rarity: 'LEGENDARY',
        autoResolve: true,
        counterability: 'NONE',
        targeting: 'SELF',
        decisionTimerOverrideMs: null,
        decayTicks: 5,
        modeLegal: ['solo'],
        educationalTag: 'The comeback window is real but narrow',
      },
      {
        id: 'CHAIN_RUMOR',
        name: 'Chain Rumor',
        deckType: 'SABOTAGE',
        baseCost: 15,
        baseEffect: { incomeDelta: -250 },
        tags: ['sabotage', 'tempo', 'momentum'],
        timingClass: ['POST', 'ANY'],
        rarity: 'COMMON',
        autoResolve: false,
        counterability: 'SOFT',
        targeting: 'OPPONENT',
        decisionTimerOverrideMs: null,
        decayTicks: 4,
        modeLegal: ['pvp'],
        educationalTag: 'Pressure compounds through repeated low-cost attacks',
      },
      {
        id: 'MEDIA_BLITZ',
        name: 'Media Blitz',
        deckType: 'SABOTAGE',
        baseCost: 35,
        baseEffect: { heatDelta: 3 },
        tags: ['sabotage', 'tempo', 'variance'],
        timingClass: ['ANY'],
        rarity: 'RARE',
        autoResolve: false,
        counterability: 'SOFT',
        targeting: 'OPPONENT',
        decisionTimerOverrideMs: null,
        decayTicks: 3,
        modeLegal: ['pvp'],
        educationalTag: 'Groundwork multiplies the attack that follows',
      },
      {
        id: 'REGULATORY_FILING',
        name: 'Regulatory Filing',
        deckType: 'SABOTAGE',
        baseCost: 35,
        baseEffect: { heatDelta: 5 },
        tags: ['sabotage', 'tempo', 'cascade'],
        timingClass: ['PRE', 'ANY'],
        rarity: 'RARE',
        autoResolve: false,
        counterability: 'SOFT',
        targeting: 'OPPONENT',
        decisionTimerOverrideMs: null,
        decayTicks: 4,
        modeLegal: ['pvp'],
        educationalTag: 'Administrative friction is economic warfare',
      },
      {
        id: 'HOSTILE_TAKEOVER',
        name: 'Hostile Takeover',
        deckType: 'SABOTAGE',
        baseCost: 60,
        baseEffect: { incomeDelta: -500, heatDelta: 4 },
        tags: ['sabotage', 'tempo', 'variance', 'heat'],
        timingClass: ['PRE', 'PSK'],
        rarity: 'LEGENDARY',
        autoResolve: false,
        counterability: 'HARD',
        targeting: 'OPPONENT',
        decisionTimerOverrideMs: 3000,
        decayTicks: 2,
        modeLegal: ['pvp'],
        educationalTag: 'Visible pressure is part of the attack',
      },
      {
        id: 'BREAK_PACT',
        name: 'Break Pact',
        deckType: 'TRUST',
        baseCost: 0,
        baseEffect: { trustDelta: -5 },
        tags: ['trust', 'tempo'],
        timingClass: ['ANY'],
        rarity: 'UNCOMMON',
        autoResolve: false,
        counterability: 'NONE',
        targeting: 'SELF',
        decisionTimerOverrideMs: null,
        decayTicks: 6,
        modeLegal: ['coop'],
        educationalTag: 'Defection begins before the public break',
      },
      {
        id: 'SILENT_EXIT',
        name: 'Silent Exit',
        deckType: 'TRUST',
        baseCost: 0,
        baseEffect: { trustDelta: -10 },
        tags: ['trust', 'tempo'],
        timingClass: ['ANY'],
        rarity: 'UNCOMMON',
        autoResolve: false,
        counterability: 'NONE',
        targeting: 'SELF',
        decisionTimerOverrideMs: null,
        decayTicks: 6,
        modeLegal: ['coop'],
        educationalTag: 'Defection becomes measurable before it becomes visible',
      },
      {
        id: 'ASSET_SEIZURE',
        name: 'Asset Seizure',
        deckType: 'TRUST',
        baseCost: 0,
        baseEffect: { trustDelta: -20, cashDelta: 0 },
        tags: ['trust', 'tempo', 'liquidity'],
        timingClass: ['ANY'],
        rarity: 'LEGENDARY',
        autoResolve: false,
        counterability: 'HARD',
        targeting: 'SELF',
        decisionTimerOverrideMs: null,
        decayTicks: 2,
        modeLegal: ['coop'],
        educationalTag: 'Betrayal has a sequence and a cost',
      },
      {
        id: 'MARKER_EXPLOIT',
        name: 'Marker Exploit',
        deckType: 'GHOST',
        baseCost: 0,
        baseEffect: { shieldDelta: 12, divergenceDelta: 0.06 },
        tags: ['divergence', 'precision', 'resilience'],
        timingClass: ['GBM'],
        rarity: 'RARE',
        autoResolve: false,
        counterability: 'NONE',
        targeting: 'SELF',
        decisionTimerOverrideMs: 4000,
        decayTicks: 3,
        modeLegal: ['ghost'],
        educationalTag: 'Exploit the record where excellence cracked',
      },
      {
        id: 'COUNTER_LEGEND_LINE',
        name: 'Counter-Legend Line',
        deckType: 'GHOST',
        baseCost: 3000,
        baseEffect: { incomeDelta: 400, divergenceDelta: 0.08 },
        tags: ['divergence', 'precision', 'variance', 'income'],
        timingClass: ['GBM', 'PRE'],
        rarity: 'LEGENDARY',
        autoResolve: false,
        counterability: 'NONE',
        targeting: 'SELF',
        decisionTimerOverrideMs: null,
        decayTicks: 3,
        modeLegal: ['ghost'],
        educationalTag: 'The ghost cannot adapt. You can.',
      },
      {
        id: 'GHOST_PASS_EXPLOIT',
        name: 'Ghost Pass Exploit',
        deckType: 'GHOST',
        baseCost: 0,
        baseEffect: { incomeDelta: 150, divergenceDelta: 0.04 },
        tags: ['divergence', 'precision', 'income'],
        timingClass: ['GBM'],
        rarity: 'RARE',
        autoResolve: false,
        counterability: 'NONE',
        targeting: 'SELF',
        decisionTimerOverrideMs: null,
        decayTicks: 2,
        modeLegal: ['ghost'],
        educationalTag: 'You possess the record. Use it.',
      },
      {
        id: 'VARIANCE_LOCK',
        name: 'Variance Lock',
        deckType: 'DISCIPLINE',
        baseCost: 1500,
        baseEffect: { shieldDelta: 4 },
        tags: ['precision', 'resilience', 'variance'],
        timingClass: ['PRE', 'ANY'],
        rarity: 'UNCOMMON',
        autoResolve: false,
        counterability: 'NONE',
        targeting: 'SELF',
        decisionTimerOverrideMs: null,
        decayTicks: 8,
        modeLegal: ['solo', 'ghost'],
        educationalTag: 'Stability has a price',
      },
      {
        id: 'IRON_DISCIPLINE',
        name: 'Iron Discipline',
        deckType: 'DISCIPLINE',
        baseCost: 5000,
        baseEffect: { shieldDelta: 8 },
        tags: ['precision', 'resilience', 'variance'],
        timingClass: ['ANY'],
        rarity: 'LEGENDARY',
        autoResolve: false,
        counterability: 'NONE',
        targeting: 'SELF',
        decisionTimerOverrideMs: null,
        decayTicks: null,
        modeLegal: ['solo', 'ghost'],
        educationalTag: 'Eliminate the worst outcome before chasing the best',
      },
      {
        id: 'SOVEREIGN_LEVERAGE',
        name: 'Sovereign Leverage',
        deckType: 'PRIVILEGED',
        baseCost: 0,
        baseEffect: { cashDelta: 6000, incomeDelta: 500 },
        tags: ['scale', 'liquidity', 'income'],
        timingClass: ['ANY'],
        rarity: 'LEGENDARY',
        autoResolve: false,
        counterability: 'NONE',
        targeting: 'SELF',
        decisionTimerOverrideMs: null,
        decayTicks: 2,
        modeLegal: ['solo', 'pvp', 'coop', 'ghost'],
        educationalTag: 'Leverage is a tool, not a trait',
      },
      {
        id: 'SYSTEMIC_OVERRIDE',
        name: 'Systemic Override',
        deckType: 'PRIVILEGED',
        baseCost: 0,
        baseEffect: { heatDelta: -50 },
        tags: ['resilience', 'heat'],
        timingClass: ['ANY'],
        rarity: 'LEGENDARY',
        autoResolve: false,
        counterability: 'NONE',
        targeting: 'GLOBAL',
        decisionTimerOverrideMs: null,
        decayTicks: 1,
        modeLegal: ['solo', 'pvp', 'coop', 'ghost'],
        educationalTag: 'A reset is not free, but it changes everything',
      },
      {
        id: 'CASCADE_BREAK',
        name: 'Cascade Break',
        deckType: 'SO',
        baseCost: 0,
        baseEffect: { cashDelta: 0 },
        tags: ['resilience', 'cascade'],
        timingClass: ['CAS', 'ANY'],
        rarity: 'LEGENDARY',
        autoResolve: false,
        counterability: 'NONE',
        targeting: 'SELF',
        decisionTimerOverrideMs: null,
        decayTicks: 2,
        modeLegal: ['solo', 'pvp', 'coop', 'ghost'],
        educationalTag: 'Breaking the chain changes the future, not the past',
      },
      {
        id: 'TIME_DEBT_PAID',
        name: 'Time Debt Paid',
        deckType: 'PRIVILEGED',
        baseCost: 0,
        baseEffect: { timeDeltaMs: 90000 },
        tags: ['tempo', 'resilience'],
        timingClass: ['END', 'ANY'],
        rarity: 'LEGENDARY',
        autoResolve: false,
        counterability: 'NONE',
        targeting: 'SELF',
        decisionTimerOverrideMs: null,
        decayTicks: 1,
        modeLegal: ['solo', 'pvp', 'coop', 'ghost'],
        educationalTag: 'Buying time is sometimes the trade',
      },
    ];
  }
}
