// AUTO-GENERATED by pzo_curriculum_gateway_generator.py — DO NOT EDIT MANUALLY
import { Job } from 'bullmq';
import { createWorker } from './index';
import { emit } from '../../api-gateway/middleware/observability/logger';

async function processReportGeneration(job: Job): Promise<void> {
  const startTime = Date.now();
  const jobData = job.data as Record<string, unknown>;

  emit({
    timestamp: new Date().toISOString(),
    level: 'info',
    message: `Processing ${job.name} job ${job.id}`,
    requestId: (jobData.requestId as string) || job.id || 'unknown',
    method: 'QUEUE',
    path: 'curriculum:report-generation',
    tenantId: (jobData.institutionId as string) || null,
  });

  try {
    // Process the job based on its type
    switch (job.name) {
      default:
        emit({
          timestamp: new Date().toISOString(),
          level: 'info',
          message: `Completed ${job.name} job ${job.id} in ${Date.now() - startTime}ms`,
          requestId: (jobData.requestId as string) || job.id || 'unknown',
          method: 'QUEUE',
          path: 'curriculum:report-generation',
          durationMs: Date.now() - startTime,
        });
        break;
    }
  } catch (err) {
    emit({
      timestamp: new Date().toISOString(),
      level: 'error',
      message: `Failed ${job.name} job ${job.id}: ${(err as Error).message}`,
      requestId: (jobData.requestId as string) || job.id || 'unknown',
      method: 'QUEUE',
      path: 'curriculum:report-generation',
      error: (err as Error).message,
      stack: (err as Error).stack,
    });
    throw err;
  }
}

export function startReportGenerationWorker(): void {
  const worker = createWorker('curriculum:report-generation', processReportGeneration as never, 3);

  worker.on('failed', (job, err) => {
    emit({
      timestamp: new Date().toISOString(),
      level: 'error',
      message: `Job ${job?.id} failed permanently: ${err.message}`,
      requestId: 'worker',
      method: 'QUEUE',
      path: 'curriculum:report-generation',
    });
  });
}
