// pzo-web/src/engines/cards/CardRegistry.ts
// POINT ZERO ONE — CARD REGISTRY v2 (Phase 3 Complete)
// 122 cards across 19 families · Density6 LLC · Confidential

import {
  BaseDeckType, ModeDeckType, type DeckType,
  CardRarity, TimingClass, CardEffectType, CardTag, Targeting, GameMode,
  DefectionStep, LegendMarkerType,
  type CardDefinition, LEGENDARY_DROP_WEIGHT,
} from './types';

const ALL_MODES: GameMode[] = [GameMode.GO_ALONE, GameMode.HEAD_TO_HEAD, GameMode.TEAM_UP, GameMode.CHASE_A_LEGEND];
const PREDATOR:  GameMode[] = [GameMode.HEAD_TO_HEAD];
const SYNDICATE: GameMode[] = [GameMode.TEAM_UP];
const PHANTOM:   GameMode[] = [GameMode.CHASE_A_LEGEND];
const EMPIRE:    GameMode[] = [GameMode.GO_ALONE];
const LDW = LEGENDARY_DROP_WEIGHT;

// ─── OPPORTUNITY (9) ──────────────────────────────────────────────────────────
const OPPORTUNITY_CARDS: CardDefinition[] = [
  { cardId:'opp_rental_001', name:'Rental Property', deckType:BaseDeckType.OPPORTUNITY, rarity:CardRarity.COMMON, timingClass:TimingClass.STANDARD, base_cost:8_000, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:1_200,duration:0}, tags:[CardTag.INCOME,CardTag.COMPOUNDING,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.SELF, educational_tag:'passive_income_real_estate', lore:'Every brick is a vote against trading your time for money.', modes_legal:ALL_MODES, is_forced:false, drop_weight:18 },
  { cardId:'opp_business_acq_002', name:'Business Acquisition', deckType:BaseDeckType.OPPORTUNITY, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.STANDARD, base_cost:25_000, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:4_500,duration:0}, tags:[CardTag.INCOME,CardTag.LEVERAGE,CardTag.CAPITAL_ALLOC,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.SELF, educational_tag:'business_acquisition_leverage', lore:"You didn't buy a business. You bought a machine that prints money.", modes_legal:ALL_MODES, is_forced:false, drop_weight:10 },
  { cardId:'opp_digital_asset_003', name:'Digital Asset Position', deckType:BaseDeckType.OPPORTUNITY, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.IMMEDIATE, base_cost:5_000, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:800,duration:3}, tags:[CardTag.TEMPO,CardTag.INCOME,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.SELF, educational_tag:'digital_asset_diversification', lore:'Asymmetric bets belong in asymmetric positions.', modes_legal:ALL_MODES, is_forced:false, drop_weight:12 },
  { cardId:'opp_equity_position_004', name:'Equity Position', deckType:BaseDeckType.OPPORTUNITY, rarity:CardRarity.RARE, timingClass:TimingClass.STANDARD, base_cost:15_000, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:2_200,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.03,duration:0}}, tags:[CardTag.COMPOUNDING,CardTag.CAPITAL_ALLOC,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.SELF, educational_tag:'equity_ownership_compound_growth', lore:"Ownership compounds. Wages don't.", modes_legal:ALL_MODES, is_forced:false, drop_weight:8 },
  { cardId:'opp_missed_window_005', name:'Missed Window', deckType:BaseDeckType.OPPORTUNITY, rarity:CardRarity.COMMON, timingClass:TimingClass.REACTIVE, base_cost:0, base_effect:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:-0.02,duration:0}, tags:[CardTag.TEMPO], targeting:Targeting.SELF, educational_tag:'opportunity_cost', lore:'The cost you never see is the one that compounds forever.', modes_legal:ALL_MODES, is_forced:true, drop_weight:0 },
  { cardId:'opp_land_contract_006', name:'Land Contract', deckType:BaseDeckType.OPPORTUNITY, rarity:CardRarity.RARE, timingClass:TimingClass.STANDARD, base_cost:18_000, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:2_800,duration:0,secondary:{effectType:CardEffectType.EXPENSE_REDUCTION,magnitude:600,duration:2}}, tags:[CardTag.INCOME,CardTag.LEVERAGE,CardTag.REAL_WORLD_FINANCE,CardTag.CAPITAL_ALLOC], targeting:Targeting.SELF, educational_tag:'seller_financing_land_contracts', lore:'The seller becomes the bank. You become the owner.', modes_legal:ALL_MODES, is_forced:false, drop_weight:7 },
  { cardId:'opp_angel_investment_007', name:'Angel Round', deckType:BaseDeckType.OPPORTUNITY, rarity:CardRarity.EPIC, timingClass:TimingClass.STANDARD, base_cost:50_000, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:8_000,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.06,duration:0}}, tags:[CardTag.INCOME,CardTag.COMPOUNDING,CardTag.LEVERAGE,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.SELF, educational_tag:'angel_investing_equity_returns', lore:'You funded the idea. The idea funded the generation.', modes_legal:ALL_MODES, is_forced:false, drop_weight:4 },
  { cardId:'opp_franchise_deal_008', name:'Franchise Deal', deckType:BaseDeckType.OPPORTUNITY, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.STANDARD, base_cost:30_000, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:3_500,duration:0}, tags:[CardTag.INCOME,CardTag.AUTOMATION,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.SELF, educational_tag:'franchise_model_scalability', lore:'Proven system. Proven market. Your capital. Your freedom.', modes_legal:ALL_MODES, is_forced:false, drop_weight:9 },
  { cardId:'opp_late_entry_009', name:'Late Entry', deckType:BaseDeckType.OPPORTUNITY, rarity:CardRarity.COMMON, timingClass:TimingClass.REACTIVE, base_cost:0, base_effect:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:-0.03,duration:0,secondary:{effectType:CardEffectType.EXPENSE_SPIKE,magnitude:1_500,duration:1}}, tags:[CardTag.TEMPO], targeting:Targeting.SELF, educational_tag:'timing_as_strategy', lore:'Everyone who waited paid the late fee. Time was always the cost.', modes_legal:ALL_MODES, is_forced:true, drop_weight:0 },
];

// ─── IPA (8) ──────────────────────────────────────────────────────────────────
const IPA_CARDS: CardDefinition[] = [
  { cardId:'ipa_digital_product_001', name:'Digital Product', deckType:BaseDeckType.IPA, rarity:CardRarity.COMMON, timingClass:TimingClass.STANDARD, base_cost:2_500, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:400,duration:0}, tags:[CardTag.INCOME,CardTag.AUTOMATION,CardTag.COMPOUNDING,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.SELF, educational_tag:'digital_product_passive_income', lore:'Build it once. Sell it a thousand times while you sleep.', modes_legal:ALL_MODES, is_forced:false, drop_weight:20 },
  { cardId:'ipa_royalty_stream_002', name:'Royalty Stream', deckType:BaseDeckType.IPA, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.STANDARD, base_cost:6_000, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:900,duration:0}, tags:[CardTag.INCOME,CardTag.COMPOUNDING,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.SELF, educational_tag:'intellectual_property_royalties', lore:"Intellectual property works overtime so you don't have to.", modes_legal:ALL_MODES, is_forced:false, drop_weight:14 },
  { cardId:'ipa_dividend_portfolio_003', name:'Dividend Portfolio', deckType:BaseDeckType.IPA, rarity:CardRarity.RARE, timingClass:TimingClass.STANDARD, base_cost:12_000, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:1_800,duration:0}, tags:[CardTag.INCOME,CardTag.COMPOUNDING,CardTag.LIQUIDITY,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.SELF, educational_tag:'dividend_investing_cashflow', lore:'The market opens every day. Your dividends do not care.', modes_legal:ALL_MODES, is_forced:false, drop_weight:9 },
  { cardId:'ipa_saas_revenue_004', name:'SaaS Revenue', deckType:BaseDeckType.IPA, rarity:CardRarity.EPIC, timingClass:TimingClass.STANDARD, base_cost:20_000, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:3_500,duration:0,secondary:{effectType:CardEffectType.HATER_HEAT_REDUCE,magnitude:5,duration:0}}, tags:[CardTag.INCOME,CardTag.AUTOMATION,CardTag.COMPOUNDING,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.SELF, educational_tag:'saas_recurring_revenue_model', lore:'Predictable revenue is the only kind worth building on.', modes_legal:ALL_MODES, is_forced:false, drop_weight:5 },
  { cardId:'ipa_real_estate_fund_005', name:'Real Estate Fund', deckType:BaseDeckType.IPA, rarity:CardRarity.RARE, timingClass:TimingClass.STANDARD, base_cost:35_000, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:4_200,duration:0,secondary:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:10,duration:0}}, tags:[CardTag.INCOME,CardTag.COMPOUNDING,CardTag.RESILIENCE,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.SELF, educational_tag:'real_estate_fund_diversification', lore:'Fifty doors without one key. Ownership at scale.', modes_legal:ALL_MODES, is_forced:false, drop_weight:6 },
  { cardId:'ipa_private_equity_006', name:'Private Equity Stake', deckType:BaseDeckType.IPA, rarity:CardRarity.EPIC, timingClass:TimingClass.STANDARD, base_cost:75_000, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:9_500,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.07,duration:0}}, tags:[CardTag.INCOME,CardTag.COMPOUNDING,CardTag.CAPITAL_ALLOC,CardTag.LEVERAGE], targeting:Targeting.SELF, educational_tag:'private_equity_illiquid_premium', lore:'Illiquidity is the premium the patient collect from the anxious.', modes_legal:ALL_MODES, is_forced:false, drop_weight:3 },
  { cardId:'ipa_licensing_deal_007', name:'Licensing Deal', deckType:BaseDeckType.IPA, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.STANDARD, base_cost:8_000, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:1_100,duration:0}, tags:[CardTag.INCOME,CardTag.LEVERAGE,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.SELF, educational_tag:'licensing_intellectual_property', lore:'They use your idea. You collect the fee. Indefinitely.', modes_legal:ALL_MODES, is_forced:false, drop_weight:13 },
  { cardId:'ipa_venture_returns_008', name:'Venture Returns', deckType:BaseDeckType.IPA, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:22_000,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.12,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.INCOME,CardTag.COMPOUNDING,CardTag.CAPITAL_ALLOC], targeting:Targeting.SELF, educational_tag:'venture_capital_power_law_returns', lore:'The 100x return is not luck. It is patience measured in years.', modes_legal:ALL_MODES, is_forced:false, drop_weight:LDW },
];

// ─── FUBAR (6) — engine-injected only ────────────────────────────────────────
const FUBAR_CARDS: CardDefinition[] = [
  { cardId:'fubar_market_crash_001', name:'Market Crash', deckType:BaseDeckType.FUBAR, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.FORCED, base_cost:0, base_effect:{effectType:CardEffectType.EXPENSE_SPIKE,magnitude:15_000,duration:2,secondary:{effectType:CardEffectType.INCOME_REDUCTION,magnitude:0.35,duration:3}}, tags:[CardTag.RESILIENCE], targeting:Targeting.ENGINE, educational_tag:'market_volatility_risk_management', lore:'The market has crashed before. The prepared survive. The rest learn.', modes_legal:ALL_MODES, is_forced:true, drop_weight:0 },
  { cardId:'fubar_tax_audit_002', name:'Tax Audit', deckType:BaseDeckType.FUBAR, rarity:CardRarity.EPIC, timingClass:TimingClass.FORCED, base_cost:0, base_effect:{effectType:CardEffectType.EXPENSE_SPIKE,magnitude:8_000,duration:1,secondary:{effectType:CardEffectType.HATER_HEAT_SPIKE,magnitude:15,duration:0}}, tags:[CardTag.RESILIENCE,CardTag.LIQUIDITY], targeting:Targeting.ENGINE, educational_tag:'tax_compliance_documentation', lore:'The audit is not the problem. The unprepared books are.', modes_legal:ALL_MODES, is_forced:true, drop_weight:0 },
  { cardId:'fubar_emergency_expense_003', name:'Emergency Expense', deckType:BaseDeckType.FUBAR, rarity:CardRarity.COMMON, timingClass:TimingClass.FORCED, base_cost:0, base_effect:{effectType:CardEffectType.EXPENSE_SPIKE,magnitude:3_500,duration:0}, tags:[CardTag.LIQUIDITY,CardTag.RESILIENCE], targeting:Targeting.ENGINE, educational_tag:'emergency_fund_necessity', lore:'The emergency fund exists for one reason. Today is that reason.', modes_legal:ALL_MODES, is_forced:true, drop_weight:0 },
  { cardId:'fubar_income_shock_004', name:'Income Shock', deckType:BaseDeckType.FUBAR, rarity:CardRarity.RARE, timingClass:TimingClass.FORCED, base_cost:0, base_effect:{effectType:CardEffectType.INCOME_REDUCTION,magnitude:0.5,duration:2}, tags:[CardTag.INCOME,CardTag.RESILIENCE], targeting:Targeting.ENGINE, educational_tag:'income_diversification_necessity', lore:'Single-stream income is a single point of failure. Now you know.', modes_legal:ALL_MODES, is_forced:true, drop_weight:0 },
  // ── RESTORED FROM v1 ──
  { cardId:'fubar_expense_spike_002', name:'Unexpected Expense', deckType:BaseDeckType.FUBAR, rarity:CardRarity.COMMON, timingClass:TimingClass.FORCED, base_cost:0, base_effect:{effectType:CardEffectType.EXPENSE_SPIKE,magnitude:3_000,duration:1}, tags:[CardTag.REAL_WORLD_FINANCE,CardTag.LIQUIDITY], targeting:Targeting.ENGINE, educational_tag:'emergency_fund_importance', lore:"Murphy's Law has a billing department.", modes_legal:ALL_MODES, is_forced:true, drop_weight:0 },
  { cardId:'fubar_regulatory_hit_003', name:'Regulatory Audit', deckType:BaseDeckType.FUBAR, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.FORCED, base_cost:0, base_effect:{effectType:CardEffectType.EXPENSE_SPIKE,magnitude:5_000,duration:0,secondary:{effectType:CardEffectType.HATER_HEAT_SPIKE,magnitude:10,duration:0}}, tags:[CardTag.REAL_WORLD_FINANCE,CardTag.RESILIENCE], targeting:Targeting.ENGINE, educational_tag:'regulatory_compliance_risk', lore:'The government always wants its cut. Schedule it.', modes_legal:ALL_MODES, is_forced:true, drop_weight:0 },
  { cardId:'fubar_bot_swarm_005', name:'Bot Swarm', deckType:BaseDeckType.FUBAR, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.FORCED, base_cost:0, base_effect:{effectType:CardEffectType.HATER_HEAT_SPIKE,magnitude:30,duration:0,secondary:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:-20,duration:0}}, tags:[CardTag.RESILIENCE,CardTag.COMBAT], targeting:Targeting.ENGINE, educational_tag:'reputation_defense_systems', lore:'Coordinated attack. The bots do not negotiate. Neither do you.', modes_legal:ALL_MODES, is_forced:true, drop_weight:0 },
  { cardId:'fubar_cascade_event_006', name:'Cascade Event', deckType:BaseDeckType.FUBAR, rarity:CardRarity.RARE, timingClass:TimingClass.FORCED, base_cost:0, base_effect:{effectType:CardEffectType.CASCADE_ACCELERATE,magnitude:2,duration:0,secondary:{effectType:CardEffectType.EXPENSE_SPIKE,magnitude:4_500,duration:1}}, tags:[CardTag.RESILIENCE,CardTag.TEMPO], targeting:Targeting.ENGINE, educational_tag:'cascade_failure_prevention', lore:"One domino fell. Watch how many follow if you don't move.", modes_legal:ALL_MODES, is_forced:true, drop_weight:0 },
];

// ─── PRIVILEGED (6) ───────────────────────────────────────────────────────────
const PRIVILEGED_CARDS: CardDefinition[] = [
  { cardId:'priv_network_call_001', name:'Network Call', deckType:BaseDeckType.PRIVILEGED, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:1_500,duration:0,secondary:{effectType:CardEffectType.HATER_HEAT_REDUCE,magnitude:8,duration:0}}, tags:[CardTag.INCOME,CardTag.RESILIENCE,CardTag.TRUST], targeting:Targeting.SELF, educational_tag:'network_as_capital', lore:'One call to the right person eliminates what took others six months.', modes_legal:ALL_MODES, is_forced:false, drop_weight:14 },
  { cardId:'priv_insider_advantage_002', name:'Insider Advantage', deckType:BaseDeckType.PRIVILEGED, rarity:CardRarity.RARE, timingClass:TimingClass.STANDARD, base_cost:0, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:3_200,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.04,duration:0}}, tags:[CardTag.INCOME,CardTag.TEMPO,CardTag.CAPITAL_ALLOC], targeting:Targeting.SELF, educational_tag:'information_edge_economics', lore:'Information asymmetry is legal when earned through relationship.', modes_legal:ALL_MODES, is_forced:false, drop_weight:8 },
  { cardId:'priv_board_seat_003', name:'Board Seat', deckType:BaseDeckType.PRIVILEGED, rarity:CardRarity.EPIC, timingClass:TimingClass.STANDARD, base_cost:0, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:5_500,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.06,duration:0}}, tags:[CardTag.INCOME,CardTag.LEVERAGE,CardTag.CAPITAL_ALLOC,CardTag.TRUST], targeting:Targeting.SELF, educational_tag:'board_governance_influence', lore:'The board seat is the throne. Attend every meeting.', modes_legal:ALL_MODES, is_forced:false, drop_weight:4 },
  { cardId:'priv_first_mover_004', name:'First Mover', deckType:BaseDeckType.PRIVILEGED, rarity:CardRarity.RARE, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:2_800,duration:0,secondary:{effectType:CardEffectType.BATTLE_BUDGET_GRANT,magnitude:10,duration:0}}, tags:[CardTag.TEMPO,CardTag.INCOME,CardTag.LEVERAGE], targeting:Targeting.SELF, educational_tag:'first_mover_advantage_dynamics', lore:'Second place has to explain why they were second. You never do.', modes_legal:ALL_MODES, is_forced:false, drop_weight:7 },
  { cardId:'priv_closed_door_005', name:'Closed Door', deckType:BaseDeckType.PRIVILEGED, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.REACTIVE, base_cost:0, base_effect:{effectType:CardEffectType.HATER_HEAT_REDUCE,magnitude:18,duration:0,secondary:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:15,duration:0}}, tags:[CardTag.RESILIENCE,CardTag.TRUST], targeting:Targeting.SELF, educational_tag:'private_resolution_power', lore:'Some problems end at the door. The privileged keep their doors private.', modes_legal:ALL_MODES, is_forced:false, drop_weight:11 },
  { cardId:'priv_direct_channel_006', name:'Direct Channel', deckType:BaseDeckType.PRIVILEGED, rarity:CardRarity.RARE, timingClass:TimingClass.STANDARD, base_cost:0, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:2_500,duration:2,secondary:{effectType:CardEffectType.HATER_HEAT_REDUCE,magnitude:12,duration:0}}, tags:[CardTag.INCOME,CardTag.RESILIENCE,CardTag.AUTOMATION], targeting:Targeting.SELF, educational_tag:'direct_distribution_power', lore:'No middleman. No margin compression. Direct.', modes_legal:ALL_MODES, is_forced:false, drop_weight:8 },
];

// ─── SO (7) ───────────────────────────────────────────────────────────────────
const SO_CARDS: CardDefinition[] = [
  { cardId:'so_convert_cash_001', name:'Convert: Pay Through', deckType:BaseDeckType.SO, rarity:CardRarity.COMMON, timingClass:TimingClass.REACTIVE, base_cost:4_000, base_effect:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:15,duration:0}, tags:[CardTag.LIQUIDITY,CardTag.RESILIENCE], targeting:Targeting.ENGINE, educational_tag:'obstacle_conversion_cash', lore:'Cash solves most problems. The rest require creativity.', modes_legal:ALL_MODES, is_forced:false, drop_weight:15 },
  { cardId:'so_convert_time_002', name:'Convert: Time Freeze', deckType:BaseDeckType.SO, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.REACTIVE, base_cost:0, base_effect:{effectType:CardEffectType.EXPENSE_REDUCTION,magnitude:0.2,duration:2,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.01,duration:0}}, tags:[CardTag.TEMPO,CardTag.RESILIENCE], targeting:Targeting.SELF, educational_tag:'time_as_capital', lore:'Time is the only resource that cannot be replenished. Spend it deliberately.', modes_legal:ALL_MODES, is_forced:false, drop_weight:12 },
  { cardId:'so_absorb_cord_003', name:'Convert: Absorb & Learn', deckType:BaseDeckType.SO, rarity:CardRarity.COMMON, timingClass:TimingClass.REACTIVE, base_cost:0, base_effect:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.02,duration:0}, tags:[CardTag.RESILIENCE,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.SELF, educational_tag:'adversity_as_education', lore:'Every hit you survive teaches you something the textbook never could.', modes_legal:ALL_MODES, is_forced:false, drop_weight:14 },
  { cardId:'so_pivot_strategy_004', name:'Strategic Pivot', deckType:BaseDeckType.SO, rarity:CardRarity.RARE, timingClass:TimingClass.REACTIVE, base_cost:0, base_effect:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:20,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.03,duration:0}}, tags:[CardTag.RESILIENCE,CardTag.TEMPO,CardTag.CAPITAL_ALLOC], targeting:Targeting.SELF, educational_tag:'strategic_pivot_mechanics', lore:'The fastest route is not always a straight line. Pivot before the wall finds you.', modes_legal:ALL_MODES, is_forced:false, drop_weight:8 },
  { cardId:'so_leverage_setback_005', name:'Leverage the Setback', deckType:BaseDeckType.SO, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.REACTIVE, base_cost:0, base_effect:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.04,duration:0}, tags:[CardTag.RESILIENCE,CardTag.LEVERAGE], targeting:Targeting.SELF, educational_tag:'antifragility_wealth', lore:'Adversity is only a setback to those who refuse to extract value from it.', modes_legal:ALL_MODES, is_forced:false, drop_weight:10 },
  { cardId:'so_regulatory_route_006', name:'Regulatory Route', deckType:BaseDeckType.SO, rarity:CardRarity.RARE, timingClass:TimingClass.REACTIVE, base_cost:5_000, base_effect:{effectType:CardEffectType.HATER_HEAT_REDUCE,magnitude:22,duration:0,secondary:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:12,duration:0}}, tags:[CardTag.RESILIENCE,CardTag.LIQUIDITY], targeting:Targeting.ENGINE, educational_tag:'regulatory_compliance_as_strategy', lore:'The law protects the prepared. Use it.', modes_legal:ALL_MODES, is_forced:false, drop_weight:7 },
  { cardId:'so_crisis_pivot_007', name:'Crisis Pivot', deckType:BaseDeckType.SO, rarity:CardRarity.EPIC, timingClass:TimingClass.REACTIVE, base_cost:0, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:2_500,duration:2,secondary:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:25,duration:0}}, tags:[CardTag.RESILIENCE,CardTag.INCOME,CardTag.TEMPO], targeting:Targeting.SELF, educational_tag:'crisis_as_opportunity', lore:'Crisis creates the opening. The sovereign entrepreneur is already moving.', modes_legal:ALL_MODES, is_forced:false, drop_weight:5 },
];

// ─── PHASE BOUNDARY (6) — GO_ALONE/engine-injected ────────────────────────────
const PHASE_BOUNDARY_CARDS: CardDefinition[] = [
  { cardId:'phase_foundation_exit_001', name:'Foundation Complete', deckType:BaseDeckType.PHASE_BOUNDARY, rarity:CardRarity.RARE, timingClass:TimingClass.PHASE_BOUNDARY, base_cost:0, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:2_000,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.05,duration:0}}, tags:[CardTag.CAPITAL_ALLOC,CardTag.INCOME], targeting:Targeting.SELF, educational_tag:'financial_foundation_milestone', lore:'Phase One complete. The foundation holds. Now build above it.', modes_legal:EMPIRE, is_forced:false, drop_weight:0 },
  { cardId:'phase_escalation_exit_002', name:'Escalation Protocol', deckType:BaseDeckType.PHASE_BOUNDARY, rarity:CardRarity.EPIC, timingClass:TimingClass.PHASE_BOUNDARY, base_cost:0, base_effect:{effectType:CardEffectType.HATER_HEAT_REDUCE,magnitude:30,duration:0,secondary:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:25,duration:0}}, tags:[CardTag.RESILIENCE,CardTag.LIQUIDITY], targeting:Targeting.SELF, educational_tag:'scaling_under_pressure', lore:'Phase Two rewrites the threat model. Adapt or be consumed.', modes_legal:EMPIRE, is_forced:false, drop_weight:0 },
  { cardId:'phase_sovereignty_decision_003', name:'Sovereignty Decision', deckType:BaseDeckType.PHASE_BOUNDARY, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.SOVEREIGNTY_DECISION, base_cost:0, base_effect:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.15,duration:0}, tags:[CardTag.CAPITAL_ALLOC,CardTag.LEVERAGE,CardTag.LEGENDARY_TAG], targeting:Targeting.SELF, educational_tag:'high_stakes_decision_making', lore:'One decision. Two paths. The engine will remember which you chose.', modes_legal:EMPIRE, is_forced:false, drop_weight:0 },
  { cardId:'phase_expansion_bridge_004', name:'Expansion Bridge', deckType:BaseDeckType.PHASE_BOUNDARY, rarity:CardRarity.EPIC, timingClass:TimingClass.PHASE_BOUNDARY, base_cost:0, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:4_500,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.06,duration:0}}, tags:[CardTag.INCOME,CardTag.CAPITAL_ALLOC,CardTag.LEVERAGE], targeting:Targeting.SELF, educational_tag:'empire_expansion_mechanics', lore:'Phase Three is not bigger. Phase Three is different. Cross deliberately.', modes_legal:EMPIRE, is_forced:false, drop_weight:0 },
  { cardId:'phase_consolidation_005', name:'Consolidation Move', deckType:BaseDeckType.PHASE_BOUNDARY, rarity:CardRarity.RARE, timingClass:TimingClass.PHASE_BOUNDARY, base_cost:0, base_effect:{effectType:CardEffectType.EXPENSE_REDUCTION,magnitude:0.25,duration:3,secondary:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:20,duration:0}}, tags:[CardTag.RESILIENCE,CardTag.LIQUIDITY,CardTag.CAPITAL_ALLOC], targeting:Targeting.SELF, educational_tag:'consolidation_before_expansion', lore:'Consolidate before you expand. Strength is not addition. It is integration.', modes_legal:EMPIRE, is_forced:false, drop_weight:0 },
  { cardId:'phase_critical_junction_006', name:'Critical Junction', deckType:BaseDeckType.PHASE_BOUNDARY, rarity:CardRarity.EPIC, timingClass:TimingClass.PHASE_BOUNDARY, base_cost:0, base_effect:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.08,duration:0,secondary:{effectType:CardEffectType.HATER_HEAT_REDUCE,magnitude:20,duration:0}}, tags:[CardTag.CAPITAL_ALLOC,CardTag.RESILIENCE,CardTag.INCOME], targeting:Targeting.SELF, educational_tag:'decision_junctions_empire', lore:'Every empire reaches this moment. The choice echoes through every phase that follows.', modes_legal:EMPIRE, is_forced:false, drop_weight:0 },
];

// ─── SABOTAGE (10) — HEAD_TO_HEAD ────────────────────────────────────────────
const SABOTAGE_CARDS: CardDefinition[] = [
  { cardId:'sab_expense_injection_001', name:'Expense Injection', deckType:ModeDeckType.SABOTAGE, rarity:CardRarity.COMMON, timingClass:TimingClass.STANDARD, base_cost:15, base_effect:{effectType:CardEffectType.EXTRACTION_FIRE,magnitude:2_500,duration:0}, tags:[CardTag.SABOTAGE,CardTag.TEMPO,CardTag.COMBAT], targeting:Targeting.OPPONENT, educational_tag:'competitive_disruption', lore:'Their expense line just became your weapon.', modes_legal:PREDATOR, is_forced:false, drop_weight:20 },
  { cardId:'sab_income_freeze_002', name:'Income Freeze', deckType:ModeDeckType.SABOTAGE, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.STANDARD, base_cost:25, base_effect:{effectType:CardEffectType.EXTRACTION_FIRE,magnitude:0.4,duration:2}, tags:[CardTag.SABOTAGE,CardTag.COMBAT,CardTag.LEVERAGE], targeting:Targeting.OPPONENT, educational_tag:'income_disruption_strategy', lore:'Freeze their income. Watch their empire crumble from the foundation.', modes_legal:PREDATOR, is_forced:false, drop_weight:14 },
  { cardId:'sab_shield_crack_003', name:'Shield Crack', deckType:ModeDeckType.SABOTAGE, rarity:CardRarity.RARE, timingClass:TimingClass.STANDARD, base_cost:40, base_effect:{effectType:CardEffectType.EXTRACTION_FIRE,magnitude:30,duration:0}, tags:[CardTag.SABOTAGE,CardTag.COMBAT], targeting:Targeting.OPPONENT, educational_tag:'defensive_vulnerability', lore:'Every fortress has a weak point. Find it. Hit it first.', modes_legal:PREDATOR, is_forced:false, drop_weight:8 },
  { cardId:'sab_bot_deploy_004', name:'Bot Deployment', deckType:ModeDeckType.SABOTAGE, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.STANDARD, base_cost:20, base_effect:{effectType:CardEffectType.HATER_HEAT_SPIKE,magnitude:20,duration:0,secondary:{effectType:CardEffectType.EXTRACTION_FIRE,magnitude:1_000,duration:0}}, tags:[CardTag.SABOTAGE,CardTag.COMBAT,CardTag.TEMPO], targeting:Targeting.OPPONENT, educational_tag:'reputation_attack_economics', lore:'Bots are cheap. Reputation damage is expensive. Arithmetic.', modes_legal:PREDATOR, is_forced:false, drop_weight:13 },
  { cardId:'sab_liquidity_drain_005', name:'Liquidity Drain', deckType:ModeDeckType.SABOTAGE, rarity:CardRarity.RARE, timingClass:TimingClass.STANDARD, base_cost:35, base_effect:{effectType:CardEffectType.EXTRACTION_FIRE,magnitude:5_500,duration:0}, tags:[CardTag.SABOTAGE,CardTag.COMBAT,CardTag.LEVERAGE], targeting:Targeting.OPPONENT, educational_tag:'liquidity_warfare', lore:'Drain their liquidity. Force liquidation at the worst moment.', modes_legal:PREDATOR, is_forced:false, drop_weight:9 },
  { cardId:'sab_tempo_spike_006', name:'Tempo Spike', deckType:ModeDeckType.SABOTAGE, rarity:CardRarity.COMMON, timingClass:TimingClass.IMMEDIATE, base_cost:8, base_effect:{effectType:CardEffectType.EXTRACTION_FIRE,magnitude:1_200,duration:0}, tags:[CardTag.SABOTAGE,CardTag.TEMPO,CardTag.COMBAT], targeting:Targeting.OPPONENT, educational_tag:'tempo_aggression', lore:'Fast, cheap, decisive. The tempo player does not wait for permission.', modes_legal:PREDATOR, is_forced:false, drop_weight:18 },
  { cardId:'sab_cascade_trigger_007', name:'Cascade Trigger', deckType:ModeDeckType.SABOTAGE, rarity:CardRarity.EPIC, timingClass:TimingClass.STANDARD, base_cost:55, base_effect:{effectType:CardEffectType.CASCADE_ACCELERATE,magnitude:2,duration:0,secondary:{effectType:CardEffectType.EXTRACTION_FIRE,magnitude:3_000,duration:0}}, tags:[CardTag.SABOTAGE,CardTag.COMBAT,CardTag.TEMPO], targeting:Targeting.OPPONENT, educational_tag:'cascade_offensive_strategy', lore:"Trigger their cascade. Let their own system finish the job.", modes_legal:PREDATOR, is_forced:false, drop_weight:4 },
  { cardId:'sab_market_flood_008', name:'Market Flood', deckType:ModeDeckType.SABOTAGE, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.STANDARD, base_cost:18, base_effect:{effectType:CardEffectType.EXTRACTION_FIRE,magnitude:1_800,duration:1,secondary:{effectType:CardEffectType.INCOME_REDUCTION,magnitude:0.15,duration:2}}, tags:[CardTag.SABOTAGE,CardTag.COMBAT,CardTag.LEVERAGE], targeting:Targeting.OPPONENT, educational_tag:'market_saturation_offense', lore:'Flood their market. Compress their margin. Watch the math do the rest.', modes_legal:PREDATOR, is_forced:false, drop_weight:12 },
  { cardId:'sab_trust_poison_009', name:'Trust Poison', deckType:ModeDeckType.SABOTAGE, rarity:CardRarity.RARE, timingClass:TimingClass.STANDARD, base_cost:30, base_effect:{effectType:CardEffectType.TRUST_SCORE_DRAIN,magnitude:15,duration:0,secondary:{effectType:CardEffectType.HATER_HEAT_SPIKE,magnitude:10,duration:0}}, tags:[CardTag.SABOTAGE,CardTag.COMBAT], targeting:Targeting.OPPONENT, educational_tag:'reputation_network_attack', lore:'The most powerful attack destroys the network that built them.', modes_legal:PREDATOR, is_forced:false, drop_weight:7 },
  { cardId:'sab_sovereign_spike_010', name:'Sovereign Spike', deckType:ModeDeckType.SABOTAGE, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.EXTRACTION_FIRE,magnitude:18_000,duration:0,secondary:{effectType:CardEffectType.HATER_HEAT_SPIKE,magnitude:25,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.SABOTAGE,CardTag.COMBAT], targeting:Targeting.OPPONENT, educational_tag:'total_financial_pressure', lore:'This is not sabotage. This is sovereignty in motion.', modes_legal:PREDATOR, is_forced:false, drop_weight:LDW },
];

// ─── COUNTER (7) — HEAD_TO_HEAD ───────────────────────────────────────────────
const COUNTER_CARDS: CardDefinition[] = [
  { cardId:'counter_absorb_001', name:'Absorb', deckType:ModeDeckType.COUNTER, rarity:CardRarity.COMMON, timingClass:TimingClass.COUNTER_WINDOW, base_cost:8, base_effect:{effectType:CardEffectType.EXTRACTION_BLOCK,magnitude:0.5,duration:0}, tags:[CardTag.COUNTER,CardTag.RESILIENCE,CardTag.COMBAT], targeting:Targeting.SELF, educational_tag:'risk_mitigation', lore:'Half the hit is still the half you survived.', modes_legal:PREDATOR, is_forced:false, drop_weight:22 },
  { cardId:'counter_full_block_002', name:'Full Block', deckType:ModeDeckType.COUNTER, rarity:CardRarity.RARE, timingClass:TimingClass.COUNTER_WINDOW, base_cost:20, base_effect:{effectType:CardEffectType.EXTRACTION_BLOCK,magnitude:1.0,duration:0}, tags:[CardTag.COUNTER,CardTag.RESILIENCE,CardTag.COMBAT], targeting:Targeting.SELF, educational_tag:'complete_risk_elimination', lore:'Zero damage. Full message delivered.', modes_legal:PREDATOR, is_forced:false, drop_weight:10 },
  { cardId:'counter_reflect_003', name:'Reflect', deckType:ModeDeckType.COUNTER, rarity:CardRarity.EPIC, timingClass:TimingClass.COUNTER_WINDOW, base_cost:35, base_effect:{effectType:CardEffectType.EXTRACTION_BLOCK,magnitude:0.75,duration:0,secondary:{effectType:CardEffectType.EXTRACTION_FIRE,magnitude:2_000,duration:0}}, tags:[CardTag.COUNTER,CardTag.COMBAT,CardTag.RESILIENCE], targeting:Targeting.SELF, educational_tag:'counter_attack_economics', lore:'Block 75%. Return the rest. The aggressor learns what reflection costs.', modes_legal:PREDATOR, is_forced:false, drop_weight:5 },
  { cardId:'counter_parry_004', name:'Parry', deckType:ModeDeckType.COUNTER, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.COUNTER_WINDOW, base_cost:10, base_effect:{effectType:CardEffectType.EXTRACTION_BLOCK,magnitude:0.3,duration:0,secondary:{effectType:CardEffectType.BATTLE_BUDGET_GRANT,magnitude:5,duration:0}}, tags:[CardTag.COUNTER,CardTag.TEMPO,CardTag.COMBAT], targeting:Targeting.SELF, educational_tag:'defensive_tempo_play', lore:'Deflect the strike, recover the budget. Efficiency over perfection.', modes_legal:PREDATOR, is_forced:false, drop_weight:15 },
  { cardId:'counter_mirror_005', name:'Mirror', deckType:ModeDeckType.COUNTER, rarity:CardRarity.RARE, timingClass:TimingClass.COUNTER_WINDOW, base_cost:25, base_effect:{effectType:CardEffectType.EXTRACTION_BLOCK,magnitude:0.6,duration:0,secondary:{effectType:CardEffectType.INCOME_BOOST,magnitude:1_500,duration:0}}, tags:[CardTag.COUNTER,CardTag.INCOME,CardTag.RESILIENCE], targeting:Targeting.SELF, educational_tag:'asymmetric_defense', lore:'They attack your money. You protect it and grow it simultaneously.', modes_legal:PREDATOR, is_forced:false, drop_weight:8 },
  { cardId:'counter_fortress_006', name:'Fortress', deckType:ModeDeckType.COUNTER, rarity:CardRarity.RARE, timingClass:TimingClass.COUNTER_WINDOW, base_cost:18, base_effect:{effectType:CardEffectType.EXTRACTION_BLOCK,magnitude:0.6,duration:0,secondary:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:15,duration:0}}, tags:[CardTag.COUNTER,CardTag.RESILIENCE,CardTag.COMBAT], targeting:Targeting.SELF, educational_tag:'defensive_fortification', lore:'Block the blow. Repair the wall. Move forward.', modes_legal:PREDATOR, is_forced:false, drop_weight:9 },
  { cardId:'counter_sovereign_wall_007', name:'Sovereign Wall', deckType:ModeDeckType.COUNTER, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.EXTRACTION_BLOCK,magnitude:1.0,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.05,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.COUNTER,CardTag.RESILIENCE,CardTag.COMBAT], targeting:Targeting.SELF, educational_tag:'sovereign_defense_system', lore:'Full block. Unbreakable. The wall is you.', modes_legal:PREDATOR, is_forced:false, drop_weight:LDW },
];

// ─── BLUFF (6) — HEAD_TO_HEAD ─────────────────────────────────────────────────
const BLUFF_CARDS: CardDefinition[] = [
  { cardId:'bluff_false_threat_001', name:'False Flag', deckType:ModeDeckType.BLUFF, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.BLUFF, base_cost:10, base_effect:{effectType:CardEffectType.BLUFF_DISPLAY,magnitude:0,duration:0,secondary:{effectType:CardEffectType.INCOME_BOOST,magnitude:800,duration:0}}, tags:[CardTag.SABOTAGE,CardTag.TEMPO,CardTag.COMBAT], targeting:Targeting.OPPONENT, educational_tag:'misdirection_strategy', lore:'They spent their counter window on a phantom. You built with theirs.', modes_legal:PREDATOR, is_forced:false, drop_weight:12 },
  { cardId:'bluff_double_down_002', name:'Double Down', deckType:ModeDeckType.BLUFF, rarity:CardRarity.RARE, timingClass:TimingClass.BLUFF, base_cost:22, base_effect:{effectType:CardEffectType.BLUFF_DISPLAY,magnitude:0,duration:0,secondary:{effectType:CardEffectType.EXTRACTION_FIRE,magnitude:3_000,duration:0}}, tags:[CardTag.SABOTAGE,CardTag.COMBAT,CardTag.TEMPO], targeting:Targeting.OPPONENT, educational_tag:'aggressive_bluff_mechanics', lore:'Show them the threat. Execute the strike. The window is the same 5 seconds.', modes_legal:PREDATOR, is_forced:false, drop_weight:8 },
  { cardId:'bluff_phantom_strike_003', name:'Phantom Strike', deckType:ModeDeckType.BLUFF, rarity:CardRarity.EPIC, timingClass:TimingClass.BLUFF, base_cost:30, base_effect:{effectType:CardEffectType.BLUFF_DISPLAY,magnitude:0,duration:0,secondary:{effectType:CardEffectType.INCOME_BOOST,magnitude:4_500,duration:0}}, tags:[CardTag.SABOTAGE,CardTag.TEMPO,CardTag.COMBAT], targeting:Targeting.OPPONENT, educational_tag:'advanced_deception_economics', lore:'The most expensive attack is the one they defended that never came.', modes_legal:PREDATOR, is_forced:false, drop_weight:5 },
  { cardId:'bluff_bait_004', name:'Bait', deckType:ModeDeckType.BLUFF, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.BLUFF, base_cost:12, base_effect:{effectType:CardEffectType.BLUFF_DISPLAY,magnitude:0,duration:0,secondary:{effectType:CardEffectType.BATTLE_BUDGET_GRANT,magnitude:15,duration:0}}, tags:[CardTag.TEMPO,CardTag.COMBAT,CardTag.SABOTAGE], targeting:Targeting.OPPONENT, educational_tag:'resource_drain_deception', lore:"They burned their budget on bait. You reclaim yours.", modes_legal:PREDATOR, is_forced:false, drop_weight:14 },
  { cardId:'bluff_feint_005', name:'Feint', deckType:ModeDeckType.BLUFF, rarity:CardRarity.COMMON, timingClass:TimingClass.BLUFF, base_cost:6, base_effect:{effectType:CardEffectType.BLUFF_DISPLAY,magnitude:0,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.015,duration:0}}, tags:[CardTag.TEMPO,CardTag.COMBAT], targeting:Targeting.OPPONENT, educational_tag:'cheap_deception_mechanics', lore:'Low risk. Low cost. Makes them guess every time.', modes_legal:PREDATOR, is_forced:false, drop_weight:16 },
  { cardId:'bluff_empire_gambit_006', name:'Empire Gambit', deckType:ModeDeckType.BLUFF, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.BLUFF_DISPLAY,magnitude:0,duration:0,secondary:{effectType:CardEffectType.INCOME_BOOST,magnitude:7_000,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.SABOTAGE,CardTag.TEMPO,CardTag.COMBAT], targeting:Targeting.OPPONENT, educational_tag:'legendary_deception_play', lore:'Show them everything. Give them nothing. Take the rest.', modes_legal:PREDATOR, is_forced:false, drop_weight:LDW },
];

// ─── AID (7) — TEAM_UP ────────────────────────────────────────────────────────
const AID_CARDS: CardDefinition[] = [
  { cardId:'aid_cash_transfer_001', name:'Emergency Transfer', deckType:ModeDeckType.AID, rarity:CardRarity.COMMON, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.TREASURY_INJECT,magnitude:5_000,duration:0}, tags:[CardTag.COOPERATIVE,CardTag.TRUST,CardTag.LIQUIDITY], targeting:Targeting.TEAMMATE, educational_tag:'cooperative_resource_sharing', lore:'The strongest alliances are built on real commitments.', modes_legal:SYNDICATE, is_forced:false, drop_weight:18 },
  { cardId:'aid_income_loan_002', name:'Income Loan', deckType:ModeDeckType.AID, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.STANDARD, base_cost:0, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:1_500,duration:3}, tags:[CardTag.COOPERATIVE,CardTag.INCOME,CardTag.TRUST], targeting:Targeting.TEAMMATE, educational_tag:'structured_lending', lore:'Terms first. Friendship second. Both stronger for it.', modes_legal:SYNDICATE, is_forced:false, drop_weight:12 },
  { cardId:'aid_shield_boost_003', name:'Shield Boost', deckType:ModeDeckType.AID, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:18,duration:0,secondary:{effectType:CardEffectType.TRUST_SCORE_BOOST,magnitude:4,duration:0}}, tags:[CardTag.COOPERATIVE,CardTag.RESILIENCE,CardTag.TRUST], targeting:Targeting.TEAMMATE, educational_tag:'team_defensive_support', lore:'Their shield is your shield. Treat it that way.', modes_legal:SYNDICATE, is_forced:false, drop_weight:14 },
  { cardId:'aid_heat_absorb_004', name:'Heat Absorption', deckType:ModeDeckType.AID, rarity:CardRarity.RARE, timingClass:TimingClass.REACTIVE, base_cost:0, base_effect:{effectType:CardEffectType.HATER_HEAT_REDUCE,magnitude:20,duration:0,secondary:{effectType:CardEffectType.TRUST_SCORE_BOOST,magnitude:6,duration:0}}, tags:[CardTag.COOPERATIVE,CardTag.RESILIENCE,CardTag.TRUST], targeting:Targeting.TEAMMATE, educational_tag:'heat_management_cooperation', lore:"You absorbed their pressure. That's alliance.", modes_legal:SYNDICATE, is_forced:false, drop_weight:9 },
  { cardId:'aid_liquidity_advance_005', name:'Liquidity Advance', deckType:ModeDeckType.AID, rarity:CardRarity.COMMON, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.TREASURY_INJECT,magnitude:3_000,duration:0}, tags:[CardTag.COOPERATIVE,CardTag.LIQUIDITY,CardTag.TRUST], targeting:Targeting.TEAMMATE, educational_tag:'cooperative_liquidity_mechanics', lore:'Liquidity shared is sovereignty preserved.', modes_legal:SYNDICATE, is_forced:false, drop_weight:16 },
  { cardId:'aid_knowledge_transfer_006', name:'Knowledge Transfer', deckType:ModeDeckType.AID, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.STANDARD, base_cost:0, base_effect:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.025,duration:0,secondary:{effectType:CardEffectType.TRUST_SCORE_BOOST,magnitude:5,duration:0}}, tags:[CardTag.COOPERATIVE,CardTag.TRUST,CardTag.REAL_WORLD_FINANCE], targeting:Targeting.TEAMMATE, educational_tag:'knowledge_as_currency', lore:'What you teach multiplies through every decision they make after.', modes_legal:SYNDICATE, is_forced:false, drop_weight:11 },
  { cardId:'aid_strategic_reserve_007', name:'Strategic Reserve', deckType:ModeDeckType.AID, rarity:CardRarity.EPIC, timingClass:TimingClass.STANDARD, base_cost:0, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:3_000,duration:2,secondary:{effectType:CardEffectType.TRUST_SCORE_BOOST,magnitude:10,duration:0}}, tags:[CardTag.COOPERATIVE,CardTag.INCOME,CardTag.TRUST,CardTag.LIQUIDITY], targeting:Targeting.TEAM_ALL, educational_tag:'collective_reserve_strategy', lore:'The reserve is a weapon every member agreed to build.', modes_legal:SYNDICATE, is_forced:false, drop_weight:5 },
];

// ─── RESCUE (5) — TEAM_UP ─────────────────────────────────────────────────────
const RESCUE_CARDS: CardDefinition[] = [
  { cardId:'rescue_shield_restore_001', name:'Emergency Shield Restore', deckType:ModeDeckType.RESCUE, rarity:CardRarity.RARE, timingClass:TimingClass.RESCUE_WINDOW, base_cost:0, base_effect:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:40,duration:0}, tags:[CardTag.COOPERATIVE,CardTag.RESILIENCE,CardTag.TRUST], targeting:Targeting.TEAMMATE, educational_tag:'crisis_intervention', lore:'The faster you arrive, the more of them you save.', modes_legal:SYNDICATE, is_forced:false, drop_weight:10 },
  { cardId:'rescue_pressure_absorb_002', name:'Pressure Absorption', deckType:ModeDeckType.RESCUE, rarity:CardRarity.EPIC, timingClass:TimingClass.RESCUE_WINDOW, base_cost:0, base_effect:{effectType:CardEffectType.HATER_HEAT_REDUCE,magnitude:25,duration:0,secondary:{effectType:CardEffectType.TRUST_SCORE_BOOST,magnitude:8,duration:0}}, tags:[CardTag.COOPERATIVE,CardTag.TRUST,CardTag.RESILIENCE], targeting:Targeting.TEAMMATE, educational_tag:'network_support_systems', lore:"You took the hit. That's the kind of partner people fight for.", modes_legal:SYNDICATE, is_forced:false, drop_weight:6 },
  { cardId:'rescue_emergency_cash_003', name:'Emergency Capital Drop', deckType:ModeDeckType.RESCUE, rarity:CardRarity.EPIC, timingClass:TimingClass.RESCUE_WINDOW, base_cost:0, base_effect:{effectType:CardEffectType.TREASURY_INJECT,magnitude:12_000,duration:0,secondary:{effectType:CardEffectType.TRUST_SCORE_BOOST,magnitude:12,duration:0}}, tags:[CardTag.COOPERATIVE,CardTag.LIQUIDITY,CardTag.TRUST], targeting:Targeting.TEAMMATE, educational_tag:'emergency_capital_deployment', lore:'Capital at the right moment is worth ten times its face value.', modes_legal:SYNDICATE, is_forced:false, drop_weight:4 },
  { cardId:'rescue_cascade_break_004', name:'Cascade Break', deckType:ModeDeckType.RESCUE, rarity:CardRarity.RARE, timingClass:TimingClass.RESCUE_WINDOW, base_cost:0, base_effect:{effectType:CardEffectType.CASCADE_INTERRUPT,magnitude:2,duration:0,secondary:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:15,duration:0}}, tags:[CardTag.COOPERATIVE,CardTag.RESILIENCE,CardTag.TRUST], targeting:Targeting.TEAMMATE, educational_tag:'cascade_rescue_mechanics', lore:'You broke the chain before it swallowed them. That is loyalty.', modes_legal:SYNDICATE, is_forced:false, drop_weight:7 },
  { cardId:'rescue_full_extraction_005', name:'Full Extraction', deckType:ModeDeckType.RESCUE, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.SHIELD_REPAIR,magnitude:50,duration:0,secondary:{effectType:CardEffectType.TRUST_SCORE_BOOST,magnitude:20,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.COOPERATIVE,CardTag.RESILIENCE,CardTag.TRUST], targeting:Targeting.TEAMMATE, educational_tag:'total_teammate_recovery', lore:'This is what a Syndicate exists for. Pull them out of the fire.', modes_legal:SYNDICATE, is_forced:false, drop_weight:LDW },
];

// ─── TRUST (6) — TEAM_UP ──────────────────────────────────────────────────────
const TRUST_CARDS: CardDefinition[] = [
  { cardId:'trust_signal_001', name:'Trust Signal', deckType:ModeDeckType.TRUST, rarity:CardRarity.COMMON, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.TRUST_SCORE_BOOST,magnitude:10,duration:0}, tags:[CardTag.TRUST,CardTag.COOPERATIVE], targeting:Targeting.TEAM_ALL, educational_tag:'trust_building_investment', lore:'Trust compounds. Plant it early.', modes_legal:SYNDICATE, is_forced:false, drop_weight:16 },
  { cardId:'trust_covenant_002', name:'Covenant', deckType:ModeDeckType.TRUST, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.STANDARD, base_cost:0, base_effect:{effectType:CardEffectType.TRUST_SCORE_BOOST,magnitude:18,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.02,duration:0}}, tags:[CardTag.TRUST,CardTag.COOPERATIVE], targeting:Targeting.TEAM_ALL, educational_tag:'covenant_alliance_mechanics', lore:'A covenant is not a contract. It is a commitment to a shared future.', modes_legal:SYNDICATE, is_forced:false, drop_weight:12 },
  { cardId:'trust_bond_003', name:'Trust Bond', deckType:ModeDeckType.TRUST, rarity:CardRarity.RARE, timingClass:TimingClass.STANDARD, base_cost:0, base_effect:{effectType:CardEffectType.TRUST_SCORE_BOOST,magnitude:22,duration:0,secondary:{effectType:CardEffectType.INCOME_BOOST,magnitude:1_200,duration:2}}, tags:[CardTag.TRUST,CardTag.COOPERATIVE,CardTag.INCOME], targeting:Targeting.TEAM_ALL, educational_tag:'trust_economic_returns', lore:'High trust Syndicates earn more. This is not philosophy. It is economics.', modes_legal:SYNDICATE, is_forced:false, drop_weight:9 },
  { cardId:'trust_alliance_004', name:'Alliance Pact', deckType:ModeDeckType.TRUST, rarity:CardRarity.EPIC, timingClass:TimingClass.STANDARD, base_cost:0, base_effect:{effectType:CardEffectType.TRUST_SCORE_BOOST,magnitude:30,duration:0,secondary:{effectType:CardEffectType.TREASURY_INJECT,magnitude:4_000,duration:0}}, tags:[CardTag.TRUST,CardTag.COOPERATIVE,CardTag.LIQUIDITY], targeting:Targeting.TEAM_ALL, educational_tag:'formal_alliance_mechanics', lore:'The pact is signed not in ink. In shared risk and shared reward.', modes_legal:SYNDICATE, is_forced:false, drop_weight:5 },
  { cardId:'trust_loyalty_test_005', name:'Loyalty Test', deckType:ModeDeckType.TRUST, rarity:CardRarity.RARE, timingClass:TimingClass.FORCED, base_cost:0, base_effect:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.05,duration:0,secondary:{effectType:CardEffectType.TRUST_SCORE_BOOST,magnitude:15,duration:0}}, tags:[CardTag.TRUST,CardTag.COOPERATIVE], targeting:Targeting.SELF, educational_tag:'loyalty_stress_testing', lore:'The test is not punishment. It reveals who you are when it costs you.', modes_legal:SYNDICATE, is_forced:true, drop_weight:0 },
  { cardId:'trust_sovereign_pact_006', name:'Sovereign Pact', deckType:ModeDeckType.TRUST, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.TRUST_SCORE_BOOST,magnitude:50,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.08,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.TRUST,CardTag.COOPERATIVE], targeting:Targeting.TEAM_ALL, educational_tag:'sovereign_alliance_peak', lore:'Maximum trust. Maximum sovereignty. The Syndicate becomes one entity.', modes_legal:SYNDICATE, is_forced:false, drop_weight:LDW },
];

// ─── DEFECTION (3) — TEAM_UP sequential arc ───────────────────────────────────
const DEFECTION_CARDS: CardDefinition[] = [
  { cardId:'def_break_pact_001', name:'Break Pact', deckType:ModeDeckType.DEFECTION, rarity:CardRarity.EPIC, timingClass:TimingClass.DEFECTION_STEP, base_cost:0, base_effect:{effectType:CardEffectType.TRUST_SCORE_DRAIN,magnitude:20,duration:0}, tags:[CardTag.SABOTAGE], targeting:Targeting.SELF, educational_tag:'alliance_dissolution', lore:'Step one of three. There is no going back from here.', modes_legal:SYNDICATE, is_forced:false, drop_weight:2 },
  { cardId:'def_silent_exit_002', name:'Silent Exit', deckType:ModeDeckType.DEFECTION, rarity:CardRarity.EPIC, timingClass:TimingClass.DEFECTION_STEP, base_cost:0, base_effect:{effectType:CardEffectType.TRUST_SCORE_DRAIN,magnitude:30,duration:0}, tags:[CardTag.SABOTAGE], targeting:Targeting.SELF, educational_tag:'covert_asset_positioning', lore:"Step two. They may see it now. It's too late either way.", modes_legal:SYNDICATE, is_forced:false, drop_weight:2 },
  { cardId:'def_asset_seizure_003', name:'Asset Seizure', deckType:ModeDeckType.DEFECTION, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.DEFECTION_STEP, base_cost:0, base_effect:{effectType:CardEffectType.TREASURY_DRAIN,magnitude:0.4,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:-LDW*0.15,duration:0}}, tags:[CardTag.SABOTAGE,CardTag.LEVERAGE], targeting:Targeting.TEAM_ALL, educational_tag:'defection_consequences', lore:'Step three. The betrayal is complete. The CORD penalty is permanent.', modes_legal:SYNDICATE, is_forced:false, drop_weight:1 },
];

// ─── GHOST (6) — CHASE_A_LEGEND ───────────────────────────────────────────────
const GHOST_CARDS: CardDefinition[] = [
  { cardId:'ghost_gold_read_001', name:'Gold Marker Read', deckType:ModeDeckType.GHOST, rarity:CardRarity.RARE, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.08,duration:0}, tags:[CardTag.PRECISION,CardTag.DETERMINISTIC], targeting:Targeting.GHOST_REF, educational_tag:'pattern_recognition', lore:'The gold markers show where they were strongest. Become stronger there.', modes_legal:PHANTOM, is_forced:false, drop_weight:12 },
  { cardId:'ghost_red_exploit_002', name:'Red Marker Exploit', deckType:ModeDeckType.GHOST, rarity:CardRarity.EPIC, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.12,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.04,duration:0}}, tags:[CardTag.PRECISION,CardTag.TEMPO], targeting:Targeting.GHOST_REF, educational_tag:'competitive_gap_exploitation', lore:"The red markers show where they cracked. Don't crack there.", modes_legal:PHANTOM, is_forced:false, drop_weight:7 },
  { cardId:'ghost_gold_pattern_003', name:'Gold Pattern Lock', deckType:ModeDeckType.GHOST, rarity:CardRarity.RARE, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.15,duration:0,secondary:{effectType:CardEffectType.VARIANCE_LOCK,magnitude:2,duration:2}}, tags:[CardTag.PRECISION,CardTag.DETERMINISTIC,CardTag.VARIANCE_RED], targeting:Targeting.GHOST_REF, educational_tag:'gold_pattern_replication', lore:'Their best decisions are not secrets. They are maps. Use them.', modes_legal:PHANTOM, is_forced:false, drop_weight:8 },
  { cardId:'ghost_gold_timing_004', name:'Gold Timing Sync', deckType:ModeDeckType.GHOST, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.VARIANCE_LOCK,magnitude:3,duration:3,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.02,duration:0}}, tags:[CardTag.PRECISION,CardTag.VARIANCE_RED,CardTag.TEMPO], targeting:Targeting.GHOST_REF, educational_tag:'timing_synchronization', lore:'Their rhythm is documented. Synchronize. Then surpass.', modes_legal:PHANTOM, is_forced:false, drop_weight:10 },
  { cardId:'ghost_red_gap_005', name:'Red Gap Strike', deckType:ModeDeckType.GHOST, rarity:CardRarity.EPIC, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.18,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.05,duration:0}}, tags:[CardTag.PRECISION,CardTag.TEMPO,CardTag.DETERMINISTIC], targeting:Targeting.GHOST_REF, educational_tag:'red_marker_gap_exploitation', lore:'Every red marker is an open door. Enter precisely.', modes_legal:PHANTOM, is_forced:false, drop_weight:5 },
  { cardId:'ghost_legend_mirror_006', name:'Legend Mirror', deckType:ModeDeckType.GHOST, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.35,duration:0,secondary:{effectType:CardEffectType.PROOF_BADGE_UNLOCK,magnitude:1,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.PRECISION,CardTag.DETERMINISTIC], targeting:Targeting.GHOST_REF, educational_tag:'legend_mirror_play', lore:'The closest you can get to being them without erasing you.', modes_legal:PHANTOM, is_forced:false, drop_weight:LDW },
];

// ─── GAP_EXPLOIT (5) — CHASE_A_LEGEND ────────────────────────────────────────
// NOTE: types.ts must add: ModeDeckType.GAP_EXPLOIT = 'GAP_EXPLOIT'
// CARD_LEGALITY_MATRIX[CHASE_A_LEGEND] must include GAP_EXPLOIT
const GAP_EXPLOIT_CARDS: CardDefinition[] = [
  { cardId:'gap_income_diff_001', name:'Income Differential', deckType:ModeDeckType.GAP_EXPLOIT, rarity:CardRarity.RARE, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.10,duration:0,secondary:{effectType:CardEffectType.INCOME_BOOST,magnitude:1_800,duration:0}}, tags:[CardTag.PRECISION,CardTag.INCOME,CardTag.DETERMINISTIC], targeting:Targeting.GHOST_REF, educational_tag:'income_gap_analysis', lore:'Calculate the income gap first. Then close it systematically.', modes_legal:PHANTOM, is_forced:false, drop_weight:10 },
  { cardId:'gap_tempo_advantage_002', name:'Tempo Advantage', deckType:ModeDeckType.GAP_EXPLOIT, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.VARIANCE_LOCK,magnitude:2,duration:2,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.02,duration:0}}, tags:[CardTag.PRECISION,CardTag.TEMPO,CardTag.VARIANCE_RED], targeting:Targeting.GHOST_REF, educational_tag:'tempo_gap_mechanics', lore:'They moved faster at this moment. Match the tempo. Exceed the outcome.', modes_legal:PHANTOM, is_forced:false, drop_weight:13 },
  { cardId:'gap_decision_edge_003', name:'Decision Edge', deckType:ModeDeckType.GAP_EXPLOIT, rarity:CardRarity.EPIC, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.20,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.06,duration:0}}, tags:[CardTag.PRECISION,CardTag.DETERMINISTIC,CardTag.TEMPO], targeting:Targeting.GHOST_REF, educational_tag:'decision_quality_gap', lore:'One better decision per phase compresses the gap permanently.', modes_legal:PHANTOM, is_forced:false, drop_weight:5 },
  { cardId:'gap_legendary_gap_004', name:'Legend Gap', deckType:ModeDeckType.GAP_EXPLOIT, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.40,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.10,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.PRECISION,CardTag.DETERMINISTIC], targeting:Targeting.GHOST_REF, educational_tag:'legend_gap_compression', lore:'The gap was never their superiority. It was your unexploited potential.', modes_legal:PHANTOM, is_forced:false, drop_weight:LDW },
  { cardId:'gap_precision_close_005', name:'Precision Close', deckType:ModeDeckType.GAP_EXPLOIT, rarity:CardRarity.RARE, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.VARIANCE_LOCK,magnitude:3,duration:3,secondary:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.12,duration:0}}, tags:[CardTag.PRECISION,CardTag.VARIANCE_RED,CardTag.DETERMINISTIC], targeting:Targeting.GHOST_REF, educational_tag:'precision_gap_closure', lore:'Lock variance. Reduce divergence. Close the gap with surgical accuracy.', modes_legal:PHANTOM, is_forced:false, drop_weight:7 },
];

// ─── DYNASTY (5) — CHASE_A_LEGEND ────────────────────────────────────────────
// NOTE: types.ts must add: ModeDeckType.DYNASTY = 'DYNASTY'
// CARD_LEGALITY_MATRIX[CHASE_A_LEGEND] must include DYNASTY
const DYNASTY_CARDS: CardDefinition[] = [
  { cardId:'dyn_legend_benchmark_001', name:'Legend Benchmark', deckType:ModeDeckType.DYNASTY, rarity:CardRarity.RARE, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.PROOF_BADGE_UNLOCK,magnitude:1,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.04,duration:0}}, tags:[CardTag.PRECISION,CardTag.DETERMINISTIC], targeting:Targeting.GHOST_REF, educational_tag:'legend_benchmark_analysis', lore:"The Legend's benchmark is not a ceiling. It is a coordinate.", modes_legal:PHANTOM, is_forced:false, drop_weight:8 },
  { cardId:'dyn_heritage_play_002', name:'Heritage Play', deckType:ModeDeckType.DYNASTY, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.08,duration:0,secondary:{effectType:CardEffectType.VARIANCE_LOCK,magnitude:1,duration:2}}, tags:[CardTag.PRECISION,CardTag.VARIANCE_RED], targeting:Targeting.GHOST_REF, educational_tag:'dynasty_heritage_mechanics', lore:'Their dynasty was built one documented decision at a time. So is yours.', modes_legal:PHANTOM, is_forced:false, drop_weight:11 },
  { cardId:'dyn_apex_moment_003', name:'Apex Moment', deckType:ModeDeckType.DYNASTY, rarity:CardRarity.EPIC, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.09,duration:0,secondary:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.10,duration:0}}, tags:[CardTag.PRECISION,CardTag.DETERMINISTIC,CardTag.TEMPO], targeting:Targeting.GHOST_REF, educational_tag:'dynasty_apex_replication', lore:'Their apex moment is recorded. Study it. Recreate it. Then go further.', modes_legal:PHANTOM, is_forced:false, drop_weight:5 },
  { cardId:'dyn_immortal_sequence_004', name:'Immortal Sequence', deckType:ModeDeckType.DYNASTY, rarity:CardRarity.RARE, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.VARIANCE_LOCK,magnitude:4,duration:4,secondary:{effectType:CardEffectType.PROOF_BADGE_UNLOCK,magnitude:1,duration:0}}, tags:[CardTag.PRECISION,CardTag.VARIANCE_RED,CardTag.DETERMINISTIC], targeting:Targeting.GHOST_REF, educational_tag:'immortal_sequence_mechanics', lore:'Some decisions were so precise they became permanent records. Add yours.', modes_legal:PHANTOM, is_forced:false, drop_weight:6 },
  { cardId:'dyn_sovereign_legacy_005', name:'Sovereign Legacy', deckType:ModeDeckType.DYNASTY, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.PROOF_BADGE_UNLOCK,magnitude:1,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.12,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.PRECISION,CardTag.DETERMINISTIC], targeting:Targeting.GHOST_REF, educational_tag:'sovereign_legacy_creation', lore:'You did not just chase the Legend. You became one.', modes_legal:PHANTOM, is_forced:false, drop_weight:LDW },
];

// ─── DISCIPLINE (4) — CHASE_A_LEGEND ─────────────────────────────────────────
const DISCIPLINE_CARDS: CardDefinition[] = [
  { cardId:'disc_variance_lock_001', name:'Variance Lock', deckType:ModeDeckType.DISCIPLINE, rarity:CardRarity.UNCOMMON, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.VARIANCE_LOCK,magnitude:3,duration:3}, tags:[CardTag.VARIANCE_RED,CardTag.DETERMINISTIC,CardTag.PRECISION], targeting:Targeting.SELF, educational_tag:'variance_reduction_strategy', lore:'Chaos is the enemy of comparison. Remove it systematically.', modes_legal:PHANTOM, is_forced:false, drop_weight:18 },
  { cardId:'disc_timing_calibrate_002', name:'Timing Calibration', deckType:ModeDeckType.DISCIPLINE, rarity:CardRarity.RARE, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.VARIANCE_LOCK,magnitude:2,duration:2,secondary:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.04,duration:0}}, tags:[CardTag.VARIANCE_RED,CardTag.PRECISION,CardTag.TEMPO], targeting:Targeting.SELF, educational_tag:'decision_timing_optimization', lore:"They didn't play better cards. They played the same cards at the right moment.", modes_legal:PHANTOM, is_forced:false, drop_weight:10 },
  { cardId:'disc_pattern_hold_003', name:'Pattern Hold', deckType:ModeDeckType.DISCIPLINE, rarity:CardRarity.EPIC, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.VARIANCE_LOCK,magnitude:4,duration:4,secondary:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.07,duration:0}}, tags:[CardTag.VARIANCE_RED,CardTag.PRECISION,CardTag.DETERMINISTIC], targeting:Targeting.SELF, educational_tag:'pattern_discipline_mechanics', lore:'Hold the pattern. Do not deviate. Precision is repetition.', modes_legal:PHANTOM, is_forced:false, drop_weight:6 },
  { cardId:'disc_absolute_focus_004', name:'Absolute Focus', deckType:ModeDeckType.DISCIPLINE, rarity:CardRarity.RARE, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.VARIANCE_LOCK,magnitude:5,duration:5,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.03,duration:0}}, tags:[CardTag.VARIANCE_RED,CardTag.DETERMINISTIC,CardTag.PRECISION], targeting:Targeting.SELF, educational_tag:'absolute_focus_economics', lore:'Locked for five decision cycles. Every variable eliminated. This is what precision costs.', modes_legal:PHANTOM, is_forced:false, drop_weight:7 },
];

// ─── CROSS-MODE LEGENDARIES (6) ───────────────────────────────────────────────
const LEGENDARY_CARDS: CardDefinition[] = [
  { cardId:'leg_sovereign_strike_001', name:'Sovereign Strike', deckType:BaseDeckType.PRIVILEGED, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.BOT_NEUTRALIZE,magnitude:5,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.10,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.COMBAT,CardTag.RESILIENCE], targeting:Targeting.SELF, educational_tag:'decisive_high_leverage_action', lore:'Cannot be blocked by any hater bot. This is what sovereignty looks like.', modes_legal:ALL_MODES, is_forced:false, drop_weight:LDW },
  { cardId:'leg_freedom_engine_002', name:'Freedom Engine', deckType:BaseDeckType.IPA, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.INCOME_BOOST,magnitude:10_000,duration:0,secondary:{effectType:CardEffectType.HATER_HEAT_REDUCE,magnitude:40,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.INCOME,CardTag.COMPOUNDING,CardTag.AUTOMATION], targeting:Targeting.SELF, educational_tag:'financial_independence_mechanics', lore:'This is the run-defining moment. Play it correctly and the story changes.', modes_legal:ALL_MODES, is_forced:false, drop_weight:LDW },
  { cardId:'leg_empire_collapse_003', name:'Empire Collapse', deckType:BaseDeckType.FUBAR, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.FORCED, base_cost:0, base_effect:{effectType:CardEffectType.CASCADE_ACCELERATE,magnitude:4,duration:0,secondary:{effectType:CardEffectType.EXPENSE_SPIKE,magnitude:25_000,duration:3}}, tags:[CardTag.LEGENDARY_TAG,CardTag.RESILIENCE], targeting:Targeting.ENGINE, educational_tag:'empire_collapse_survival', lore:'The greatest test of an empire is not expansion. It is surviving collapse.', modes_legal:EMPIRE, is_forced:true, drop_weight:0 },
  { cardId:'leg_phantom_override_004', name:'Phantom Override', deckType:ModeDeckType.GHOST, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.DIVERGENCE_REDUCE,magnitude:0.50,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.15,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.PRECISION,CardTag.DETERMINISTIC], targeting:Targeting.GHOST_REF, educational_tag:'phantom_override_mechanics', lore:'The ghost never expected you to close the gap this completely.', modes_legal:PHANTOM, is_forced:false, drop_weight:LDW },
  { cardId:'leg_syndicate_rupture_005', name:'Syndicate Rupture', deckType:ModeDeckType.DEFECTION, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.TREASURY_DRAIN,magnitude:0.6,duration:0,secondary:{effectType:CardEffectType.TRUST_SCORE_DRAIN,magnitude:60,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.SABOTAGE], targeting:Targeting.TEAM_ALL, educational_tag:'alliance_rupture_consequences', lore:'When a Syndicate breaks at this level, the entire system remembers.', modes_legal:SYNDICATE, is_forced:false, drop_weight:LDW },
  { cardId:'leg_predator_apex_006', name:'Predator Apex', deckType:ModeDeckType.SABOTAGE, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.EXTRACTION_FIRE,magnitude:30_000,duration:0,secondary:{effectType:CardEffectType.BOT_NEUTRALIZE,magnitude:3,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.SABOTAGE,CardTag.COMBAT], targeting:Targeting.OPPONENT, educational_tag:'predator_apex_strike', lore:'The apex predator does not threaten. It executes.', modes_legal:PREDATOR, is_forced:false, drop_weight:LDW },
];

// ─── PROOF BADGE (3) ──────────────────────────────────────────────────────────
const PROOF_BADGE_CARDS: CardDefinition[] = [
  { cardId:'badge_ghost_hunter_001', name:'Ghost Hunter', deckType:ModeDeckType.GHOST, rarity:CardRarity.EPIC, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.PROOF_BADGE_UNLOCK,magnitude:1,duration:0}, tags:[CardTag.PRECISION,CardTag.DETERMINISTIC], targeting:Targeting.GHOST_REF, educational_tag:'excellence_documentation', lore:'Beat the ghost at its own game. The proof card will say so permanently.', modes_legal:PHANTOM, is_forced:false, drop_weight:4 },
  { cardId:'badge_legend_slayer_002', name:'Legend Slayer', deckType:ModeDeckType.GHOST, rarity:CardRarity.EPIC, timingClass:TimingClass.IMMEDIATE, base_cost:0, base_effect:{effectType:CardEffectType.PROOF_BADGE_UNLOCK,magnitude:1,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.06,duration:0}}, tags:[CardTag.PRECISION,CardTag.DETERMINISTIC], targeting:Targeting.GHOST_REF, educational_tag:'legend_defeat_documentation', lore:"You didn't just close the gap. You opened a lead.", modes_legal:PHANTOM, is_forced:false, drop_weight:3 },
  { cardId:'badge_dynasty_architect_003', name:'Dynasty Architect', deckType:ModeDeckType.DYNASTY, rarity:CardRarity.LEGENDARY, timingClass:TimingClass.LEGENDARY, base_cost:0, base_effect:{effectType:CardEffectType.PROOF_BADGE_UNLOCK,magnitude:3,duration:0,secondary:{effectType:CardEffectType.CORD_BONUS_FLAT,magnitude:0.15,duration:0}}, tags:[CardTag.LEGENDARY_TAG,CardTag.PRECISION,CardTag.DETERMINISTIC], targeting:Targeting.GHOST_REF, educational_tag:'dynasty_architecture', lore:'Three badges. One run. The Dynasty Architect leaves nothing undocumented.', modes_legal:PHANTOM, is_forced:false, drop_weight:LDW },
];

// ═══════════════════════════════════════════════════════════════════════════════
// MASTER REGISTRY — 120 definitions
// ═══════════════════════════════════════════════════════════════════════════════

const ALL_CARD_DEFINITIONS: CardDefinition[] = [
  ...OPPORTUNITY_CARDS,    //  9
  ...IPA_CARDS,            //  8
  ...FUBAR_CARDS,          //  8
  ...PRIVILEGED_CARDS,     //  6
  ...SO_CARDS,             //  7
  ...PHASE_BOUNDARY_CARDS, //  6
  ...SABOTAGE_CARDS,       // 10
  ...COUNTER_CARDS,        //  7
  ...BLUFF_CARDS,          //  6
  ...AID_CARDS,            //  7
  ...RESCUE_CARDS,         //  5
  ...TRUST_CARDS,          //  6
  ...DEFECTION_CARDS,      //  3
  ...GHOST_CARDS,          //  6
  ...GAP_EXPLOIT_CARDS,    //  5
  ...DYNASTY_CARDS,        //  5
  ...DISCIPLINE_CARDS,     //  4
  ...LEGENDARY_CARDS,      //  6
  ...PROOF_BADGE_CARDS,    //  3  → TOTAL: 122
];

const FROZEN_DEFINITIONS = ALL_CARD_DEFINITIONS.map(d => Object.freeze({ ...d }));

// Fail-fast duplicate ID assertion — runs once at module load
;(function assertUniqueIds() {
  const seen = new Set<string>();
  for (const d of FROZEN_DEFINITIONS) {
    if (seen.has(d.cardId)) throw new Error(`[CardRegistry] DUPLICATE cardId: '${d.cardId}'`);
    seen.add(d.cardId);
  }
})();

export const CARD_REGISTRY: ReadonlyMap<string, CardDefinition> = new Map(
  FROZEN_DEFINITIONS.map(d => [d.cardId, d])
);

export const CARDS_BY_DECK_TYPE: ReadonlyMap<string, CardDefinition[]> = new Map(
  Object.values({ ...BaseDeckType, ...ModeDeckType }).map(deckType => [
    deckType,
    FROZEN_DEFINITIONS.filter(d => d.deckType === deckType),
  ])
);

export function getCardDefinition(cardId: string): CardDefinition {
  const def = CARD_REGISTRY.get(cardId);
  if (!def) throw new Error(`[CardRegistry] Unknown cardId: '${cardId}'`);
  return def;
}
export function getDrawableCards(deckType: DeckType): CardDefinition[] {
  return (CARDS_BY_DECK_TYPE.get(deckType) ?? []).filter(d => d.drop_weight > 0);
}
export function getInjectedCards(): CardDefinition[] {
  return FROZEN_DEFINITIONS.filter(d => d.drop_weight === 0 && d.is_forced);
}
export function getCardsForMode(mode: GameMode): CardDefinition[] {
  return FROZEN_DEFINITIONS.filter(d => d.modes_legal.includes(mode));
}
export function getLegendaryCards(deckType?: DeckType): CardDefinition[] {
  return FROZEN_DEFINITIONS.filter(d => d.rarity === CardRarity.LEGENDARY && (!deckType || d.deckType === deckType));
}
export { ALL_CARD_DEFINITIONS };