#!/usr/bin/env python3
"""pzo_fs.py — safe file write utilities, scaffold helpers, SHA-256 verification.

Version: 2.0.0 (2026-02-27)
"""

from __future__ import annotations

import hashlib
import os
import shutil
from pathlib import Path
from typing import Optional


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def atomic_write_text(path: Path, text: str) -> None:
    """Write text to path atomically using tmp+rename (crash-safe)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".writing.tmp")
    try:
        tmp.write_text(text, encoding="utf-8")
        os.replace(tmp, path)
    except Exception:
        try:
            tmp.unlink(missing_ok=True)
        except Exception:
            pass
        raise


def backup_file(path: Path) -> Optional[Path]:
    """Create a timestamped backup of path if it exists. Returns backup path or None."""
    if not path.exists():
        return None
    import time
    ts = int(time.time())
    bak = path.with_suffix(f"{path.suffix}.bak.{ts}")
    shutil.copy2(path, bak)
    return bak


def ensure_placeholder_ts(path: Path, export_name: Optional[str] = None) -> bool:
    """Create a typecheck-safe TypeScript placeholder if the file doesn't exist.

    Returns True if placeholder was created, False if file already existed.
    """
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    name = export_name or path.stem
    # Minimal export-safe placeholder that passes `tsc --noEmit`
    placeholder = (
        f"// FILE: {path.name}\n"
        f"// STATUS: placeholder — implementation pending\n"
        f"// DO NOT EDIT: generated by pzo_fs.ensure_placeholder_ts\n"
        f"\nexport {{}};\n"
    )
    path.write_text(placeholder, encoding="utf-8")
    return True


def ensure_dir(path: Path) -> None:
    """Create directory and all parents. Idempotent."""
    path.mkdir(parents=True, exist_ok=True)


def read_file_safe(path: Path, max_bytes: int = 0) -> Optional[str]:
    """Read a text file, returning None on any error. Optionally truncate."""
    try:
        if not path.exists():
            return None
        text = path.read_text(encoding="utf-8", errors="replace")
        if max_bytes and len(text) > max_bytes:
            text = text[:max_bytes] + "\n... [TRUNCATED]\n"
        return text
    except Exception:
        return None
