// AUTO-GENERATED by pzo_curriculum_gateway_generator.py — DO NOT EDIT MANUALLY
import { Request, Response, NextFunction } from 'express';

export function requireScope(...requiredScopes: string[]) {
  return (req: Request, res: Response, next: NextFunction): void => {
    const ctx = req.tenantContext;
    if (!ctx) {
      res.status(401).json({
        ok: false, requestId: 'unknown',
        error: { code: 'UNAUTHORIZED', message: 'No tenant context' },
      });
      return;
    }

    if (ctx.actorType === 'system_admin') {
      next();
      return;
    }

    const hasScope = requiredScopes.every(s => ctx.scopes.includes(s));
    if (!hasScope) {
      res.status(403).json({
        ok: false, requestId: ctx.requestId,
        error: {
          code: 'FORBIDDEN',
          message: `Missing required scope(s): ${requiredScopes.join(', ')}`,
        },
      });
      return;
    }

    next();
  };
}
