// AUTO-GENERATED by pzo_curriculum_gateway_generator.py — DO NOT EDIT MANUALLY
import { Request, Response, NextFunction } from 'express';
import { TenantContext } from './types';

export function resolveTenant(req: Request, res: Response, next: NextFunction): void {
  const requestId = (req.headers['x-request-id'] as string) || crypto.randomUUID();

  if (req.tenantContext) {
    req.tenantContext.requestId = requestId;
    next();
    return;
  }

  req.tenantContext = {
    requestId,
    institutionId: null,
    partnerId: null,
    actorType: 'player',
    actorId: 'anonymous',
    userId: 'anonymous',
    scopes: [],
    sessionId: 'anonymous',
    ipAddress: (req.headers['x-forwarded-for'] as string) || req.ip || 'unknown',
    userAgent: req.headers['user-agent'] || 'unknown',
  };

  next();
}
