// AUTO-GENERATED by pzo_curriculum_gateway_generator.py — DO NOT EDIT MANUALLY
      import { Request, Response, NextFunction } from 'express';

      const FLAG_DEFAULTS: Record<string, boolean> = {
        'curriculum.enabled': true,
'curriculum.institutions.enabled': true,
'curriculum.benchmarks.enabled': false,
'curriculum.reports.enabled': false,
'curriculum.exports.enabled': false,
'curriculum.facilitator_os.enabled': false,
'curriculum.webhooks.enabled': false,
'curriculum.creator_packs.enabled': false,
      };

      function isEnabled(flagName: string): boolean {
        const envKey = 'PZO_FF_' + flagName.toUpperCase().replace(/\./g, '_');
        const envVal = process.env[envKey];
        if (envVal !== undefined) {
          return envVal === 'true' || envVal === '1';
        }
        return FLAG_DEFAULTS[flagName] ?? false;
      }

      export function requireFlag(flagName: string) {
        return (req: Request, res: Response, next: NextFunction): void => {
          if (!isEnabled(flagName)) {
            res.status(404).json({
              ok: false,
              requestId: req.tenantContext?.requestId || 'unknown',
              error: { code: 'NOT_FOUND', message: 'Resource not found' },
            });
            return;
          }
          next();
        };
      }

      export { isEnabled };
