-- Point Zero One Digital - Backend Migrations - 0001_init_schema.sql - /Users/mervinlarry/workspaces/adam/Projects/adam/point_zero_one_master/backend/migrations/0001_init_schema.sql
BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION set_row_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    is_founder BOOLEAN NOT NULL DEFAULT FALSE,
    staking_balance_cents BIGINT NOT NULL DEFAULT 0,
    needs_re_verification BOOLEAN NOT NULL DEFAULT FALSE,
    re_verification_requested_at TIMESTAMPTZ,
    abuse_risk_score INTEGER NOT NULL DEFAULT 0,
    abuse_flags JSONB NOT NULL DEFAULT '[]'::jsonb,
    abuse_flagged_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT accounts_email_not_blank
        CHECK (char_length(btrim(email)) > 0),
    CONSTRAINT accounts_staking_balance_nonnegative
        CHECK (staking_balance_cents >= 0),
    CONSTRAINT accounts_abuse_risk_score_nonnegative
        CHECK (abuse_risk_score >= 0),
    CONSTRAINT accounts_abuse_flags_is_array
        CHECK (jsonb_typeof(abuse_flags) = 'array')
);

CREATE TABLE IF NOT EXISTS guest_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_ua VARCHAR(512) NOT NULL DEFAULT '',
    device_ip VARCHAR(45) NOT NULL DEFAULT '',
    run_history JSONB NOT NULL DEFAULT '[]'::jsonb,
    upgraded_to_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT guest_sessions_run_history_is_array
        CHECK (jsonb_typeof(run_history) = 'array')
);

CREATE UNIQUE INDEX IF NOT EXISTS accounts_email_normalized_uidx
    ON accounts ((lower(btrim(email))));

CREATE INDEX IF NOT EXISTS accounts_is_founder_idx
    ON accounts (is_founder);

CREATE INDEX IF NOT EXISTS accounts_needs_re_verification_idx
    ON accounts (needs_re_verification)
    WHERE needs_re_verification = TRUE;

CREATE INDEX IF NOT EXISTS accounts_abuse_risk_score_idx
    ON accounts (abuse_risk_score);

CREATE INDEX IF NOT EXISTS accounts_abuse_flagged_at_idx
    ON accounts (abuse_flagged_at);

CREATE INDEX IF NOT EXISTS accounts_abuse_flags_gin_idx
    ON accounts USING GIN (abuse_flags);

CREATE INDEX IF NOT EXISTS idx_guest_sessions_device
    ON guest_sessions (device_ua, device_ip);

CREATE INDEX IF NOT EXISTS guest_sessions_created_at_idx
    ON guest_sessions (created_at DESC);

CREATE INDEX IF NOT EXISTS guest_sessions_upgraded_to_id_idx
    ON guest_sessions (upgraded_to_id)
    WHERE upgraded_to_id IS NOT NULL;

DROP TRIGGER IF EXISTS guest_sessions_set_updated_at ON guest_sessions;
CREATE TRIGGER guest_sessions_set_updated_at
BEFORE UPDATE ON guest_sessions
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

COMMIT;