-- ============================================================================
-- POINT ZERO ONE — ENGINE ALIGNMENT SUPPLEMENT
-- 0002_engine_alignment.sql
-- ============================================================================
-- Purpose:
--   Add persistence surfaces that bridge the deployed schema to the live
--   engine contracts in pzo-web/src/engines/
--
--   1. Card mode overlay system (ModeOverlayEngine.ts)
--   2. Card tag weight override tables (CardScorer.ts)
--   3. CORD breakdown / integrity hardening (SovereigntyEngine.ts)
--   4. Run tick checksums (ReplayIntegrityChecker.ts)
--   5. Run proof artifacts (ProofGenerator.ts)
--   6. Verified Run Explorer projection (read model)
--   7. Contract reference tables (runtime ↔ persistence vocabulary)
--   8. Bot profile registry (BotProfileRegistry.ts)
--
-- Depends on: 0001_pzo_sovereign_schema.sql
-- Density6 LLC · Point Zero One · Sovereign Infrastructure
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1. CARD MODE OVERLAY SYSTEM
-- ============================================================================
-- ModeOverlayEngine.ts applies per-mode tag weight multipliers, cost modifiers,
-- targeting overrides, and legality at draw time. These tables persist that
-- configuration so it can be versioned and hot-reloaded.

-- 1.1 Per-card, per-mode legality
CREATE TABLE IF NOT EXISTS game.card_mode_legality (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_definition_id  INTEGER NOT NULL REFERENCES game.card_definitions(id) ON DELETE CASCADE,
    game_mode           game_mode NOT NULL,
    is_legal            BOOLEAN NOT NULL DEFAULT TRUE,
    reason              TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cml_card_mode_unique UNIQUE (card_definition_id, game_mode)
);

CREATE INDEX IF NOT EXISTS cml_mode_legal_idx ON game.card_mode_legality (game_mode, is_legal);
SELECT create_updated_at_trigger('game', 'card_mode_legality');

-- 1.2 Per-card, per-mode runtime overlays
CREATE TABLE IF NOT EXISTS game.card_mode_overlays (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_definition_id  INTEGER NOT NULL REFERENCES game.card_definitions(id) ON DELETE CASCADE,
    game_mode           game_mode NOT NULL,
    ruleset_version_id  INTEGER REFERENCES game.ruleset_versions(id) ON DELETE SET NULL,
    cost_multiplier     NUMERIC(8,4) NOT NULL DEFAULT 1.0,
    effect_multiplier   NUMERIC(8,4) NOT NULL DEFAULT 1.0,
    targeting_override  card_targeting,
    decision_timer_ms   INTEGER,
    timing_override     timing_class,
    overlay_json        JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cmo_overlay_is_object CHECK (jsonb_typeof(overlay_json) = 'object'),
    CONSTRAINT cmo_timer_nonneg CHECK (decision_timer_ms IS NULL OR decision_timer_ms >= 0),
    CONSTRAINT cmo_card_mode_unique UNIQUE (card_definition_id, game_mode)
);

CREATE INDEX IF NOT EXISTS cmo_mode_active_idx ON game.card_mode_overlays (game_mode, is_active);
SELECT create_updated_at_trigger('game', 'card_mode_overlays');

-- 1.3 Per-card, per-mode tag weight overrides
-- ModeOverlayEngine.ts: MODE_TAG_WEIGHTS[mode][tag] * card-specific override
CREATE TABLE IF NOT EXISTS game.card_tag_weight_overrides (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_definition_id  INTEGER NOT NULL REFERENCES game.card_definitions(id) ON DELETE CASCADE,
    game_mode           game_mode NOT NULL,
    tag                 VARCHAR(64) NOT NULL,
    weight              NUMERIC(8,4) NOT NULL DEFAULT 1.0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ctw_tag_not_blank CHECK (char_length(btrim(tag)) > 0),
    CONSTRAINT ctw_weight_positive CHECK (weight > 0),
    CONSTRAINT ctw_card_mode_tag_unique UNIQUE (card_definition_id, game_mode, tag)
);

CREATE INDEX IF NOT EXISTS ctw_mode_tag_idx ON game.card_tag_weight_overrides (game_mode, tag);

-- 1.4 Per-card, per-mode timing window permissions
CREATE TABLE IF NOT EXISTS game.card_timing_windows (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_definition_id  INTEGER NOT NULL REFERENCES game.card_definitions(id) ON DELETE CASCADE,
    game_mode           game_mode NOT NULL,
    timing              timing_class NOT NULL,
    is_allowed          BOOLEAN NOT NULL DEFAULT TRUE,
    window_duration_ms  INTEGER,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ctwin_duration_nonneg CHECK (window_duration_ms IS NULL OR window_duration_ms >= 0),
    CONSTRAINT ctwin_card_mode_timing_unique UNIQUE (card_definition_id, game_mode, timing)
);

CREATE INDEX IF NOT EXISTS ctwin_mode_timing_idx ON game.card_timing_windows (game_mode, timing);

-- ============================================================================
-- 2. CORD BREAKDOWN / INTEGRITY HARDENING
-- ============================================================================
-- SovereigntyEngine.ts completeRun() pipeline:
--   Step 1: ReplayIntegrityChecker.verify()
--   Step 2: ProofGenerator.generate() + buildSignature()
--   Step 3: RunGradeAssigner.computeScore()
-- These tables persist the detailed output of each step.

-- 2.1 CORD score breakdown per run
CREATE TABLE IF NOT EXISTS game.run_cord_breakdowns (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                  INTEGER NOT NULL REFERENCES game.runs(id) ON DELETE CASCADE,
    decision_speed_score    NUMERIC(12,6) NOT NULL DEFAULT 0,
    shields_maintained_pct  NUMERIC(12,6) NOT NULL DEFAULT 0,
    hater_sabotages_blocked INTEGER NOT NULL DEFAULT 0,
    cascade_chains_broken   INTEGER NOT NULL DEFAULT 0,
    pressure_survived_score NUMERIC(12,6) NOT NULL DEFAULT 0,
    outcome_multiplier      NUMERIC(8,4) NOT NULL DEFAULT 1.0,
    mode_multiplier         NUMERIC(8,4) NOT NULL DEFAULT 1.0,
    mode_bonus_json         JSONB NOT NULL DEFAULT '{}'::jsonb,
    raw_cord                NUMERIC(18,6) NOT NULL DEFAULT 0,
    final_cord              NUMERIC(18,6) NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rcb_mode_bonus_is_object CHECK (jsonb_typeof(mode_bonus_json) = 'object'),
    CONSTRAINT rcb_raw_cord_nonneg CHECK (raw_cord >= 0),
    CONSTRAINT rcb_final_cord_nonneg CHECK (final_cord >= 0),
    CONSTRAINT rcb_run_unique UNIQUE (run_id)
);

CREATE INDEX IF NOT EXISTS rcb_run_idx ON game.run_cord_breakdowns (run_id);
CREATE INDEX IF NOT EXISTS rcb_final_cord_idx ON game.run_cord_breakdowns (final_cord DESC);
SELECT create_updated_at_trigger('game', 'run_cord_breakdowns');

-- 2.2 Tick stream checksums (ReplayIntegrityChecker)
CREATE TABLE IF NOT EXISTS game.run_tick_checksums (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              INTEGER NOT NULL REFERENCES game.runs(id) ON DELETE CASCADE,
    first_tick          INTEGER NOT NULL,
    last_tick           INTEGER NOT NULL,
    tick_count          INTEGER NOT NULL,
    checksum_sha256     VARCHAR(64) NOT NULL,
    source              VARCHAR(32) NOT NULL DEFAULT 'engine',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rtc_first_tick_nonneg CHECK (first_tick >= 0),
    CONSTRAINT rtc_last_tick_nonneg CHECK (last_tick >= 0),
    CONSTRAINT rtc_tick_count_positive CHECK (tick_count > 0),
    CONSTRAINT rtc_range_valid CHECK (last_tick >= first_tick),
    CONSTRAINT rtc_checksum_format CHECK (char_length(btrim(checksum_sha256)) = 64),
    CONSTRAINT rtc_run_range_unique UNIQUE (run_id, first_tick, last_tick)
);

CREATE INDEX IF NOT EXISTS rtc_run_idx ON game.run_tick_checksums (run_id);

-- 2.3 Proof artifacts (ProofGenerator)
CREATE TABLE IF NOT EXISTS game.run_proof_artifacts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              INTEGER NOT NULL REFERENCES game.runs(id) ON DELETE CASCADE,
    proof_hash          VARCHAR(64) NOT NULL,
    artifact_kind       VARCHAR(32) NOT NULL,
    storage_url         VARCHAR(512),
    render_status       VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    border_style        VARCHAR(32),
    metadata_json       JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rpa_proof_hash_format CHECK (char_length(btrim(proof_hash)) = 64),
    CONSTRAINT rpa_kind_not_blank CHECK (char_length(btrim(artifact_kind)) > 0),
    CONSTRAINT rpa_render_status_valid CHECK (render_status IN ('PENDING','RENDERING','READY','FAILED')),
    CONSTRAINT rpa_metadata_is_object CHECK (jsonb_typeof(metadata_json) = 'object')
);

CREATE INDEX IF NOT EXISTS rpa_run_idx ON game.run_proof_artifacts (run_id);
CREATE INDEX IF NOT EXISTS rpa_kind_idx ON game.run_proof_artifacts (artifact_kind);
CREATE INDEX IF NOT EXISTS rpa_proof_hash_idx ON game.run_proof_artifacts (proof_hash);
SELECT create_updated_at_trigger('game', 'run_proof_artifacts');

-- 2.4 Integrity review queue
CREATE TABLE IF NOT EXISTS game.run_integrity_reviews (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              INTEGER NOT NULL REFERENCES game.runs(id) ON DELETE CASCADE,
    verdict             verification_status NOT NULL,
    reviewer_kind       VARCHAR(32) NOT NULL DEFAULT 'SYSTEM',
    proof_hash_at_review VARCHAR(64),
    tick_checksum_at_review VARCHAR(64),
    review_notes        TEXT,
    evidence_json       JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rir_evidence_is_object CHECK (jsonb_typeof(evidence_json) = 'object')
);

CREATE INDEX IF NOT EXISTS rir_run_idx ON game.run_integrity_reviews (run_id, created_at DESC);
CREATE INDEX IF NOT EXISTS rir_verdict_idx ON game.run_integrity_reviews (verdict);

-- ============================================================================
-- 3. ADDITIONAL RUN COLUMNS (safe ALTER ADD)
-- ============================================================================
-- Add tick_stream_checksum to runs for fast integrity lookup
ALTER TABLE game.runs
    ADD COLUMN IF NOT EXISTS tick_stream_checksum VARCHAR(64);

-- ============================================================================
-- 4. VERIFIED RUN EXPLORER (READ MODEL)
-- ============================================================================
-- Denormalized projection fed by SovereigntyEngine on RUN_COMPLETED.
-- The Verified Run Explorer queries this, not the operational runs table.

CREATE TABLE IF NOT EXISTS analytics.verified_run_explorer (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              INTEGER NOT NULL REFERENCES game.runs(id) ON DELETE CASCADE,
    user_id             INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    game_mode           game_mode NOT NULL,
    verification        verification_status NOT NULL,
    grade               run_grade,
    cord                NUMERIC(18,6) NOT NULL DEFAULT 0,
    outcome             run_outcome,
    proof_hash          VARCHAR(64),
    season_key          VARCHAR(32),
    is_public           BOOLEAN NOT NULL DEFAULT FALSE,
    filter_tags         TEXT[] NOT NULL DEFAULT '{}',
    highlight_json      JSONB NOT NULL DEFAULT '{}'::jsonb,
    completed_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vre_highlight_is_object CHECK (jsonb_typeof(highlight_json) = 'object'),
    CONSTRAINT vre_cord_nonneg CHECK (cord >= 0),
    CONSTRAINT vre_run_unique UNIQUE (run_id)
);

CREATE INDEX IF NOT EXISTS vre_mode_grade_cord_idx ON analytics.verified_run_explorer (game_mode, grade, cord DESC);
CREATE INDEX IF NOT EXISTS vre_verification_public_idx ON analytics.verified_run_explorer (verification, is_public, cord DESC);
CREATE INDEX IF NOT EXISTS vre_user_idx ON analytics.verified_run_explorer (user_id, cord DESC);
CREATE INDEX IF NOT EXISTS vre_filter_tags_gin_idx ON analytics.verified_run_explorer USING GIN (filter_tags);
CREATE INDEX IF NOT EXISTS vre_proof_hash_idx ON analytics.verified_run_explorer (proof_hash) WHERE proof_hash IS NOT NULL;
SELECT create_updated_at_trigger('analytics', 'verified_run_explorer');

-- 4.1 Proof card catalog (monetization surface)
CREATE TABLE IF NOT EXISTS analytics.proof_card_catalog (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              INTEGER NOT NULL REFERENCES game.runs(id) ON DELETE CASCADE,
    proof_artifact_id   BIGINT REFERENCES game.run_proof_artifacts(id) ON DELETE SET NULL,
    proof_hash          VARCHAR(64) NOT NULL,
    border_style        VARCHAR(32),
    price_shards        INTEGER NOT NULL DEFAULT 99,
    is_purchasable      BOOLEAN NOT NULL DEFAULT TRUE,
    metadata_json       JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pcc_metadata_is_object CHECK (jsonb_typeof(metadata_json) = 'object'),
    CONSTRAINT pcc_price_nonneg CHECK (price_shards >= 0),
    CONSTRAINT pcc_run_unique UNIQUE (run_id)
);

CREATE INDEX IF NOT EXISTS pcc_purchasable_idx ON analytics.proof_card_catalog (is_purchasable, created_at DESC);

-- ============================================================================
-- 5. BOT PROFILE REGISTRY (BotProfileRegistry.ts)
-- ============================================================================
-- Persists bot personality definitions so they can be versioned per ruleset.
-- BotProfileRegistry.ts currently hardcodes these — this table enables
-- hot-reload and A/B testing of bot behaviors.

CREATE TABLE IF NOT EXISTS game.bot_profiles (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id              bot_identity NOT NULL,
    ruleset_version_id  INTEGER REFERENCES game.ruleset_versions(id) ON DELETE SET NULL,
    display_name        VARCHAR(128) NOT NULL,
    personality_tag     VARCHAR(64) NOT NULL,
    attack_vector       VARCHAR(128) NOT NULL,
    base_heat           INTEGER NOT NULL DEFAULT 0,
    activation_phase    run_phase NOT NULL DEFAULT 'ESCALATION',
    config_json         JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bp_display_name_not_blank CHECK (char_length(btrim(display_name)) > 0),
    CONSTRAINT bp_personality_not_blank CHECK (char_length(btrim(personality_tag)) > 0),
    CONSTRAINT bp_heat_nonneg CHECK (base_heat >= 0),
    CONSTRAINT bp_config_is_object CHECK (jsonb_typeof(config_json) = 'object'),
    CONSTRAINT bp_bot_ruleset_unique UNIQUE (bot_id, ruleset_version_id)
);

CREATE INDEX IF NOT EXISTS bp_bot_idx ON game.bot_profiles (bot_id);
CREATE INDEX IF NOT EXISTS bp_active_idx ON game.bot_profiles (is_active) WHERE is_active = TRUE;
SELECT create_updated_at_trigger('game', 'bot_profiles');

-- Seed default bot profiles (matching BotProfileRegistry.ts)
INSERT INTO game.bot_profiles (bot_id, display_name, personality_tag, attack_vector, base_heat, activation_phase)
VALUES
    ('BOT_01', 'The Liquidator',    'aggressive',   'asset_stripping',     30, 'ESCALATION'),
    ('BOT_02', 'The Bureaucrat',    'passive',      'regulatory_friction', 15, 'FOUNDATION'),
    ('BOT_03', 'The Manipulator',   'deceptive',    'market_manipulation', 25, 'ESCALATION'),
    ('BOT_04', 'Crash Prophet',     'prophetic',    'crash_prediction',    40, 'SOVEREIGNTY'),
    ('BOT_05', 'Legacy Heir',       'entitled',     'inheritance_drain',   20, 'ESCALATION')
ON CONFLICT (bot_id, ruleset_version_id) DO NOTHING;

-- ============================================================================
-- 6. CONTRACT REFERENCE TABLES
-- ============================================================================
-- Single source of truth for runtime ↔ persistence vocabulary alignment.
-- Engine code can query these to validate enums at startup.

CREATE TABLE IF NOT EXISTS game.contract_game_modes (
    code            game_mode PRIMARY KEY,
    display_alias   VARCHAR(32) NOT NULL,
    display_name    VARCHAR(128) NOT NULL,
    tagline         VARCHAR(255),
    icon            VARCHAR(8),
    min_players     INTEGER NOT NULL DEFAULT 1,
    max_players     INTEGER NOT NULL DEFAULT 1,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO game.contract_game_modes (code, display_alias, display_name, tagline, icon, min_players, max_players)
VALUES
    ('GO_ALONE',        'EMPIRE',    'Go Alone',         'The Isolated Sovereign',   '🏛️', 1, 1),
    ('HEAD_TO_HEAD',    'PREDATOR',  'Head to Head',     'The Financial Predator',   '⚔️', 2, 2),
    ('TEAM_UP',         'SYNDICATE', 'Team Up',          'The Trust Architect',      '🤝', 2, 4),
    ('CHASE_A_LEGEND',  'PHANTOM',   'Chase a Legend',   'The Ghost Hunter',         '👻', 1, 1)
ON CONFLICT (code) DO NOTHING;

CREATE TABLE IF NOT EXISTS game.contract_timing_classes (
    code            timing_class PRIMARY KEY,
    description     TEXT NOT NULL,
    mode_scope      VARCHAR(64) NOT NULL DEFAULT 'ALL',
    window_default_ms INTEGER,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO game.contract_timing_classes (code, description, mode_scope, window_default_ms)
VALUES
    ('IMMEDIATE',           'Playable any tick, no restrictions',           'ALL', NULL),
    ('REACTIVE',            'Must play within 2 ticks of trigger',         'ALL', 2400),
    ('STANDARD',            'Normal play window, always open',             'ALL', NULL),
    ('HOLD',                'Empire only — timer paused, staged for later','GO_ALONE', NULL),
    ('COUNTER_WINDOW',      'Predator only — 5-sec defensive response',   'HEAD_TO_HEAD', 5000),
    ('RESCUE_WINDOW',       'Syndicate only — teammate rescue response',   'TEAM_UP', 8000),
    ('PHASE_BOUNDARY',      'Empire only — 5-tick window at phase edge',   'GO_ALONE', 6000),
    ('FORCED',              'Cannot be discarded, must resolve',           'ALL', NULL),
    ('LEGENDARY',           'Legendary card timing — rare window',         'ALL', 10000),
    ('BLUFF',               'Predator only — deception window',            'HEAD_TO_HEAD', 3000),
    ('DEFECTION_STEP',      'Syndicate only — 3-card betrayal arc step',   'TEAM_UP', 15000),
    ('SOVEREIGNTY_DECISION','Late-run terminal decision window',           'ALL', 30000)
ON CONFLICT (code) DO NOTHING;

CREATE TABLE IF NOT EXISTS game.contract_bot_profiles (
    code            bot_identity PRIMARY KEY,
    display_name    VARCHAR(128) NOT NULL,
    personality     VARCHAR(64) NOT NULL,
    attack_vector   VARCHAR(128) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO game.contract_bot_profiles (code, display_name, personality, attack_vector)
VALUES
    ('BOT_01', 'The Liquidator',  'aggressive', 'asset_stripping'),
    ('BOT_02', 'The Bureaucrat',  'passive',    'regulatory_friction'),
    ('BOT_03', 'The Manipulator', 'deceptive',  'market_manipulation'),
    ('BOT_04', 'Crash Prophet',   'prophetic',  'crash_prediction'),
    ('BOT_05', 'Legacy Heir',     'entitled',   'inheritance_drain')
ON CONFLICT (code) DO NOTHING;

-- ============================================================================
-- 7. ENGINE STATE PERSISTENCE VIEWS
-- ============================================================================
-- Convenience views for common engine queries. PgBouncer-safe (no SET).

-- Active runs per mode (for matchmaking / capacity)
CREATE OR REPLACE VIEW game.v_active_runs AS
SELECT
    game_mode,
    COUNT(*) AS active_count,
    MIN(started_at) AS oldest_start,
    MAX(total_ticks) AS max_ticks
FROM game.runs
WHERE status IN ('RUNNING','LOADING','PAUSED')
GROUP BY game_mode;

-- Leaderboard-ready verified runs
CREATE OR REPLACE VIEW analytics.v_leaderboard_verified AS
SELECT
    r.id AS run_id,
    r.user_id,
    u.handle,
    r.game_mode,
    r.cord_final,
    r.grade,
    r.outcome,
    r.proof_hash,
    r.is_bleed_mode,
    r.completed_at
FROM game.runs r
JOIN users u ON u.id = r.user_id
WHERE r.verification = 'VERIFIED'
  AND r.outcome = 'FREEDOM'
  AND r.cord_final > 0
ORDER BY r.cord_final DESC;

-- Bot activity summary per run
CREATE OR REPLACE VIEW game.v_run_bot_summary AS
SELECT
    run_id,
    bot,
    MAX(heat) AS peak_heat,
    COUNT(*) FILTER (WHERE state = 'ATTACKING') AS attack_ticks,
    COUNT(*) FILTER (WHERE state = 'NEUTRALIZED') AS neutralized_ticks,
    MAX(tick) AS last_tick
FROM game.run_bot_states
GROUP BY run_id, bot;

COMMIT;

-- ============================================================================
-- POST-TRANSACTION COMMENTS
-- ============================================================================
COMMENT ON TABLE game.card_mode_overlays IS 'Per-card, per-mode runtime overrides — populated from ModeOverlayEngine.ts config';
COMMENT ON TABLE game.card_tag_weight_overrides IS 'Per-card, per-mode tag scoring weights — MODE_TAG_WEIGHTS in ModeOverlayEngine.ts';
COMMENT ON TABLE game.run_cord_breakdowns IS 'Detailed CORD score decomposition — output of RunGradeAssigner.computeScore()';
COMMENT ON TABLE game.run_tick_checksums IS 'Tick stream integrity verification — output of ReplayIntegrityChecker.verify()';
COMMENT ON TABLE game.run_proof_artifacts IS 'Proof card rendering pipeline — output of ProofGenerator.generate()';
COMMENT ON TABLE game.run_integrity_reviews IS 'Integrity review queue — system and manual verdicts';
COMMENT ON TABLE analytics.verified_run_explorer IS 'Denormalized read model for Verified Run Explorer — fed by SovereigntyEngine.completeRun()';
COMMENT ON TABLE game.bot_profiles IS 'Versioned bot personality definitions — matches BotProfileRegistry.ts';
COMMENT ON TABLE game.contract_game_modes IS 'Canonical mode vocabulary — runtime queries this to validate enum alignment';
COMMENT ON TABLE game.contract_timing_classes IS 'Canonical timing class vocabulary with mode scope and default window durations';
