-- Point Zero One Digital - Backend Migrations - 0002_seasons.sql - /Users/mervinlarry/workspaces/adam/Projects/adam/point_zero_one_master/backend/migrations/0002_seasons.sql

BEGIN;

DO $$
BEGIN
    CREATE TYPE season_membership_type AS ENUM ('BRONZE', 'SILVER', 'GOLD');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS seasons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    membership_type season_membership_type NOT NULL DEFAULT 'BRONZE',
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT seasons_name_not_blank CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT seasons_date_range_valid CHECK (end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS season_windows (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id INTEGER NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT season_windows_date_range_valid CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS seasons_start_date_idx
    ON seasons (start_date);

CREATE INDEX IF NOT EXISTS seasons_end_date_idx
    ON seasons (end_date);

CREATE INDEX IF NOT EXISTS seasons_is_active_idx
    ON seasons (is_active);

CREATE INDEX IF NOT EXISTS seasons_membership_type_idx
    ON seasons (membership_type);

CREATE UNIQUE INDEX IF NOT EXISTS seasons_one_active_per_membership_uidx
    ON seasons (membership_type)
    WHERE is_active = TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS season_windows_season_id_start_date_uidx
    ON season_windows (season_id, start_date);

CREATE INDEX IF NOT EXISTS season_windows_season_id_end_date_idx
    ON season_windows (season_id, end_date);

DROP TRIGGER IF EXISTS seasons_set_updated_at ON seasons;
CREATE TRIGGER seasons_set_updated_at
BEFORE UPDATE ON seasons
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS season_windows_set_updated_at ON season_windows;
CREATE TRIGGER season_windows_set_updated_at
BEFORE UPDATE ON season_windows
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

COMMIT;