-- Point Zero One Digital - Backend Migrations - 0002_seasons.sql - /Users/mervinlarry/workspaces/adam/Projects/adam/point_zero_one_master/backend/migrations/0002_seasons.sql

BEGIN;

CREATE TABLE IF NOT EXISTS season0_members (
    player_id VARCHAR(16) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    season0_token VARCHAR(16) NOT NULL UNIQUE,
    founding_pass_id VARCHAR(16) NOT NULL,
    tier VARCHAR(32) NOT NULL DEFAULT 'founding',
    community_access BOOLEAN NOT NULL DEFAULT TRUE,
    joined_at TIMESTAMPTZ NOT NULL,
    referred_by VARCHAR(16),
    transaction_history JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT season0_members_email_not_blank
        CHECK (char_length(btrim(email)) > 0),
    CONSTRAINT season0_members_token_not_blank
        CHECK (char_length(btrim(season0_token)) > 0),
    CONSTRAINT season0_members_founding_pass_id_not_blank
        CHECK (char_length(btrim(founding_pass_id)) > 0),
    CONSTRAINT season0_members_tier_not_blank
        CHECK (char_length(btrim(tier)) > 0),
    CONSTRAINT season0_members_transaction_history_is_array
        CHECK (jsonb_typeof(transaction_history) = 'array')
);

CREATE TABLE IF NOT EXISTS season0_membership_states (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(16) NOT NULL UNIQUE,
    streak_current INTEGER NOT NULL DEFAULT 0,
    streak_longest INTEGER NOT NULL DEFAULT 0,
    freezes_remaining INTEGER NOT NULL DEFAULT 3,
    freeze_history JSONB NOT NULL DEFAULT '[]'::jsonb,
    act_completed JSONB NOT NULL DEFAULT '[]'::jsonb,
    current_act VARCHAR(32) NOT NULL DEFAULT 'Claim',
    grace_active BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT season0_membership_states_streak_current_nonnegative
        CHECK (streak_current >= 0),
    CONSTRAINT season0_membership_states_streak_longest_nonnegative
        CHECK (streak_longest >= 0),
    CONSTRAINT season0_membership_states_freezes_remaining_nonnegative
        CHECK (freezes_remaining >= 0),
    CONSTRAINT season0_membership_states_freeze_history_is_array
        CHECK (jsonb_typeof(freeze_history) = 'array'),
    CONSTRAINT season0_membership_states_act_completed_is_array
        CHECK (jsonb_typeof(act_completed) = 'array'),
    CONSTRAINT season0_membership_states_current_act_not_blank
        CHECK (char_length(btrim(current_act)) > 0)
);

CREATE TABLE IF NOT EXISTS season0_waitlist_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(16) NOT NULL UNIQUE,
    position INTEGER NOT NULL DEFAULT 0,
    joined_at TIMESTAMPTZ,
    ip_address VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT season0_waitlist_entries_position_nonnegative
        CHECK (position >= 0)
);

CREATE TABLE IF NOT EXISTS season0_iab (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(16) NOT NULL UNIQUE,
    bundle JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT season0_iab_bundle_is_object
        CHECK (jsonb_typeof(bundle) = 'object')
);

CREATE TABLE IF NOT EXISTS referral_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id VARCHAR(16) NOT NULL,
    code VARCHAR(64) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    successful_invites INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT referral_records_owner_id_not_blank
        CHECK (char_length(btrim(owner_id)) > 0),
    CONSTRAINT referral_records_code_not_blank
        CHECK (char_length(btrim(code)) > 0),
    CONSTRAINT referral_records_successful_invites_nonnegative
        CHECK (successful_invites >= 0)
);

CREATE TABLE IF NOT EXISTS referral_daily_states (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(16) NOT NULL,
    day_start TIMESTAMPTZ NOT NULL,
    daily_count INTEGER NOT NULL DEFAULT 0,
    last_invite_at TIMESTAMPTZ,
    suppressed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT referral_daily_states_player_id_not_blank
        CHECK (char_length(btrim(player_id)) > 0),
    CONSTRAINT referral_daily_states_daily_count_nonnegative
        CHECK (daily_count >= 0),
    CONSTRAINT referral_daily_states_player_day_unique
        UNIQUE (player_id, day_start)
);

CREATE TABLE IF NOT EXISTS proof_stamps (
    stamp_id UUID PRIMARY KEY,
    component_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(16) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    "timestamp" TIMESTAMPTZ NOT NULL,
    CONSTRAINT proof_stamps_component_id_not_blank
        CHECK (char_length(btrim(component_id)) > 0),
    CONSTRAINT proof_stamps_owner_id_not_blank
        CHECK (char_length(btrim(owner_id)) > 0),
    CONSTRAINT proof_stamps_content_hash_not_blank
        CHECK (char_length(btrim(content_hash)) > 0)
);

CREATE INDEX IF NOT EXISTS season0_members_joined_at_idx
    ON season0_members (joined_at DESC);

CREATE INDEX IF NOT EXISTS season0_members_referred_by_idx
    ON season0_members (referred_by)
    WHERE referred_by IS NOT NULL;

CREATE INDEX IF NOT EXISTS season0_membership_states_player_id_idx
    ON season0_membership_states (player_id);

CREATE INDEX IF NOT EXISTS season0_membership_states_streak_current_idx
    ON season0_membership_states (streak_current DESC);

CREATE INDEX IF NOT EXISTS season0_waitlist_entries_joined_at_idx
    ON season0_waitlist_entries (joined_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS season0_waitlist_entries_position_real_uidx
    ON season0_waitlist_entries (position)
    WHERE player_id <> '__COUNTER__';

CREATE INDEX IF NOT EXISTS season0_iab_player_id_idx
    ON season0_iab (player_id);

CREATE INDEX IF NOT EXISTS referral_records_owner_id_idx
    ON referral_records (owner_id);

CREATE INDEX IF NOT EXISTS referral_records_active_idx
    ON referral_records (active)
    WHERE active = TRUE;

CREATE INDEX IF NOT EXISTS referral_daily_states_player_id_idx
    ON referral_daily_states (player_id);

CREATE INDEX IF NOT EXISTS referral_daily_states_day_start_idx
    ON referral_daily_states (day_start DESC);

CREATE INDEX IF NOT EXISTS referral_daily_states_suppressed_idx
    ON referral_daily_states (suppressed)
    WHERE suppressed = TRUE;

CREATE INDEX IF NOT EXISTS proof_stamps_owner_id_idx
    ON proof_stamps (owner_id);

CREATE INDEX IF NOT EXISTS proof_stamps_component_id_idx
    ON proof_stamps (component_id);

CREATE INDEX IF NOT EXISTS proof_stamps_timestamp_idx
    ON proof_stamps ("timestamp" DESC);

DROP TRIGGER IF EXISTS season0_membership_states_set_updated_at ON season0_membership_states;
CREATE TRIGGER season0_membership_states_set_updated_at
BEFORE UPDATE ON season0_membership_states
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

COMMIT;