-- File: backend/migrations/0004_event_store.sql

BEGIN;

CREATE TABLE IF NOT EXISTS global_event_store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id VARCHAR(255) NOT NULL,
    aggregate_kind VARCHAR(64) NOT NULL,
    event_name VARCHAR(128) NOT NULL,
    stream_version INTEGER NOT NULL,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    correlation_id VARCHAR(255),
    causation_id VARCHAR(255),
    idempotency_key VARCHAR(255),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT global_event_store_aggregate_id_not_blank
        CHECK (char_length(btrim(aggregate_id)) > 0),
    CONSTRAINT global_event_store_aggregate_kind_not_blank
        CHECK (char_length(btrim(aggregate_kind)) > 0),
    CONSTRAINT global_event_store_event_name_not_blank
        CHECK (char_length(btrim(event_name)) > 0),
    CONSTRAINT global_event_store_stream_version_positive
        CHECK (stream_version > 0),
    CONSTRAINT global_event_store_payload_object
        CHECK (jsonb_typeof(payload_json) = 'object'),
    CONSTRAINT global_event_store_metadata_object
        CHECK (jsonb_typeof(metadata_json) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS global_event_store_stream_version_uidx
    ON global_event_store (aggregate_kind, aggregate_id, stream_version);

CREATE UNIQUE INDEX IF NOT EXISTS global_event_store_idempotency_key_uidx
    ON global_event_store (idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS global_event_store_stream_lookup_idx
    ON global_event_store (aggregate_kind, aggregate_id, occurred_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS global_event_store_event_name_idx
    ON global_event_store (event_name);

CREATE INDEX IF NOT EXISTS global_event_store_correlation_id_idx
    ON global_event_store (correlation_id);

CREATE INDEX IF NOT EXISTS global_event_store_recorded_at_brin_idx
    ON global_event_store USING BRIN (recorded_at);

CREATE INDEX IF NOT EXISTS global_event_store_occurred_at_brin_idx
    ON global_event_store USING BRIN (occurred_at);

CREATE INDEX IF NOT EXISTS global_event_store_payload_json_gin_idx
    ON global_event_store USING GIN (payload_json);

CREATE INDEX IF NOT EXISTS global_event_store_metadata_json_gin_idx
    ON global_event_store USING GIN (metadata_json);

COMMIT;