-- Point Zero One Digital - Card Definitions and Versions, Deck Definitions and Compositions, Ruleset Versions
-- Strict types, no 'any', export all public symbols, include JSDoc - /Users/mervinlarry/workspaces/adam/Projects/adam/point_zero_one_master/backend/migrations/0011_cards.sql
-- CREATE IF NOT EXISTS for idempotency

BEGIN;

CREATE OR REPLACE FUNCTION set_row_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DO $$
BEGIN
    CREATE TYPE game_mode AS ENUM (
        'GO_ALONE',
        'HEAD_TO_HEAD',
        'TEAM_UP',
        'CHASE_A_LEGEND'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
    CREATE TYPE deck_type AS ENUM (
        'OPPORTUNITY',
        'IPA',
        'FUBAR',
        'PRIVILEGED',
        'SO',
        'PHASE_BOUNDARY',
        'SABOTAGE',
        'COUNTER',
        'BLUFF',
        'AID',
        'RESCUE',
        'TRUST',
        'DEFECTION',
        'GHOST',
        'DISCIPLINE',
        'GAP_EXPLOIT',
        'DYNASTY'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
    CREATE TYPE card_rarity AS ENUM (
        'COMMON',
        'UNCOMMON',
        'RARE',
        'EPIC',
        'LEGENDARY'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
    CREATE TYPE timing_class AS ENUM (
        'IMMEDIATE',
        'REACTIVE',
        'STANDARD',
        'HOLD',
        'COUNTER_WINDOW',
        'RESCUE_WINDOW',
        'PHASE_BOUNDARY',
        'FORCED',
        'LEGENDARY',
        'BLUFF',
        'DEFECTION_STEP',
        'SOVEREIGNTY_DECISION'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
    CREATE TYPE card_targeting AS ENUM (
        'SELF',
        'OPPONENT',
        'TEAMMATE',
        'TEAM_ALL',
        'GHOST_REF',
        'ENGINE'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS ruleset_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL,
    content_hash CHAR(64) NOT NULL,
    ruleset_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    notes TEXT,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ruleset_versions_version_positive
        CHECK (version > 0),
    CONSTRAINT ruleset_versions_content_hash_not_blank
        CHECK (char_length(btrim(content_hash)) > 0),
    CONSTRAINT ruleset_versions_ruleset_json_object
        CHECK (jsonb_typeof(ruleset_json) = 'object')
);

CREATE TABLE IF NOT EXISTS card_definitions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    deck_type deck_type NOT NULL,
    rarity card_rarity NOT NULL,
    timing_class timing_class NOT NULL,
    base_cost INTEGER NOT NULL DEFAULT 0,
    base_effect_json JSONB NOT NULL,
    tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    targeting card_targeting NOT NULL,
    educational_tag VARCHAR(255) NOT NULL,
    lore TEXT NOT NULL,
    modes_legal game_mode[] NOT NULL,
    is_forced BOOLEAN NOT NULL DEFAULT FALSE,
    drop_weight INTEGER NOT NULL DEFAULT 0,
    source_family VARCHAR(64),
    is_engine_injected_only BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT card_definitions_card_id_not_blank
        CHECK (char_length(btrim(card_id)) > 0),
    CONSTRAINT card_definitions_name_not_blank
        CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT card_definitions_base_cost_nonnegative
        CHECK (base_cost >= 0),
    CONSTRAINT card_definitions_drop_weight_nonnegative
        CHECK (drop_weight >= 0),
    CONSTRAINT card_definitions_educational_tag_not_blank
        CHECK (char_length(btrim(educational_tag)) > 0),
    CONSTRAINT card_definitions_lore_not_blank
        CHECK (char_length(btrim(lore)) > 0),
    CONSTRAINT card_definitions_base_effect_json_object
        CHECK (jsonb_typeof(base_effect_json) = 'object'),
    CONSTRAINT card_definitions_modes_legal_nonempty
        CHECK (cardinality(modes_legal) > 0)
);

CREATE TABLE IF NOT EXISTS card_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_definition_id INTEGER NOT NULL REFERENCES card_definitions(id) ON DELETE CASCADE,
    ruleset_version_id INTEGER NOT NULL REFERENCES ruleset_versions(id) ON DELETE CASCADE,
    version INTEGER NOT NULL,
    content_hash CHAR(64) NOT NULL,
    content_json JSONB NOT NULL,
    is_current BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT card_versions_version_positive
        CHECK (version > 0),
    CONSTRAINT card_versions_content_hash_not_blank
        CHECK (char_length(btrim(content_hash)) > 0),
    CONSTRAINT card_versions_content_json_object
        CHECK (jsonb_typeof(content_json) = 'object')
);

CREATE TABLE IF NOT EXISTS deck_definitions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    game_mode game_mode NOT NULL,
    ruleset_version_id INTEGER NOT NULL REFERENCES ruleset_versions(id) ON DELETE CASCADE,
    deck_types_legal deck_type[] NOT NULL DEFAULT ARRAY[]::deck_type[],
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_draw_stack BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT deck_definitions_code_not_blank
        CHECK (char_length(btrim(code)) > 0),
    CONSTRAINT deck_definitions_name_not_blank
        CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT deck_definitions_metadata_json_object
        CHECK (jsonb_typeof(metadata_json) = 'object')
);

CREATE TABLE IF NOT EXISTS deck_compositions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_definition_id INTEGER NOT NULL REFERENCES deck_definitions(id) ON DELETE CASCADE,
    card_version_id INTEGER NOT NULL REFERENCES card_versions(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 1,
    position_hint INTEGER,
    is_forced_injection BOOLEAN NOT NULL DEFAULT FALSE,
    inclusion_rules_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT deck_compositions_quantity_positive
        CHECK (quantity > 0),
    CONSTRAINT deck_compositions_position_hint_nonnegative
        CHECK (position_hint IS NULL OR position_hint >= 0),
    CONSTRAINT deck_compositions_inclusion_rules_json_object
        CHECK (jsonb_typeof(inclusion_rules_json) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS ruleset_versions_version_uidx
    ON ruleset_versions (version);

CREATE UNIQUE INDEX IF NOT EXISTS ruleset_versions_content_hash_uidx
    ON ruleset_versions (content_hash);

CREATE UNIQUE INDEX IF NOT EXISTS ruleset_versions_one_active_uidx
    ON ruleset_versions (is_active)
    WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS ruleset_versions_created_at_idx
    ON ruleset_versions (created_at);

CREATE UNIQUE INDEX IF NOT EXISTS card_definitions_card_id_uidx
    ON card_definitions (card_id);

CREATE UNIQUE INDEX IF NOT EXISTS card_definitions_name_uidx
    ON card_definitions (name);

CREATE INDEX IF NOT EXISTS card_definitions_deck_type_idx
    ON card_definitions (deck_type);

CREATE INDEX IF NOT EXISTS card_definitions_rarity_idx
    ON card_definitions (rarity);

CREATE INDEX IF NOT EXISTS card_definitions_timing_class_idx
    ON card_definitions (timing_class);

CREATE INDEX IF NOT EXISTS card_definitions_targeting_idx
    ON card_definitions (targeting);

CREATE INDEX IF NOT EXISTS card_definitions_is_forced_idx
    ON card_definitions (is_forced);

CREATE INDEX IF NOT EXISTS card_definitions_drop_weight_idx
    ON card_definitions (drop_weight);

CREATE INDEX IF NOT EXISTS card_definitions_modes_legal_gin_idx
    ON card_definitions USING GIN (modes_legal);

CREATE INDEX IF NOT EXISTS card_definitions_tags_gin_idx
    ON card_definitions USING GIN (tags);

CREATE INDEX IF NOT EXISTS card_definitions_base_effect_json_gin_idx
    ON card_definitions USING GIN (base_effect_json);

CREATE UNIQUE INDEX IF NOT EXISTS card_versions_definition_ruleset_version_uidx
    ON card_versions (card_definition_id, ruleset_version_id, version);

CREATE UNIQUE INDEX IF NOT EXISTS card_versions_content_hash_uidx
    ON card_versions (content_hash);

CREATE INDEX IF NOT EXISTS card_versions_card_definition_id_idx
    ON card_versions (card_definition_id);

CREATE INDEX IF NOT EXISTS card_versions_ruleset_version_id_idx
    ON card_versions (ruleset_version_id);

CREATE UNIQUE INDEX IF NOT EXISTS card_versions_one_current_per_definition_uidx
    ON card_versions (card_definition_id)
    WHERE is_current = TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS deck_definitions_code_ruleset_version_uidx
    ON deck_definitions (code, ruleset_version_id);

CREATE UNIQUE INDEX IF NOT EXISTS deck_definitions_name_ruleset_version_uidx
    ON deck_definitions (name, ruleset_version_id);

CREATE INDEX IF NOT EXISTS deck_definitions_game_mode_idx
    ON deck_definitions (game_mode);

CREATE INDEX IF NOT EXISTS deck_definitions_ruleset_version_id_idx
    ON deck_definitions (ruleset_version_id);

CREATE INDEX IF NOT EXISTS deck_definitions_deck_types_legal_gin_idx
    ON deck_definitions USING GIN (deck_types_legal);

CREATE UNIQUE INDEX IF NOT EXISTS deck_compositions_deck_card_version_uidx
    ON deck_compositions (deck_definition_id, card_version_id);

CREATE INDEX IF NOT EXISTS deck_compositions_card_version_id_idx
    ON deck_compositions (card_version_id);

CREATE INDEX IF NOT EXISTS deck_compositions_position_hint_idx
    ON deck_compositions (position_hint);

CREATE INDEX IF NOT EXISTS deck_compositions_forced_injection_idx
    ON deck_compositions (is_forced_injection);

CREATE INDEX IF NOT EXISTS deck_compositions_inclusion_rules_json_gin_idx
    ON deck_compositions USING GIN (inclusion_rules_json);

DROP TRIGGER IF EXISTS ruleset_versions_set_updated_at ON ruleset_versions;
CREATE TRIGGER ruleset_versions_set_updated_at
BEFORE UPDATE ON ruleset_versions
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS card_definitions_set_updated_at ON card_definitions;
CREATE TRIGGER card_definitions_set_updated_at
BEFORE UPDATE ON card_definitions
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS card_versions_set_updated_at ON card_versions;
CREATE TRIGGER card_versions_set_updated_at
BEFORE UPDATE ON card_versions
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS deck_definitions_set_updated_at ON deck_definitions;
CREATE TRIGGER deck_definitions_set_updated_at
BEFORE UPDATE ON deck_definitions
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS deck_compositions_set_updated_at ON deck_compositions;
CREATE TRIGGER deck_compositions_set_updated_at
BEFORE UPDATE ON deck_compositions
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

COMMIT;