-- Point Zero One Digital - content_versions.sql
-- Strict types, no 'any', export all public symbols - /Users/mervinlarry/workspaces/adam/Projects/adam/point_zero_one_master/backend/migrations/0012_content_versions.sql
-- CREATE IF NOT EXISTS, idempotent

BEGIN;

CREATE OR REPLACE FUNCTION set_row_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DO $$
BEGIN
    CREATE TYPE content_lifecycle_status AS ENUM (
        'DRAFT',
        'READY',
        'VALIDATING',
        'PUBLISHED',
        'RETIRED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS content_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(64) NOT NULL,
    content_key VARCHAR(255) NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    ruleset_version_id INTEGER REFERENCES ruleset_versions(id) ON DELETE SET NULL,
    template VARCHAR(128),
    rubric TEXT,
    benchmark_seed_set JSONB NOT NULL DEFAULT '[]'::jsonb,
    pin_set JSONB NOT NULL DEFAULT '[]'::jsonb,
    pin_set_hash VARCHAR(64),
    content_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    content_hash VARCHAR(64) NOT NULL,
    status content_lifecycle_status NOT NULL DEFAULT 'DRAFT',
    published_by VARCHAR(255),
    published_at TIMESTAMPTZ,
    retired_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT content_versions_content_type_not_blank
        CHECK (char_length(btrim(content_type)) > 0),
    CONSTRAINT content_versions_content_key_not_blank
        CHECK (char_length(btrim(content_key)) > 0),
    CONSTRAINT content_versions_version_positive
        CHECK (version > 0),
    CONSTRAINT content_versions_content_hash_format
        CHECK (char_length(btrim(content_hash)) = 64),
    CONSTRAINT content_versions_pin_set_hash_format
        CHECK (
            pin_set_hash IS NULL
            OR char_length(btrim(pin_set_hash)) = 64
        ),
    CONSTRAINT content_versions_content_json_object
        CHECK (jsonb_typeof(content_json) = 'object'),
    CONSTRAINT content_versions_benchmark_seed_set_array
        CHECK (jsonb_typeof(benchmark_seed_set) = 'array'),
    CONSTRAINT content_versions_pin_set_array
        CHECK (jsonb_typeof(pin_set) = 'array'),
    CONSTRAINT content_versions_published_requires_timestamp
        CHECK (
            status <> 'PUBLISHED'
            OR published_at IS NOT NULL
        ),
    CONSTRAINT content_versions_retired_requires_timestamp
        CHECK (
            status <> 'RETIRED'
            OR retired_at IS NOT NULL
        ),
    CONSTRAINT content_versions_retired_after_published
        CHECK (
            retired_at IS NULL
            OR published_at IS NULL
            OR retired_at >= published_at
        ),
    CONSTRAINT content_versions_type_key_version_unique
        UNIQUE (content_type, content_key, version),
    CONSTRAINT content_versions_content_hash_unique
        UNIQUE (content_hash)
);

CREATE TABLE IF NOT EXISTS content_rollout_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_version_id BIGINT NOT NULL REFERENCES content_versions(id) ON DELETE CASCADE,
    flag_id VARCHAR(128) NOT NULL,
    mode_code VARCHAR(16),
    program_type VARCHAR(32),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT content_rollout_flags_flag_id_not_blank
        CHECK (char_length(btrim(flag_id)) > 0),
    CONSTRAINT content_rollout_flags_mode_code_valid
        CHECK (
            mode_code IS NULL
            OR mode_code IN ('solo', 'pvp', 'coop', 'ghost')
        ),
    CONSTRAINT content_rollout_flags_program_type_valid
        CHECK (
            program_type IS NULL
            OR program_type IN (
                'school',
                'employer',
                'church',
                'community',
                'facilitator',
                'internal'
            )
        ),
    CONSTRAINT content_rollout_flags_metadata_json_object
        CHECK (jsonb_typeof(metadata_json) = 'object')
);

CREATE TABLE IF NOT EXISTS content_pin_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_version_id BIGINT NOT NULL REFERENCES content_versions(id) ON DELETE CASCADE,
    ruleset_version_id INTEGER REFERENCES ruleset_versions(id) ON DELETE SET NULL,
    pin_key VARCHAR(255) NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT content_pin_registry_pin_key_not_blank
        CHECK (char_length(btrim(pin_key)) > 0),
    CONSTRAINT content_pin_registry_position_nonnegative
        CHECK (position >= 0),
    CONSTRAINT content_pin_registry_content_pin_unique
        UNIQUE (content_version_id, pin_key)
);

CREATE TABLE IF NOT EXISTS content_publish_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_hash VARCHAR(64) NOT NULL REFERENCES content_versions(content_hash) ON DELETE CASCADE,
    version_pin_set JSONB NOT NULL DEFAULT '[]'::jsonb,
    version_pin_hash VARCHAR(64) NOT NULL,
    publish_actor VARCHAR(255) NOT NULL,
    published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT content_publish_receipts_content_hash_format
        CHECK (char_length(btrim(content_hash)) = 64),
    CONSTRAINT content_publish_receipts_version_pin_hash_format
        CHECK (char_length(btrim(version_pin_hash)) = 64),
    CONSTRAINT content_publish_receipts_publish_actor_not_blank
        CHECK (char_length(btrim(publish_actor)) > 0),
    CONSTRAINT content_publish_receipts_version_pin_set_array
        CHECK (jsonb_typeof(version_pin_set) = 'array'),
    CONSTRAINT content_publish_receipts_receipt_unique
        UNIQUE (content_hash, version_pin_hash, publish_actor)
);

CREATE INDEX IF NOT EXISTS content_versions_ruleset_version_id_idx
    ON content_versions (ruleset_version_id);

CREATE INDEX IF NOT EXISTS content_versions_status_idx
    ON content_versions (status);

CREATE INDEX IF NOT EXISTS content_versions_content_type_idx
    ON content_versions (content_type);

CREATE INDEX IF NOT EXISTS content_versions_published_at_idx
    ON content_versions (published_at DESC);

CREATE INDEX IF NOT EXISTS content_versions_retired_at_idx
    ON content_versions (retired_at DESC);

CREATE INDEX IF NOT EXISTS content_versions_benchmark_seed_set_gin_idx
    ON content_versions USING GIN (benchmark_seed_set);

CREATE INDEX IF NOT EXISTS content_versions_pin_set_gin_idx
    ON content_versions USING GIN (pin_set);

CREATE UNIQUE INDEX IF NOT EXISTS content_rollout_flags_scope_uidx
    ON content_rollout_flags (
        content_version_id,
        flag_id,
        COALESCE(mode_code, ''),
        COALESCE(program_type, '')
    );

CREATE INDEX IF NOT EXISTS content_rollout_flags_flag_id_idx
    ON content_rollout_flags (flag_id);

CREATE INDEX IF NOT EXISTS content_rollout_flags_mode_code_idx
    ON content_rollout_flags (mode_code);

CREATE INDEX IF NOT EXISTS content_rollout_flags_program_type_idx
    ON content_rollout_flags (program_type);

CREATE INDEX IF NOT EXISTS content_rollout_flags_enabled_idx
    ON content_rollout_flags (enabled);

CREATE INDEX IF NOT EXISTS content_pin_registry_ruleset_version_id_idx
    ON content_pin_registry (ruleset_version_id);

CREATE INDEX IF NOT EXISTS content_pin_registry_pin_key_idx
    ON content_pin_registry (pin_key);

CREATE INDEX IF NOT EXISTS content_pin_registry_position_idx
    ON content_pin_registry (position);

CREATE INDEX IF NOT EXISTS content_publish_receipts_content_hash_published_at_idx
    ON content_publish_receipts (content_hash, published_at DESC);

CREATE INDEX IF NOT EXISTS content_publish_receipts_version_pin_hash_idx
    ON content_publish_receipts (version_pin_hash);

DROP TRIGGER IF EXISTS content_versions_set_updated_at ON content_versions;
CREATE TRIGGER content_versions_set_updated_at
BEFORE UPDATE ON content_versions
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS content_rollout_flags_set_updated_at ON content_rollout_flags;
CREATE TRIGGER content_rollout_flags_set_updated_at
BEFORE UPDATE ON content_rollout_flags
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

COMMIT;