-- Point Zero One Digital - Backend Migration: 0050_card_forge.sql
-- Strict TypeScript, no 'any', export all public symbols, JSDoc comments -/Users/mervinlarry/workspaces/adam/Projects/adam/point_zero_one_master/backend/migrations/0050_card_forge.sql
-- SQL: includes indexes, foreign keys, comments; idempotent (CREATE IF NOT EXISTS)
-- Bash: set -euo pipefail, log all actions

BEGIN;

CREATE OR REPLACE FUNCTION set_row_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DO $$
BEGIN
    CREATE TYPE card_forge_submission_state AS ENUM (
        'DRAFT',
        'SUBMITTED',
        'IN_REVIEW',
        'APPROVED',
        'REJECTED',
        'MINTED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
    CREATE TYPE gauntlet_round_state AS ENUM (
        'QUEUED',
        'OPEN',
        'CLOSED',
        'ARCHIVED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
    CREATE TYPE gauntlet_vote_verdict AS ENUM (
        'APPROVE',
        'REJECT',
        'ABSTAIN'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS card_forge_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_account_id INTEGER REFERENCES accounts(id) ON DELETE SET NULL,
    source_card_definition_id INTEGER REFERENCES card_definitions(id) ON DELETE SET NULL,
    source_card_version_id INTEGER REFERENCES card_versions(id) ON DELETE SET NULL,
    ruleset_version_id INTEGER REFERENCES ruleset_versions(id) ON DELETE SET NULL,
    submission_slug VARCHAR(128) NOT NULL,
    candidate_name VARCHAR(255) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    submission_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    notes_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    state card_forge_submission_state NOT NULL DEFAULT 'DRAFT',
    submitted_at TIMESTAMPTZ,
    reviewed_at TIMESTAMPTZ,
    minted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT card_forge_submissions_slug_not_blank
        CHECK (char_length(btrim(submission_slug)) > 0),
    CONSTRAINT card_forge_submissions_name_not_blank
        CHECK (char_length(btrim(candidate_name)) > 0),
    CONSTRAINT card_forge_submissions_content_hash_format
        CHECK (char_length(btrim(content_hash)) = 64),
    CONSTRAINT card_forge_submissions_submission_object
        CHECK (jsonb_typeof(submission_json) = 'object'),
    CONSTRAINT card_forge_submissions_notes_object
        CHECK (jsonb_typeof(notes_json) = 'object'),
    CONSTRAINT card_forge_submissions_submitted_gate
        CHECK (
            state IN ('DRAFT')
            OR submitted_at IS NOT NULL
        ),
    CONSTRAINT card_forge_submissions_reviewed_gate
        CHECK (
            state NOT IN ('APPROVED', 'REJECTED', 'MINTED')
            OR reviewed_at IS NOT NULL
        ),
    CONSTRAINT card_forge_submissions_minted_gate
        CHECK (
            state <> 'MINTED'
            OR minted_at IS NOT NULL
        ),
    CONSTRAINT card_forge_submissions_slug_unique
        UNIQUE (submission_slug),
    CONSTRAINT card_forge_submissions_hash_unique
        UNIQUE (content_hash)
);

CREATE TABLE IF NOT EXISTS gauntlet_rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruleset_version_id INTEGER NOT NULL REFERENCES ruleset_versions(id) ON DELETE CASCADE,
    mode_code VARCHAR(32) NOT NULL,
    round_no INTEGER NOT NULL,
    state gauntlet_round_state NOT NULL DEFAULT 'QUEUED',
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT gauntlet_rounds_mode_code_valid
        CHECK (
            mode_code IN (
                'GO_ALONE',
                'HEAD_TO_HEAD',
                'TEAM_UP',
                'CHASE_A_LEGEND'
            )
        ),
    CONSTRAINT gauntlet_rounds_round_positive
        CHECK (round_no > 0),
    CONSTRAINT gauntlet_rounds_metadata_object
        CHECK (jsonb_typeof(metadata_json) = 'object'),
    CONSTRAINT gauntlet_rounds_ends_after_start
        CHECK (
            starts_at IS NULL
            OR ends_at IS NULL
            OR ends_at >= starts_at
        ),
    CONSTRAINT gauntlet_rounds_unique_scope
        UNIQUE (ruleset_version_id, mode_code, round_no)
);

CREATE TABLE IF NOT EXISTS gauntlet_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gauntlet_round_id BIGINT NOT NULL REFERENCES gauntlet_rounds(id) ON DELETE CASCADE,
    submission_id BIGINT NOT NULL REFERENCES card_forge_submissions(id) ON DELETE CASCADE,
    submitted_by_account_id INTEGER REFERENCES accounts(id) ON DELETE SET NULL,
    seed_score NUMERIC(8, 4),
    submission_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT gauntlet_submissions_metadata_object
        CHECK (jsonb_typeof(metadata_json) = 'object'),
    CONSTRAINT gauntlet_submissions_seed_score_nonnegative
        CHECK (seed_score IS NULL OR seed_score >= 0),
    CONSTRAINT gauntlet_submissions_unique_entry
        UNIQUE (gauntlet_round_id, submission_id)
);

CREATE TABLE IF NOT EXISTS gauntlet_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gauntlet_round_id BIGINT NOT NULL REFERENCES gauntlet_rounds(id) ON DELETE CASCADE,
    voter_account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    submission_id BIGINT NOT NULL REFERENCES card_forge_submissions(id) ON DELETE CASCADE,
    verdict gauntlet_vote_verdict NOT NULL DEFAULT 'APPROVE',
    vote_score SMALLINT,
    rationale_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    vote_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT gauntlet_votes_score_range
        CHECK (
            vote_score IS NULL
            OR (vote_score >= 1 AND vote_score <= 5)
        ),
    CONSTRAINT gauntlet_votes_rationale_object
        CHECK (jsonb_typeof(rationale_json) = 'object'),
    CONSTRAINT gauntlet_votes_unique_ballot
        UNIQUE (gauntlet_round_id, voter_account_id, submission_id)
);

CREATE TABLE IF NOT EXISTS minted_community_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL REFERENCES card_forge_submissions(id) ON DELETE CASCADE,
    minted_card_definition_id INTEGER REFERENCES card_definitions(id) ON DELETE SET NULL,
    minted_card_version_id INTEGER REFERENCES card_versions(id) ON DELETE SET NULL,
    creator_royalty_bps INTEGER NOT NULL DEFAULT 0,
    publish_receipt_hash VARCHAR(64),
    minting_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT minted_community_cards_royalty_bps_valid
        CHECK (
            creator_royalty_bps >= 0
            AND creator_royalty_bps <= 10000
        ),
    CONSTRAINT minted_community_cards_publish_receipt_hash_format
        CHECK (
            publish_receipt_hash IS NULL
            OR char_length(btrim(publish_receipt_hash)) = 64
        ),
    CONSTRAINT minted_community_cards_submission_unique
        UNIQUE (submission_id),
    CONSTRAINT minted_community_cards_card_version_unique
        UNIQUE (minted_card_version_id)
);

CREATE TABLE IF NOT EXISTS creator_royalty_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    payout_currency CHAR(3) NOT NULL DEFAULT 'USD',
    payout_destination VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT creator_royalty_accounts_currency_format
        CHECK (char_length(payout_currency) = 3),
    CONSTRAINT creator_royalty_accounts_account_unique
        UNIQUE (account_id)
);

CREATE TABLE IF NOT EXISTS creator_royalty_accruals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    royalty_account_id BIGINT NOT NULL REFERENCES creator_royalty_accounts(id) ON DELETE CASCADE,
    minted_community_card_id BIGINT NOT NULL REFERENCES minted_community_cards(id) ON DELETE CASCADE,
    source_purchase_id VARCHAR(255),
    royalty_earned_cents BIGINT NOT NULL DEFAULT 0,
    accrual_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    settled_at TIMESTAMPTZ,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT creator_royalty_accruals_earned_nonnegative
        CHECK (royalty_earned_cents >= 0),
    CONSTRAINT creator_royalty_accruals_metadata_object
        CHECK (jsonb_typeof(metadata_json) = 'object')
);

CREATE INDEX IF NOT EXISTS card_forge_submissions_author_account_id_idx
    ON card_forge_submissions (author_account_id);

CREATE INDEX IF NOT EXISTS card_forge_submissions_ruleset_version_id_idx
    ON card_forge_submissions (ruleset_version_id);

CREATE INDEX IF NOT EXISTS card_forge_submissions_state_idx
    ON card_forge_submissions (state);

CREATE INDEX IF NOT EXISTS card_forge_submissions_created_at_idx
    ON card_forge_submissions (created_at DESC);

CREATE INDEX IF NOT EXISTS gauntlet_rounds_state_idx
    ON gauntlet_rounds (state);

CREATE INDEX IF NOT EXISTS gauntlet_rounds_starts_at_idx
    ON gauntlet_rounds (starts_at DESC);

CREATE INDEX IF NOT EXISTS gauntlet_submissions_round_id_idx
    ON gauntlet_submissions (gauntlet_round_id);

CREATE INDEX IF NOT EXISTS gauntlet_submissions_submission_id_idx
    ON gauntlet_submissions (submission_id);

CREATE INDEX IF NOT EXISTS gauntlet_votes_round_id_idx
    ON gauntlet_votes (gauntlet_round_id);

CREATE INDEX IF NOT EXISTS gauntlet_votes_submission_id_idx
    ON gauntlet_votes (submission_id);

CREATE INDEX IF NOT EXISTS gauntlet_votes_verdict_idx
    ON gauntlet_votes (verdict);

CREATE INDEX IF NOT EXISTS minted_community_cards_definition_idx
    ON minted_community_cards (minted_card_definition_id);

CREATE INDEX IF NOT EXISTS minted_community_cards_minting_time_idx
    ON minted_community_cards (minting_time DESC);

CREATE INDEX IF NOT EXISTS creator_royalty_accruals_account_id_idx
    ON creator_royalty_accruals (royalty_account_id);

CREATE INDEX IF NOT EXISTS creator_royalty_accruals_card_id_idx
    ON creator_royalty_accruals (minted_community_card_id);

CREATE INDEX IF NOT EXISTS creator_royalty_accruals_accrual_time_idx
    ON creator_royalty_accruals (accrual_time DESC);

DROP TRIGGER IF EXISTS card_forge_submissions_set_updated_at ON card_forge_submissions;
CREATE TRIGGER card_forge_submissions_set_updated_at
BEFORE UPDATE ON card_forge_submissions
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS gauntlet_rounds_set_updated_at ON gauntlet_rounds;
CREATE TRIGGER gauntlet_rounds_set_updated_at
BEFORE UPDATE ON gauntlet_rounds
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS creator_royalty_accounts_set_updated_at ON creator_royalty_accounts;
CREATE TRIGGER creator_royalty_accounts_set_updated_at
BEFORE UPDATE ON creator_royalty_accounts
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

COMMIT;