-- Point Zero One Digital - Macro Shock Migrations - 0051_macro_shock.sql - /Users/mervinlarry/workspaces/adam/Projects/adam/point_zero_one_master/backend/migrations/0051_macro_shock.sql

BEGIN;

CREATE OR REPLACE FUNCTION set_row_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DO $$
BEGIN
    CREATE TYPE macro_event_source AS ENUM (
        'ENGINE',
        'LIVEOPS',
        'LEGEND_DECAY',
        'COMMUNITY_HEAT',
        'FUBAR',
        'BOT'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
    CREATE TYPE macro_event_state AS ENUM (
        'SCHEDULED',
        'TRIGGERED',
        'RESOLVED',
        'CANCELED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
    CREATE TYPE shock_broadcast_audience AS ENUM (
        'RUN',
        'PLAYER',
        'TEAM',
        'SPECTATOR',
        'GLOBAL'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
    CREATE TYPE macro_policy_state AS ENUM (
        'ACTIVE',
        'EXPIRED',
        'REVOKED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
    CREATE TYPE macro_claim_state AS ENUM (
        'PENDING',
        'PAID',
        'DENIED'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS macro_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(64),
    mode_code VARCHAR(32) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    source macro_event_source NOT NULL DEFAULT 'ENGINE',
    phase_code VARCHAR(32),
    state macro_event_state NOT NULL DEFAULT 'SCHEDULED',
    severity SMALLINT NOT NULL DEFAULT 0,
    scheduled_at TIMESTAMPTZ,
    triggered_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT macro_events_mode_code_valid
        CHECK (
            mode_code IN (
                'GO_ALONE',
                'HEAD_TO_HEAD',
                'TEAM_UP',
                'CHASE_A_LEGEND'
            )
        ),
    CONSTRAINT macro_events_event_type_not_blank
        CHECK (char_length(btrim(event_type)) > 0),
    CONSTRAINT macro_events_severity_range
        CHECK (severity >= 0 AND severity <= 100),
    CONSTRAINT macro_events_payload_object
        CHECK (jsonb_typeof(payload_json) = 'object'),
    CONSTRAINT macro_events_metadata_object
        CHECK (jsonb_typeof(metadata_json) = 'object'),
    CONSTRAINT macro_events_schedule_order_valid
        CHECK (
            scheduled_at IS NULL
            OR triggered_at IS NULL
            OR triggered_at >= scheduled_at
        ),
    CONSTRAINT macro_events_resolution_order_valid
        CHECK (
            resolved_at IS NULL
            OR triggered_at IS NULL
            OR resolved_at >= triggered_at
        )
);

CREATE TABLE IF NOT EXISTS macro_shock_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES macro_events(id) ON DELETE CASCADE,
    target_run_id VARCHAR(64),
    target_player_ref VARCHAR(64),
    injected_card_definition_id INTEGER REFERENCES card_definitions(id) ON DELETE SET NULL,
    injected_card_id VARCHAR(128),
    deck_type VARCHAR(64) NOT NULL,
    insertion_count INTEGER NOT NULL DEFAULT 1,
    data_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT macro_shock_cards_identity_present
        CHECK (
            injected_card_definition_id IS NOT NULL
            OR injected_card_id IS NOT NULL
        ),
    CONSTRAINT macro_shock_cards_deck_type_not_blank
        CHECK (char_length(btrim(deck_type)) > 0),
    CONSTRAINT macro_shock_cards_insertion_count_positive
        CHECK (insertion_count > 0),
    CONSTRAINT macro_shock_cards_data_object
        CHECK (jsonb_typeof(data_json) = 'object')
);

CREATE TABLE IF NOT EXISTS shock_broadcasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES macro_events(id) ON DELETE CASCADE,
    audience shock_broadcast_audience NOT NULL,
    target_player_ref VARCHAR(64),
    message TEXT NOT NULL,
    data_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMPTZ,
    CONSTRAINT shock_broadcasts_message_not_blank
        CHECK (char_length(btrim(message)) > 0),
    CONSTRAINT shock_broadcasts_data_object
        CHECK (jsonb_typeof(data_json) = 'object')
);

CREATE TABLE IF NOT EXISTS shock_insertions_per_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES macro_events(id) ON DELETE CASCADE,
    run_id VARCHAR(64) NOT NULL,
    player_ref VARCHAR(64),
    insertion_count INTEGER NOT NULL DEFAULT 0,
    impact_score NUMERIC(12, 4) NOT NULL DEFAULT 0,
    data_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT shock_insertions_per_run_run_id_not_blank
        CHECK (char_length(btrim(run_id)) > 0),
    CONSTRAINT shock_insertions_per_run_count_nonnegative
        CHECK (insertion_count >= 0),
    CONSTRAINT shock_insertions_per_run_data_object
        CHECK (jsonb_typeof(data_json) = 'object')
);

CREATE TABLE IF NOT EXISTS macro_insurance_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    coverage_tier SMALLINT NOT NULL DEFAULT 0,
    mode_code VARCHAR(32),
    state macro_policy_state NOT NULL DEFAULT 'ACTIVE',
    coverage_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    effective_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT macro_insurance_policies_tier_valid
        CHECK (coverage_tier >= 0 AND coverage_tier <= 10),
    CONSTRAINT macro_insurance_policies_mode_code_valid
        CHECK (
            mode_code IS NULL
            OR mode_code IN (
                'GO_ALONE',
                'HEAD_TO_HEAD',
                'TEAM_UP',
                'CHASE_A_LEGEND'
            )
        ),
    CONSTRAINT macro_insurance_policies_coverage_object
        CHECK (jsonb_typeof(coverage_json) = 'object'),
    CONSTRAINT macro_insurance_policies_expiry_after_effective
        CHECK (
            expires_at IS NULL
            OR expires_at >= effective_at
        )
);

CREATE TABLE IF NOT EXISTS macro_insurance_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id BIGINT NOT NULL REFERENCES macro_insurance_policies(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES macro_events(id) ON DELETE CASCADE,
    run_id VARCHAR(64),
    payout_cents BIGINT NOT NULL DEFAULT 0,
    claim_state macro_claim_state NOT NULL DEFAULT 'PENDING',
    claim_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    settled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT macro_insurance_claims_payout_nonnegative
        CHECK (payout_cents >= 0),
    CONSTRAINT macro_insurance_claims_claim_object
        CHECK (jsonb_typeof(claim_json) = 'object')
);

CREATE INDEX IF NOT EXISTS macro_events_run_id_idx
    ON macro_events (run_id);

CREATE INDEX IF NOT EXISTS macro_events_mode_code_idx
    ON macro_events (mode_code);

CREATE INDEX IF NOT EXISTS macro_events_event_type_idx
    ON macro_events (event_type);

CREATE INDEX IF NOT EXISTS macro_events_source_idx
    ON macro_events (source);

CREATE INDEX IF NOT EXISTS macro_events_state_idx
    ON macro_events (state);

CREATE INDEX IF NOT EXISTS macro_events_triggered_at_idx
    ON macro_events (triggered_at DESC);

CREATE INDEX IF NOT EXISTS macro_shock_cards_event_id_idx
    ON macro_shock_cards (event_id);

CREATE INDEX IF NOT EXISTS macro_shock_cards_target_run_id_idx
    ON macro_shock_cards (target_run_id);

CREATE INDEX IF NOT EXISTS macro_shock_cards_deck_type_idx
    ON macro_shock_cards (deck_type);

CREATE INDEX IF NOT EXISTS shock_broadcasts_event_id_idx
    ON shock_broadcasts (event_id);

CREATE INDEX IF NOT EXISTS shock_broadcasts_audience_idx
    ON shock_broadcasts (audience);

CREATE INDEX IF NOT EXISTS shock_broadcasts_target_player_ref_idx
    ON shock_broadcasts (target_player_ref);

CREATE INDEX IF NOT EXISTS shock_insertions_per_run_event_id_idx
    ON shock_insertions_per_run (event_id);

CREATE INDEX IF NOT EXISTS shock_insertions_per_run_run_id_idx
    ON shock_insertions_per_run (run_id);

CREATE INDEX IF NOT EXISTS macro_insurance_policies_account_id_idx
    ON macro_insurance_policies (account_id);

CREATE INDEX IF NOT EXISTS macro_insurance_policies_mode_code_idx
    ON macro_insurance_policies (mode_code);

CREATE INDEX IF NOT EXISTS macro_insurance_policies_state_idx
    ON macro_insurance_policies (state);

CREATE INDEX IF NOT EXISTS macro_insurance_claims_policy_id_idx
    ON macro_insurance_claims (policy_id);

CREATE INDEX IF NOT EXISTS macro_insurance_claims_event_id_idx
    ON macro_insurance_claims (event_id);

CREATE INDEX IF NOT EXISTS macro_insurance_claims_claim_state_idx
    ON macro_insurance_claims (claim_state);

DROP TRIGGER IF EXISTS macro_events_set_updated_at ON macro_events;
CREATE TRIGGER macro_events_set_updated_at
BEFORE UPDATE ON macro_events
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS macro_insurance_policies_set_updated_at ON macro_insurance_policies;
CREATE TRIGGER macro_insurance_policies_set_updated_at
BEFORE UPDATE ON macro_insurance_policies
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS macro_insurance_claims_set_updated_at ON macro_insurance_claims;
CREATE TRIGGER macro_insurance_claims_set_updated_at
BEFORE UPDATE ON macro_insurance_claims
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

COMMIT;