-- File: backend/migrations/0070_notifications.sql
BEGIN;

CREATE OR REPLACE FUNCTION set_row_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

DO $$
BEGIN
  CREATE TYPE notification_channel AS ENUM (
    'push',
    'email',
    'sms'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE notification_delivery_status AS ENUM (
    'queued',
    'sent',
    'delivered',
    'failed',
    'suppressed',
    'read'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE notification_subscription_status AS ENUM (
    'active',
    'unsubscribed',
    'bounced',
    'revoked'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE push_platform AS ENUM (
    'ios',
    'android',
    'web',
    'unknown'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS notification_preferences (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  push_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  email_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  sms_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  marketing_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  digest_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  quiet_hours_timezone VARCHAR(64),
  do_not_disturb_windows JSONB NOT NULL DEFAULT '[]'::jsonb,
  channel_overrides_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notification_preferences_user_id_unique UNIQUE (user_id),
  CONSTRAINT notification_preferences_dnd_windows_array
    CHECK (jsonb_typeof(do_not_disturb_windows) = 'array'),
  CONSTRAINT notification_preferences_channel_overrides_object
    CHECK (jsonb_typeof(channel_overrides_json) = 'object')
);

CREATE TABLE IF NOT EXISTS notification_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  notification_type VARCHAR(255) NOT NULL,
  channel notification_channel NOT NULL,
  template_key VARCHAR(255),
  status notification_delivery_status NOT NULL DEFAULT 'queued',
  idempotency_key VARCHAR(255),
  provider_message_id VARCHAR(255),
  error_message TEXT,
  scheduled_for TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  read_at TIMESTAMPTZ,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notification_log_notification_type_not_blank
    CHECK (char_length(btrim(notification_type)) > 0),
  CONSTRAINT notification_log_data_object
    CHECK (jsonb_typeof(data) = 'object'),
  CONSTRAINT notification_log_idempotency_key_not_blank
    CHECK (idempotency_key IS NULL OR char_length(btrim(idempotency_key)) > 0),
  CONSTRAINT notification_log_sent_after_create
    CHECK (sent_at IS NULL OR sent_at >= created_at),
  CONSTRAINT notification_log_delivered_after_sent
    CHECK (
      delivered_at IS NULL
      OR sent_at IS NULL
      OR delivered_at >= sent_at
    ),
  CONSTRAINT notification_log_read_after_delivery
    CHECK (
      read_at IS NULL
      OR delivered_at IS NULL
      OR read_at >= delivered_at
    )
);

CREATE TABLE IF NOT EXISTS push_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  platform push_platform NOT NULL DEFAULT 'unknown',
  device_id INTEGER REFERENCES devices(id) ON DELETE SET NULL,
  last_seen_at TIMESTAMPTZ,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_at TIMESTAMPTZ,
  CONSTRAINT push_tokens_token_not_blank
    CHECK (char_length(btrim(token)) > 0),
  CONSTRAINT push_tokens_metadata_json_object
    CHECK (jsonb_typeof(metadata_json) = 'object'),
  CONSTRAINT push_tokens_revoked_requires_inactive
    CHECK (revoked_at IS NULL OR is_active = FALSE)
);

CREATE TABLE IF NOT EXISTS email_subscriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  email VARCHAR(320) NOT NULL,
  subscription_type VARCHAR(64) NOT NULL DEFAULT 'transactional',
  status notification_subscription_status NOT NULL DEFAULT 'active',
  verified_at TIMESTAMPTZ,
  unsubscribed_at TIMESTAMPTZ,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT email_subscriptions_email_not_blank
    CHECK (char_length(btrim(email)) > 0),
  CONSTRAINT email_subscriptions_subscription_type_not_blank
    CHECK (char_length(btrim(subscription_type)) > 0),
  CONSTRAINT email_subscriptions_metadata_json_object
    CHECK (jsonb_typeof(metadata_json) = 'object'),
  CONSTRAINT email_subscriptions_unsubscribed_after_created
    CHECK (unsubscribed_at IS NULL OR unsubscribed_at >= created_at)
);

CREATE TABLE IF NOT EXISTS sms_subscriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  phone_number VARCHAR(32) NOT NULL,
  subscription_type VARCHAR(64) NOT NULL DEFAULT 'transactional',
  status notification_subscription_status NOT NULL DEFAULT 'active',
  verified_at TIMESTAMPTZ,
  unsubscribed_at TIMESTAMPTZ,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sms_subscriptions_phone_number_not_blank
    CHECK (char_length(btrim(phone_number)) > 0),
  CONSTRAINT sms_subscriptions_phone_number_e164ish
    CHECK (phone_number ~ '^\+?[1-9][0-9]{7,19}$'),
  CONSTRAINT sms_subscriptions_subscription_type_not_blank
    CHECK (char_length(btrim(subscription_type)) > 0),
  CONSTRAINT sms_subscriptions_metadata_json_object
    CHECK (jsonb_typeof(metadata_json) = 'object'),
  CONSTRAINT sms_subscriptions_unsubscribed_after_created
    CHECK (unsubscribed_at IS NULL OR unsubscribed_at >= created_at)
);

CREATE INDEX IF NOT EXISTS notification_preferences_user_id_idx
  ON notification_preferences (user_id);

CREATE INDEX IF NOT EXISTS notification_log_user_id_idx
  ON notification_log (user_id);

CREATE INDEX IF NOT EXISTS notification_log_notification_type_idx
  ON notification_log (notification_type);

CREATE INDEX IF NOT EXISTS notification_log_channel_status_idx
  ON notification_log (channel, status);

CREATE INDEX IF NOT EXISTS notification_log_created_at_idx
  ON notification_log (created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS notification_log_idempotency_key_uidx
  ON notification_log (idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS notification_log_data_gin_idx
  ON notification_log
  USING GIN (data);

CREATE INDEX IF NOT EXISTS push_tokens_user_id_idx
  ON push_tokens (user_id);

CREATE INDEX IF NOT EXISTS push_tokens_device_id_idx
  ON push_tokens (device_id);

CREATE UNIQUE INDEX IF NOT EXISTS push_tokens_token_active_uidx
  ON push_tokens (token)
  WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS push_tokens_last_seen_at_idx
  ON push_tokens (last_seen_at DESC);

CREATE INDEX IF NOT EXISTS email_subscriptions_user_id_idx
  ON email_subscriptions (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS email_subscriptions_user_email_type_uidx
  ON email_subscriptions (user_id, lower(email), subscription_type);

CREATE INDEX IF NOT EXISTS email_subscriptions_status_idx
  ON email_subscriptions (status);

CREATE INDEX IF NOT EXISTS sms_subscriptions_user_id_idx
  ON sms_subscriptions (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS sms_subscriptions_user_phone_type_uidx
  ON sms_subscriptions (user_id, phone_number, subscription_type);

CREATE INDEX IF NOT EXISTS sms_subscriptions_status_idx
  ON sms_subscriptions (status);

DROP TRIGGER IF EXISTS notification_preferences_set_updated_at ON notification_preferences;
CREATE TRIGGER notification_preferences_set_updated_at
BEFORE UPDATE ON notification_preferences
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS notification_log_set_updated_at ON notification_log;
CREATE TRIGGER notification_log_set_updated_at
BEFORE UPDATE ON notification_log
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS push_tokens_set_updated_at ON push_tokens;
CREATE TRIGGER push_tokens_set_updated_at
BEFORE UPDATE ON push_tokens
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS email_subscriptions_set_updated_at ON email_subscriptions;
CREATE TRIGGER email_subscriptions_set_updated_at
BEFORE UPDATE ON email_subscriptions
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS sms_subscriptions_set_updated_at ON sms_subscriptions;
CREATE TRIGGER sms_subscriptions_set_updated_at
BEFORE UPDATE ON sms_subscriptions
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

COMMIT;