-- backend/migrations/2026_02_20_add_curriculum_measurements.sql

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Assumes training_scenarios is the canonical curriculum/scenario table.
-- If that table has not yet been materialized in your deployed schema,
-- create/fold it before applying this migration.

CREATE TABLE IF NOT EXISTS scenario_attempt_aggregates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_scenario_id UUID NOT NULL REFERENCES training_scenarios(id) ON DELETE CASCADE,
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    cohort_id INTEGER REFERENCES cohorts(id) ON DELETE SET NULL,
    attempt_number INTEGER NOT NULL,
    score NUMERIC(10, 2) NOT NULL,
    completion_time TIMESTAMPTZ NOT NULL,
    duration_ms INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT scenario_attempt_aggregates_attempt_positive
        CHECK (attempt_number > 0),
    CONSTRAINT scenario_attempt_aggregates_duration_nonnegative
        CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT scenario_attempt_aggregates_unique
        UNIQUE (training_scenario_id, account_id, attempt_number)
);

CREATE TABLE IF NOT EXISTS scenario_failure_modes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mode_key VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT scenario_failure_modes_key_not_blank
        CHECK (char_length(btrim(mode_key)) > 0),
    CONSTRAINT scenario_failure_modes_name_not_blank
        CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT scenario_failure_modes_key_unique
        UNIQUE (mode_key)
);

CREATE TABLE IF NOT EXISTS failure_mode_aggregates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_scenario_id UUID NOT NULL REFERENCES training_scenarios(id) ON DELETE CASCADE,
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    cohort_id INTEGER REFERENCES cohorts(id) ON DELETE SET NULL,
    failure_mode_id UUID NOT NULL REFERENCES scenario_failure_modes(id) ON DELETE RESTRICT,
    occurrence_count INTEGER NOT NULL DEFAULT 1,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT failure_mode_aggregates_occurrence_positive
        CHECK (occurrence_count > 0)
);

CREATE TABLE IF NOT EXISTS improvement_deltas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_attempt_aggregate_id BIGINT NOT NULL
        REFERENCES scenario_attempt_aggregates(id) ON DELETE CASCADE,
    previous_score NUMERIC(10, 2) NOT NULL,
    current_score NUMERIC(10, 2) NOT NULL,
    improvement_percentage NUMERIC(7, 3) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT improvement_deltas_unique_attempt
        UNIQUE (scenario_attempt_aggregate_id)
);

CREATE TABLE IF NOT EXISTS risk_literacy_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    cohort_id INTEGER REFERENCES cohorts(id) ON DELETE SET NULL,
    score NUMERIC(10, 2) NOT NULL,
    measured_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT risk_literacy_scores_unique
        UNIQUE (account_id, measured_at)
);

CREATE TABLE IF NOT EXISTS dashboard_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER REFERENCES accounts(id) ON DELETE CASCADE,
    cohort_id INTEGER REFERENCES cohorts(id) ON DELETE CASCADE,
    institution_id INTEGER REFERENCES institutions(id) ON DELETE CASCADE,
    snapshot_kind VARCHAR(64) NOT NULL DEFAULT 'curriculum_dashboard',
    snapshot_data JSONB NOT NULL,
    captured_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dashboard_snapshots_subject_present
        CHECK (
            account_id IS NOT NULL
            OR cohort_id IS NOT NULL
            OR institution_id IS NOT NULL
        ),
    CONSTRAINT dashboard_snapshots_kind_not_blank
        CHECK (char_length(btrim(snapshot_kind)) > 0),
    CONSTRAINT dashboard_snapshots_data_is_object
        CHECK (jsonb_typeof(snapshot_data) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_scenario_attempt_aggregates_scenario
    ON scenario_attempt_aggregates (training_scenario_id);

CREATE INDEX IF NOT EXISTS idx_scenario_attempt_aggregates_account
    ON scenario_attempt_aggregates (account_id);

CREATE INDEX IF NOT EXISTS idx_scenario_attempt_aggregates_cohort
    ON scenario_attempt_aggregates (cohort_id);

CREATE INDEX IF NOT EXISTS idx_scenario_attempt_aggregates_completion_time
    ON scenario_attempt_aggregates (completion_time DESC);

CREATE INDEX IF NOT EXISTS idx_failure_mode_aggregates_scenario
    ON failure_mode_aggregates (training_scenario_id);

CREATE INDEX IF NOT EXISTS idx_failure_mode_aggregates_account
    ON failure_mode_aggregates (account_id);

CREATE INDEX IF NOT EXISTS idx_failure_mode_aggregates_failure_mode
    ON failure_mode_aggregates (failure_mode_id);

CREATE INDEX IF NOT EXISTS idx_failure_mode_aggregates_recorded_at
    ON failure_mode_aggregates (recorded_at DESC);

CREATE INDEX IF NOT EXISTS idx_risk_literacy_scores_account
    ON risk_literacy_scores (account_id);

CREATE INDEX IF NOT EXISTS idx_risk_literacy_scores_cohort
    ON risk_literacy_scores (cohort_id);

CREATE INDEX IF NOT EXISTS idx_risk_literacy_scores_measured_at
    ON risk_literacy_scores (measured_at DESC);

CREATE INDEX IF NOT EXISTS idx_dashboard_snapshots_account
    ON dashboard_snapshots (account_id);

CREATE INDEX IF NOT EXISTS idx_dashboard_snapshots_cohort
    ON dashboard_snapshots (cohort_id);

CREATE INDEX IF NOT EXISTS idx_dashboard_snapshots_institution
    ON dashboard_snapshots (institution_id);

CREATE INDEX IF NOT EXISTS idx_dashboard_snapshots_kind
    ON dashboard_snapshots (snapshot_kind);

CREATE INDEX IF NOT EXISTS idx_dashboard_snapshots_captured_at
    ON dashboard_snapshots (captured_at DESC);

CREATE INDEX IF NOT EXISTS idx_dashboard_snapshots_data_gin
    ON dashboard_snapshots USING GIN (snapshot_data);

COMMIT;