-- File: backend/migrations/2026_02_20_add_alerting.sql
BEGIN;

CREATE OR REPLACE FUNCTION set_row_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

DO $$
BEGIN
  CREATE TYPE alert_severity AS ENUM (
    'info',
    'warning',
    'critical'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE alert_firing_state AS ENUM (
    'open',
    'acknowledged',
    'suppressed',
    'resolved'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS alert_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  aggregate_kind VARCHAR(64),
  event_name VARCHAR(128),
  severity alert_severity NOT NULL DEFAULT 'warning',
  is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  dedupe_window_seconds INTEGER NOT NULL DEFAULT 300,
  rule_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT alert_rules_name_not_blank
    CHECK (char_length(btrim(name)) > 0),
  CONSTRAINT alert_rules_aggregate_kind_not_blank
    CHECK (aggregate_kind IS NULL OR char_length(btrim(aggregate_kind)) > 0),
  CONSTRAINT alert_rules_event_name_not_blank
    CHECK (event_name IS NULL OR char_length(btrim(event_name)) > 0),
  CONSTRAINT alert_rules_dedupe_window_nonnegative
    CHECK (dedupe_window_seconds >= 0),
  CONSTRAINT alert_rules_rule_json_object
    CHECK (jsonb_typeof(rule_json) = 'object')
);

CREATE TABLE IF NOT EXISTS alert_firings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id INTEGER NOT NULL REFERENCES alert_rules(id) ON DELETE CASCADE,
  run_id INTEGER REFERENCES runs(id) ON DELETE SET NULL,
  run_event_id INTEGER REFERENCES run_events(id) ON DELETE SET NULL,
  global_event_store_id BIGINT REFERENCES global_event_store(id) ON DELETE SET NULL,
  aggregate_kind VARCHAR(64),
  aggregate_id VARCHAR(255),
  event_name VARCHAR(128),
  fingerprint VARCHAR(255) NOT NULL,
  state alert_firing_state NOT NULL DEFAULT 'open',
  context_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  acknowledged_at TIMESTAMPTZ,
  suppressed_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT alert_firings_fingerprint_not_blank
    CHECK (char_length(btrim(fingerprint)) > 0),
  CONSTRAINT alert_firings_aggregate_kind_not_blank
    CHECK (aggregate_kind IS NULL OR char_length(btrim(aggregate_kind)) > 0),
  CONSTRAINT alert_firings_aggregate_id_not_blank
    CHECK (aggregate_id IS NULL OR char_length(btrim(aggregate_id)) > 0),
  CONSTRAINT alert_firings_event_name_not_blank
    CHECK (event_name IS NULL OR char_length(btrim(event_name)) > 0),
  CONSTRAINT alert_firings_context_json_object
    CHECK (jsonb_typeof(context_json) = 'object'),
  CONSTRAINT alert_firings_ack_after_open
    CHECK (acknowledged_at IS NULL OR acknowledged_at >= opened_at),
  CONSTRAINT alert_firings_suppress_after_open
    CHECK (suppressed_at IS NULL OR suppressed_at >= opened_at),
  CONSTRAINT alert_firings_resolve_after_open
    CHECK (resolved_at IS NULL OR resolved_at >= opened_at)
);

CREATE TABLE IF NOT EXISTS alert_suppressions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firing_id INTEGER NOT NULL REFERENCES alert_firings(id) ON DELETE CASCADE,
  suppressed_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  suppression_reason TEXT NOT NULL,
  scope_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMPTZ,
  CONSTRAINT alert_suppressions_reason_not_blank
    CHECK (char_length(btrim(suppression_reason)) > 0),
  CONSTRAINT alert_suppressions_scope_json_object
    CHECK (jsonb_typeof(scope_json) = 'object'),
  CONSTRAINT alert_suppressions_expiry_after_create
    CHECK (expires_at IS NULL OR expires_at >= created_at)
);

CREATE TABLE IF NOT EXISTS runbook_links (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firing_id INTEGER NOT NULL REFERENCES alert_firings(id) ON DELETE CASCADE,
  runbook_key VARCHAR(255) NOT NULL,
  runbook_title VARCHAR(255),
  runbook_url TEXT,
  runbook_version VARCHAR(64),
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT runbook_links_runbook_key_not_blank
    CHECK (char_length(btrim(runbook_key)) > 0),
  CONSTRAINT runbook_links_metadata_json_object
    CHECK (jsonb_typeof(metadata_json) = 'object'),
  CONSTRAINT runbook_links_firing_id_runbook_key_unique
    UNIQUE (firing_id, runbook_key)
);

CREATE TABLE IF NOT EXISTS alert_acknowledgements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firing_id INTEGER NOT NULL REFERENCES alert_firings(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  acknowledger VARCHAR(255) NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT alert_acknowledgements_acknowledger_not_blank
    CHECK (char_length(btrim(acknowledger)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS alert_rules_name_uidx
  ON alert_rules (name);

CREATE INDEX IF NOT EXISTS alert_rules_enabled_scope_idx
  ON alert_rules (is_enabled, aggregate_kind, event_name);

CREATE INDEX IF NOT EXISTS alert_rules_severity_idx
  ON alert_rules (severity);

CREATE INDEX IF NOT EXISTS alert_rules_rule_json_gin_idx
  ON alert_rules
  USING GIN (rule_json);

CREATE INDEX IF NOT EXISTS alert_firings_rule_id_idx
  ON alert_firings (rule_id);

CREATE INDEX IF NOT EXISTS alert_firings_run_id_idx
  ON alert_firings (run_id);

CREATE INDEX IF NOT EXISTS alert_firings_run_event_id_idx
  ON alert_firings (run_event_id);

CREATE INDEX IF NOT EXISTS alert_firings_global_event_store_id_idx
  ON alert_firings (global_event_store_id);

CREATE INDEX IF NOT EXISTS alert_firings_state_idx
  ON alert_firings (state);

CREATE INDEX IF NOT EXISTS alert_firings_opened_at_idx
  ON alert_firings (opened_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS alert_firings_open_fingerprint_uidx
  ON alert_firings (rule_id, fingerprint)
  WHERE state = 'open';

CREATE INDEX IF NOT EXISTS alert_firings_context_json_gin_idx
  ON alert_firings
  USING GIN (context_json);

CREATE INDEX IF NOT EXISTS alert_suppressions_firing_id_idx
  ON alert_suppressions (firing_id);

CREATE INDEX IF NOT EXISTS alert_suppressions_user_id_idx
  ON alert_suppressions (suppressed_by_user_id);

CREATE INDEX IF NOT EXISTS alert_suppressions_expires_at_idx
  ON alert_suppressions (expires_at);

CREATE INDEX IF NOT EXISTS runbook_links_firing_id_idx
  ON runbook_links (firing_id);

CREATE INDEX IF NOT EXISTS alert_acknowledgements_firing_id_idx
  ON alert_acknowledgements (firing_id);

CREATE INDEX IF NOT EXISTS alert_acknowledgements_user_id_idx
  ON alert_acknowledgements (user_id);

CREATE INDEX IF NOT EXISTS alert_acknowledgements_created_at_idx
  ON alert_acknowledgements (created_at DESC);

DROP TRIGGER IF EXISTS alert_rules_set_updated_at ON alert_rules;
CREATE TRIGGER alert_rules_set_updated_at
BEFORE UPDATE ON alert_rules
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS alert_firings_set_updated_at ON alert_firings;
CREATE TRIGGER alert_firings_set_updated_at
BEFORE UPDATE ON alert_firings
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS runbook_links_set_updated_at ON runbook_links;
CREATE TRIGGER runbook_links_set_updated_at
BEFORE UPDATE ON runbook_links
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS alert_acknowledgements_set_updated_at ON alert_acknowledgements;
CREATE TRIGGER alert_acknowledgements_set_updated_at
BEFORE UPDATE ON alert_acknowledgements
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

COMMIT;