// ═══════════════════════════════════════════════════════════════════════════════
// POINT ZERO ONE — src/ml/m05a_macro_regime_classifier_cash_decay_tuner.ts
// AUTO-GENERATED by scripts/build_ml_mechanics.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/build_ml_mechanics.py --force
//
// ML Companion : M05A — Macro Regime Classifier + Cash Decay Tuner
// Core Pair    : M05
// Tiers        : BASELINE, SEQUENCE_DL, POLICY_RL
// Placement    : server
// Budget       : real_time
// Lock-Off     : YES — competitive mode can disable balance nudges
//
// ML Design Laws (non-negotiable):
//   ✦ ML can suggest; rules decide — NEVER rewrite resolved ledger history
//   ✦ Bounded nudges — all outputs have explicit caps + monotonic constraints
//   ✦ Auditability — every inference writes (ruleset_version, seed, tick, cap, output)
//   ✦ Privacy — no contact-graph mining; in-session signals only for social reasoning
//
// Density6 LLC · Point Zero One · Confidential · All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════════

// ── What this adds ────────────────────────────────────────────────────────────
/**
 * M05A — Macro Regime Classifier + Cash Decay Tuner
 *
 * Primary function:
 *   Classify current market regime from run state signals; tune cash decay rate to stay within design bounds
 *
 * What this adds to M05:
 * 1. Classify current market regime in real time and tune cash decay rate within bounded design envelope.
 * 2. Ensures regime transitions feel earned, not arbitrary; detects when macro is too punishing for skill band.
 * 3. Drives Macro Shock Scheduler (M20) pre-computation.
 *
 * Core mechanic pair: M05
 */

// ── Shared telemetry input (standard across all ML companions) ────────────────
export interface M05ATelemetryInput {
  runSeed:           string;
  tickIndex:         number;
  rulesetVersion:    string;
  macroRegime:       string;
  portfolioSnapshot: Record<string, unknown>;
  actionTimeline:    Record<string, unknown>[];
  uiInteraction:     Record<string, unknown>;
  socialEvents:      Record<string, unknown>[];
  outcomeEvents:     Record<string, unknown>[];
  /** Optional — only included for mechanics that need ledger history */
  ledgerEvents?:     Record<string, unknown>[];
  /** Optional — only included for contract-graph mechanics */
  contractGraph?:    Record<string, unknown>;
  /** Player opt-in preferences — ML honours opt-out silently */
  userOptIn:         Record<string, boolean>;
}

// ── Primary output contract ───────────────────────────────────────────────────
/** Standard base output — all ML mechanics return this shape + extensions */
export interface M05ABaseOutput {
  /** 0–1 score — semantic depends on mechanic (risk / value / trust / etc.) */
  score:          number;
  /** ≤5 plain-English factors explaining the score */
  topFactors:     string[];
  /** Single-sentence bounded recommendation (never a guarantee) */
  recommendation: string;
  /** SHA256(inputs + outputs + ruleset_version + caps) */
  auditHash:      string;
}

/** Extended output — M05A-specific signals */
export interface M05AOutput extends M05ABaseOutput {
  regimeClassification: unknown;  // regime_classification
  regimeConfidence: unknown;  // regime_confidence
  decayRateDelta: unknown;  // decay_rate_delta
  transitionProbability: unknown;  // transition_probability
}

// ── Model tiers ───────────────────────────────────────────────────────────────
export type M05ATier = 'baseline' | 'sequence_dl' | 'policy_rl';

/** M05A — Tier: BASELINE
 *  Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
 */
export interface M05ABaselineConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M05A — Tier: SEQUENCE_DL
 *  TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
 */
export interface M05ASequenceDlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M05A — Tier: POLICY_RL
 *  Constrained contextual bandit / offline RL (decision routing + bounded nudges)
 */
export interface M05APolicyRlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

// ── Inference placement ───────────────────────────────────────────────────────
export type M05APlacement = 'server';

export interface M05AInferencePlacement {
  /** Server-side — integrity, balancing, anti-abuse, economy */
  server: boolean;
  /** Inference budget: real_time | batch | hybrid */
  budget: 'real_time';
}

// ── Guardrails (non-negotiable) ───────────────────────────────────────────────
export interface M05AGuardrails {
  /** ML NEVER rewrites resolved ledger history */
  determinismPreserved:   true;
  /** All outputs have explicit caps + monotonic constraints */
  boundedNudges:          true;
  /** Every inference writes a signed receipt to the run ledger */
  auditabilityRequired:   true;
  /** No contact-graph mining; in-session signals only */
  privacyEnforced:        true;
  /** Competitive modes can lock off balance nudges (integrity always stays on) */
  competitiveLockOffAllowed: true;
  /** Output cap for the primary score field */
  scoreCap:               1.0;
  /** Minimum abstain threshold — below this confidence, output null recommendation */
  abstainThreshold:       number;
}

// ── Evaluation contract (minimum bar) ────────────────────────────────────────
export interface M05AEvalContract {
  /** regime_classification_accuracy */
  /** false_transition_rate */
  /** decay_calibration_ECE */
  /** All mechanics: moment yield ≥ 3 share moments/run (FUBAR, flip, missed bag) */
  momentYieldMinimum: 3;
  /** All mechanics: trust metric — low 'rigged' reports */
  maxRiggedReportRate: number;
  /** All mechanics: fairness drift across skill bands */
  maxFairnessDrift: number;
}

// ── Model card ────────────────────────────────────────────────────────────────
/** Identity stamp — emitted with every inference receipt */
export interface M05AModelCard {
  modelId:           'M05A';
  coreMechanicPair:  'M05';
  tier:              M05ATier;
  modelVersion:      string;
  trainCutDate:      string;
  featureSchemaHash: string;
  ruleset_version:   string;
}

// ── Constants ─────────────────────────────────────────────────────────────────
export const M05A_ML_CONSTANTS = {
  ML_ID:            'M05A',
  CORE_PAIR:        'M05',
  MODEL_NAME:       'Macro Regime Classifier + Cash Decay Tuner',
  TIERS:            ['baseline', 'sequence_dl', 'policy_rl'] as const,
  PLACEMENT:        ['server'] as const,
  BUDGET:           'real_time' as const,
  CAN_LOCK_OFF:      true,
  GUARDRAILS: {
    determinismPreserved:       true,
    boundedNudges:              true,
    auditabilityRequired:       true,
    privacyEnforced:            true,
    competitiveLockOffAllowed:  true,
    scoreCap:                   1.0,
    abstainThreshold:           0.35,
  },
  EVAL_FOCUS: ["regime_classification_accuracy", "false_transition_rate", "decay_calibration_ECE"],
  PRIMARY_OUTPUTS: ["regime_classification", "regime_confidence", "decay_rate_delta", "transition_probability"],
} as const;

// ── Main inference function ───────────────────────────────────────────────────
/**
 * runM05aMl
 *
 * Async — fires after core exec_hook (M05), reads output, returns advisory signals.
 * NEVER mutates state. All suggestions are bounded. Competitive mode can disable
 * balance nudges (can_lock_off=true); integrity signals always run.
 *
 * @param input     - Telemetry input snapshot
 * @param tier      - Model tier to use (default: 'baseline' for latency budget)
 * @param modelCard - Identity stamp for audit receipt
 * @returns         - M05AOutput + signed audit_hash
 */
export async function runM05aMl(
  input:     M05ATelemetryInput,
  tier:      M05ATier = 'baseline',
  modelCard: Omit<M05AModelCard, 'modelId' | 'coreMechanicPair'>,
): Promise<M05AOutput> {
  // ── TODO: implement M05A — Macro Regime Classifier + Cash Decay Tuner ─────────────────────────────────
  //
  // Implementation checklist:
  // □ Validate input schema against featureSchemaHash
  // □ Select inference backend based on `tier` parameter
  // □ Apply input privacy filters (no PII, no cross-player contact graph)
  // □ Run inference → raw score + top_factors
  // □ Apply output caps: score = Math.min(score, M05A_ML_CONSTANTS.GUARDRAILS.scoreCap)
  // □ Apply monotonic constraints where relevant
  // □ Abstain if confidence < abstainThreshold (return null recommendation)
  // □ Compute auditHash = SHA256(inputs + outputs + ruleset_version + caps)
  // □ Write signed receipt to run ledger (never skip this step)
  // □ Return M05AOutput — never mutate run state directly
  //
  // Tier routing:
  // // □ tier === 'baseline' → Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
// □ tier === 'sequence_dl' → TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
// □ tier === 'policy_rl' → Constrained contextual bandit / offline RL (decision routing + bounded nudges)
  //
  // Placement: server | Budget: real_time
  //
  // ─────────────────────────────────────────────────────────────────────────
  throw new Error('M05A (Macro Regime Classifier + Cash Decay Tuner) ML inference is not yet implemented.');
}

// ── Degraded mode fallback ────────────────────────────────────────────────────
/**
 * M05AFallback — rule-based fallback when ML is unavailable.
 * Must never throw; must return a valid (degraded) M05AOutput.
 * Competitive modes may use this exclusively when ML is locked off.
 */
export function runM05aMlFallback(
  _input: M05ATelemetryInput,
): M05AOutput {
  // TODO: implement rule-based fallback for M05A
  // Fallback must:
  //   □ Return score = 0.5 (neutral / unknown)
  //   □ Return topFactors = ['ML unavailable — rule-based fallback active']
  //   □ Return recommendation = 'See rule engine output'
  //   □ Compute deterministic auditHash from input seed + 'fallback'
  //   □ Zero-out all M05A-specific extended outputs
  throw new Error('M05A fallback not yet implemented.');
}
