// ═══════════════════════════════════════════════════════════════════════════════
// POINT ZERO ONE — src/ml/m105a_last_look_window_misclick_guard_regret_amplifier.ts
// AUTO-GENERATED by scripts/build_ml_mechanics.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/build_ml_mechanics.py --force
//
// ML Companion : M105A — Last Look Window Misclick Guard + Regret Amplifier
// Core Pair    : M105
// Tiers        : BASELINE, SEQUENCE_DL, POLICY_RL
// Placement    : client
// Budget       : real_time
// Lock-Off     : YES — competitive mode can disable balance nudges
//
// ML Design Laws (non-negotiable):
//   ✦ ML can suggest; rules decide — NEVER rewrite resolved ledger history
//   ✦ Bounded nudges — all outputs have explicit caps + monotonic constraints
//   ✦ Auditability — every inference writes (ruleset_version, seed, tick, cap, output)
//   ✦ Privacy — no contact-graph mining; in-session signals only for social reasoning
//
// Density6 LLC · Point Zero One · Confidential · All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════════

// ── What this adds ────────────────────────────────────────────────────────────
/**
 * M105A — Last Look Window Misclick Guard + Regret Amplifier
 *
 * Primary function:
 *   Detect likely misclick in last-look window; amplify regret signal for post-mortem when a misclick costs the run
 *
 * What this adds to M105:
 * 1. Detect likely misclicks in the last-look window before they become irreversible.
 * 2. Amplify regret signal in post-mortem: 'you misclicked here' with tick evidence.
 * 3. Generates misclick guard receipts for support appeals.
 *
 * Core mechanic pair: M105
 */

// ── Shared telemetry input (standard across all ML companions) ────────────────
export interface M105ATelemetryInput {
  runSeed:           string;
  tickIndex:         number;
  rulesetVersion:    string;
  macroRegime:       string;
  portfolioSnapshot: Record<string, unknown>;
  actionTimeline:    Record<string, unknown>[];
  uiInteraction:     Record<string, unknown>;
  socialEvents:      Record<string, unknown>[];
  outcomeEvents:     Record<string, unknown>[];
  /** Optional — only included for mechanics that need ledger history */
  ledgerEvents?:     Record<string, unknown>[];
  /** Optional — only included for contract-graph mechanics */
  contractGraph?:    Record<string, unknown>;
  /** Player opt-in preferences — ML honours opt-out silently */
  userOptIn:         Record<string, boolean>;
}

// ── Primary output contract ───────────────────────────────────────────────────
/** Standard base output — all ML mechanics return this shape + extensions */
export interface M105ABaseOutput {
  /** 0–1 score — semantic depends on mechanic (risk / value / trust / etc.) */
  score:          number;
  /** ≤5 plain-English factors explaining the score */
  topFactors:     string[];
  /** Single-sentence bounded recommendation (never a guarantee) */
  recommendation: string;
  /** SHA256(inputs + outputs + ruleset_version + caps) */
  auditHash:      string;
}

/** Extended output — M105A-specific signals */
export interface M105AOutput extends M105ABaseOutput {
  misclickProbability: unknown;  // misclick_probability
  regretAmplificationSignal: unknown;  // regret_amplification_signal
  guardReceipt: unknown;  // guard_receipt
  supportEvidence: unknown;  // support_evidence
}

// ── Model tiers ───────────────────────────────────────────────────────────────
export type M105ATier = 'baseline' | 'sequence_dl' | 'policy_rl';

/** M105A — Tier: BASELINE
 *  Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
 */
export interface M105ABaselineConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M105A — Tier: SEQUENCE_DL
 *  TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
 */
export interface M105ASequenceDlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M105A — Tier: POLICY_RL
 *  Constrained contextual bandit / offline RL (decision routing + bounded nudges)
 */
export interface M105APolicyRlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

// ── Inference placement ───────────────────────────────────────────────────────
export type M105APlacement = 'client';

export interface M105AInferencePlacement {
  /** On-device inference — privacy-safe, low-latency UX signals */
  client: boolean;
  /** Inference budget: real_time | batch | hybrid */
  budget: 'real_time';
}

// ── Guardrails (non-negotiable) ───────────────────────────────────────────────
export interface M105AGuardrails {
  /** ML NEVER rewrites resolved ledger history */
  determinismPreserved:   true;
  /** All outputs have explicit caps + monotonic constraints */
  boundedNudges:          true;
  /** Every inference writes a signed receipt to the run ledger */
  auditabilityRequired:   true;
  /** No contact-graph mining; in-session signals only */
  privacyEnforced:        true;
  /** Competitive modes can lock off balance nudges (integrity always stays on) */
  competitiveLockOffAllowed: true;
  /** Output cap for the primary score field */
  scoreCap:               1.0;
  /** Minimum abstain threshold — below this confidence, output null recommendation */
  abstainThreshold:       number;
}

// ── Evaluation contract (minimum bar) ────────────────────────────────────────
export interface M105AEvalContract {
  /** misclick_detection_AUC */
  /** false_guard_rate */
  /** regret_signal_precision */
  /** All mechanics: moment yield ≥ 3 share moments/run (FUBAR, flip, missed bag) */
  momentYieldMinimum: 3;
  /** All mechanics: trust metric — low 'rigged' reports */
  maxRiggedReportRate: number;
  /** All mechanics: fairness drift across skill bands */
  maxFairnessDrift: number;
}

// ── Model card ────────────────────────────────────────────────────────────────
/** Identity stamp — emitted with every inference receipt */
export interface M105AModelCard {
  modelId:           'M105A';
  coreMechanicPair:  'M105';
  tier:              M105ATier;
  modelVersion:      string;
  trainCutDate:      string;
  featureSchemaHash: string;
  ruleset_version:   string;
}

// ── Constants ─────────────────────────────────────────────────────────────────
export const M105A_ML_CONSTANTS = {
  ML_ID:            'M105A',
  CORE_PAIR:        'M105',
  MODEL_NAME:       'Last Look Window Misclick Guard + Regret Amplifier',
  TIERS:            ['baseline', 'sequence_dl', 'policy_rl'] as const,
  PLACEMENT:        ['client'] as const,
  BUDGET:           'real_time' as const,
  CAN_LOCK_OFF:      true,
  GUARDRAILS: {
    determinismPreserved:       true,
    boundedNudges:              true,
    auditabilityRequired:       true,
    privacyEnforced:            true,
    competitiveLockOffAllowed:  true,
    scoreCap:                   1.0,
    abstainThreshold:           0.35,
  },
  EVAL_FOCUS: ["misclick_detection_AUC", "false_guard_rate", "regret_signal_precision"],
  PRIMARY_OUTPUTS: ["misclick_probability", "regret_amplification_signal", "guard_receipt", "support_evidence"],
} as const;

// ── Main inference function ───────────────────────────────────────────────────
/**
 * runM105aMl
 *
 * Async — fires after core exec_hook (M105), reads output, returns advisory signals.
 * NEVER mutates state. All suggestions are bounded. Competitive mode can disable
 * balance nudges (can_lock_off=true); integrity signals always run.
 *
 * @param input     - Telemetry input snapshot
 * @param tier      - Model tier to use (default: 'baseline' for latency budget)
 * @param modelCard - Identity stamp for audit receipt
 * @returns         - M105AOutput + signed audit_hash
 */
export async function runM105aMl(
  input:     M105ATelemetryInput,
  tier:      M105ATier = 'baseline',
  modelCard: Omit<M105AModelCard, 'modelId' | 'coreMechanicPair'>,
): Promise<M105AOutput> {
  // ── TODO: implement M105A — Last Look Window Misclick Guard + Regret Amplifier ─────────────────────────────────
  //
  // Implementation checklist:
  // □ Validate input schema against featureSchemaHash
  // □ Select inference backend based on `tier` parameter
  // □ Apply input privacy filters (no PII, no cross-player contact graph)
  // □ Run inference → raw score + top_factors
  // □ Apply output caps: score = Math.min(score, M105A_ML_CONSTANTS.GUARDRAILS.scoreCap)
  // □ Apply monotonic constraints where relevant
  // □ Abstain if confidence < abstainThreshold (return null recommendation)
  // □ Compute auditHash = SHA256(inputs + outputs + ruleset_version + caps)
  // □ Write signed receipt to run ledger (never skip this step)
  // □ Return M105AOutput — never mutate run state directly
  //
  // Tier routing:
  // // □ tier === 'baseline' → Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
// □ tier === 'sequence_dl' → TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
// □ tier === 'policy_rl' → Constrained contextual bandit / offline RL (decision routing + bounded nudges)
  //
  // Placement: client | Budget: real_time
  //
  // ─────────────────────────────────────────────────────────────────────────
  throw new Error('M105A (Last Look Window Misclick Guard + Regret Amplifier) ML inference is not yet implemented.');
}

// ── Degraded mode fallback ────────────────────────────────────────────────────
/**
 * M105AFallback — rule-based fallback when ML is unavailable.
 * Must never throw; must return a valid (degraded) M105AOutput.
 * Competitive modes may use this exclusively when ML is locked off.
 */
export function runM105aMlFallback(
  _input: M105ATelemetryInput,
): M105AOutput {
  // TODO: implement rule-based fallback for M105A
  // Fallback must:
  //   □ Return score = 0.5 (neutral / unknown)
  //   □ Return topFactors = ['ML unavailable — rule-based fallback active']
  //   □ Return recommendation = 'See rule engine output'
  //   □ Compute deterministic auditHash from input seed + 'fallback'
  //   □ Zero-out all M105A-specific extended outputs
  throw new Error('M105A fallback not yet implemented.');
}
