// ═══════════════════════════════════════════════════════════════════════════════
// POINT ZERO ONE — src/ml/m123a_king_of_the_hill_streak_story_arc_narrator.ts
// AUTO-GENERATED by scripts/build_ml_mechanics.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/build_ml_mechanics.py --force
//
// ML Companion : M123A — King-of-the-Hill Streak Story Arc Narrator
// Core Pair    : M123
// Tiers        : BASELINE, SEQUENCE_DL, POLICY_RL
// Placement    : server
// Budget       : batch
// Lock-Off     : YES — competitive mode can disable balance nudges
//
// ML Design Laws (non-negotiable):
//   ✦ ML can suggest; rules decide — NEVER rewrite resolved ledger history
//   ✦ Bounded nudges — all outputs have explicit caps + monotonic constraints
//   ✦ Auditability — every inference writes (ruleset_version, seed, tick, cap, output)
//   ✦ Privacy — no contact-graph mining; in-session signals only for social reasoning
//
// Density6 LLC · Point Zero One · Confidential · All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════════

// ── What this adds ────────────────────────────────────────────────────────────
/**
 * M123A — King-of-the-Hill Streak Story Arc Narrator
 *
 * Primary function:
 *   Narrate king-of-the-hill streak arcs for social sharing; generate stake rotation fairness signals
 *
 * What this adds to M123:
 * 1. Narrate king-of-the-hill streak arcs as shareable social stories.
 * 2. Generate stake rotation fairness signals: stakes never become prohibitively punishing.
 * 3. Streak legitimacy: verify consecutive wins against collusion patterns.
 *
 * Core mechanic pair: M123
 */

// ── Shared telemetry input (standard across all ML companions) ────────────────
export interface M123ATelemetryInput {
  runSeed:           string;
  tickIndex:         number;
  rulesetVersion:    string;
  macroRegime:       string;
  portfolioSnapshot: Record<string, unknown>;
  actionTimeline:    Record<string, unknown>[];
  uiInteraction:     Record<string, unknown>;
  socialEvents:      Record<string, unknown>[];
  outcomeEvents:     Record<string, unknown>[];
  /** Optional — only included for mechanics that need ledger history */
  ledgerEvents?:     Record<string, unknown>[];
  /** Optional — only included for contract-graph mechanics */
  contractGraph?:    Record<string, unknown>;
  /** Player opt-in preferences — ML honours opt-out silently */
  userOptIn:         Record<string, boolean>;
}

// ── Primary output contract ───────────────────────────────────────────────────
/** Standard base output — all ML mechanics return this shape + extensions */
export interface M123ABaseOutput {
  /** 0–1 score — semantic depends on mechanic (risk / value / trust / etc.) */
  score:          number;
  /** ≤5 plain-English factors explaining the score */
  topFactors:     string[];
  /** Single-sentence bounded recommendation (never a guarantee) */
  recommendation: string;
  /** SHA256(inputs + outputs + ruleset_version + caps) */
  auditHash:      string;
}

/** Extended output — M123A-specific signals */
export interface M123AOutput extends M123ABaseOutput {
  streakNarrative: unknown;  // streak_narrative
  stakeFairnessSignal: unknown;  // stake_fairness_signal
  legitimacyScore: unknown;  // legitimacy_score
  sharePrompt: unknown;  // share_prompt
}

// ── Model tiers ───────────────────────────────────────────────────────────────
export type M123ATier = 'baseline' | 'sequence_dl' | 'policy_rl';

/** M123A — Tier: BASELINE
 *  Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
 */
export interface M123ABaselineConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M123A — Tier: SEQUENCE_DL
 *  TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
 */
export interface M123ASequenceDlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M123A — Tier: POLICY_RL
 *  Constrained contextual bandit / offline RL (decision routing + bounded nudges)
 */
export interface M123APolicyRlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

// ── Inference placement ───────────────────────────────────────────────────────
export type M123APlacement = 'server';

export interface M123AInferencePlacement {
  /** Server-side — integrity, balancing, anti-abuse, economy */
  server: boolean;
  /** Inference budget: real_time | batch | hybrid */
  budget: 'batch';
}

// ── Guardrails (non-negotiable) ───────────────────────────────────────────────
export interface M123AGuardrails {
  /** ML NEVER rewrites resolved ledger history */
  determinismPreserved:   true;
  /** All outputs have explicit caps + monotonic constraints */
  boundedNudges:          true;
  /** Every inference writes a signed receipt to the run ledger */
  auditabilityRequired:   true;
  /** No contact-graph mining; in-session signals only */
  privacyEnforced:        true;
  /** Competitive modes can lock off balance nudges (integrity always stays on) */
  competitiveLockOffAllowed: true;
  /** Output cap for the primary score field */
  scoreCap:               1.0;
  /** Minimum abstain threshold — below this confidence, output null recommendation */
  abstainThreshold:       number;
}

// ── Evaluation contract (minimum bar) ────────────────────────────────────────
export interface M123AEvalContract {
  /** narrative_quality_rating */
  /** stake_fairness_calibration */
  /** legitimacy_AUC */
  /** All mechanics: moment yield ≥ 3 share moments/run (FUBAR, flip, missed bag) */
  momentYieldMinimum: 3;
  /** All mechanics: trust metric — low 'rigged' reports */
  maxRiggedReportRate: number;
  /** All mechanics: fairness drift across skill bands */
  maxFairnessDrift: number;
}

// ── Model card ────────────────────────────────────────────────────────────────
/** Identity stamp — emitted with every inference receipt */
export interface M123AModelCard {
  modelId:           'M123A';
  coreMechanicPair:  'M123';
  tier:              M123ATier;
  modelVersion:      string;
  trainCutDate:      string;
  featureSchemaHash: string;
  ruleset_version:   string;
}

// ── Constants ─────────────────────────────────────────────────────────────────
export const M123A_ML_CONSTANTS = {
  ML_ID:            'M123A',
  CORE_PAIR:        'M123',
  MODEL_NAME:       'King-of-the-Hill Streak Story Arc Narrator',
  TIERS:            ['baseline', 'sequence_dl', 'policy_rl'] as const,
  PLACEMENT:        ['server'] as const,
  BUDGET:           'batch' as const,
  CAN_LOCK_OFF:      true,
  GUARDRAILS: {
    determinismPreserved:       true,
    boundedNudges:              true,
    auditabilityRequired:       true,
    privacyEnforced:            true,
    competitiveLockOffAllowed:  true,
    scoreCap:                   1.0,
    abstainThreshold:           0.35,
  },
  EVAL_FOCUS: ["narrative_quality_rating", "stake_fairness_calibration", "legitimacy_AUC"],
  PRIMARY_OUTPUTS: ["streak_narrative", "stake_fairness_signal", "legitimacy_score", "share_prompt"],
} as const;

// ── Main inference function ───────────────────────────────────────────────────
/**
 * runM123aMl
 *
 * Async — fires after core exec_hook (M123), reads output, returns advisory signals.
 * NEVER mutates state. All suggestions are bounded. Competitive mode can disable
 * balance nudges (can_lock_off=true); integrity signals always run.
 *
 * @param input     - Telemetry input snapshot
 * @param tier      - Model tier to use (default: 'baseline' for latency budget)
 * @param modelCard - Identity stamp for audit receipt
 * @returns         - M123AOutput + signed audit_hash
 */
export async function runM123aMl(
  input:     M123ATelemetryInput,
  tier:      M123ATier = 'baseline',
  modelCard: Omit<M123AModelCard, 'modelId' | 'coreMechanicPair'>,
): Promise<M123AOutput> {
  // ── TODO: implement M123A — King-of-the-Hill Streak Story Arc Narrator ─────────────────────────────────
  //
  // Implementation checklist:
  // □ Validate input schema against featureSchemaHash
  // □ Select inference backend based on `tier` parameter
  // □ Apply input privacy filters (no PII, no cross-player contact graph)
  // □ Run inference → raw score + top_factors
  // □ Apply output caps: score = Math.min(score, M123A_ML_CONSTANTS.GUARDRAILS.scoreCap)
  // □ Apply monotonic constraints where relevant
  // □ Abstain if confidence < abstainThreshold (return null recommendation)
  // □ Compute auditHash = SHA256(inputs + outputs + ruleset_version + caps)
  // □ Write signed receipt to run ledger (never skip this step)
  // □ Return M123AOutput — never mutate run state directly
  //
  // Tier routing:
  // // □ tier === 'baseline' → Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
// □ tier === 'sequence_dl' → TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
// □ tier === 'policy_rl' → Constrained contextual bandit / offline RL (decision routing + bounded nudges)
  //
  // Placement: server | Budget: batch
  //
  // ─────────────────────────────────────────────────────────────────────────
  throw new Error('M123A (King-of-the-Hill Streak Story Arc Narrator) ML inference is not yet implemented.');
}

// ── Degraded mode fallback ────────────────────────────────────────────────────
/**
 * M123AFallback — rule-based fallback when ML is unavailable.
 * Must never throw; must return a valid (degraded) M123AOutput.
 * Competitive modes may use this exclusively when ML is locked off.
 */
export function runM123aMlFallback(
  _input: M123ATelemetryInput,
): M123AOutput {
  // TODO: implement rule-based fallback for M123A
  // Fallback must:
  //   □ Return score = 0.5 (neutral / unknown)
  //   □ Return topFactors = ['ML unavailable — rule-based fallback active']
  //   □ Return recommendation = 'See rule engine output'
  //   □ Compute deterministic auditHash from input seed + 'fallback'
  //   □ Zero-out all M123A-specific extended outputs
  throw new Error('M123A fallback not yet implemented.');
}
