// ═══════════════════════════════════════════════════════════════════════════════
// POINT ZERO ONE — src/ml/m27a_clause_outcome_forecaster_triggers_escapes_penalties.ts
// AUTO-GENERATED by scripts/build_ml_mechanics.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/build_ml_mechanics.py --force
//
// ML Companion : M27A — Clause Outcome Forecaster (Triggers, Escapes, Penalties)
// Core Pair    : M27
// Tiers        : BASELINE, SEQUENCE_DL, GRAPH_DL, POLICY_RL
// Placement    : server
// Budget       : real_time
// Lock-Off     : YES — competitive mode can disable balance nudges
//
// ML Design Laws (non-negotiable):
//   ✦ ML can suggest; rules decide — NEVER rewrite resolved ledger history
//   ✦ Bounded nudges — all outputs have explicit caps + monotonic constraints
//   ✦ Auditability — every inference writes (ruleset_version, seed, tick, cap, output)
//   ✦ Privacy — no contact-graph mining; in-session signals only for social reasoning
//
// Density6 LLC · Point Zero One · Confidential · All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════════

// ── What this adds ────────────────────────────────────────────────────────────
/**
 * M27A — Clause Outcome Forecaster (Triggers, Escapes, Penalties)
 *
 * Primary function:
 *   Forecast probability of each contract clause triggering; surface under-appreciated penalty exposure
 *
 * What this adds to M27:
 * 1. Forecast probability of each contract clause triggering given current run state.
 * 2. Surfaces under-appreciated penalty exposure before the clause fires.
 * 3. Feeds arbitration triage (M55a) with pre-computed clause risk.
 *
 * Core mechanic pair: M27
 */

// ── Shared telemetry input (standard across all ML companions) ────────────────
export interface M27ATelemetryInput {
  runSeed:           string;
  tickIndex:         number;
  rulesetVersion:    string;
  macroRegime:       string;
  portfolioSnapshot: Record<string, unknown>;
  actionTimeline:    Record<string, unknown>[];
  uiInteraction:     Record<string, unknown>;
  socialEvents:      Record<string, unknown>[];
  outcomeEvents:     Record<string, unknown>[];
  /** Optional — only included for mechanics that need ledger history */
  ledgerEvents?:     Record<string, unknown>[];
  /** Optional — only included for contract-graph mechanics */
  contractGraph?:    Record<string, unknown>;
  /** Player opt-in preferences — ML honours opt-out silently */
  userOptIn:         Record<string, boolean>;
}

// ── Primary output contract ───────────────────────────────────────────────────
/** Standard base output — all ML mechanics return this shape + extensions */
export interface M27ABaseOutput {
  /** 0–1 score — semantic depends on mechanic (risk / value / trust / etc.) */
  score:          number;
  /** ≤5 plain-English factors explaining the score */
  topFactors:     string[];
  /** Single-sentence bounded recommendation (never a guarantee) */
  recommendation: string;
  /** SHA256(inputs + outputs + ruleset_version + caps) */
  auditHash:      string;
}

/** Extended output — M27A-specific signals */
export interface M27AOutput extends M27ABaseOutput {
  clauseTriggerProbabilities: unknown;  // clause_trigger_probabilities
  penaltyExposure: unknown;  // penalty_exposure
  escapeWindowEstimate: unknown;  // escape_window_estimate
  arbitrationPrecompute: unknown;  // arbitration_precompute
}

// ── Model tiers ───────────────────────────────────────────────────────────────
export type M27ATier = 'baseline' | 'sequence_dl' | 'graph_dl' | 'policy_rl';

/** M27A — Tier: BASELINE
 *  Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
 */
export interface M27ABaselineConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M27A — Tier: SEQUENCE_DL
 *  TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
 */
export interface M27ASequenceDlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M27A — Tier: GRAPH_DL
 *  GNN over contract / market / ledger graphs (relationship-aware, higher cost)
 */
export interface M27AGraphDlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M27A — Tier: POLICY_RL
 *  Constrained contextual bandit / offline RL (decision routing + bounded nudges)
 */
export interface M27APolicyRlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

// ── Inference placement ───────────────────────────────────────────────────────
export type M27APlacement = 'server';

export interface M27AInferencePlacement {
  /** Server-side — integrity, balancing, anti-abuse, economy */
  server: boolean;
  /** Inference budget: real_time | batch | hybrid */
  budget: 'real_time';
}

// ── Guardrails (non-negotiable) ───────────────────────────────────────────────
export interface M27AGuardrails {
  /** ML NEVER rewrites resolved ledger history */
  determinismPreserved:   true;
  /** All outputs have explicit caps + monotonic constraints */
  boundedNudges:          true;
  /** Every inference writes a signed receipt to the run ledger */
  auditabilityRequired:   true;
  /** No contact-graph mining; in-session signals only */
  privacyEnforced:        true;
  /** Competitive modes can lock off balance nudges (integrity always stays on) */
  competitiveLockOffAllowed: true;
  /** Output cap for the primary score field */
  scoreCap:               1.0;
  /** Minimum abstain threshold — below this confidence, output null recommendation */
  abstainThreshold:       number;
}

// ── Evaluation contract (minimum bar) ────────────────────────────────────────
export interface M27AEvalContract {
  /** clause_trigger_calibration_ECE */
  /** penalty_exposure_recall */
  /** arbitration_precompute_accuracy */
  /** All mechanics: moment yield ≥ 3 share moments/run (FUBAR, flip, missed bag) */
  momentYieldMinimum: 3;
  /** All mechanics: trust metric — low 'rigged' reports */
  maxRiggedReportRate: number;
  /** All mechanics: fairness drift across skill bands */
  maxFairnessDrift: number;
}

// ── Model card ────────────────────────────────────────────────────────────────
/** Identity stamp — emitted with every inference receipt */
export interface M27AModelCard {
  modelId:           'M27A';
  coreMechanicPair:  'M27';
  tier:              M27ATier;
  modelVersion:      string;
  trainCutDate:      string;
  featureSchemaHash: string;
  ruleset_version:   string;
}

// ── Constants ─────────────────────────────────────────────────────────────────
export const M27A_ML_CONSTANTS = {
  ML_ID:            'M27A',
  CORE_PAIR:        'M27',
  MODEL_NAME:       'Clause Outcome Forecaster (Triggers, Escapes, Penalties)',
  TIERS:            ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'] as const,
  PLACEMENT:        ['server'] as const,
  BUDGET:           'real_time' as const,
  CAN_LOCK_OFF:      true,
  GUARDRAILS: {
    determinismPreserved:       true,
    boundedNudges:              true,
    auditabilityRequired:       true,
    privacyEnforced:            true,
    competitiveLockOffAllowed:  true,
    scoreCap:                   1.0,
    abstainThreshold:           0.35,
  },
  EVAL_FOCUS: ["clause_trigger_calibration_ECE", "penalty_exposure_recall", "arbitration_precompute_accuracy"],
  PRIMARY_OUTPUTS: ["clause_trigger_probabilities", "penalty_exposure", "escape_window_estimate", "arbitration_precompute"],
} as const;

// ── Main inference function ───────────────────────────────────────────────────
/**
 * runM27aMl
 *
 * Async — fires after core exec_hook (M27), reads output, returns advisory signals.
 * NEVER mutates state. All suggestions are bounded. Competitive mode can disable
 * balance nudges (can_lock_off=true); integrity signals always run.
 *
 * @param input     - Telemetry input snapshot
 * @param tier      - Model tier to use (default: 'baseline' for latency budget)
 * @param modelCard - Identity stamp for audit receipt
 * @returns         - M27AOutput + signed audit_hash
 */
export async function runM27aMl(
  input:     M27ATelemetryInput,
  tier:      M27ATier = 'baseline',
  modelCard: Omit<M27AModelCard, 'modelId' | 'coreMechanicPair'>,
): Promise<M27AOutput> {
  // ── TODO: implement M27A — Clause Outcome Forecaster (Triggers, Escapes, Penalties) ─────────────────────────────────
  //
  // Implementation checklist:
  // □ Validate input schema against featureSchemaHash
  // □ Select inference backend based on `tier` parameter
  // □ Apply input privacy filters (no PII, no cross-player contact graph)
  // □ Run inference → raw score + top_factors
  // □ Apply output caps: score = Math.min(score, M27A_ML_CONSTANTS.GUARDRAILS.scoreCap)
  // □ Apply monotonic constraints where relevant
  // □ Abstain if confidence < abstainThreshold (return null recommendation)
  // □ Compute auditHash = SHA256(inputs + outputs + ruleset_version + caps)
  // □ Write signed receipt to run ledger (never skip this step)
  // □ Return M27AOutput — never mutate run state directly
  //
  // Tier routing:
  // // □ tier === 'baseline' → Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
// □ tier === 'sequence_dl' → TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
// □ tier === 'graph_dl' → GNN over contract / market / ledger graphs (relationship-aware, higher cost)
// □ tier === 'policy_rl' → Constrained contextual bandit / offline RL (decision routing + bounded nudges)
  //
  // Placement: server | Budget: real_time
  //
  // ─────────────────────────────────────────────────────────────────────────
  throw new Error('M27A (Clause Outcome Forecaster (Triggers, Escapes, Penalties)) ML inference is not yet implemented.');
}

// ── Degraded mode fallback ────────────────────────────────────────────────────
/**
 * M27AFallback — rule-based fallback when ML is unavailable.
 * Must never throw; must return a valid (degraded) M27AOutput.
 * Competitive modes may use this exclusively when ML is locked off.
 */
export function runM27aMlFallback(
  _input: M27ATelemetryInput,
): M27AOutput {
  // TODO: implement rule-based fallback for M27A
  // Fallback must:
  //   □ Return score = 0.5 (neutral / unknown)
  //   □ Return topFactors = ['ML unavailable — rule-based fallback active']
  //   □ Return recommendation = 'See rule engine output'
  //   □ Compute deterministic auditHash from input seed + 'fallback'
  //   □ Zero-out all M27A-specific extended outputs
  throw new Error('M27A fallback not yet implemented.');
}
