// ═══════════════════════════════════════════════════════════════════════════════
// POINT ZERO ONE — src/ml/m38a_quest_router_moment_quest_personalization_novelty.ts
// AUTO-GENERATED by scripts/build_ml_mechanics.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/build_ml_mechanics.py --force
//
// ML Companion : M38A — Quest Router (Moment Quest Personalization + Novelty)
// Core Pair    : M38
// Family       : progression
// Category     : recommender
// IntelSignal  : recommendationPower
// Tiers        : BASELINE, SEQUENCE_DL, GRAPH_DL, POLICY_RL
// Placement    : server
// Budget       : real_time
// Lock-Off     : YES — competitive mode can disable balance nudges
//
// ML Design Laws (non-negotiable):
//   ✦ ML can suggest; rules decide — NEVER rewrite resolved ledger history
//   ✦ Bounded nudges — all outputs have explicit caps + monotonic constraints
//   ✦ Auditability — every inference writes (ruleset_version, seed, tick, cap, output)
//   ✦ Privacy — no contact-graph mining; in-session signals only
//
// Density6 LLC · Point Zero One · Confidential · All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════════

// ── What this adds ────────────────────────────────────────────────────────────
/**
 * M38A — Quest Router (Moment Quest Personalization + Novelty)
 *
 * Primary function:
 *   Route moment quests to maximize player novelty and share probability without repeating quest archetypes
 *
 * What this adds to M38:
 * 1. Route moment quests to maximize player novelty and share probability.
 * 2. Avoids repeating quest archetypes the player has already mastered.
 * 3. Feeds quest completion analytics for season design.
 *
 * Intelligence signal → IntelligenceState.recommendationPower
 * Core mechanic pair  → M38
 */

// ── Telemetry input ───────────────────────────────────────────────────────────
export interface M38ATelemetryInput {
  runSeed:           string;
  tickIndex:         number;
  rulesetVersion:    string;
  macroRegime:       string;
  portfolioSnapshot: Record<string, unknown>;
  actionTimeline:    Record<string, unknown>[];
  uiInteraction:     Record<string, unknown>;
  socialEvents:      Record<string, unknown>[];
  outcomeEvents:     Record<string, unknown>[];
  ledgerEvents?:     Record<string, unknown>[];
  contractGraph?:    Record<string, unknown>;
  userOptIn:         Record<string, boolean>;
  // Extended inputs for M38A (progression family)

}

// Telemetry events subscribed by M38A
// 

// ── Primary output contract ───────────────────────────────────────────────────
export interface M38ABaseOutput {
  score:          number;  // 0–1, semantic depends on mechanic
  topFactors:     string[];
  recommendation: string;
  auditHash:      string;  // SHA256(inputs + outputs + ruleset_version + caps)
}

export interface M38AOutput extends M38ABaseOutput {
  questRouteRecommendation: unknown;  // quest_route_recommendation
  noveltyScore: unknown;  // novelty_score
  shareProbability: unknown;  // share_probability
  archetypeMasteryMap: unknown;  // archetype_mastery_map
}

// ── Model tiers ───────────────────────────────────────────────────────────────
export type M38ATier = 'baseline' | 'sequence_dl' | 'graph_dl' | 'policy_rl';

/** M38A — Tier: BASELINE
 *  GBM + calibrated logistic (fast, low-cost, production default)
 */
export interface M38ABaselineConfig {
  enabled:          boolean;
  modelVersion:     string;
  featureSchemaHash: string;
  latencySLOMs:     number;   // 0 = batch/async
}

/** M38A — Tier: SEQUENCE_DL
 *  TCN / Transformer encoder over event streams (sequential patterns)
 */
export interface M38ASequenceDlConfig {
  enabled:          boolean;
  modelVersion:     string;
  featureSchemaHash: string;
  latencySLOMs:     number;   // 0 = batch/async
}

/** M38A — Tier: GRAPH_DL
 *  GNN over contract / market / ledger graphs (relationship-aware)
 */
export interface M38AGraphDlConfig {
  enabled:          boolean;
  modelVersion:     string;
  featureSchemaHash: string;
  latencySLOMs:     number;   // 0 = batch/async
}

/** M38A — Tier: POLICY_RL
 *  Constrained contextual bandit / offline PPO (bounded nudges)
 */
export interface M38APolicyRlConfig {
  enabled:          boolean;
  modelVersion:     string;
  featureSchemaHash: string;
  latencySLOMs:     number;   // 0 = batch/async
}

// ── Inference placement ───────────────────────────────────────────────────────
export type M38APlacement = 'server';

export interface M38AInferencePlacement {
  /** Server-side — integrity, balancing, anti-abuse, economy */
  server: boolean;
  budget: 'real_time';
}

// ── Guardrails (non-negotiable) ───────────────────────────────────────────────
export interface M38AGuardrails {
  determinismPreserved:        true;
  boundedNudges:               true;
  auditabilityRequired:        true;
  privacyEnforced:             true;
  competitiveLockOffAllowed:   true;
  scoreCap:                    1.0;
  abstainThreshold:            number;
}

// ── Evaluation contract ───────────────────────────────────────────────────────
export interface M38AEvalContract {
  /** quest_completion_rate */
  /** share_yield */
  /** novelty_entropy */
  momentYieldMinimum:  3;
  maxRiggedReportRate: number;
  maxFairnessDrift:    number;
}

// ── Model card ────────────────────────────────────────────────────────────────
export interface M38AModelCard {
  modelId:            'M38A';
  coreMechanicPair:   'M38';
  intelligenceSignal: 'recommendationPower';
  modelCategory:      'recommender';
  family:             'progression';
  tier:               M38ATier;
  modelVersion:       string;
  trainCutDate:       string;
  featureSchemaHash:  string;
  rulesetVersion:     string;
}

// ── Constants ─────────────────────────────────────────────────────────────────
export const M38A_ML_CONSTANTS = {
  ML_ID:              'M38A',
  CORE_PAIR:          'M38',
  MODEL_NAME:         'Quest Router (Moment Quest Personalization + Novelty)',
  INTEL_SIGNAL:       'recommendationPower' as const,
  MODEL_CATEGORY:     'recommender' as const,
  FAMILY:             'progression' as const,
  TIERS:              ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'] as const,
  PLACEMENT:          ['server'] as const,
  BUDGET:             'real_time' as const,
  CAN_LOCK_OFF:        true,
  GUARDRAILS: {
    determinismPreserved:      true,
    boundedNudges:             true,
    auditabilityRequired:      true,
    privacyEnforced:           true,
    competitiveLockOffAllowed: true,
    scoreCap:                  1.0,
    abstainThreshold:          0.35,
  },
  EVAL_FOCUS:         ["quest_completion_rate", "share_yield", "novelty_entropy"],
  PRIMARY_OUTPUTS:    ["quest_route_recommendation", "novelty_score", "share_probability", "archetype_mastery_map"],
  TELEMETRY_EVENTS:   [],
} as const;

// ── Main inference function ───────────────────────────────────────────────────
/**
 * runM38aMl
 *
 * Fires after M38 exec_hook, reads resolved output, returns advisory signals.
 * NEVER mutates game state. All suggestions are bounded.
 * Competitive mode may disable balance nudges (can_lock_off=true).
 * Integrity signals always run regardless of lock-off state.
 *
 * @param input     Telemetry snapshot
 * @param tier      Model tier to route (default: 'baseline' for latency budget)
 * @param modelCard Identity stamp written to every audit receipt
 * @returns         M38AOutput with signed auditHash
 */
export async function runM38aMl(
  input:     M38ATelemetryInput,
  tier:      M38ATier = 'baseline',
  modelCard: Omit<M38AModelCard, 'modelId' | 'coreMechanicPair'>,
): Promise<M38AOutput> {
  // ── TODO: implement M38A — Quest Router (Moment Quest Personalization + Novelty) ─────────────────────────────────
  //
  // Implementation checklist:
  // □ Validate input schema against featureSchemaHash
  // □ Select inference backend based on `tier` parameter
  // □ tier === 'baseline' → GBM + calibrated logistic (fast, low-cost, production default)
  // □ tier === 'sequence_dl' → TCN / Transformer encoder over event streams (sequential patterns)
  // □ tier === 'graph_dl' → GNN over contract / market / ledger graphs (relationship-aware)
  // □ tier === 'policy_rl' → Constrained contextual bandit / offline PPO (bounded nudges)
  // □ Apply input privacy filters (no PII, no cross-player contact graph)
  // □ Run inference → raw score + top_factors
  // □ Apply output caps: score = Math.min(score, M38A_ML_CONSTANTS.GUARDRAILS.scoreCap)
  // □ Apply monotonic constraints where relevant
  // □ Abstain if confidence < M38A_ML_CONSTANTS.GUARDRAILS.abstainThreshold
  // □ Compute auditHash = SHA256(inputs + outputs + ruleset_version + caps)
  // □ Write signed receipt to run ledger (NEVER skip)
  // □ Return M38AOutput — NEVER mutate run state directly
  //
  // Placement: server | Budget: real_time
  // ExecHook:  after_m38_resolve
  // ─────────────────────────────────────────────────────────────────────────
  throw new Error('M38A (Quest Router (Moment Quest Personalization + Novelty)) ML inference not yet implemented.');
}

// ── Degraded-mode fallback ────────────────────────────────────────────────────
/**
 * runM38aMlFallback — rule-based fallback when ML is unavailable.
 * Must never throw. Returns valid (degraded) M38AOutput.
 * Competitive modes use this when ML nudges are locked off.
 */
export function runM38aMlFallback(
  _input: M38ATelemetryInput,
): M38AOutput {
  // TODO: implement rule-based fallback for M38A
  // Fallback must:
  //   □ Return score = 0.5 (neutral / unknown)
  //   □ Return topFactors = ['ML unavailable — rule-based fallback active']
  //   □ Return recommendation = 'See rule engine output'
  //   □ Compute deterministic auditHash from input seed + 'fallback'
  //   □ Zero-out all M38A-specific extended outputs
  throw new Error('M38A fallback not yet implemented.');
}

// ── IntelligenceState integration note ───────────────────────────────────────
// This mechanic writes to IntelligenceState.recommendationPower
// Heuristic substitute (until ML is live):
//   intelligence.recommendationPower = archetypeMatchScore * noveltyEntropy
// Replace with: runM38aMl(telemetry, tier, modelCard).then(out => intelligence.recommendationPower = out.score)
