// ═══════════════════════════════════════════════════════════════════════════════
// POINT ZERO ONE — src/ml/m42a_prompt_minimalism_controller_when_to_speak_when_to_stay.ts
// AUTO-GENERATED by scripts/build_ml_mechanics.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/build_ml_mechanics.py --force
//
// ML Companion : M42A — Prompt Minimalism Controller (When to Speak, When to Stay Silent)
// Core Pair    : M42
// Tiers        : BASELINE, SEQUENCE_DL, GRAPH_DL, POLICY_RL
// Placement    : client
// Budget       : real_time
// Lock-Off     : YES — competitive mode can disable balance nudges
//
// ML Design Laws (non-negotiable):
//   ✦ ML can suggest; rules decide — NEVER rewrite resolved ledger history
//   ✦ Bounded nudges — all outputs have explicit caps + monotonic constraints
//   ✦ Auditability — every inference writes (ruleset_version, seed, tick, cap, output)
//   ✦ Privacy — no contact-graph mining; in-session signals only for social reasoning
//
// Density6 LLC · Point Zero One · Confidential · All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════════

// ── What this adds ────────────────────────────────────────────────────────────
/**
 * M42A — Prompt Minimalism Controller (When to Speak, When to Stay Silent)
 *
 * Primary function:
 *   Predict when a guided prompt adds value vs. breaks immersion; enforce minimalism without leaving players lost
 *
 * What this adds to M42:
 * 1. Predict when a guided prompt adds genuine value vs. breaks immersion.
 * 2. Enforces prompt minimalism: fewer, higher-signal prompts.
 * 3. Learns individual tolerance for guidance; respects opt-out permanently.
 *
 * Core mechanic pair: M42
 */

// ── Shared telemetry input (standard across all ML companions) ────────────────
export interface M42ATelemetryInput {
  runSeed:           string;
  tickIndex:         number;
  rulesetVersion:    string;
  macroRegime:       string;
  portfolioSnapshot: Record<string, unknown>;
  actionTimeline:    Record<string, unknown>[];
  uiInteraction:     Record<string, unknown>;
  socialEvents:      Record<string, unknown>[];
  outcomeEvents:     Record<string, unknown>[];
  /** Optional — only included for mechanics that need ledger history */
  ledgerEvents?:     Record<string, unknown>[];
  /** Optional — only included for contract-graph mechanics */
  contractGraph?:    Record<string, unknown>;
  /** Player opt-in preferences — ML honours opt-out silently */
  userOptIn:         Record<string, boolean>;
}

// ── Primary output contract ───────────────────────────────────────────────────
/** Standard base output — all ML mechanics return this shape + extensions */
export interface M42ABaseOutput {
  /** 0–1 score — semantic depends on mechanic (risk / value / trust / etc.) */
  score:          number;
  /** ≤5 plain-English factors explaining the score */
  topFactors:     string[];
  /** Single-sentence bounded recommendation (never a guarantee) */
  recommendation: string;
  /** SHA256(inputs + outputs + ruleset_version + caps) */
  auditHash:      string;
}

/** Extended output — M42A-specific signals */
export interface M42AOutput extends M42ABaseOutput {
  promptValueScore: unknown;  // prompt_value_score
  immersionBreakRisk: unknown;  // immersion_break_risk
  silenceRecommendation: unknown;  // silence_recommendation
  individualToleranceEstimate: unknown;  // individual_tolerance_estimate
}

// ── Model tiers ───────────────────────────────────────────────────────────────
export type M42ATier = 'baseline' | 'sequence_dl' | 'graph_dl' | 'policy_rl';

/** M42A — Tier: BASELINE
 *  Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
 */
export interface M42ABaselineConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M42A — Tier: SEQUENCE_DL
 *  TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
 */
export interface M42ASequenceDlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M42A — Tier: GRAPH_DL
 *  GNN over contract / market / ledger graphs (relationship-aware, higher cost)
 */
export interface M42AGraphDlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M42A — Tier: POLICY_RL
 *  Constrained contextual bandit / offline RL (decision routing + bounded nudges)
 */
export interface M42APolicyRlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

// ── Inference placement ───────────────────────────────────────────────────────
export type M42APlacement = 'client';

export interface M42AInferencePlacement {
  /** On-device inference — privacy-safe, low-latency UX signals */
  client: boolean;
  /** Inference budget: real_time | batch | hybrid */
  budget: 'real_time';
}

// ── Guardrails (non-negotiable) ───────────────────────────────────────────────
export interface M42AGuardrails {
  /** ML NEVER rewrites resolved ledger history */
  determinismPreserved:   true;
  /** All outputs have explicit caps + monotonic constraints */
  boundedNudges:          true;
  /** Every inference writes a signed receipt to the run ledger */
  auditabilityRequired:   true;
  /** No contact-graph mining; in-session signals only */
  privacyEnforced:        true;
  /** Competitive modes can lock off balance nudges (integrity always stays on) */
  competitiveLockOffAllowed: true;
  /** Output cap for the primary score field */
  scoreCap:               1.0;
  /** Minimum abstain threshold — below this confidence, output null recommendation */
  abstainThreshold:       number;
}

// ── Evaluation contract (minimum bar) ────────────────────────────────────────
export interface M42AEvalContract {
  /** prompt_acceptance_rate */
  /** immersion_break_rate */
  /** guidance_satisfaction */
  /** All mechanics: moment yield ≥ 3 share moments/run (FUBAR, flip, missed bag) */
  momentYieldMinimum: 3;
  /** All mechanics: trust metric — low 'rigged' reports */
  maxRiggedReportRate: number;
  /** All mechanics: fairness drift across skill bands */
  maxFairnessDrift: number;
}

// ── Model card ────────────────────────────────────────────────────────────────
/** Identity stamp — emitted with every inference receipt */
export interface M42AModelCard {
  modelId:           'M42A';
  coreMechanicPair:  'M42';
  tier:              M42ATier;
  modelVersion:      string;
  trainCutDate:      string;
  featureSchemaHash: string;
  ruleset_version:   string;
}

// ── Constants ─────────────────────────────────────────────────────────────────
export const M42A_ML_CONSTANTS = {
  ML_ID:            'M42A',
  CORE_PAIR:        'M42',
  MODEL_NAME:       'Prompt Minimalism Controller (When to Speak, When to Stay Silent)',
  TIERS:            ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'] as const,
  PLACEMENT:        ['client'] as const,
  BUDGET:           'real_time' as const,
  CAN_LOCK_OFF:      true,
  GUARDRAILS: {
    determinismPreserved:       true,
    boundedNudges:              true,
    auditabilityRequired:       true,
    privacyEnforced:            true,
    competitiveLockOffAllowed:  true,
    scoreCap:                   1.0,
    abstainThreshold:           0.35,
  },
  EVAL_FOCUS: ["prompt_acceptance_rate", "immersion_break_rate", "guidance_satisfaction"],
  PRIMARY_OUTPUTS: ["prompt_value_score", "immersion_break_risk", "silence_recommendation", "individual_tolerance_estimate"],
} as const;

// ── Main inference function ───────────────────────────────────────────────────
/**
 * runM42aMl
 *
 * Async — fires after core exec_hook (M42), reads output, returns advisory signals.
 * NEVER mutates state. All suggestions are bounded. Competitive mode can disable
 * balance nudges (can_lock_off=true); integrity signals always run.
 *
 * @param input     - Telemetry input snapshot
 * @param tier      - Model tier to use (default: 'baseline' for latency budget)
 * @param modelCard - Identity stamp for audit receipt
 * @returns         - M42AOutput + signed audit_hash
 */
export async function runM42aMl(
  input:     M42ATelemetryInput,
  tier:      M42ATier = 'baseline',
  modelCard: Omit<M42AModelCard, 'modelId' | 'coreMechanicPair'>,
): Promise<M42AOutput> {
  // ── TODO: implement M42A — Prompt Minimalism Controller (When to Speak, When to Stay Silent) ─────────────────────────────────
  //
  // Implementation checklist:
  // □ Validate input schema against featureSchemaHash
  // □ Select inference backend based on `tier` parameter
  // □ Apply input privacy filters (no PII, no cross-player contact graph)
  // □ Run inference → raw score + top_factors
  // □ Apply output caps: score = Math.min(score, M42A_ML_CONSTANTS.GUARDRAILS.scoreCap)
  // □ Apply monotonic constraints where relevant
  // □ Abstain if confidence < abstainThreshold (return null recommendation)
  // □ Compute auditHash = SHA256(inputs + outputs + ruleset_version + caps)
  // □ Write signed receipt to run ledger (never skip this step)
  // □ Return M42AOutput — never mutate run state directly
  //
  // Tier routing:
  // // □ tier === 'baseline' → Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
// □ tier === 'sequence_dl' → TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
// □ tier === 'graph_dl' → GNN over contract / market / ledger graphs (relationship-aware, higher cost)
// □ tier === 'policy_rl' → Constrained contextual bandit / offline RL (decision routing + bounded nudges)
  //
  // Placement: client | Budget: real_time
  //
  // ─────────────────────────────────────────────────────────────────────────
  throw new Error('M42A (Prompt Minimalism Controller (When to Speak, When to Stay Silent)) ML inference is not yet implemented.');
}

// ── Degraded mode fallback ────────────────────────────────────────────────────
/**
 * M42AFallback — rule-based fallback when ML is unavailable.
 * Must never throw; must return a valid (degraded) M42AOutput.
 * Competitive modes may use this exclusively when ML is locked off.
 */
export function runM42aMlFallback(
  _input: M42ATelemetryInput,
): M42AOutput {
  // TODO: implement rule-based fallback for M42A
  // Fallback must:
  //   □ Return score = 0.5 (neutral / unknown)
  //   □ Return topFactors = ['ML unavailable — rule-based fallback active']
  //   □ Return recommendation = 'See rule engine output'
  //   □ Compute deterministic auditHash from input seed + 'fallback'
  //   □ Zero-out all M42A-specific extended outputs
  throw new Error('M42A fallback not yet implemented.');
}
