// ═══════════════════════════════════════════════════════════════════════════════
// POINT ZERO ONE — src/ml/m43a_what_if_tutor_counterfactual_policy_explainer.ts
// AUTO-GENERATED by scripts/build_ml_mechanics.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/build_ml_mechanics.py --force
//
// ML Companion : M43A — What-If Tutor (Counterfactual Policy Explainer)
// Core Pair    : M43
// Family       : progression
// Category     : predictor
// IntelSignal  : personalization
// Tiers        : BASELINE, SEQUENCE_DL, GRAPH_DL, CAUSAL
// Placement    : server
// Budget       : batch
// Lock-Off     : YES — competitive mode can disable balance nudges
//
// ML Design Laws (non-negotiable):
//   ✦ ML can suggest; rules decide — NEVER rewrite resolved ledger history
//   ✦ Bounded nudges — all outputs have explicit caps + monotonic constraints
//   ✦ Auditability — every inference writes (ruleset_version, seed, tick, cap, output)
//   ✦ Privacy — no contact-graph mining; in-session signals only
//
// Density6 LLC · Point Zero One · Confidential · All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════════

// ── What this adds ────────────────────────────────────────────────────────────
/**
 * M43A — What-If Tutor (Counterfactual Policy Explainer)
 *
 * Primary function:
 *   Generate counterfactual 'what if you had done X instead' scenarios using causal policy explanation
 *
 * What this adds to M43:
 * 1. Generate counterfactual 'what if you had done X instead' scenarios in the Practice Sandbox.
 * 2. Uses causal policy explanation to surface actionable alternatives, not just outcomes.
 * 3. Never teaches optimal exploitation; focuses on principle, not mechanical edge.
 *
 * Intelligence signal → IntelligenceState.personalization
 * Core mechanic pair  → M43
 */

// ── Telemetry input ───────────────────────────────────────────────────────────
export interface M43ATelemetryInput {
  runSeed:           string;
  tickIndex:         number;
  rulesetVersion:    string;
  macroRegime:       string;
  portfolioSnapshot: Record<string, unknown>;
  actionTimeline:    Record<string, unknown>[];
  uiInteraction:     Record<string, unknown>;
  socialEvents:      Record<string, unknown>[];
  outcomeEvents:     Record<string, unknown>[];
  ledgerEvents?:     Record<string, unknown>[];
  contractGraph?:    Record<string, unknown>;
  userOptIn:         Record<string, boolean>;
  // Extended inputs for M43A (progression family)

}

// Telemetry events subscribed by M43A
// 

// ── Primary output contract ───────────────────────────────────────────────────
export interface M43ABaseOutput {
  score:          number;  // 0–1, semantic depends on mechanic
  topFactors:     string[];
  recommendation: string;
  auditHash:      string;  // SHA256(inputs + outputs + ruleset_version + caps)
}

export interface M43AOutput extends M43ABaseOutput {
  counterfactualScenarios: unknown;  // counterfactual_scenarios
  causalExplanation: unknown;  // causal_explanation
  principleLesson: unknown;  // principle_lesson
  exploitationGuardPassed: unknown;  // exploitation_guard_passed
}

// ── Model tiers ───────────────────────────────────────────────────────────────
export type M43ATier = 'baseline' | 'sequence_dl' | 'graph_dl' | 'causal';

/** M43A — Tier: BASELINE
 *  GBM + calibrated logistic (fast, low-cost, production default)
 */
export interface M43ABaselineConfig {
  enabled:          boolean;
  modelVersion:     string;
  featureSchemaHash: string;
  latencySLOMs:     number;   // 0 = batch/async
}

/** M43A — Tier: SEQUENCE_DL
 *  TCN / Transformer encoder over event streams (sequential patterns)
 */
export interface M43ASequenceDlConfig {
  enabled:          boolean;
  modelVersion:     string;
  featureSchemaHash: string;
  latencySLOMs:     number;   // 0 = batch/async
}

/** M43A — Tier: GRAPH_DL
 *  GNN over contract / market / ledger graphs (relationship-aware)
 */
export interface M43AGraphDlConfig {
  enabled:          boolean;
  modelVersion:     string;
  featureSchemaHash: string;
  latencySLOMs:     number;   // 0 = batch/async
}

/** M43A — Tier: CAUSAL
 *  Causal inference + DiD (counterfactual explanations)
 */
export interface M43ACausalConfig {
  enabled:          boolean;
  modelVersion:     string;
  featureSchemaHash: string;
  latencySLOMs:     number;   // 0 = batch/async
}

// ── Inference placement ───────────────────────────────────────────────────────
export type M43APlacement = 'server';

export interface M43AInferencePlacement {
  /** Server-side — integrity, balancing, anti-abuse, economy */
  server: boolean;
  budget: 'batch';
}

// ── Guardrails (non-negotiable) ───────────────────────────────────────────────
export interface M43AGuardrails {
  determinismPreserved:        true;
  boundedNudges:               true;
  auditabilityRequired:        true;
  privacyEnforced:             true;
  competitiveLockOffAllowed:   true;
  scoreCap:                    1.0;
  abstainThreshold:            number;
}

// ── Evaluation contract ───────────────────────────────────────────────────────
export interface M43AEvalContract {
  /** counterfactual_plausibility */
  /** principle_lesson_clarity */
  /** exploitation_guard_AUC */
  momentYieldMinimum:  3;
  maxRiggedReportRate: number;
  maxFairnessDrift:    number;
}

// ── Model card ────────────────────────────────────────────────────────────────
export interface M43AModelCard {
  modelId:            'M43A';
  coreMechanicPair:   'M43';
  intelligenceSignal: 'personalization';
  modelCategory:      'predictor';
  family:             'progression';
  tier:               M43ATier;
  modelVersion:       string;
  trainCutDate:       string;
  featureSchemaHash:  string;
  rulesetVersion:     string;
}

// ── Constants ─────────────────────────────────────────────────────────────────
export const M43A_ML_CONSTANTS = {
  ML_ID:              'M43A',
  CORE_PAIR:          'M43',
  MODEL_NAME:         'What-If Tutor (Counterfactual Policy Explainer)',
  INTEL_SIGNAL:       'personalization' as const,
  MODEL_CATEGORY:     'predictor' as const,
  FAMILY:             'progression' as const,
  TIERS:              ['baseline', 'sequence_dl', 'graph_dl', 'causal'] as const,
  PLACEMENT:          ['server'] as const,
  BUDGET:             'batch' as const,
  CAN_LOCK_OFF:        true,
  GUARDRAILS: {
    determinismPreserved:      true,
    boundedNudges:             true,
    auditabilityRequired:      true,
    privacyEnforced:           true,
    competitiveLockOffAllowed: true,
    scoreCap:                  1.0,
    abstainThreshold:          0.35,
  },
  EVAL_FOCUS:         ["counterfactual_plausibility", "principle_lesson_clarity", "exploitation_guard_AUC"],
  PRIMARY_OUTPUTS:    ["counterfactual_scenarios", "causal_explanation", "principle_lesson", "exploitation_guard_passed"],
  TELEMETRY_EVENTS:   [],
} as const;

// ── Main inference function ───────────────────────────────────────────────────
/**
 * runM43aMl
 *
 * Fires after M43 exec_hook, reads resolved output, returns advisory signals.
 * NEVER mutates game state. All suggestions are bounded.
 * Competitive mode may disable balance nudges (can_lock_off=true).
 * Integrity signals always run regardless of lock-off state.
 *
 * @param input     Telemetry snapshot
 * @param tier      Model tier to route (default: 'baseline' for latency budget)
 * @param modelCard Identity stamp written to every audit receipt
 * @returns         M43AOutput with signed auditHash
 */
export async function runM43aMl(
  input:     M43ATelemetryInput,
  tier:      M43ATier = 'baseline',
  modelCard: Omit<M43AModelCard, 'modelId' | 'coreMechanicPair'>,
): Promise<M43AOutput> {
  // ── TODO: implement M43A — What-If Tutor (Counterfactual Policy Explainer) ─────────────────────────────────
  //
  // Implementation checklist:
  // □ Validate input schema against featureSchemaHash
  // □ Select inference backend based on `tier` parameter
  // □ tier === 'baseline' → GBM + calibrated logistic (fast, low-cost, production default)
  // □ tier === 'sequence_dl' → TCN / Transformer encoder over event streams (sequential patterns)
  // □ tier === 'graph_dl' → GNN over contract / market / ledger graphs (relationship-aware)
  // □ tier === 'causal' → Causal inference + DiD (counterfactual explanations)
  // □ Apply input privacy filters (no PII, no cross-player contact graph)
  // □ Run inference → raw score + top_factors
  // □ Apply output caps: score = Math.min(score, M43A_ML_CONSTANTS.GUARDRAILS.scoreCap)
  // □ Apply monotonic constraints where relevant
  // □ Abstain if confidence < M43A_ML_CONSTANTS.GUARDRAILS.abstainThreshold
  // □ Compute auditHash = SHA256(inputs + outputs + ruleset_version + caps)
  // □ Write signed receipt to run ledger (NEVER skip)
  // □ Return M43AOutput — NEVER mutate run state directly
  //
  // Placement: server | Budget: batch
  // ExecHook:  after_m43_resolve
  // ─────────────────────────────────────────────────────────────────────────
  throw new Error('M43A (What-If Tutor (Counterfactual Policy Explainer)) ML inference not yet implemented.');
}

// ── Degraded-mode fallback ────────────────────────────────────────────────────
/**
 * runM43aMlFallback — rule-based fallback when ML is unavailable.
 * Must never throw. Returns valid (degraded) M43AOutput.
 * Competitive modes use this when ML nudges are locked off.
 */
export function runM43aMlFallback(
  _input: M43ATelemetryInput,
): M43AOutput {
  // TODO: implement rule-based fallback for M43A
  // Fallback must:
  //   □ Return score = 0.5 (neutral / unknown)
  //   □ Return topFactors = ['ML unavailable — rule-based fallback active']
  //   □ Return recommendation = 'See rule engine output'
  //   □ Compute deterministic auditHash from input seed + 'fallback'
  //   □ Zero-out all M43A-specific extended outputs
  throw new Error('M43A fallback not yet implemented.');
}

// ── IntelligenceState integration note ───────────────────────────────────────
// This mechanic writes to IntelligenceState.personalization
// Heuristic substitute (until ML is live):
//   intelligence.personalization = skillBandIndex * sessionProgressionRate
// Replace with: runM43aMl(telemetry, tier, modelCard).then(out => intelligence.personalization = out.score)
