// ═══════════════════════════════════════════════════════════════════════════════
// POINT ZERO ONE — src/ml/m45a_training_wheels_scheduler_grace_period_optimization.ts
// AUTO-GENERATED by scripts/build_ml_mechanics.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/build_ml_mechanics.py --force
//
// ML Companion : M45A — Training Wheels Scheduler (Grace-Period Optimization)
// Core Pair    : M45
// Tiers        : BASELINE, SEQUENCE_DL, GRAPH_DL, POLICY_RL
// Placement    : server
// Budget       : batch
// Lock-Off     : YES — competitive mode can disable balance nudges
//
// ML Design Laws (non-negotiable):
//   ✦ ML can suggest; rules decide — NEVER rewrite resolved ledger history
//   ✦ Bounded nudges — all outputs have explicit caps + monotonic constraints
//   ✦ Auditability — every inference writes (ruleset_version, seed, tick, cap, output)
//   ✦ Privacy — no contact-graph mining; in-session signals only for social reasoning
//
// Density6 LLC · Point Zero One · Confidential · All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════════

// ── What this adds ────────────────────────────────────────────────────────────
/**
 * M45A — Training Wheels Scheduler (Grace-Period Optimization)
 *
 * Primary function:
 *   Optimize grace period duration and protection strength per player; remove training wheels at the right moment
 *
 * What this adds to M45:
 * 1. Optimize grace period duration and protection strength per player skill trajectory.
 * 2. Remove training wheels at the exact moment the player is ready — not too early, not too late.
 * 3. Detects grace period abuse: players deliberately staying in protection mode.
 *
 * Core mechanic pair: M45
 */

// ── Shared telemetry input (standard across all ML companions) ────────────────
export interface M45ATelemetryInput {
  runSeed:           string;
  tickIndex:         number;
  rulesetVersion:    string;
  macroRegime:       string;
  portfolioSnapshot: Record<string, unknown>;
  actionTimeline:    Record<string, unknown>[];
  uiInteraction:     Record<string, unknown>;
  socialEvents:      Record<string, unknown>[];
  outcomeEvents:     Record<string, unknown>[];
  /** Optional — only included for mechanics that need ledger history */
  ledgerEvents?:     Record<string, unknown>[];
  /** Optional — only included for contract-graph mechanics */
  contractGraph?:    Record<string, unknown>;
  /** Player opt-in preferences — ML honours opt-out silently */
  userOptIn:         Record<string, boolean>;
}

// ── Primary output contract ───────────────────────────────────────────────────
/** Standard base output — all ML mechanics return this shape + extensions */
export interface M45ABaseOutput {
  /** 0–1 score — semantic depends on mechanic (risk / value / trust / etc.) */
  score:          number;
  /** ≤5 plain-English factors explaining the score */
  topFactors:     string[];
  /** Single-sentence bounded recommendation (never a guarantee) */
  recommendation: string;
  /** SHA256(inputs + outputs + ruleset_version + caps) */
  auditHash:      string;
}

/** Extended output — M45A-specific signals */
export interface M45AOutput extends M45ABaseOutput {
  optimalGraceDuration: unknown;  // optimal_grace_duration
  removalReadinessScore: unknown;  // removal_readiness_score
  abuseFlag: unknown;  // abuse_flag
  protectionStrengthDelta: unknown;  // protection_strength_delta
}

// ── Model tiers ───────────────────────────────────────────────────────────────
export type M45ATier = 'baseline' | 'sequence_dl' | 'graph_dl' | 'policy_rl';

/** M45A — Tier: BASELINE
 *  Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
 */
export interface M45ABaselineConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M45A — Tier: SEQUENCE_DL
 *  TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
 */
export interface M45ASequenceDlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M45A — Tier: GRAPH_DL
 *  GNN over contract / market / ledger graphs (relationship-aware, higher cost)
 */
export interface M45AGraphDlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M45A — Tier: POLICY_RL
 *  Constrained contextual bandit / offline RL (decision routing + bounded nudges)
 */
export interface M45APolicyRlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

// ── Inference placement ───────────────────────────────────────────────────────
export type M45APlacement = 'server';

export interface M45AInferencePlacement {
  /** Server-side — integrity, balancing, anti-abuse, economy */
  server: boolean;
  /** Inference budget: real_time | batch | hybrid */
  budget: 'batch';
}

// ── Guardrails (non-negotiable) ───────────────────────────────────────────────
export interface M45AGuardrails {
  /** ML NEVER rewrites resolved ledger history */
  determinismPreserved:   true;
  /** All outputs have explicit caps + monotonic constraints */
  boundedNudges:          true;
  /** Every inference writes a signed receipt to the run ledger */
  auditabilityRequired:   true;
  /** No contact-graph mining; in-session signals only */
  privacyEnforced:        true;
  /** Competitive modes can lock off balance nudges (integrity always stays on) */
  competitiveLockOffAllowed: true;
  /** Output cap for the primary score field */
  scoreCap:               1.0;
  /** Minimum abstain threshold — below this confidence, output null recommendation */
  abstainThreshold:       number;
}

// ── Evaluation contract (minimum bar) ────────────────────────────────────────
export interface M45AEvalContract {
  /** grace_removal_success_rate */
  /** abuse_detection_AUC */
  /** post_grace_retention */
  /** All mechanics: moment yield ≥ 3 share moments/run (FUBAR, flip, missed bag) */
  momentYieldMinimum: 3;
  /** All mechanics: trust metric — low 'rigged' reports */
  maxRiggedReportRate: number;
  /** All mechanics: fairness drift across skill bands */
  maxFairnessDrift: number;
}

// ── Model card ────────────────────────────────────────────────────────────────
/** Identity stamp — emitted with every inference receipt */
export interface M45AModelCard {
  modelId:           'M45A';
  coreMechanicPair:  'M45';
  tier:              M45ATier;
  modelVersion:      string;
  trainCutDate:      string;
  featureSchemaHash: string;
  ruleset_version:   string;
}

// ── Constants ─────────────────────────────────────────────────────────────────
export const M45A_ML_CONSTANTS = {
  ML_ID:            'M45A',
  CORE_PAIR:        'M45',
  MODEL_NAME:       'Training Wheels Scheduler (Grace-Period Optimization)',
  TIERS:            ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'] as const,
  PLACEMENT:        ['server'] as const,
  BUDGET:           'batch' as const,
  CAN_LOCK_OFF:      true,
  GUARDRAILS: {
    determinismPreserved:       true,
    boundedNudges:              true,
    auditabilityRequired:       true,
    privacyEnforced:            true,
    competitiveLockOffAllowed:  true,
    scoreCap:                   1.0,
    abstainThreshold:           0.35,
  },
  EVAL_FOCUS: ["grace_removal_success_rate", "abuse_detection_AUC", "post_grace_retention"],
  PRIMARY_OUTPUTS: ["optimal_grace_duration", "removal_readiness_score", "abuse_flag", "protection_strength_delta"],
} as const;

// ── Main inference function ───────────────────────────────────────────────────
/**
 * runM45aMl
 *
 * Async — fires after core exec_hook (M45), reads output, returns advisory signals.
 * NEVER mutates state. All suggestions are bounded. Competitive mode can disable
 * balance nudges (can_lock_off=true); integrity signals always run.
 *
 * @param input     - Telemetry input snapshot
 * @param tier      - Model tier to use (default: 'baseline' for latency budget)
 * @param modelCard - Identity stamp for audit receipt
 * @returns         - M45AOutput + signed audit_hash
 */
export async function runM45aMl(
  input:     M45ATelemetryInput,
  tier:      M45ATier = 'baseline',
  modelCard: Omit<M45AModelCard, 'modelId' | 'coreMechanicPair'>,
): Promise<M45AOutput> {
  // ── TODO: implement M45A — Training Wheels Scheduler (Grace-Period Optimization) ─────────────────────────────────
  //
  // Implementation checklist:
  // □ Validate input schema against featureSchemaHash
  // □ Select inference backend based on `tier` parameter
  // □ Apply input privacy filters (no PII, no cross-player contact graph)
  // □ Run inference → raw score + top_factors
  // □ Apply output caps: score = Math.min(score, M45A_ML_CONSTANTS.GUARDRAILS.scoreCap)
  // □ Apply monotonic constraints where relevant
  // □ Abstain if confidence < abstainThreshold (return null recommendation)
  // □ Compute auditHash = SHA256(inputs + outputs + ruleset_version + caps)
  // □ Write signed receipt to run ledger (never skip this step)
  // □ Return M45AOutput — never mutate run state directly
  //
  // Tier routing:
  // // □ tier === 'baseline' → Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
// □ tier === 'sequence_dl' → TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
// □ tier === 'graph_dl' → GNN over contract / market / ledger graphs (relationship-aware, higher cost)
// □ tier === 'policy_rl' → Constrained contextual bandit / offline RL (decision routing + bounded nudges)
  //
  // Placement: server | Budget: batch
  //
  // ─────────────────────────────────────────────────────────────────────────
  throw new Error('M45A (Training Wheels Scheduler (Grace-Period Optimization)) ML inference is not yet implemented.');
}

// ── Degraded mode fallback ────────────────────────────────────────────────────
/**
 * M45AFallback — rule-based fallback when ML is unavailable.
 * Must never throw; must return a valid (degraded) M45AOutput.
 * Competitive modes may use this exclusively when ML is locked off.
 */
export function runM45aMlFallback(
  _input: M45ATelemetryInput,
): M45AOutput {
  // TODO: implement rule-based fallback for M45A
  // Fallback must:
  //   □ Return score = 0.5 (neutral / unknown)
  //   □ Return topFactors = ['ML unavailable — rule-based fallback active']
  //   □ Return recommendation = 'See rule engine output'
  //   □ Compute deterministic auditHash from input seed + 'fallback'
  //   □ Zero-out all M45A-specific extended outputs
  throw new Error('M45A fallback not yet implemented.');
}
