// ═══════════════════════════════════════════════════════════════════════════════
// POINT ZERO ONE — src/ml/m77a_delegated_operator_oversight_scope_compliance_abuse_pre.ts
// AUTO-GENERATED by scripts/build_ml_mechanics.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/build_ml_mechanics.py --force
//
// ML Companion : M77A — Delegated Operator Oversight (Scope Compliance + Abuse Predictor)
// Core Pair    : M77
// Tiers        : BASELINE, SEQUENCE_DL, POLICY_RL
// Placement    : server
// Budget       : real_time
// Lock-Off     : YES — competitive mode can disable balance nudges
//
// ML Design Laws (non-negotiable):
//   ✦ ML can suggest; rules decide — NEVER rewrite resolved ledger history
//   ✦ Bounded nudges — all outputs have explicit caps + monotonic constraints
//   ✦ Auditability — every inference writes (ruleset_version, seed, tick, cap, output)
//   ✦ Privacy — no contact-graph mining; in-session signals only for social reasoning
//
// Density6 LLC · Point Zero One · Confidential · All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════════

// ── What this adds ────────────────────────────────────────────────────────────
/**
 * M77A — Delegated Operator Oversight (Scope Compliance + Abuse Predictor)
 *
 * Primary function:
 *   Monitor delegated operator actions for scope compliance; predict abuse before it damages the table
 *
 * What this adds to M77:
 * 1. Monitor delegated operator actions for scope compliance in real time.
 * 2. Predict operator abuse trajectories before damage occurs.
 * 3. Generates delegation audit receipts.
 *
 * Core mechanic pair: M77
 */

// ── Shared telemetry input (standard across all ML companions) ────────────────
export interface M77ATelemetryInput {
  runSeed:           string;
  tickIndex:         number;
  rulesetVersion:    string;
  macroRegime:       string;
  portfolioSnapshot: Record<string, unknown>;
  actionTimeline:    Record<string, unknown>[];
  uiInteraction:     Record<string, unknown>;
  socialEvents:      Record<string, unknown>[];
  outcomeEvents:     Record<string, unknown>[];
  /** Optional — only included for mechanics that need ledger history */
  ledgerEvents?:     Record<string, unknown>[];
  /** Optional — only included for contract-graph mechanics */
  contractGraph?:    Record<string, unknown>;
  /** Player opt-in preferences — ML honours opt-out silently */
  userOptIn:         Record<string, boolean>;
}

// ── Primary output contract ───────────────────────────────────────────────────
/** Standard base output — all ML mechanics return this shape + extensions */
export interface M77ABaseOutput {
  /** 0–1 score — semantic depends on mechanic (risk / value / trust / etc.) */
  score:          number;
  /** ≤5 plain-English factors explaining the score */
  topFactors:     string[];
  /** Single-sentence bounded recommendation (never a guarantee) */
  recommendation: string;
  /** SHA256(inputs + outputs + ruleset_version + caps) */
  auditHash:      string;
}

/** Extended output — M77A-specific signals */
export interface M77AOutput extends M77ABaseOutput {
  scopeComplianceScore: unknown;  // scope_compliance_score
  abusePrediction: unknown;  // abuse_prediction
  delegationReceipt: unknown;  // delegation_receipt
  interventionRecommendation: unknown;  // intervention_recommendation
}

// ── Model tiers ───────────────────────────────────────────────────────────────
export type M77ATier = 'baseline' | 'sequence_dl' | 'policy_rl';

/** M77A — Tier: BASELINE
 *  Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
 */
export interface M77ABaselineConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M77A — Tier: SEQUENCE_DL
 *  TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
 */
export interface M77ASequenceDlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

/** M77A — Tier: POLICY_RL
 *  Constrained contextual bandit / offline RL (decision routing + bounded nudges)
 */
export interface M77APolicyRlConfig {
  enabled: boolean;
  /** Model version string — increment on retrain */
  modelVersion: string;
  /** Feature schema hash — must match training schema */
  featureSchemaHash: string;
  /** Inference latency SLO in ms (0 = batch/async) */
  latencySLOMs: number;
}

// ── Inference placement ───────────────────────────────────────────────────────
export type M77APlacement = 'server';

export interface M77AInferencePlacement {
  /** Server-side — integrity, balancing, anti-abuse, economy */
  server: boolean;
  /** Inference budget: real_time | batch | hybrid */
  budget: 'real_time';
}

// ── Guardrails (non-negotiable) ───────────────────────────────────────────────
export interface M77AGuardrails {
  /** ML NEVER rewrites resolved ledger history */
  determinismPreserved:   true;
  /** All outputs have explicit caps + monotonic constraints */
  boundedNudges:          true;
  /** Every inference writes a signed receipt to the run ledger */
  auditabilityRequired:   true;
  /** No contact-graph mining; in-session signals only */
  privacyEnforced:        true;
  /** Competitive modes can lock off balance nudges (integrity always stays on) */
  competitiveLockOffAllowed: true;
  /** Output cap for the primary score field */
  scoreCap:               1.0;
  /** Minimum abstain threshold — below this confidence, output null recommendation */
  abstainThreshold:       number;
}

// ── Evaluation contract (minimum bar) ────────────────────────────────────────
export interface M77AEvalContract {
  /** scope_violation_recall */
  /** abuse_prediction_AUC */
  /** false_flag_rate */
  /** All mechanics: moment yield ≥ 3 share moments/run (FUBAR, flip, missed bag) */
  momentYieldMinimum: 3;
  /** All mechanics: trust metric — low 'rigged' reports */
  maxRiggedReportRate: number;
  /** All mechanics: fairness drift across skill bands */
  maxFairnessDrift: number;
}

// ── Model card ────────────────────────────────────────────────────────────────
/** Identity stamp — emitted with every inference receipt */
export interface M77AModelCard {
  modelId:           'M77A';
  coreMechanicPair:  'M77';
  tier:              M77ATier;
  modelVersion:      string;
  trainCutDate:      string;
  featureSchemaHash: string;
  ruleset_version:   string;
}

// ── Constants ─────────────────────────────────────────────────────────────────
export const M77A_ML_CONSTANTS = {
  ML_ID:            'M77A',
  CORE_PAIR:        'M77',
  MODEL_NAME:       'Delegated Operator Oversight (Scope Compliance + Abuse Predictor)',
  TIERS:            ['baseline', 'sequence_dl', 'policy_rl'] as const,
  PLACEMENT:        ['server'] as const,
  BUDGET:           'real_time' as const,
  CAN_LOCK_OFF:      true,
  GUARDRAILS: {
    determinismPreserved:       true,
    boundedNudges:              true,
    auditabilityRequired:       true,
    privacyEnforced:            true,
    competitiveLockOffAllowed:  true,
    scoreCap:                   1.0,
    abstainThreshold:           0.35,
  },
  EVAL_FOCUS: ["scope_violation_recall", "abuse_prediction_AUC", "false_flag_rate"],
  PRIMARY_OUTPUTS: ["scope_compliance_score", "abuse_prediction", "delegation_receipt", "intervention_recommendation"],
} as const;

// ── Main inference function ───────────────────────────────────────────────────
/**
 * runM77aMl
 *
 * Async — fires after core exec_hook (M77), reads output, returns advisory signals.
 * NEVER mutates state. All suggestions are bounded. Competitive mode can disable
 * balance nudges (can_lock_off=true); integrity signals always run.
 *
 * @param input     - Telemetry input snapshot
 * @param tier      - Model tier to use (default: 'baseline' for latency budget)
 * @param modelCard - Identity stamp for audit receipt
 * @returns         - M77AOutput + signed audit_hash
 */
export async function runM77aMl(
  input:     M77ATelemetryInput,
  tier:      M77ATier = 'baseline',
  modelCard: Omit<M77AModelCard, 'modelId' | 'coreMechanicPair'>,
): Promise<M77AOutput> {
  // ── TODO: implement M77A — Delegated Operator Oversight (Scope Compliance + Abuse Predictor) ─────────────────────────────────
  //
  // Implementation checklist:
  // □ Validate input schema against featureSchemaHash
  // □ Select inference backend based on `tier` parameter
  // □ Apply input privacy filters (no PII, no cross-player contact graph)
  // □ Run inference → raw score + top_factors
  // □ Apply output caps: score = Math.min(score, M77A_ML_CONSTANTS.GUARDRAILS.scoreCap)
  // □ Apply monotonic constraints where relevant
  // □ Abstain if confidence < abstainThreshold (return null recommendation)
  // □ Compute auditHash = SHA256(inputs + outputs + ruleset_version + caps)
  // □ Write signed receipt to run ledger (never skip this step)
  // □ Return M77AOutput — never mutate run state directly
  //
  // Tier routing:
  // // □ tier === 'baseline' → Gradient-boosted trees + calibrated logistic models (fast, low-cost, production default)
// □ tier === 'sequence_dl' → TCN / Transformer encoder over event streams (higher accuracy, sequential patterns)
// □ tier === 'policy_rl' → Constrained contextual bandit / offline RL (decision routing + bounded nudges)
  //
  // Placement: server | Budget: real_time
  //
  // ─────────────────────────────────────────────────────────────────────────
  throw new Error('M77A (Delegated Operator Oversight (Scope Compliance + Abuse Predictor)) ML inference is not yet implemented.');
}

// ── Degraded mode fallback ────────────────────────────────────────────────────
/**
 * M77AFallback — rule-based fallback when ML is unavailable.
 * Must never throw; must return a valid (degraded) M77AOutput.
 * Competitive modes may use this exclusively when ML is locked off.
 */
export function runM77aMlFallback(
  _input: M77ATelemetryInput,
): M77AOutput {
  // TODO: implement rule-based fallback for M77A
  // Fallback must:
  //   □ Return score = 0.5 (neutral / unknown)
  //   □ Return topFactors = ['ML unavailable — rule-based fallback active']
  //   □ Return recommendation = 'See rule engine output'
  //   □ Compute deterministic auditHash from input seed + 'fallback'
  //   □ Zero-out all M77A-specific extended outputs
  throw new Error('M77A fallback not yet implemented.');
}
