// ═══════════════════════════════════════════════════════════════════════════════
// POINT ZERO ONE — src/ml/m81a_synergy_tree_branch_recommender_identity_routing_non_de.ts
// AUTO-GENERATED by scripts/build_ml_mechanics.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/build_ml_mechanics.py --force
//
// ML Companion : M81A — Synergy Tree Branch Recommender (Identity Routing + Non-Degenerate Paths)
// Core Pair    : M81
// Family       : balance
// Category     : recommender
// IntelSignal  : recommendationPower
// Tiers        : BASELINE, SEQUENCE_DL, POLICY_RL
// Placement    : client, server
// Budget       : real_time
// Lock-Off     : YES — competitive mode can disable balance nudges
//
// ML Design Laws (non-negotiable):
//   ✦ ML can suggest; rules decide — NEVER rewrite resolved ledger history
//   ✦ Bounded nudges — all outputs have explicit caps + monotonic constraints
//   ✦ Auditability — every inference writes (ruleset_version, seed, tick, cap, output)
//   ✦ Privacy — no contact-graph mining; in-session signals only
//
// Density6 LLC · Point Zero One · Confidential · All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════════

// ── What this adds ────────────────────────────────────────────────────────────
/**
 * M81A — Synergy Tree Branch Recommender (Identity Routing + Non-Degenerate Paths)
 *
 * Primary function:
 *   Recommend synergy tree branches that match player identity while filtering degenerate meta paths
 *
 * What this adds to M81:
 * 1. Recommend synergy tree branches matching player identity and play style.
 * 2. Filter degenerate meta paths that trivialize game balance.
 * 3. Novelty injection: surfaces under-explored branches.
 *
 * Intelligence signal → IntelligenceState.recommendationPower
 * Core mechanic pair  → M81
 */

// ── Telemetry input ───────────────────────────────────────────────────────────
export interface M81ATelemetryInput {
  runSeed:           string;
  tickIndex:         number;
  rulesetVersion:    string;
  macroRegime:       string;
  portfolioSnapshot: Record<string, unknown>;
  actionTimeline:    Record<string, unknown>[];
  uiInteraction:     Record<string, unknown>;
  socialEvents:      Record<string, unknown>[];
  outcomeEvents:     Record<string, unknown>[];
  ledgerEvents?:     Record<string, unknown>[];
  contractGraph?:    Record<string, unknown>;
  userOptIn:         Record<string, boolean>;
  // Extended inputs for M81A (balance family)

}

// Telemetry events subscribed by M81A
// 

// ── Primary output contract ───────────────────────────────────────────────────
export interface M81ABaseOutput {
  score:          number;  // 0–1, semantic depends on mechanic
  topFactors:     string[];
  recommendation: string;
  auditHash:      string;  // SHA256(inputs + outputs + ruleset_version + caps)
}

export interface M81AOutput extends M81ABaseOutput {
  branchRecommendation: unknown;  // branch_recommendation
  degeneratePathFlag: unknown;  // degenerate_path_flag
  noveltyScore: unknown;  // novelty_score
  identityMatch: unknown;  // identity_match
}

// ── Model tiers ───────────────────────────────────────────────────────────────
export type M81ATier = 'baseline' | 'sequence_dl' | 'policy_rl';

/** M81A — Tier: BASELINE
 *  GBM + calibrated logistic (fast, low-cost, production default)
 */
export interface M81ABaselineConfig {
  enabled:          boolean;
  modelVersion:     string;
  featureSchemaHash: string;
  latencySLOMs:     number;   // 0 = batch/async
}

/** M81A — Tier: SEQUENCE_DL
 *  TCN / Transformer encoder over event streams (sequential patterns)
 */
export interface M81ASequenceDlConfig {
  enabled:          boolean;
  modelVersion:     string;
  featureSchemaHash: string;
  latencySLOMs:     number;   // 0 = batch/async
}

/** M81A — Tier: POLICY_RL
 *  Constrained contextual bandit / offline PPO (bounded nudges)
 */
export interface M81APolicyRlConfig {
  enabled:          boolean;
  modelVersion:     string;
  featureSchemaHash: string;
  latencySLOMs:     number;   // 0 = batch/async
}

// ── Inference placement ───────────────────────────────────────────────────────
export type M81APlacement = 'client' | 'server';

export interface M81AInferencePlacement {
  /** On-device — privacy-safe, low-latency UX signals */
  client: boolean;
  /** Server-side — integrity, balancing, anti-abuse, economy */
  server: boolean;
  budget: 'real_time';
}

// ── Guardrails (non-negotiable) ───────────────────────────────────────────────
export interface M81AGuardrails {
  determinismPreserved:        true;
  boundedNudges:               true;
  auditabilityRequired:        true;
  privacyEnforced:             true;
  competitiveLockOffAllowed:   true;
  scoreCap:                    1.0;
  abstainThreshold:            number;
}

// ── Evaluation contract ───────────────────────────────────────────────────────
export interface M81AEvalContract {
  /** recommendation_acceptance_rate */
  /** degenerate_path_recall */
  /** identity_match_accuracy */
  momentYieldMinimum:  3;
  maxRiggedReportRate: number;
  maxFairnessDrift:    number;
}

// ── Model card ────────────────────────────────────────────────────────────────
export interface M81AModelCard {
  modelId:            'M81A';
  coreMechanicPair:   'M81';
  intelligenceSignal: 'recommendationPower';
  modelCategory:      'recommender';
  family:             'balance';
  tier:               M81ATier;
  modelVersion:       string;
  trainCutDate:       string;
  featureSchemaHash:  string;
  rulesetVersion:     string;
}

// ── Constants ─────────────────────────────────────────────────────────────────
export const M81A_ML_CONSTANTS = {
  ML_ID:              'M81A',
  CORE_PAIR:          'M81',
  MODEL_NAME:         'Synergy Tree Branch Recommender (Identity Routing + Non-Degenerate Paths)',
  INTEL_SIGNAL:       'recommendationPower' as const,
  MODEL_CATEGORY:     'recommender' as const,
  FAMILY:             'balance' as const,
  TIERS:              ['baseline', 'sequence_dl', 'policy_rl'] as const,
  PLACEMENT:          ['client', 'server'] as const,
  BUDGET:             'real_time' as const,
  CAN_LOCK_OFF:        true,
  GUARDRAILS: {
    determinismPreserved:      true,
    boundedNudges:             true,
    auditabilityRequired:      true,
    privacyEnforced:           true,
    competitiveLockOffAllowed: true,
    scoreCap:                  1.0,
    abstainThreshold:          0.35,
  },
  EVAL_FOCUS:         ["recommendation_acceptance_rate", "degenerate_path_recall", "identity_match_accuracy"],
  PRIMARY_OUTPUTS:    ["branch_recommendation", "degenerate_path_flag", "novelty_score", "identity_match"],
  TELEMETRY_EVENTS:   [],
} as const;

// ── Main inference function ───────────────────────────────────────────────────
/**
 * runM81aMl
 *
 * Fires after M81 exec_hook, reads resolved output, returns advisory signals.
 * NEVER mutates game state. All suggestions are bounded.
 * Competitive mode may disable balance nudges (can_lock_off=true).
 * Integrity signals always run regardless of lock-off state.
 *
 * @param input     Telemetry snapshot
 * @param tier      Model tier to route (default: 'baseline' for latency budget)
 * @param modelCard Identity stamp written to every audit receipt
 * @returns         M81AOutput with signed auditHash
 */
export async function runM81aMl(
  input:     M81ATelemetryInput,
  tier:      M81ATier = 'baseline',
  modelCard: Omit<M81AModelCard, 'modelId' | 'coreMechanicPair'>,
): Promise<M81AOutput> {
  // ── TODO: implement M81A — Synergy Tree Branch Recommender (Identity Routing + Non-Degenerate Paths) ─────────────────────────────────
  //
  // Implementation checklist:
  // □ Validate input schema against featureSchemaHash
  // □ Select inference backend based on `tier` parameter
  // □ tier === 'baseline' → GBM + calibrated logistic (fast, low-cost, production default)
  // □ tier === 'sequence_dl' → TCN / Transformer encoder over event streams (sequential patterns)
  // □ tier === 'policy_rl' → Constrained contextual bandit / offline PPO (bounded nudges)
  // □ Apply input privacy filters (no PII, no cross-player contact graph)
  // □ Run inference → raw score + top_factors
  // □ Apply output caps: score = Math.min(score, M81A_ML_CONSTANTS.GUARDRAILS.scoreCap)
  // □ Apply monotonic constraints where relevant
  // □ Abstain if confidence < M81A_ML_CONSTANTS.GUARDRAILS.abstainThreshold
  // □ Compute auditHash = SHA256(inputs + outputs + ruleset_version + caps)
  // □ Write signed receipt to run ledger (NEVER skip)
  // □ Return M81AOutput — NEVER mutate run state directly
  //
  // Placement: client, server | Budget: real_time
  // ExecHook:  after_m81_resolve
  // ─────────────────────────────────────────────────────────────────────────
  throw new Error('M81A (Synergy Tree Branch Recommender (Identity Routing + Non-Degenerate Paths)) ML inference not yet implemented.');
}

// ── Degraded-mode fallback ────────────────────────────────────────────────────
/**
 * runM81aMlFallback — rule-based fallback when ML is unavailable.
 * Must never throw. Returns valid (degraded) M81AOutput.
 * Competitive modes use this when ML nudges are locked off.
 */
export function runM81aMlFallback(
  _input: M81ATelemetryInput,
): M81AOutput {
  // TODO: implement rule-based fallback for M81A
  // Fallback must:
  //   □ Return score = 0.5 (neutral / unknown)
  //   □ Return topFactors = ['ML unavailable — rule-based fallback active']
  //   □ Return recommendation = 'See rule engine output'
  //   □ Compute deterministic auditHash from input seed + 'fallback'
  //   □ Zero-out all M81A-specific extended outputs
  throw new Error('M81A fallback not yet implemented.');
}

// ── IntelligenceState integration note ───────────────────────────────────────
// This mechanic writes to IntelligenceState.recommendationPower
// Heuristic substitute (until ML is live):
//   intelligence.recommendationPower = archetypeMatchScore * noveltyEntropy
// Replace with: runM81aMl(telemetry, tier, modelCard).then(out => intelligence.recommendationPower = out.score)
