// AUTO-GENERATED, NOW MANUALLY EDITED BY ANTONIO by scripts/build_ml_mechanics.py — DO NOT EDIT MANUALLY
// Density6 LLC · Point Zero One · Confidential
// MLMechanicsRouter — dispatch table for all 150 ML companion mechanics

export type MLBudget   = 'real_time' | 'batch' | 'hybrid';
export type MLFamily   = 'integrity' | 'market' | 'social' | 'contract' | 'economy' | 'progression' | 'balance' | 'forensics' | 'co_op';
export type MLCategory = 'classifier' | 'predictor' | 'recommender' | 'rl_policy' | 'anomaly_detector' | 'generator' | 'controller' | 'embedding_model';
export type MLIntelSignal = 'alpha' | 'risk' | 'volatility' | 'antiCheat' | 'personalization' | 'rewardFit' | 'recommendationPower' | 'churnRisk' | 'momentum';

export interface MLDispatch {
  ml_id:             string;    // 'M01A'
  core_id:           string;    // 'M01'
  mechanic_id:       string;    // 'M01a' (lowercase, mlLoader key)
  model_name:        string;
  intelligence_signal: MLIntelSignal;
  model_category:    MLCategory;
  family:            MLFamily;
  tiers:             readonly string[];
  placement:         readonly string[];
  budget:            MLBudget;
  can_lock_off:      boolean;
  priority:          1 | 2 | 3;
  training_phase:    1 | 2 | 3;
  exec_hook:         string;
}

/** Full dispatch table — one entry per ML mechanic. */
export const ML_DISPATCH_TABLE: readonly MLDispatch[] = [
  { ml_id: 'M01A', core_id: 'M01', mechanic_id: 'm01aa' if not r['ml_id'].lower().endswith('a') else 'm01a', model_name: "Seed Integrity + Deterministic Replay Forensics", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m01_resolve' },
  { ml_id: 'M02A', core_id: 'M02', mechanic_id: 'm02aa' if not r['ml_id'].lower().endswith('a') else 'm02a', model_name: "Pressure-Aware Difficulty Shaping (Timer Stress Model)", intelligence_signal: 'personalization', model_category: 'controller', family: 'balance', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m02_resolve' },
  { ml_id: 'M03A', core_id: 'M03', mechanic_id: 'm03aa' if not r['ml_id'].lower().endswith('a') else 'm03a', model_name: "Solvency Collapse Predictor (Run Death Forecaster)", intelligence_signal: 'risk', model_category: 'predictor', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m03_resolve' },
  { ml_id: 'M04A', core_id: 'M04', mechanic_id: 'm04aa' if not r['ml_id'].lower().endswith('a') else 'm04a', model_name: "Deck Reactor RL Policy (Dynamic Draw Mixing)", intelligence_signal: 'recommendationPower', model_category: 'rl_policy', family: 'balance', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m04_resolve' },
  { ml_id: 'M05A', core_id: 'M05', mechanic_id: 'm05aa' if not r['ml_id'].lower().endswith('a') else 'm05a', model_name: "Macro Regime Classifier + Cash Decay Tuner", intelligence_signal: 'volatility', model_category: 'classifier', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m05_resolve' },
  { ml_id: 'M06A', core_id: 'M06', mechanic_id: 'm06aa' if not r['ml_id'].lower().endswith('a') else 'm06a', model_name: "Cashflow Forecast + Portfolio Health Embeddings", intelligence_signal: 'alpha', model_category: 'embedding_model', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m06_resolve' },
  { ml_id: 'M07A', core_id: 'M07', mechanic_id: 'm07aa' if not r['ml_id'].lower().endswith('a') else 'm07a', model_name: "Affordability + Default Risk Scorer (Purchase Resolver)", intelligence_signal: 'risk', model_category: 'predictor', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m07_resolve' },
  { ml_id: 'M08A', core_id: 'M08', mechanic_id: 'm08aa' if not r['ml_id'].lower().endswith('a') else 'm08a', model_name: "Shield Timing Policy (Clutch Intervention Model)", intelligence_signal: 'momentum', model_category: 'rl_policy', family: 'balance', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m08_resolve' },
  { ml_id: 'M09A', core_id: 'M09', mechanic_id: 'm09aa' if not r['ml_id'].lower().endswith('a') else 'm09a', model_name: "Opportunity Value Model + Regret Stamp Generator", intelligence_signal: 'alpha', model_category: 'predictor', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m09_resolve' },
  { ml_id: 'M10A', core_id: 'M10', mechanic_id: 'm10aa' if not r['ml_id'].lower().endswith('a') else 'm10a', model_name: "Exit Timing Model (Pulse Sell / Flip Optimizer)", intelligence_signal: 'alpha', model_category: 'predictor', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m10_resolve' },
  { ml_id: 'M11A', core_id: 'M11', mechanic_id: 'm11aa' if not r['ml_id'].lower().endswith('a') else 'm11a', model_name: "Hesitation / Inertia Detector (Micro-Behavior DL)", intelligence_signal: 'personalization', model_category: 'classifier', family: 'balance', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m11_resolve' },
  { ml_id: 'M12A', core_id: 'M12', mechanic_id: 'm12aa' if not r['ml_id'].lower().endswith('a') else 'm12a', model_name: "FUBAR Cascade Risk Model (Crisis Graph)", intelligence_signal: 'risk', model_category: 'predictor', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m12_resolve' },
  { ml_id: 'M13A', core_id: 'M13', mechanic_id: 'm13aa' if not r['ml_id'].lower().endswith('a') else 'm13a', model_name: "Friction Module Tuner (Constrained Bandits)", intelligence_signal: 'personalization', model_category: 'controller', family: 'balance', tiers: ['baseline', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m13_resolve' },
  { ml_id: 'M14A', core_id: 'M14', mechanic_id: 'm14aa' if not r['ml_id'].lower().endswith('a') else 'm14a', model_name: "Disadvantage Draft Personalizer (Style-Aware)", intelligence_signal: 'personalization', model_category: 'recommender', family: 'progression', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m14_resolve' },
  { ml_id: 'M15A', core_id: 'M15', mechanic_id: 'm15aa' if not r['ml_id'].lower().endswith('a') else 'm15a', model_name: "Social Token Recommender (Co-Author Engine)", intelligence_signal: 'rewardFit', model_category: 'recommender', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m15_resolve' },
  { ml_id: 'M16A', core_id: 'M16', mechanic_id: 'm16aa' if not r['ml_id'].lower().endswith('a') else 'm16a', model_name: "Consensus vs Contrarian Predictor (Hot Seat Vote)", intelligence_signal: 'recommendationPower', model_category: 'predictor', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m16_resolve' },
  { ml_id: 'M17A', core_id: 'M17', mechanic_id: 'm17aa' if not r['ml_id'].lower().endswith('a') else 'm17a', model_name: "Bailout Trigger Classifier (Clutch Assist Gate)", intelligence_signal: 'momentum', model_category: 'classifier', family: 'balance', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m17_resolve' },
  { ml_id: 'M18A', core_id: 'M18', mechanic_id: 'm18aa' if not r['ml_id'].lower().endswith('a') else 'm18a', model_name: "Griefing Detection + Adversarial Budgeting", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m18_resolve' },
  { ml_id: 'M19A', core_id: 'M19', mechanic_id: 'm19aa' if not r['ml_id'].lower().endswith('a') else 'm19a', model_name: "Season Meta Balancer (Offline Simulation + RL)", intelligence_signal: 'volatility', model_category: 'rl_policy', family: 'balance', tiers: ['baseline', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m19_resolve' },
  { ml_id: 'M20A', core_id: 'M20', mechanic_id: 'm20aa' if not r['ml_id'].lower().endswith('a') else 'm20a', model_name: "Macro Shock Generator (Distribution + Constraints)", intelligence_signal: 'volatility', model_category: 'generator', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m20_resolve' },
  { ml_id: 'M21A', core_id: 'M21', mechanic_id: 'm21aa' if not r['ml_id'].lower().endswith('a') else 'm21a', model_name: "Meta-Progression Personalization (Unlock Routing)", intelligence_signal: 'churnRisk', model_category: 'recommender', family: 'progression', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m21_resolve' },
  { ml_id: 'M22A', core_id: 'M22', mechanic_id: 'm22aa' if not r['ml_id'].lower().endswith('a') else 'm22a', model_name: "Moment Forge Classifier (3-Moment Guarantee Controller)", intelligence_signal: 'rewardFit', model_category: 'classifier', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m22_resolve' },
  { ml_id: 'M23A', core_id: 'M23', mechanic_id: 'm23aa' if not r['ml_id'].lower().endswith('a') else 'm23a', model_name: "Highlight Detection (Auto-Clip DL)", intelligence_signal: 'rewardFit', model_category: 'classifier', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m23_resolve' },
  { ml_id: 'M24A', core_id: 'M24', mechanic_id: 'm24aa' if not r['ml_id'].lower().endswith('a') else 'm24a', model_name: "Challenge Matchmaking (Seed + Ghost Similarity)", intelligence_signal: 'personalization', model_category: 'embedding_model', family: 'progression', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m24_resolve' },
  { ml_id: 'M25A', core_id: 'M25', mechanic_id: 'm25aa' if not r['ml_id'].lower().endswith('a') else 'm25a', model_name: "Improvement Overlay Models (Skill Signals + Causal Experimen", intelligence_signal: 'personalization', model_category: 'predictor', family: 'progression', tiers: ['baseline', 'sequence_dl', 'causal', 'policy_rl'], placement: ['client', 'server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m25_resolve' },
  { ml_id: 'M26A', core_id: 'M26', mechanic_id: 'm26aa' if not r['ml_id'].lower().endswith('a') else 'm26a', model_name: "Co-op Contract Fairness + Partner-Risk Scorer", intelligence_signal: 'risk', model_category: 'predictor', family: 'contract', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m26_resolve' },
  { ml_id: 'M27A', core_id: 'M27', mechanic_id: 'm27aa' if not r['ml_id'].lower().endswith('a') else 'm27a', model_name: "Clause Outcome Forecaster (Triggers, Escapes, Penalties)", intelligence_signal: 'risk', model_category: 'predictor', family: 'contract', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m27_resolve' },
  { ml_id: 'M28A', core_id: 'M28', mechanic_id: 'm28aa' if not r['ml_id'].lower().endswith('a') else 'm28a', model_name: "Handshake Negotiation Coach (Timer-Window Optimizer)", intelligence_signal: 'recommendationPower', model_category: 'recommender', family: 'contract', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m28_resolve' },
  { ml_id: 'M29A', core_id: 'M29', mechanic_id: 'm29aa' if not r['ml_id'].lower().endswith('a') else 'm29a', model_name: "Mutual Risk Pool Actuary (Payout Likelihood + Anti-Abuse)", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'co_op', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m29_resolve' },
  { ml_id: 'M30A', core_id: 'M30', mechanic_id: 'm30aa' if not r['ml_id'].lower().endswith('a') else 'm30a', model_name: "Default Cascade Predictor (Takeover vs Unwind Routing)", intelligence_signal: 'risk', model_category: 'predictor', family: 'co_op', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m30_resolve' },
  { ml_id: 'M31A', core_id: 'M31', mechanic_id: 'm31aa' if not r['ml_id'].lower().endswith('a') else 'm31a', model_name: "Synergy Discovery Engine (Combo Mining + Balance Watchdog)", intelligence_signal: 'volatility', model_category: 'anomaly_detector', family: 'balance', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m31_resolve' },
  { ml_id: 'M32A', core_id: 'M32', mechanic_id: 'm32aa' if not r['ml_id'].lower().endswith('a') else 'm32a', model_name: "Liquidity Ladder Planner (Rung Completion + Fragility Scorer", intelligence_signal: 'risk', model_category: 'predictor', family: 'market', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m32_resolve' },
  { ml_id: 'M33A', core_id: 'M33', mechanic_id: 'm33aa' if not r['ml_id'].lower().endswith('a') else 'm33a', model_name: "Hedge Pair Validator (Correlation Drift + Shock Stress)", intelligence_signal: 'risk', model_category: 'predictor', family: 'market', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m33_resolve' },
  { ml_id: 'M34A', core_id: 'M34', mechanic_id: 'm34aa' if not r['ml_id'].lower().endswith('a') else 'm34a', model_name: "Mod Impact Estimator (Socket Choice + Counterfactual Regret)", intelligence_signal: 'alpha', model_category: 'recommender', family: 'market', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m34_resolve' },
  { ml_id: 'M35A', core_id: 'M35', mechanic_id: 'm35aa' if not r['ml_id'].lower().endswith('a') else 'm35a', model_name: "Portfolio Heat Controller (Overconcentration + Friction Tune", intelligence_signal: 'risk', model_category: 'controller', family: 'market', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m35_resolve' },
  { ml_id: 'M36A', core_id: 'M36', mechanic_id: 'm36aa' if not r['ml_id'].lower().endswith('a') else 'm36a', model_name: "Achievement Proof Verifier (Ledger-Backed Badge Integrity)", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m36_resolve' },
  { ml_id: 'M37A', core_id: 'M37', mechanic_id: 'm37aa' if not r['ml_id'].lower().endswith('a') else 'm37a', model_name: "Bounty Failure Forecaster (Streak Collapse Predictor)", intelligence_signal: 'churnRisk', model_category: 'predictor', family: 'economy', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'causal'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m37_resolve' },
  { ml_id: 'M38A', core_id: 'M38', mechanic_id: 'm38aa' if not r['ml_id'].lower().endswith('a') else 'm38a', model_name: "Quest Router (Moment Quest Personalization + Novelty)", intelligence_signal: 'recommendationPower', model_category: 'recommender', family: 'progression', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m38_resolve' },
  { ml_id: 'M39A', core_id: 'M39', mechanic_id: 'm39aa' if not r['ml_id'].lower().endswith('a') else 'm39a', model_name: "Trophy Economy Balancer (Inflation Control + Anti-Farm)", intelligence_signal: 'volatility', model_category: 'controller', family: 'economy', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m39_resolve' },
  { ml_id: 'M40A', core_id: 'M40', mechanic_id: 'm40aa' if not r['ml_id'].lower().endswith('a') else 'm40a', model_name: "Cosmetic Exchange Fraud Detector (Market Integrity)", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m40_resolve' },
  { ml_id: 'M41A', core_id: 'M41', mechanic_id: 'm41aa' if not r['ml_id'].lower().endswith('a') else 'm41a', model_name: "Onboarding Skill Estimator (90-Second Boot Run Classifier)", intelligence_signal: 'personalization', model_category: 'classifier', family: 'progression', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m41_resolve' },
  { ml_id: 'M42A', core_id: 'M42', mechanic_id: 'm42aa' if not r['ml_id'].lower().endswith('a') else 'm42a', model_name: "Prompt Minimalism Controller (When to Speak, When to Stay Si", intelligence_signal: 'personalization', model_category: 'controller', family: 'progression', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['client'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m42_resolve' },
  { ml_id: 'M43A', core_id: 'M43', mechanic_id: 'm43aa' if not r['ml_id'].lower().endswith('a') else 'm43a', model_name: "What-If Tutor (Counterfactual Policy Explainer)", intelligence_signal: 'personalization', model_category: 'predictor', family: 'progression', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'causal'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m43_resolve' },
  { ml_id: 'M44A', core_id: 'M44', mechanic_id: 'm44aa' if not r['ml_id'].lower().endswith('a') else 'm44a', model_name: "Starter Path Matchmaker (Archetype Routing + Anti-Boredom)", intelligence_signal: 'personalization', model_category: 'recommender', family: 'progression', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m44_resolve' },
  { ml_id: 'M45A', core_id: 'M45', mechanic_id: 'm45aa' if not r['ml_id'].lower().endswith('a') else 'm45a', model_name: "Training Wheels Scheduler (Grace-Period Optimization)", intelligence_signal: 'churnRisk', model_category: 'controller', family: 'progression', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m45_resolve' },
  { ml_id: 'M46A', core_id: 'M46', mechanic_id: 'm46aa' if not r['ml_id'].lower().endswith('a') else 'm46a', model_name: "Ledger Anomaly Detector (Event Stream Forensics)", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m46_resolve' },
  { ml_id: 'M47A', core_id: 'M47', mechanic_id: 'm47aa' if not r['ml_id'].lower().endswith('a') else 'm47a', model_name: "Signature & Freshness Monitor (Client Action Integrity)", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m47_resolve' },
  { ml_id: 'M48A', core_id: 'M48', mechanic_id: 'm48aa' if not r['ml_id'].lower().endswith('a') else 'm48a', model_name: "Replay Consistency Model (Deterministic Validator Assist)", intelligence_signal: 'antiCheat', model_category: 'classifier', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m48_resolve' },
  { ml_id: 'M49A', core_id: 'M49', mechanic_id: 'm49aa' if not r['ml_id'].lower().endswith('a') else 'm49a', model_name: "Exploit Response Policy (Auto-Containment Optimizer)", intelligence_signal: 'antiCheat', model_category: 'rl_policy', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m49_resolve' },
  { ml_id: 'M50A', core_id: 'M50', mechanic_id: 'm50aa' if not r['ml_id'].lower().endswith('a') else 'm50a', model_name: "Proof Card Verifier (Receipt Hash Trust Layer)", intelligence_signal: 'antiCheat', model_category: 'classifier', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m50_resolve' },
  { ml_id: 'M51A', core_id: 'M51', mechanic_id: 'm51aa' if not r['ml_id'].lower().endswith('a') else 'm51a', model_name: "Syndicate Coalition Scoring (Multi-Party Deal Stability)", intelligence_signal: 'risk', model_category: 'predictor', family: 'co_op', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m51_resolve' },
  { ml_id: 'M52A', core_id: 'M52', mechanic_id: 'm52aa' if not r['ml_id'].lower().endswith('a') else 'm52a', model_name: "Escrow Milestone Success Model (Gaming-Resistant Release Gat", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'contract', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m52_resolve' },
  { ml_id: 'M53A', core_id: 'M53', mechanic_id: 'm53aa' if not r['ml_id'].lower().endswith('a') else 'm53a', model_name: "Reliability & Collusion Monitor (Reputation Stake)", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m53_resolve' },
  { ml_id: 'M54A', core_id: 'M54', mechanic_id: 'm54aa' if not r['ml_id'].lower().endswith('a') else 'm54a', model_name: "Restructure Acceptance Forecaster (Distress Term Triage)", intelligence_signal: 'recommendationPower', model_category: 'predictor', family: 'contract', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m54_resolve' },
  { ml_id: 'M55A', core_id: 'M55', mechanic_id: 'm55aa' if not r['ml_id'].lower().endswith('a') else 'm55a', model_name: "Arbitration Triage + Verdict Summarizer (Replay Evidence)", intelligence_signal: 'antiCheat', model_category: 'classifier', family: 'forensics', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m55_resolve' },
  { ml_id: 'M56A', core_id: 'M56', mechanic_id: 'm56aa' if not r['ml_id'].lower().endswith('a') else 'm56a', model_name: "Doctrine Alignment Model (Playstyle Consistency + Hypocrisy ", intelligence_signal: 'personalization', model_category: 'classifier', family: 'forensics', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m56_resolve' },
  { ml_id: 'M57A', core_id: 'M57', mechanic_id: 'm57aa' if not r['ml_id'].lower().endswith('a') else 'm57a', model_name: "Rebalancing Pulse Action Planner (Seconds-to-Save Router)", intelligence_signal: 'momentum', model_category: 'rl_policy', family: 'market', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m57_resolve' },
  { ml_id: 'M58A', core_id: 'M58', mechanic_id: 'm58aa' if not r['ml_id'].lower().endswith('a') else 'm58a', model_name: "Stress Test Selector (Risk/Reward Balancer + Anti-Farm)", intelligence_signal: 'antiCheat', model_category: 'recommender', family: 'balance', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m58_resolve' },
  { ml_id: 'M59A', core_id: 'M59', mechanic_id: 'm59aa' if not r['ml_id'].lower().endswith('a') else 'm59a', model_name: "Complexity Heat Calibrator (Combo Degeneracy Detector)", intelligence_signal: 'volatility', model_category: 'anomaly_detector', family: 'balance', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m59_resolve' },
  { ml_id: 'M60A', core_id: 'M60', mechanic_id: 'm60aa' if not r['ml_id'].lower().endswith('a') else 'm60a', model_name: "Liability Netting Advisor (Cascade Minimization Under Caps)", intelligence_signal: 'risk', model_category: 'recommender', family: 'market', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m60_resolve' },
  { ml_id: 'M61A', core_id: 'M61', mechanic_id: 'm61aa' if not r['ml_id'].lower().endswith('a') else 'm61a', model_name: "Badge Tier Threshold Calibrator (Bronze\u2192Platinum Distributio", intelligence_signal: 'volatility', model_category: 'controller', family: 'economy', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m61_resolve' },
  { ml_id: 'M62A', core_id: 'M62', mechanic_id: 'm62aa' if not r['ml_id'].lower().endswith('a') else 'm62a', model_name: "Team Contribution Estimator (Anti-Tagalong Credit Attributio", intelligence_signal: 'antiCheat', model_category: 'predictor', family: 'co_op', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m62_resolve' },
  { ml_id: 'M63A', core_id: 'M63', mechanic_id: 'm63aa' if not r['ml_id'].lower().endswith('a') else 'm63a', model_name: "Sponsored Bounty Integrity Guard (Stake Escrow + Collusion D", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m63_resolve' },
  { ml_id: 'M64A', core_id: 'M64', mechanic_id: 'm64aa' if not r['ml_id'].lower().endswith('a') else 'm64a', model_name: "Leaderboard Trust & Re-Verify Scheduler (Proof-Weighted Rank", intelligence_signal: 'antiCheat', model_category: 'classifier', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m64_resolve' },
  { ml_id: 'M65A', core_id: 'M65', mechanic_id: 'm65aa' if not r['ml_id'].lower().endswith('a') else 'm65a', model_name: "Variety Index Abuse Detector (Anti-Grind Curve Hardener)", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m65_resolve' },
  { ml_id: 'M66A', core_id: 'M66', mechanic_id: 'm66aa' if not r['ml_id'].lower().endswith('a') else 'm66a', model_name: "Mentor Matchmaker + Quality Guard (Guided Co-op Onboarding)", intelligence_signal: 'personalization', model_category: 'recommender', family: 'co_op', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m66_resolve' },
  { ml_id: 'M67A', core_id: 'M67', mechanic_id: 'm67aa' if not r['ml_id'].lower().endswith('a') else 'm67a', model_name: "UI Unlock Gatekeeper (Progressive Disclosure + Smurf Detecti", intelligence_signal: 'personalization', model_category: 'classifier', family: 'progression', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m67_resolve' },
  { ml_id: 'M68A', core_id: 'M68', mechanic_id: 'm68aa' if not r['ml_id'].lower().endswith('a') else 'm68a', model_name: "Failure Rehab Scenario Generator (Death-Snapshot Curriculum)", intelligence_signal: 'personalization', model_category: 'generator', family: 'progression', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'causal'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m68_resolve' },
  { ml_id: 'M69A', core_id: 'M69', mechanic_id: 'm69aa' if not r['ml_id'].lower().endswith('a') else 'm69a', model_name: "Choice Drill Generator + Skill Rating (Micro-Sim Test Engine", intelligence_signal: 'personalization', model_category: 'generator', family: 'progression', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m69_resolve' },
  { ml_id: 'M70A', core_id: 'M70', mechanic_id: 'm70aa' if not r['ml_id'].lower().endswith('a') else 'm70a', model_name: "Co-op Bootcamp Orchestrator (Team Flow + Dropout Resilience)", intelligence_signal: 'churnRisk', model_category: 'controller', family: 'co_op', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m70_resolve' },
  { ml_id: 'M71A', core_id: 'M71', mechanic_id: 'm71aa' if not r['ml_id'].lower().endswith('a') else 'm71a', model_name: "Device Trust Fusion Model (Attestation + Behavior + Network)", intelligence_signal: 'antiCheat', model_category: 'embedding_model', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m71_resolve' },
  { ml_id: 'M72A', core_id: 'M72', mechanic_id: 'm72aa' if not r['ml_id'].lower().endswith('a') else 'm72a', model_name: "Action Budget Anomaly Detector (Anti-Bot Pace Control)", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m72_resolve' },
  { ml_id: 'M73A', core_id: 'M73', mechanic_id: 'm73aa' if not r['ml_id'].lower().endswith('a') else 'm73a', model_name: "Market Settlement Anomaly Model (2PC / Finality Dupe Detecti", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m73_resolve' },
  { ml_id: 'M74A', core_id: 'M74', mechanic_id: 'm74aa' if not r['ml_id'].lower().endswith('a') else 'm74a', model_name: "Forensic Bundle Summarizer + Redactor (Truth Packets)", intelligence_signal: 'antiCheat', model_category: 'generator', family: 'forensics', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m74_resolve' },
  { ml_id: 'M75A', core_id: 'M75', mechanic_id: 'm75aa' if not r['ml_id'].lower().endswith('a') else 'm75a', model_name: "Integrity Digest Generator (Privacy-Safe Transparency Audit)", intelligence_signal: 'antiCheat', model_category: 'generator', family: 'forensics', tiers: ['baseline', 'sequence_dl', 'graph_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m75_resolve' },
  { ml_id: 'M76A', core_id: 'M76', mechanic_id: 'm76aa' if not r['ml_id'].lower().endswith('a') else 'm76a', model_name: "Contract Voting Dynamics Model (Deadlock + Manipulation Dete", intelligence_signal: 'antiCheat', model_category: 'predictor', family: 'contract', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m76_resolve' },
  { ml_id: 'M77A', core_id: 'M77', mechanic_id: 'm77aa' if not r['ml_id'].lower().endswith('a') else 'm77a', model_name: "Delegated Operator Oversight (Scope Compliance + Abuse Predi", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m77_resolve' },
  { ml_id: 'M78A', core_id: 'M78', mechanic_id: 'm78aa' if not r['ml_id'].lower().endswith('a') else 'm78a', model_name: "Collateral Call Stress Forecaster (Top-Up Likelihood + Defau", intelligence_signal: 'risk', model_category: 'predictor', family: 'co_op', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m78_resolve' },
  { ml_id: 'M79A', core_id: 'M79', mechanic_id: 'm79aa' if not r['ml_id'].lower().endswith('a') else 'm79a', model_name: "Shared Objective Bond Success Model (Coordination + Sabotage", intelligence_signal: 'antiCheat', model_category: 'predictor', family: 'co_op', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m79_resolve' },
  { ml_id: 'M80A', core_id: 'M80', mechanic_id: 'm80aa' if not r['ml_id'].lower().endswith('a') else 'm80a', model_name: "Contract Receipt Card Generator (Proof Compression + Readabi", intelligence_signal: 'rewardFit', model_category: 'generator', family: 'contract', tiers: ['baseline', 'sequence_dl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m80_resolve' },
  { ml_id: 'M81A', core_id: 'M81', mechanic_id: 'm81aa' if not r['ml_id'].lower().endswith('a') else 'm81a', model_name: "Synergy Tree Branch Recommender (Identity Routing + Non-Dege", intelligence_signal: 'recommendationPower', model_category: 'recommender', family: 'balance', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m81_resolve' },
  { ml_id: 'M82A', core_id: 'M82', mechanic_id: 'm82aa' if not r['ml_id'].lower().endswith('a') else 'm82a', model_name: "Timing Chain Recognizer (Sequence DL + Window Coach)", intelligence_signal: 'momentum', model_category: 'classifier', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m82_resolve' },
  { ml_id: 'M83A', core_id: 'M83', mechanic_id: 'm83aa' if not r['ml_id'].lower().endswith('a') else 'm83a', model_name: "Risk Parity Dial Optimizer (Constraint-Aware Exposure Rebala", intelligence_signal: 'risk', model_category: 'controller', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m83_resolve' },
  { ml_id: 'M84A', core_id: 'M84', mechanic_id: 'm84aa' if not r['ml_id'].lower().endswith('a') else 'm84a', model_name: "Catalyst Pairing Compatibility Model (Bridge Safety + Degene", intelligence_signal: 'volatility', model_category: 'predictor', family: 'balance', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m84_resolve' },
  { ml_id: 'M85A', core_id: 'M85', mechanic_id: 'm85aa' if not r['ml_id'].lower().endswith('a') else 'm85a', model_name: "Mutation Draft Planner (Rewrite Selection + Collapse Risk Sc", intelligence_signal: 'alpha', model_category: 'rl_policy', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m85_resolve' },
  { ml_id: 'M86A', core_id: 'M86', mechanic_id: 'm86aa' if not r['ml_id'].lower().endswith('a') else 'm86a', model_name: "Micro-Proof Moment Detector (Fine-Grain Highlight Miner)", intelligence_signal: 'rewardFit', model_category: 'classifier', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m86_resolve' },
  { ml_id: 'M87A', core_id: 'M87', mechanic_id: 'm87aa' if not r['ml_id'].lower().endswith('a') else 'm87a', model_name: "Season Relic Mint Governor (Scarcity + Anti-Farm Control)", intelligence_signal: 'volatility', model_category: 'controller', family: 'economy', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m87_resolve' },
  { ml_id: 'M88A', core_id: 'M88', mechanic_id: 'm88aa' if not r['ml_id'].lower().endswith('a') else 'm88a', model_name: "Team Title Attribution Model (Contribution + Eligibility Ver", intelligence_signal: 'antiCheat', model_category: 'predictor', family: 'co_op', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m88_resolve' },
  { ml_id: 'M89A', core_id: 'M89', mechanic_id: 'm89aa' if not r['ml_id'].lower().endswith('a') else 'm89a', model_name: "Trust Multiplier Fairness Auditor (Integrity Incentives)", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m89_resolve' },
  { ml_id: 'M90A', core_id: 'M90', mechanic_id: 'm90aa' if not r['ml_id'].lower().endswith('a') else 'm90a', model_name: "Salvage & Reroll Economy Stabilizer (Loop Detection + Sink A", intelligence_signal: 'volatility', model_category: 'anomaly_detector', family: 'economy', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m90_resolve' },
  { ml_id: 'M91A', core_id: 'M91', mechanic_id: 'm91aa' if not r['ml_id'].lower().endswith('a') else 'm91a', model_name: "First-Table Safety Model (Social Onboarding Abuse Preventer)", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m91_resolve' },
  { ml_id: 'M92A', core_id: 'M92', mechanic_id: 'm92aa' if not r['ml_id'].lower().endswith('a') else 'm92a', model_name: "Ghost Mentor Curation Engine (Best Replays + Overlay Quality", intelligence_signal: 'personalization', model_category: 'recommender', family: 'progression', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m92_resolve' },
  { ml_id: 'M93A', core_id: 'M93', mechanic_id: 'm93aa' if not r['ml_id'].lower().endswith('a') else 'm93a', model_name: "Loadout Lab Constraint Explainer (Preview Accuracy + CORD Es", intelligence_signal: 'recommendationPower', model_category: 'predictor', family: 'progression', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m93_resolve' },
  { ml_id: 'M94A', core_id: 'M94', mechanic_id: 'm94aa' if not r['ml_id'].lower().endswith('a') else 'm94a', model_name: "Glossary Ping Relevance Model (Speak-Only-When-Needed)", intelligence_signal: 'personalization', model_category: 'classifier', family: 'progression', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m94_resolve' },
  { ml_id: 'M95A', core_id: 'M95', mechanic_id: 'm95aa' if not r['ml_id'].lower().endswith('a') else 'm95a', model_name: "Wipe Clinic Causal Explainer (Minimal Counterfactual Generat", intelligence_signal: 'personalization', model_category: 'predictor', family: 'forensics', tiers: ['baseline', 'sequence_dl', 'causal'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m95_resolve' },
  { ml_id: 'M96A', core_id: 'M96', mechanic_id: 'm96aa' if not r['ml_id'].lower().endswith('a') else 'm96a', model_name: "Time Drift & Lag Exploit Classifier (Server-Time Authority G", intelligence_signal: 'antiCheat', model_category: 'classifier', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m96_resolve' },
  { ml_id: 'M97A', core_id: 'M97', mechanic_id: 'm97aa' if not r['ml_id'].lower().endswith('a') else 'm97a', model_name: "Seed Commit/Reveal Verifier (RNG Integrity + Bias Monitor)", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m97_resolve' },
  { ml_id: 'M98A', core_id: 'M98', mechanic_id: 'm98aa' if not r['ml_id'].lower().endswith('a') else 'm98a', model_name: "Quarantine Compute Scheduler (Fast-Path Clean Runs, Deep-Pat", intelligence_signal: 'antiCheat', model_category: 'controller', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m98_resolve' },
  { ml_id: 'M99A', core_id: 'M99', mechanic_id: 'm99aa' if not r['ml_id'].lower().endswith('a') else 'm99a', model_name: "Integrity Challenge Placement Optimizer (Non-Disruptive + Hi", intelligence_signal: 'antiCheat', model_category: 'controller', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m99_resolve' },
  { ml_id: 'M100A', core_id: 'M100', mechanic_id: 'm100aa' if not r['ml_id'].lower().endswith('a') else 'm100a', model_name: "Appeal Triage & Evidence Chain Checker (Verifiable Enforceme", intelligence_signal: 'antiCheat', model_category: 'classifier', family: 'forensics', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m100_resolve' },
  { ml_id: 'M101A', core_id: 'M101', mechanic_id: 'm101aa' if not r['ml_id'].lower().endswith('a') else 'm101a', model_name: "Mutator Draft Recommender + Balance Forecaster", intelligence_signal: 'recommendationPower', model_category: 'recommender', family: 'balance', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m101_resolve' },
  { ml_id: 'M102A', core_id: 'M102', mechanic_id: 'm102aa' if not r['ml_id'].lower().endswith('a') else 'm102a', model_name: "Forked Timeline Ghost Outcome Generator", intelligence_signal: 'alpha', model_category: 'generator', family: 'forensics', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m102_resolve' },
  { ml_id: 'M103A', core_id: 'M103', mechanic_id: 'm103aa' if not r['ml_id'].lower().endswith('a') else 'm103a', model_name: "Emergency Liquidity Panic Button Coach", intelligence_signal: 'momentum', model_category: 'recommender', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m103_resolve' },
  { ml_id: 'M104A', core_id: 'M104', mechanic_id: 'm104aa' if not r['ml_id'].lower().endswith('a') else 'm104a', model_name: "Deal Scarcity Anticipation Model", intelligence_signal: 'alpha', model_category: 'predictor', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m104_resolve' },
  { ml_id: 'M105A', core_id: 'M105', mechanic_id: 'm105aa' if not r['ml_id'].lower().endswith('a') else 'm105a', model_name: "Last Look Window Misclick Guard + Regret Amplifier", intelligence_signal: 'personalization', model_category: 'classifier', family: 'balance', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m105_resolve' },
  { ml_id: 'M106A', core_id: 'M106', mechanic_id: 'm106aa' if not r['ml_id'].lower().endswith('a') else 'm106a', model_name: "Asset Condition Failure Predictor + Maintenance Planner", intelligence_signal: 'risk', model_category: 'predictor', family: 'market', tiers: ['baseline', 'sequence_dl', 'causal'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m106_resolve' },
  { ml_id: 'M107A', core_id: 'M107', mechanic_id: 'm107aa' if not r['ml_id'].lower().endswith('a') else 'm107a', model_name: "Refi Eligibility Estimator + Term Optimizer", intelligence_signal: 'alpha', model_category: 'predictor', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m107_resolve' },
  { ml_id: 'M108A', core_id: 'M108', mechanic_id: 'm108aa' if not r['ml_id'].lower().endswith('a') else 'm108a', model_name: "Partial Fill Probability + Timing Tutor", intelligence_signal: 'alpha', model_category: 'predictor', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m108_resolve' },
  { ml_id: 'M109A', core_id: 'M109', mechanic_id: 'm109aa' if not r['ml_id'].lower().endswith('a') else 'm109a', model_name: "Macro News Burst Impact Synth + Regime Detector", intelligence_signal: 'volatility', model_category: 'predictor', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m109_resolve' },
  { ml_id: 'M110A', core_id: 'M110', mechanic_id: 'm110aa' if not r['ml_id'].lower().endswith('a') else 'm110a', model_name: "UI Stall Predictor + Auto-Default Guard", intelligence_signal: 'antiCheat', model_category: 'predictor', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m110_resolve' },
  { ml_id: 'M111A', core_id: 'M111', mechanic_id: 'm111aa' if not r['ml_id'].lower().endswith('a') else 'm111a', model_name: "Portfolio Macro Synth + Safety Verifier", intelligence_signal: 'risk', model_category: 'controller', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m111_resolve' },
  { ml_id: 'M112A', core_id: 'M112', mechanic_id: 'm112aa' if not r['ml_id'].lower().endswith('a') else 'm112a', model_name: "Optimal Split Estimator (Precision Sell Coach)", intelligence_signal: 'alpha', model_category: 'recommender', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m112_resolve' },
  { ml_id: 'M113A', core_id: 'M113', mechanic_id: 'm113aa' if not r['ml_id'].lower().endswith('a') else 'm113a', model_name: "Order Priority Stack Sacrifice Planner (Graph-Aware)", intelligence_signal: 'momentum', model_category: 'rl_policy', family: 'market', tiers: ['baseline', 'sequence_dl', 'graph_dl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 1, training_phase: 1, exec_hook: 'after_m113_resolve' },
  { ml_id: 'M114A', core_id: 'M114', mechanic_id: 'm114aa' if not r['ml_id'].lower().endswith('a') else 'm114a', model_name: "Timing Tax Reaction-Time Coach + Window Predictor", intelligence_signal: 'momentum', model_category: 'classifier', family: 'balance', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m114_resolve' },
  { ml_id: 'M115A', core_id: 'M115', mechanic_id: 'm115aa' if not r['ml_id'].lower().endswith('a') else 'm115a', model_name: "Heat-Swap Exposure Rebalancer Suggestion", intelligence_signal: 'risk', model_category: 'recommender', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m115_resolve' },
  { ml_id: 'M116A', core_id: 'M116', mechanic_id: 'm116aa' if not r['ml_id'].lower().endswith('a') else 'm116a', model_name: "Table Role Fit Matcher + Conflict Predictor", intelligence_signal: 'personalization', model_category: 'recommender', family: 'co_op', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m116_resolve' },
  { ml_id: 'M117A', core_id: 'M117', mechanic_id: 'm117aa' if not r['ml_id'].lower().endswith('a') else 'm117a', model_name: "Table Feed Moment Ranker + Auto-Highlight Builder", intelligence_signal: 'rewardFit', model_category: 'recommender', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m117_resolve' },
  { ml_id: 'M118A', core_id: 'M118', mechanic_id: 'm118aa' if not r['ml_id'].lower().endswith('a') else 'm118a', model_name: "Clip Remix Chain Suggestor + Safety Filter", intelligence_signal: 'rewardFit', model_category: 'classifier', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m118_resolve' },
  { ml_id: 'M119A', core_id: 'M119', mechanic_id: 'm119aa' if not r['ml_id'].lower().endswith('a') else 'm119a', model_name: "Rivalry Ledger Nemesis Arc Detector", intelligence_signal: 'rewardFit', model_category: 'classifier', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m119_resolve' },
  { ml_id: 'M120A', core_id: 'M120', mechanic_id: 'm120aa' if not r['ml_id'].lower().endswith('a') else 'm120a', model_name: "Consent Gate Chaos Mode Recommender", intelligence_signal: 'rewardFit', model_category: 'recommender', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m120_resolve' },
  { ml_id: 'M121A', core_id: 'M121', mechanic_id: 'm121aa' if not r['ml_id'].lower().endswith('a') else 'm121a', model_name: "Daily Gauntlet Leaderboard Integrity Monitor", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m121_resolve' },
  { ml_id: 'M122A', core_id: 'M122', mechanic_id: 'm122aa' if not r['ml_id'].lower().endswith('a') else 'm122a', model_name: "Weekly Draft League Advisor + Draft Order Fairness", intelligence_signal: 'recommendationPower', model_category: 'recommender', family: 'balance', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m122_resolve' },
  { ml_id: 'M123A', core_id: 'M123', mechanic_id: 'm123aa' if not r['ml_id'].lower().endswith('a') else 'm123a', model_name: "King-of-the-Hill Streak Story Arc Narrator", intelligence_signal: 'rewardFit', model_category: 'generator', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m123_resolve' },
  { ml_id: 'M124A', core_id: 'M124', mechanic_id: 'm124aa' if not r['ml_id'].lower().endswith('a') else 'm124a', model_name: "Speedrun Micro-Coach + Split Timer Optimizer", intelligence_signal: 'personalization', model_category: 'controller', family: 'balance', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m124_resolve' },
  { ml_id: 'M125A', core_id: 'M125', mechanic_id: 'm125aa' if not r['ml_id'].lower().endswith('a') else 'm125a', model_name: "No-Ghost Hardcore Integrity Verifier", intelligence_signal: 'antiCheat', model_category: 'classifier', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m125_resolve' },
  { ml_id: 'M126A', core_id: 'M126', mechanic_id: 'm126aa' if not r['ml_id'].lower().endswith('a') else 'm126a', model_name: "Cosmetic Loadout Style Recommender + Auto-Set Builder", intelligence_signal: 'recommendationPower', model_category: 'recommender', family: 'progression', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m126_resolve' },
  { ml_id: 'M127A', core_id: 'M127', mechanic_id: 'm127aa' if not r['ml_id'].lower().endswith('a') else 'm127a', model_name: "Proof-Bound Crafting Recipe Discoverer + Legibility Scorer", intelligence_signal: 'recommendationPower', model_category: 'recommender', family: 'economy', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m127_resolve' },
  { ml_id: 'M128A', core_id: 'M128', mechanic_id: 'm128aa' if not r['ml_id'].lower().endswith('a') else 'm128a', model_name: "Season Sink Health Monitor + Burn Rate Optimizer", intelligence_signal: 'volatility', model_category: 'controller', family: 'economy', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m128_resolve' },
  { ml_id: 'M129A', core_id: 'M129', mechanic_id: 'm129aa' if not r['ml_id'].lower().endswith('a') else 'm129a', model_name: "Creator Pack Caption Generator + Moment Stinger Selector", intelligence_signal: 'rewardFit', model_category: 'generator', family: 'social', tiers: ['baseline', 'sequence_dl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m129_resolve' },
  { ml_id: 'M130A', core_id: 'M130', mechanic_id: 'm130aa' if not r['ml_id'].lower().endswith('a') else 'm130a', model_name: "Table Vault Contribution Planner + Fairness Auditor", intelligence_signal: 'antiCheat', model_category: 'predictor', family: 'co_op', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m130_resolve' },
  { ml_id: 'M131A', core_id: 'M131', mechanic_id: 'm131aa' if not r['ml_id'].lower().endswith('a') else 'm131a', model_name: "Faction Sponsor Match + Power Guard", intelligence_signal: 'personalization', model_category: 'recommender', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m131_resolve' },
  { ml_id: 'M132A', core_id: 'M132', mechanic_id: 'm132aa' if not r['ml_id'].lower().endswith('a') else 'm132a', model_name: "Case Files Forensic Summarizer + Root-Cause Ranker", intelligence_signal: 'personalization', model_category: 'predictor', family: 'forensics', tiers: ['baseline', 'causal', 'retrieval'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m132_resolve' },
  { ml_id: 'M133A', core_id: 'M133', mechanic_id: 'm133aa' if not r['ml_id'].lower().endswith('a') else 'm133a', model_name: "Seasonal Story Beat Planner + Narrative Coherence Guard", intelligence_signal: 'rewardFit', model_category: 'generator', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m133_resolve' },
  { ml_id: 'M134A', core_id: 'M134', mechanic_id: 'm134aa' if not r['ml_id'].lower().endswith('a') else 'm134a', model_name: "NPC Counterparty Behavioral Emulator (Deterministic Persona ", intelligence_signal: 'personalization', model_category: 'controller', family: 'market', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m134_resolve' },
  { ml_id: 'M135A', core_id: 'M135', mechanic_id: 'm135aa' if not r['ml_id'].lower().endswith('a') else 'm135a', model_name: "Reputation Label Model + Drift Detector", intelligence_signal: 'personalization', model_category: 'classifier', family: 'forensics', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m135_resolve' },
  { ml_id: 'M136A', core_id: 'M136', mechanic_id: 'm136aa' if not r['ml_id'].lower().endswith('a') else 'm136a', model_name: "Ruleset Signature Verifier + Change Impact Estimator", intelligence_signal: 'antiCheat', model_category: 'classifier', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m136_resolve' },
  { ml_id: 'M137A', core_id: 'M137', mechanic_id: 'm137aa' if not r['ml_id'].lower().endswith('a') else 'm137a', model_name: "Mid-Run Hotfix Triage + Quarantine Router", intelligence_signal: 'antiCheat', model_category: 'controller', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m137_resolve' },
  { ml_id: 'M138A', core_id: 'M138', mechanic_id: 'm138aa' if not r['ml_id'].lower().endswith('a') else 'm138a', model_name: "Server Load Predictor + Graceful Degradation Planner", intelligence_signal: 'antiCheat', model_category: 'predictor', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m138_resolve' },
  { ml_id: 'M139A', core_id: 'M139', mechanic_id: 'm139aa' if not r['ml_id'].lower().endswith('a') else 'm139a', model_name: "Offline Queue On-Device Verifier + Sync Priority Ranker", intelligence_signal: 'antiCheat', model_category: 'classifier', family: 'integrity', tiers: ['baseline', 'sequence_dl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m139_resolve' },
  { ml_id: 'M140A', core_id: 'M140', mechanic_id: 'm140aa' if not r['ml_id'].lower().endswith('a') else 'm140a', model_name: "Player Evidence Export Redaction Assistant + Packet Summariz", intelligence_signal: 'antiCheat', model_category: 'generator', family: 'forensics', tiers: ['baseline', 'sequence_dl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m140_resolve' },
  { ml_id: 'M141A', core_id: 'M141', mechanic_id: 'm141aa' if not r['ml_id'].lower().endswith('a') else 'm141a', model_name: "Async Table Proxy Vote Predictor + Fairness Guard", intelligence_signal: 'antiCheat', model_category: 'predictor', family: 'contract', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m141_resolve' },
  { ml_id: 'M142A', core_id: 'M142', mechanic_id: 'm142aa' if not r['ml_id'].lower().endswith('a') else 'm142a', model_name: "House Rules Lobby Configuration Advisor + Safety Validator", intelligence_signal: 'antiCheat', model_category: 'classifier', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m142_resolve' },
  { ml_id: 'M143A', core_id: 'M143', mechanic_id: 'm143aa' if not r['ml_id'].lower().endswith('a') else 'm143a', model_name: "Table Penalties Brigading Detector + Toxicity Classifier", intelligence_signal: 'antiCheat', model_category: 'anomaly_detector', family: 'integrity', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: false, priority: 1, training_phase: 1, exec_hook: 'after_m143_resolve' },
  { ml_id: 'M144A', core_id: 'M144', mechanic_id: 'm144aa' if not r['ml_id'].lower().endswith('a') else 'm144a', model_name: "Spectator Theater Delay Optimizer + Prediction Bet Calibrato", intelligence_signal: 'rewardFit', model_category: 'controller', family: 'social', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m144_resolve' },
  { ml_id: 'M145A', core_id: 'M145', mechanic_id: 'm145aa' if not r['ml_id'].lower().endswith('a') else 'm145a', model_name: "Tournament Bracket Seeding Fairness Model", intelligence_signal: 'antiCheat', model_category: 'predictor', family: 'balance', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m145_resolve' },
  { ml_id: 'M146A', core_id: 'M146', mechanic_id: 'm146aa' if not r['ml_id'].lower().endswith('a') else 'm146a', model_name: "Audit Event Doc Burden Estimator + Auto-Fill Assistant", intelligence_signal: 'personalization', model_category: 'generator', family: 'forensics', tiers: ['baseline', 'sequence_dl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 3, training_phase: 3, exec_hook: 'after_m146_resolve' },
  { ml_id: 'M147A', core_id: 'M147', mechanic_id: 'm147aa' if not r['ml_id'].lower().endswith('a') else 'm147a', model_name: "Litigation Risk Early Warning + Mitigation Planner", intelligence_signal: 'risk', model_category: 'predictor', family: 'contract', tiers: ['baseline', 'sequence_dl', 'causal'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m147_resolve' },
  { ml_id: 'M148A', core_id: 'M148', mechanic_id: 'm148aa' if not r['ml_id'].lower().endswith('a') else 'm148a', model_name: "Counterparty Freeze Forecast + Premium Estimator", intelligence_signal: 'risk', model_category: 'predictor', family: 'contract', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m148_resolve' },
  { ml_id: 'M149A', core_id: 'M149', mechanic_id: 'm149aa' if not r['ml_id'].lower().endswith('a') else 'm149a', model_name: "Regulatory Window Compliance Planner + Cost Minimizer", intelligence_signal: 'risk', model_category: 'predictor', family: 'contract', tiers: ['baseline', 'sequence_dl', 'policy_rl'], placement: ['client', 'server'], budget: 'real_time', can_lock_off: true, priority: 2, training_phase: 2, exec_hook: 'after_m149_resolve' },
  { ml_id: 'M150A', core_id: 'M150', mechanic_id: 'm150aa' if not r['ml_id'].lower().endswith('a') else 'm150a', model_name: "Finality Ceremony Verifier Assistant + Final Card Composer", intelligence_signal: 'rewardFit', model_category: 'generator', family: 'integrity', tiers: ['baseline', 'sequence_dl'], placement: ['server'], budget: 'batch', can_lock_off: true, priority: 2, training_phase: 3, exec_hook: 'after_m150_resolve' },
] as const;

// ── Query helpers ────────────────────────────────────────────────────────────
export function getMLDispatch(ml_id: string): MLDispatch | undefined {
  return ML_DISPATCH_TABLE.find(d => d.ml_id === ml_id.toUpperCase() || d.mechanic_id === ml_id.toLowerCase());
}
export function getMLForCore(core_id: string): readonly MLDispatch[] {
  return ML_DISPATCH_TABLE.filter(d => d.core_id === core_id);
}
export function getMLBySignal(signal: MLIntelSignal): readonly MLDispatch[] {
  return ML_DISPATCH_TABLE.filter(d => d.intelligence_signal === signal);
}
export function getMLByFamily(family: MLFamily): readonly MLDispatch[] {
  return ML_DISPATCH_TABLE.filter(d => d.family === family);
}
export function getMLByCategory(cat: MLCategory): readonly MLDispatch[] {
  return ML_DISPATCH_TABLE.filter(d => d.model_category === cat);
}
export function getRealTimeMLMechanics(): readonly MLDispatch[] {
  return ML_DISPATCH_TABLE.filter(d => d.budget === 'real_time');
}
export function getBatchMLMechanics(): readonly MLDispatch[] {
  return ML_DISPATCH_TABLE.filter(d => d.budget === 'batch');
}
export function getAlwaysOnMLMechanics(): readonly MLDispatch[] {
  return ML_DISPATCH_TABLE.filter(d => !d.can_lock_off);
}
export function getPhase1MLMechanics(): readonly MLDispatch[] {
  return ML_DISPATCH_TABLE.filter(d => d.training_phase === 1);
}
export function getMLByPriority(p: 1|2|3): readonly MLDispatch[] {
  return ML_DISPATCH_TABLE.filter(d => d.priority === p);
}
