/*
 * POINT ZERO ONE — BACKEND ENGINE CORE
 * /backend/src/game/engine/core/CardOverlayResolver.ts
 *
 * Doctrine:
 * - the same base card mutates by mode at draw time
 * - legality is backend-owned
 * - tags drive routing and scoring across modes
 * - timing classes are validated against runtime windows, not UI assumptions
 * - ML scoring is a first-class concern at the overlay resolution layer
 * - all tag weights, resource types, and divergence potentials are deterministic
 */

import type {
  CardDefinition,
  CardInstance,
  DeckType,
  DivergencePotential,
  EffectPayload,
  ModeCode,
  ModeOverlay,
  PressureTier,
  Targeting,
  TimingClass,
} from './GamePrimitives';
import {
  mergeEffectPayload,
  resolveModeOverlay,
  createCardInstance,
  normalizeModeOverlay,
  isModeCode,
  isTimingClass,
  isDeckType,
  MODE_CODES,
  PRESSURE_TIERS,
  TIMING_CLASSES,
  DECK_TYPES,
  SHIELD_LAYER_IDS,
  SHIELD_LAYER_LABEL_BY_ID,
  DEFAULT_MODE_OVERLAY,
  getShieldLayerLabel,
} from './GamePrimitives';
import type { RunStateSnapshot } from './RunStateSnapshot';
import { createDeterministicId, checksumSnapshot, checksumParts, stableStringify } from './Deterministic';

// ============================================================================
// MARK: Resource Type
// ============================================================================

export type ResourceType =
  | 'cash'
  | 'battle_budget'
  | 'shared_treasury'
  | 'free';

// ============================================================================
// MARK: Resolved Card View
// ============================================================================

export interface ResolvedCardView {
  definitionId: string;
  mode: ModeCode;
  legal: boolean;
  legalityReasons: string[];
  resourceType: ResourceType;
  cost: number;
  effect: EffectPayload;
  targeting: Targeting;
  timingClass: TimingClass[];
  timingLocks: TimingClass[];
  tags: string[];
  tagWeights: Record<string, number>;
  autoResolve: boolean;
  decisionTimerMs: number | null;
  decayTicksRemaining: number | null;
  divergencePotential: DivergencePotential;
  /** ML scoring context attached at resolution time. */
  mlScore: CardMLScore;
  /** DL tensor input extracted from resolution context. */
  dlInputVector: readonly number[];
  /** Play recommendation generated by the overlay resolver. */
  playRecommendation: PlayRecommendation;
}

// ============================================================================
// MARK: Validate Card Play
// ============================================================================

export interface ValidateCardPlayInput {
  snapshot: RunStateSnapshot;
  card: CardDefinition | CardInstance;
  requestedTimingClass?: TimingClass;
  availableTimingClasses?: readonly TimingClass[];
  actorId?: string;
}

export interface CardPlayValidationResult {
  legal: boolean;
  chosenTimingClass: TimingClass | null;
  reasons: string[];
  resolved: ResolvedCardView;
  /** Validation diagnostics for telemetry. */
  diagnostics: CardPlayDiagnostics;
}

export interface CardPlayDiagnostics {
  readonly timingWindowOpen: boolean;
  readonly resourceSufficient: boolean;
  readonly modeLegalityPassed: boolean;
  readonly deckLegalityPassed: boolean;
  readonly modeOverlayBlocked: boolean;
  readonly ghostMarkerRequired: boolean;
  readonly phaseBoundaryRequired: boolean;
  readonly counterWindowRequired: boolean;
  readonly aidWindowRequired: boolean;
  readonly validationDurationMs: number;
  readonly checksumAtValidation: string;
}

// ============================================================================
// MARK: ML Scoring Surfaces
// ============================================================================

/**
 * ML score attached to every resolved card view.
 * Drives recommendation engine, deck entropy analysis, and chat signals.
 */
export interface CardMLScore {
  /** Estimated play value (0.0–1.0) relative to current snapshot context. */
  readonly playValue: number;
  /** Expected economy impact normalized to current cash position. */
  readonly economyImpact: number;
  /** Expected shield impact normalized to current shield pct. */
  readonly shieldImpact: number;
  /** Expected pressure relief normalized to current tier. */
  readonly pressureRelief: number;
  /** Expected cascade chain trigger probability. */
  readonly cascadeTriggerProb: number;
  /** Tempo advantage gained vs. opponent (PvP-relevant). */
  readonly tempoAdvantage: number;
  /** Trust impact (coop-relevant). */
  readonly trustImpact: number;
  /** Divergence alignment score (ghost-relevant). */
  readonly divergenceAlignment: number;
  /** Composite urgency score — how critical this card is right now. */
  readonly urgencyScore: number;
  /** Confidence in the score given current data richness. */
  readonly confidence: number;
  /** Tag affinity breakdown per-mode. */
  readonly tagAffinities: Readonly<Record<string, number>>;
  /** Model version that generated this score. */
  readonly modelVersion: string;
}

/**
 * DL input tensor shape descriptor for a card resolution.
 */
export interface CardDLTensorDescriptor {
  readonly inputShape: readonly number[];
  readonly inputData: readonly number[];
  readonly outputShape: readonly number[];
  readonly modelKey: string;
}

/**
 * Play recommendation generated by the overlay resolver.
 */
export interface PlayRecommendation {
  readonly recommended: boolean;
  readonly priority: 'MUST_PLAY' | 'HIGH' | 'MEDIUM' | 'LOW' | 'AVOID';
  readonly rationale: readonly string[];
  readonly alternativeTags: readonly string[];
  readonly bestTimingClass: TimingClass | null;
  readonly estimatedEffectiveness: number;
}

// ============================================================================
// MARK: Combo and Interaction Surfaces
// ============================================================================

/**
 * A combo score between two cards in the hand.
 */
export interface CardComboScore {
  readonly cardAId: string;
  readonly cardBId: string;
  readonly synergyScore: number;
  readonly sharedTags: readonly string[];
  readonly cascadeAmplification: number;
  readonly pressureDoubling: boolean;
  readonly timingAlignment: boolean;
  readonly description: string;
}

/**
 * Full hand analysis result.
 */
export interface HandAnalysis {
  readonly handSize: number;
  readonly playableCount: number;
  readonly totalExpectedValue: number;
  readonly topCard: ResolvedCardView | null;
  readonly combos: readonly CardComboScore[];
  readonly deckEntropyEstimate: number;
  readonly diversityScore: number;
  readonly timingCoverage: readonly TimingClass[];
  readonly tagDistribution: Readonly<Record<string, number>>;
  readonly mlVector: readonly number[];
}

// ============================================================================
// MARK: Constants
// ============================================================================

const ML_MODEL_VERSION = 'card-overlay-v1.2';

const MODE_TAG_WEIGHTS: Record<ModeCode, Record<string, number>> = {
  solo: {
    liquidity: 2.0,
    income: 2.2,
    resilience: 1.8,
    scale: 2.5,
    tempo: 1.0,
    sabotage: 0.0,
    counter: 0.0,
    heat: 0.6,
    trust: 0.0,
    aid: 0.0,
    precision: 1.2,
    divergence: 0.0,
    variance: 1.0,
    cascade: 1.8,
    momentum: 2.0,
    discipline: 1.6,
    opportunity: 2.1,
    network: 1.4,
    shield: 1.7,
    bleed: 0.5,
  },
  pvp: {
    liquidity: 0.8,
    income: 0.6,
    resilience: 1.0,
    scale: 0.5,
    tempo: 2.4,
    sabotage: 2.8,
    counter: 2.2,
    heat: 1.5,
    trust: 0.0,
    aid: 0.0,
    precision: 0.8,
    divergence: 0.0,
    variance: 1.4,
    cascade: 1.2,
    momentum: 1.5,
    discipline: 0.4,
    opportunity: 1.0,
    network: 0.6,
    shield: 1.3,
    bleed: 1.8,
  },
  coop: {
    liquidity: 1.5,
    income: 1.8,
    resilience: 2.0,
    scale: 1.3,
    tempo: 1.0,
    sabotage: 0.2,
    counter: 0.5,
    heat: 0.8,
    trust: 3.0,
    aid: 2.5,
    precision: 1.0,
    divergence: 0.0,
    variance: 0.4,
    cascade: 1.6,
    momentum: 1.2,
    discipline: 0.8,
    opportunity: 1.5,
    network: 2.0,
    shield: 1.8,
    bleed: 0.3,
  },
  ghost: {
    liquidity: 1.2,
    income: 1.0,
    resilience: 1.4,
    scale: 0.9,
    tempo: 1.8,
    sabotage: 0.0,
    counter: 0.0,
    heat: 1.0,
    trust: 0.0,
    aid: 0.0,
    precision: 2.6,
    divergence: 3.0,
    variance: 0.3,
    cascade: 1.5,
    momentum: 1.0,
    discipline: 1.2,
    opportunity: 1.3,
    network: 0.7,
    shield: 1.1,
    bleed: 0.4,
  },
};

const DECK_MODE_LEGALITY: Record<DeckType, ModeCode[]> = {
  OPPORTUNITY: ['solo', 'pvp', 'coop', 'ghost'],
  IPA: ['solo', 'pvp', 'coop', 'ghost'],
  FUBAR: ['solo', 'pvp', 'coop', 'ghost'],
  MISSED_OPPORTUNITY: ['solo', 'pvp', 'coop', 'ghost'],
  PRIVILEGED: ['solo', 'pvp', 'coop', 'ghost'],
  SO: ['solo', 'pvp', 'coop', 'ghost'],
  SABOTAGE: ['pvp'],
  COUNTER: ['pvp'],
  AID: ['coop'],
  RESCUE: ['coop'],
  DISCIPLINE: ['solo', 'ghost'],
  TRUST: ['coop'],
  BLUFF: ['pvp'],
  GHOST: ['ghost'],
};

const PRESSURE_COST_MULTIPLIER: Record<PressureTier, number> = {
  T0: 0.95,
  T1: 1.0,
  T2: 1.06,
  T3: 1.14,
  T4: 1.25,
};

/**
 * ML play value weights per pressure tier.
 */
const TIER_PLAY_VALUE_MODIFIER: Record<PressureTier, number> = {
  T0: 0.8,
  T1: 1.0,
  T2: 1.15,
  T3: 1.35,
  T4: 1.6,
};

/**
 * Estimated cascade trigger probability by deck type.
 */
const DECK_CASCADE_PROB: Record<DeckType, number> = {
  OPPORTUNITY: 0.25,
  IPA: 0.15,
  FUBAR: 0.4,
  MISSED_OPPORTUNITY: 0.05,
  PRIVILEGED: 0.3,
  SO: 0.2,
  SABOTAGE: 0.35,
  COUNTER: 0.2,
  AID: 0.15,
  RESCUE: 0.1,
  DISCIPLINE: 0.2,
  TRUST: 0.1,
  BLUFF: 0.3,
  GHOST: 0.45,
};

/**
 * Combo synergy score matrix (tag pair → score).
 */
const TAG_COMBO_MATRIX: Record<string, Record<string, number>> = {
  income: { momentum: 0.8, scale: 0.7, cascade: 0.6, liquidity: 0.5 },
  momentum: { income: 0.8, cascade: 0.9, opportunity: 0.7 },
  cascade: { momentum: 0.9, income: 0.6, shield: 0.7, precision: 0.6 },
  shield: { resilience: 0.8, cascade: 0.7, aid: 0.7, network: 0.5 },
  sabotage: { tempo: 0.9, counter: 0.8, heat: 0.7, bleed: 0.75 },
  counter: { sabotage: 0.8, tempo: 0.7, precision: 0.75 },
  precision: { divergence: 0.9, counter: 0.75, ghost: 0.85 },
  divergence: { precision: 0.9, ghost: 0.95 },
  trust: { aid: 0.9, network: 0.8, resilience: 0.6 },
  aid: { trust: 0.9, shield: 0.7, resilience: 0.65 },
  discipline: { resilience: 0.7, momentum: 0.5 },
  opportunity: { momentum: 0.7, income: 0.65, scale: 0.6 },
  network: { trust: 0.8, aid: 0.6, shield: 0.5 },
};

// ============================================================================
// MARK: Utility Helpers
// ============================================================================

function uniqueStrings(values: readonly string[]): string[] {
  return Array.from(new Set(values));
}

function uniqueTimingClasses(values: readonly TimingClass[]): TimingClass[] {
  return Array.from(new Set(values));
}

function roundCurrency(value: number): number {
  return Math.round(value * 100) / 100;
}

function roundThousandths(value: number): number {
  return Math.round(value * 1000) / 1000;
}

function clamp01(value: number): number {
  return Math.max(0, Math.min(1, value));
}

function copyEffect(effect: EffectPayload): EffectPayload {
  return {
    cashDelta: effect.cashDelta,
    debtDelta: effect.debtDelta,
    incomeDelta: effect.incomeDelta,
    expenseDelta: effect.expenseDelta,
    shieldDelta: effect.shieldDelta,
    heatDelta: effect.heatDelta,
    trustDelta: effect.trustDelta,
    treasuryDelta: effect.treasuryDelta,
    battleBudgetDelta: effect.battleBudgetDelta,
    holdChargeDelta: effect.holdChargeDelta,
    counterIntelDelta: effect.counterIntelDelta,
    timeDeltaMs: effect.timeDeltaMs,
    divergenceDelta: effect.divergenceDelta,
    cascadeTag: effect.cascadeTag ?? null,
    injectCards: effect.injectCards ? [...effect.injectCards] : undefined,
    exhaustCards: effect.exhaustCards ? [...effect.exhaustCards] : undefined,
    grantBadges: effect.grantBadges ? [...effect.grantBadges] : undefined,
    namedActionId: effect.namedActionId ?? null,
  };
}

function multiplyEffect(
  effect: EffectPayload,
  multiplier: number,
): EffectPayload {
  const next = copyEffect(effect);

  if (typeof next.cashDelta === 'number') {
    next.cashDelta = roundCurrency(next.cashDelta * multiplier);
  }

  if (typeof next.incomeDelta === 'number') {
    next.incomeDelta = roundCurrency(next.incomeDelta * multiplier);
  }

  if (typeof next.shieldDelta === 'number') {
    next.shieldDelta = roundCurrency(next.shieldDelta * multiplier);
  }

  if (typeof next.heatDelta === 'number') {
    next.heatDelta = roundCurrency(next.heatDelta * multiplier);
  }

  if (typeof next.trustDelta === 'number') {
    next.trustDelta = roundCurrency(next.trustDelta * multiplier);
  }

  if (typeof next.timeDeltaMs === 'number') {
    next.timeDeltaMs = Math.trunc(next.timeDeltaMs * multiplier);
  }

  if (typeof next.divergenceDelta === 'number') {
    next.divergenceDelta = roundCurrency(next.divergenceDelta * multiplier);
  }

  if (typeof next.debtDelta === 'number') {
    next.debtDelta = roundCurrency(next.debtDelta * multiplier);
  }

  if (typeof next.expenseDelta === 'number') {
    next.expenseDelta = roundCurrency(next.expenseDelta * multiplier);
  }

  if (typeof next.treasuryDelta === 'number') {
    next.treasuryDelta = roundCurrency(next.treasuryDelta * multiplier);
  }

  if (typeof next.battleBudgetDelta === 'number') {
    next.battleBudgetDelta = roundCurrency(next.battleBudgetDelta * multiplier);
  }

  if (typeof next.holdChargeDelta === 'number') {
    next.holdChargeDelta = roundCurrency(next.holdChargeDelta * multiplier);
  }

  if (typeof next.counterIntelDelta === 'number') {
    next.counterIntelDelta = roundCurrency(next.counterIntelDelta * multiplier);
  }

  return next;
}

function getModeOverlay(
  definition: CardDefinition,
  mode: ModeCode,
): Partial<ModeOverlay> | null {
  return definition.modeOverlay?.[mode] ?? null;
}

function isNearGhostMarker(snapshot: RunStateSnapshot): boolean {
  return snapshot.cards.ghostMarkers.some(
    (marker) => Math.abs(marker.tick - snapshot.tick) <= 3,
  );
}

function phaseBoundaryWindowOpen(snapshot: RunStateSnapshot): boolean {
  return snapshot.mode === 'solo' && snapshot.modeState.phaseBoundaryWindowsRemaining > 0;
}

function deriveResourceType(
  definition: CardDefinition,
  mode: ModeCode,
): ResourceType {
  if (definition.baseCost <= 0) {
    return 'free';
  }

  if (
    mode === 'pvp' &&
    (definition.deckType === 'SABOTAGE' ||
      definition.deckType === 'COUNTER')
  ) {
    return 'battle_budget';
  }

  if (
    mode === 'coop' &&
    (definition.deckType === 'AID' ||
      definition.deckType === 'RESCUE' ||
      definition.deckType === 'TRUST')
  ) {
    return 'shared_treasury';
  }

  return 'cash';
}

function deriveTargeting(
  definition: CardDefinition,
  mode: ModeCode,
  overlay: Partial<ModeOverlay> | null,
): Targeting {
  if (overlay?.targetingOverride) {
    return overlay.targetingOverride;
  }

  if (mode === 'solo') {
    return 'SELF';
  }

  if (mode === 'pvp') {
    if (
      definition.deckType === 'SABOTAGE' ||
      definition.deckType === 'BLUFF'
    ) {
      return 'OPPONENT';
    }

    if (definition.deckType === 'COUNTER') {
      return 'SELF';
    }
  }

  if (mode === 'coop') {
    if (definition.deckType === 'AID') {
      return 'TEAMMATE';
    }

    if (
      definition.deckType === 'RESCUE' ||
      definition.deckType === 'TRUST'
    ) {
      return 'TEAM';
    }
  }

  if (mode === 'ghost') {
    return 'SELF';
  }

  return definition.targeting;
}

function deriveDivergencePotential(
  definition: CardDefinition,
  snapshot: RunStateSnapshot,
  overlay: Partial<ModeOverlay> | null,
): DivergencePotential {
  if (overlay?.divergencePotential) {
    return overlay.divergencePotential;
  }

  if (snapshot.mode !== 'ghost') {
    return 'LOW';
  }

  if (
    definition.deckType === 'GHOST' ||
    definition.tags.includes('divergence')
  ) {
    return isNearGhostMarker(snapshot) ? 'HIGH' : 'MEDIUM';
  }

  if (definition.tags.includes('precision')) {
    return 'MEDIUM';
  }

  return 'LOW';
}

function deriveTimingLocks(
  overlay: Partial<ModeOverlay> | null,
): TimingClass[] {
  return overlay?.timingLock ? uniqueTimingClasses(overlay.timingLock as TimingClass[]) : [];
}

function computeTrustModifier(snapshot: RunStateSnapshot): number {
  if (snapshot.mode !== 'coop') {
    return 1;
  }

  const scores = Object.values(snapshot.modeState.trustScores);
  if (scores.length === 0) {
    return 1;
  }

  const average =
    scores.reduce((sum, score) => sum + Number(score || 0), 0) / scores.length;

  if (average >= 90) {
    return 1.25;
  }

  if (average >= 75) {
    return 1.12;
  }

  if (average >= 50) {
    return 1.0;
  }

  if (average >= 25) {
    return 0.9;
  }

  return 0.8;
}

function computeModeEffectModifier(
  definition: CardDefinition,
  snapshot: RunStateSnapshot,
): number {
  let modifier = 1;

  if (snapshot.mode === 'ghost' && isNearGhostMarker(snapshot)) {
    if (
      definition.tags.includes('precision') ||
      definition.tags.includes('divergence') ||
      definition.deckType === 'GHOST'
    ) {
      modifier += 0.2;
    }
  }

  if (snapshot.mode === 'pvp') {
    if (
      definition.deckType === 'SABOTAGE' &&
      snapshot.pressure.tier === 'T4'
    ) {
      modifier += 0.15;
    }

    if (definition.deckType === 'COUNTER') {
      modifier += 0.08;
    }
  }

  if (snapshot.mode === 'coop') {
    if (
      definition.deckType === 'AID' ||
      definition.deckType === 'RESCUE' ||
      definition.deckType === 'TRUST'
    ) {
      modifier *= computeTrustModifier(snapshot);
    }
  }

  if (snapshot.mode === 'solo') {
    if (
      definition.deckType === 'DISCIPLINE' &&
      snapshot.pressure.tier === 'T3'
    ) {
      modifier += 0.1;
    }

    if (
      definition.tags.includes('income') &&
      snapshot.phase === 'FOUNDATION'
    ) {
      modifier += 0.05;
    }
  }

  return modifier;
}

function defaultDecisionTimerMs(
  definition: CardDefinition,
  snapshot: RunStateSnapshot,
  resolvedTimingClass: readonly TimingClass[],
): number | null {
  if (definition.decisionTimerOverrideMs !== null) {
    return definition.decisionTimerOverrideMs;
  }

  if (definition.autoResolve) {
    return null;
  }

  if (resolvedTimingClass.includes('CTR')) {
    return 5_000;
  }

  if (resolvedTimingClass.includes('FATE')) {
    return 4_000;
  }

  if (resolvedTimingClass.includes('PHZ')) {
    return snapshot.timers.currentTickDurationMs * 5;
  }

  if (resolvedTimingClass.includes('GBM')) {
    return snapshot.timers.currentTickDurationMs * 3;
  }

  let timer = snapshot.timers.currentTickDurationMs;

  const totalShield = snapshot.shield.layers.reduce(
    (sum, layer) => sum + layer.current,
    0,
  );

  if (snapshot.mode === 'solo' && snapshot.pressure.tier === 'T4') {
    timer = Math.round(timer * 0.85);
  }

  if (snapshot.mode === 'solo' && totalShield <= 0 && snapshot.pressure.tier >= 'T3') {
    timer = Math.round(timer * 0.75);
  }

  return timer;
}

function defaultDecayTicks(definition: CardDefinition, snapshot: RunStateSnapshot): number | null {
  if (definition.decayTicks !== null) {
    return definition.decayTicks;
  }

  if (snapshot.mode === 'ghost' && definition.deckType === 'GHOST') {
    return 3;
  }

  if (snapshot.mode === 'pvp' && definition.deckType === 'COUNTER') {
    return 2;
  }

  return null;
}

function determineDynamicLegality(
  definition: CardDefinition,
  snapshot: RunStateSnapshot,
): string[] {
  const reasons: string[] = [];

  if (!definition.modeLegal.includes(snapshot.mode)) {
    reasons.push(`Card ${definition.id} is not legal in mode ${snapshot.mode}.`);
  }

  const deckModes = DECK_MODE_LEGALITY[definition.deckType] ?? [];
  if (!deckModes.includes(snapshot.mode)) {
    reasons.push(
      `Deck type ${definition.deckType} is not permitted in mode ${snapshot.mode}.`,
    );
  }

  if (
    snapshot.mode === 'ghost' &&
    definition.deckType === 'GHOST' &&
    !snapshot.modeState.legendMarkersEnabled
  ) {
    reasons.push('Ghost cards require legend markers to be enabled.');
  }

  if (
    snapshot.mode === 'solo' &&
    definition.timingClass.includes('PHZ') &&
    !phaseBoundaryWindowOpen(snapshot)
  ) {
    reasons.push('Phase Boundary cards require an active phase boundary window.');
  }

  if (
    snapshot.mode !== 'pvp' &&
    (definition.timingClass.includes('CTR') ||
      definition.deckType === 'COUNTER' ||
      definition.deckType === 'SABOTAGE' ||
      definition.deckType === 'BLUFF')
  ) {
    reasons.push('Predator combat cards are legal only in PvP mode.');
  }

  if (
    snapshot.mode !== 'coop' &&
    (definition.timingClass.includes('AID') ||
      definition.timingClass.includes('RES') ||
      definition.deckType === 'AID' ||
      definition.deckType === 'RESCUE' ||
      definition.deckType === 'TRUST')
  ) {
    reasons.push('Aid, Rescue, and Trust cards are legal only in co-op mode.');
  }

  if (
    snapshot.mode !== 'ghost' &&
    (definition.timingClass.includes('GBM') ||
      definition.deckType === 'GHOST')
  ) {
    reasons.push('Ghost Benchmark cards are legal only in Phantom mode.');
  }

  return reasons;
}

function selectedTimingClass(
  resolvedTimingClass: readonly TimingClass[],
  requestedTimingClass: TimingClass | undefined,
  availableTimingClasses: readonly TimingClass[],
): TimingClass | null {
  if (requestedTimingClass) {
    return requestedTimingClass;
  }

  const exact = resolvedTimingClass.find((timingClass) =>
    availableTimingClasses.includes(timingClass),
  );

  if (exact) {
    return exact;
  }

  if (resolvedTimingClass.includes('ANY')) {
    return availableTimingClasses[0] ?? 'ANY';
  }

  return null;
}

// ============================================================================
// MARK: ML Scoring Internals
// ============================================================================

function computeEconomyImpact(
  effect: EffectPayload,
  snapshot: RunStateSnapshot,
): number {
  const cashPosition = snapshot.economy.cash;
  if (cashPosition <= 0) return 0;

  const cashDelta = effect.cashDelta ?? 0;
  const incomeDelta = (effect.incomeDelta ?? 0) * 12;
  const totalDelta = cashDelta + incomeDelta;
  return clamp01(totalDelta / Math.max(1, cashPosition) * 0.5 + 0.5);
}

function computeShieldImpact(
  effect: EffectPayload,
  snapshot: RunStateSnapshot,
): number {
  const shieldDelta = effect.shieldDelta ?? 0;
  if (shieldDelta === 0) return 0;

  const totalCurrent = snapshot.shield.layers.reduce((s, l) => s + l.current, 0);
  const totalMax = snapshot.shield.layers.reduce((s, l) => s + l.max, 0);
  if (totalMax === 0) return 0;

  const currentPct = totalCurrent / totalMax;
  const normalized = shieldDelta / totalMax;

  if (shieldDelta > 0) {
    return clamp01(normalized * (2 - currentPct));
  }

  return clamp01(-normalized * (1 + (1 - currentPct)));
}

function computePressureRelief(
  definition: CardDefinition,
  snapshot: RunStateSnapshot,
): number {
  const PRESSURE_ORDER = ['T0', 'T1', 'T2', 'T3', 'T4'];
  const tierIndex = PRESSURE_ORDER.indexOf(snapshot.pressure.tier);

  const hasPressureRelief =
    definition.tags.includes('resilience') ||
    definition.tags.includes('counter') ||
    definition.tags.includes('discipline') ||
    definition.deckType === 'COUNTER' ||
    definition.deckType === 'RESCUE' ||
    definition.deckType === 'DISCIPLINE';

  if (!hasPressureRelief) return 0;
  return clamp01((tierIndex / 4) * 1.2);
}

function computeTempoAdvantage(
  definition: CardDefinition,
  snapshot: RunStateSnapshot,
): number {
  if (snapshot.mode !== 'pvp') return 0;

  const tempoTags = ['tempo', 'sabotage', 'counter', 'bleed'];
  const hasTempo = definition.tags.some((t) => tempoTags.includes(t));
  if (!hasTempo) return 0;

  const battleBudgetRatio = snapshot.battle.battleBudget / Math.max(1, snapshot.battle.battleBudgetCap);
  return clamp01(0.3 + battleBudgetRatio * 0.7);
}

function computeTrustImpact(
  effect: EffectPayload,
  snapshot: RunStateSnapshot,
): number {
  if (snapshot.mode !== 'coop') return 0;
  const trustDelta = effect.trustDelta ?? 0;
  if (trustDelta === 0) return 0;
  return clamp01(Math.abs(trustDelta) / 20);
}

function computeDivergenceAlignment(
  definition: CardDefinition,
  snapshot: RunStateSnapshot,
): number {
  if (snapshot.mode !== 'ghost') return 0;

  const isGhostCard = definition.deckType === 'GHOST' || definition.tags.includes('divergence') || definition.tags.includes('precision');
  if (!isGhostCard) return 0;

  const gapProgress = clamp01(1 - Math.abs(snapshot.sovereignty.gapVsLegend));
  const markerProximity = isNearGhostMarker(snapshot) ? 0.4 : 0;
  return clamp01(gapProgress * 0.6 + markerProximity);
}

function computeCascadeTriggerProb(
  definition: CardDefinition,
  snapshot: RunStateSnapshot,
): number {
  const base = DECK_CASCADE_PROB[definition.deckType] ?? 0.1;
  const hasTag = definition.tags.includes('cascade') ? 1.3 : 1.0;
  const chainBonus = snapshot.cascade.activeChains.length > 0 ? 1.2 : 1.0;
  return clamp01(base * hasTag * chainBonus);
}

function computeUrgencyScore(
  definition: CardDefinition,
  snapshot: RunStateSnapshot,
  tagWeights: Record<string, number>,
): number {
  const PRESSURE_ORDER = ['T0', 'T1', 'T2', 'T3', 'T4'];
  const tierIndex = PRESSURE_ORDER.indexOf(snapshot.pressure.tier) / 4;
  const tierModifier = TIER_PLAY_VALUE_MODIFIER[snapshot.pressure.tier];

  const relevantTagScore = definition.tags.reduce((sum, tag) => {
    const weight = tagWeights[tag] ?? 1.0;
    return sum + weight;
  }, 0) / Math.max(1, definition.tags.length);

  const shieldPct = snapshot.shield.layers.reduce((s, l) => s + l.current, 0) /
    Math.max(1, snapshot.shield.layers.reduce((s, l) => s + l.max, 0));

  const timeRatio = snapshot.timers.elapsedMs /
    Math.max(1, snapshot.timers.seasonBudgetMs + snapshot.timers.extensionBudgetMs);

  const urgency = (relevantTagScore * 0.4 + tierIndex * 0.3 + (1 - shieldPct) * 0.2 + timeRatio * 0.1) * tierModifier;

  return clamp01(urgency);
}

function computeTagAffinities(
  definition: CardDefinition,
  snapshot: RunStateSnapshot,
): Record<string, number> {
  const affinities: Record<string, number> = {};
  const baseWeights = MODE_TAG_WEIGHTS[snapshot.mode];

  for (const tag of definition.tags) {
    const baseWeight = baseWeights[tag] ?? 1.0;
    const comboBonus = computeTagComboBonus(tag, definition.tags);
    affinities[tag] = roundThousandths(clamp01(baseWeight / 3.0 * (1 + comboBonus * 0.3)));
  }

  return affinities;
}

function computeTagComboBonus(tag: string, allTags: readonly string[]): number {
  const comboRow = TAG_COMBO_MATRIX[tag];
  if (!comboRow) return 0;

  let bonus = 0;
  for (const other of allTags) {
    if (other !== tag && comboRow[other] !== undefined) {
      bonus += comboRow[other];
    }
  }

  return Math.min(1.0, bonus);
}

function buildMLScore(
  definition: CardDefinition,
  resolved: Omit<ResolvedCardView, 'mlScore' | 'dlInputVector' | 'playRecommendation'>,
  snapshot: RunStateSnapshot,
): CardMLScore {
  const economyImpact = computeEconomyImpact(resolved.effect, snapshot);
  const shieldImpact = computeShieldImpact(resolved.effect, snapshot);
  const pressureRelief = computePressureRelief(definition, snapshot);
  const tempoAdvantage = computeTempoAdvantage(definition, snapshot);
  const trustImpact = computeTrustImpact(resolved.effect, snapshot);
  const divergenceAlignment = computeDivergenceAlignment(definition, snapshot);
  const cascadeTriggerProb = computeCascadeTriggerProb(definition, snapshot);
  const urgencyScore = computeUrgencyScore(definition, snapshot, resolved.tagWeights);
  const tagAffinities = computeTagAffinities(definition, snapshot);

  const playValue = clamp01(
    economyImpact * 0.25 +
    shieldImpact * 0.15 +
    pressureRelief * 0.15 +
    tempoAdvantage * 0.1 +
    trustImpact * 0.1 +
    divergenceAlignment * 0.1 +
    cascadeTriggerProb * 0.1 +
    urgencyScore * 0.05,
  );

  const confidence = clamp01(
    0.5 + snapshot.telemetry.decisions.filter((d) => d.accepted).length / 40,
  );

  return {
    playValue: roundThousandths(playValue),
    economyImpact: roundThousandths(economyImpact),
    shieldImpact: roundThousandths(shieldImpact),
    pressureRelief: roundThousandths(pressureRelief),
    cascadeTriggerProb: roundThousandths(cascadeTriggerProb),
    tempoAdvantage: roundThousandths(tempoAdvantage),
    trustImpact: roundThousandths(trustImpact),
    divergenceAlignment: roundThousandths(divergenceAlignment),
    urgencyScore: roundThousandths(urgencyScore),
    confidence: roundThousandths(confidence),
    tagAffinities,
    modelVersion: ML_MODEL_VERSION,
  };
}

function buildDLInputVector(
  definition: CardDefinition,
  resolved: Omit<ResolvedCardView, 'mlScore' | 'dlInputVector' | 'playRecommendation'>,
  snapshot: RunStateSnapshot,
): number[] {
  const PRESSURE_ORDER = ['T0', 'T1', 'T2', 'T3', 'T4'];
  const PHASE_ORDER = ['FOUNDATION', 'ESCALATION', 'SOVEREIGNTY'];
  const MODE_ORDER = ['solo', 'pvp', 'coop', 'ghost'];
  const DECK_ORDER = DECK_TYPES as unknown as DeckType[];
  const TIMING_ORDER = TIMING_CLASSES as unknown as TimingClass[];

  const deckIndex = DECK_ORDER.indexOf(definition.deckType);
  const primaryTiming = resolved.timingClass[0] ?? 'ANY';
  const timingIndex = TIMING_ORDER.indexOf(primaryTiming);

  const shieldTotal = snapshot.shield.layers.reduce((s, l) => s + l.current, 0);
  const shieldMax = snapshot.shield.layers.reduce((s, l) => s + l.max, 0);

  return [
    // Card features
    resolved.cost / 100_000,
    deckIndex / Math.max(1, DECK_ORDER.length),
    timingIndex / Math.max(1, TIMING_ORDER.length),
    definition.autoResolve ? 1 : 0,
    definition.tags.length / 10,
    ['LEGENDARY', 'RARE', 'UNCOMMON', 'COMMON'].indexOf(definition.rarity) / 3,
    resolved.divergencePotential === 'HIGH' ? 1 : resolved.divergencePotential === 'MEDIUM' ? 0.5 : 0,

    // Snapshot context
    PRESSURE_ORDER.indexOf(snapshot.pressure.tier) / 4,
    snapshot.pressure.score,
    PHASE_ORDER.indexOf(snapshot.phase) / 2,
    MODE_ORDER.indexOf(snapshot.mode) / 3,
    shieldMax === 0 ? 1 : shieldTotal / shieldMax,
    snapshot.economy.cash / 500_000,
    snapshot.economy.netWorth / 1_000_000,
    snapshot.economy.incomePerTick / 50_000,
    snapshot.tension.score,
    snapshot.tension.anticipation,
    snapshot.cascade.activeChains.length / 10,
    snapshot.cards.hand.length / 8,
    snapshot.modeState.bleedMode ? 1 : 0,
    snapshot.battle.firstBloodClaimed ? 1 : 0,
    snapshot.sovereignty.gapVsLegend,
    snapshot.timers.elapsedMs / Math.max(1, snapshot.timers.seasonBudgetMs),

    // Resource state
    resolved.resourceType === 'cash' ? 1 : 0,
    resolved.resourceType === 'battle_budget' ? 1 : 0,
    resolved.resourceType === 'shared_treasury' ? 1 : 0,
    resolved.resourceType === 'free' ? 1 : 0,
  ];
}

function buildPlayRecommendation(
  definition: CardDefinition,
  resolved: Omit<ResolvedCardView, 'mlScore' | 'dlInputVector' | 'playRecommendation'>,
  mlScore: CardMLScore,
  snapshot: RunStateSnapshot,
): PlayRecommendation {
  const rationale: string[] = [];
  const alternativeTags: string[] = [];

  if (!resolved.legal) {
    return {
      recommended: false,
      priority: 'AVOID',
      rationale: [...resolved.legalityReasons],
      alternativeTags: [],
      bestTimingClass: null,
      estimatedEffectiveness: 0,
    };
  }

  let priority: PlayRecommendation['priority'] = 'MEDIUM';

  if (mlScore.urgencyScore >= 0.8) {
    priority = 'MUST_PLAY';
    rationale.push(`Urgency score ${mlScore.urgencyScore.toFixed(2)} — critical play window.`);
  } else if (mlScore.playValue >= 0.7) {
    priority = 'HIGH';
    rationale.push(`Play value ${mlScore.playValue.toFixed(2)} — high expected return.`);
  } else if (mlScore.playValue >= 0.45) {
    priority = 'MEDIUM';
  } else if (mlScore.playValue >= 0.2) {
    priority = 'LOW';
    rationale.push(`Play value ${mlScore.playValue.toFixed(2)} — marginal return.`);
  } else {
    priority = 'AVOID';
    rationale.push(`Play value ${mlScore.playValue.toFixed(2)} — low priority in current context.`);
  }

  if (mlScore.economyImpact >= 0.6) {
    rationale.push(`Strong economy impact: ${mlScore.economyImpact.toFixed(2)}.`);
  }

  if (mlScore.pressureRelief >= 0.5) {
    rationale.push(`Meaningful pressure relief at ${snapshot.pressure.tier}.`);
  }

  if (mlScore.cascadeTriggerProb >= 0.35) {
    rationale.push(`${(mlScore.cascadeTriggerProb * 100).toFixed(0)}% cascade trigger probability.`);
  }

  if (snapshot.mode === 'pvp' && mlScore.tempoAdvantage >= 0.5) {
    rationale.push(`High tempo advantage: ${mlScore.tempoAdvantage.toFixed(2)}.`);
  }

  if (snapshot.mode === 'ghost' && mlScore.divergenceAlignment >= 0.5) {
    rationale.push(`Aligned with legend gap at ${snapshot.sovereignty.gapVsLegend.toFixed(3)}.`);
  }

  const baseWeights = MODE_TAG_WEIGHTS[snapshot.mode];
  const sortedTags = Object.entries(baseWeights)
    .filter(([tag]) => !definition.tags.includes(tag))
    .sort(([, a], [, b]) => b - a)
    .slice(0, 3)
    .map(([tag]) => tag);
  alternativeTags.push(...sortedTags);

  const bestTimingClass = resolved.timingClass[0] ?? null;

  return {
    recommended: priority !== 'AVOID',
    priority,
    rationale: Object.freeze(rationale),
    alternativeTags: Object.freeze(alternativeTags),
    bestTimingClass,
    estimatedEffectiveness: roundThousandths(mlScore.playValue * (1 + mlScore.urgencyScore * 0.5)),
  };
}

// ============================================================================
// MARK: CardOverlayResolver — Main Class
// ============================================================================

export class CardOverlayResolver {

  // ============================================================================
  // MARK: Core Resolution
  // ============================================================================

  public resolveDefinition(
    definition: CardDefinition,
    snapshot: RunStateSnapshot,
  ): ResolvedCardView {
    const overlay = getModeOverlay(definition, snapshot.mode);
    const normalizedOverlay = normalizeModeOverlay(overlay);
    const legalityReasons = determineDynamicLegality(definition, snapshot);

    if (overlay?.legal === false) {
      legalityReasons.push(
        `Mode overlay explicitly marks ${definition.id} illegal in ${snapshot.mode}.`,
      );
    }

    const pressureMultiplier = PRESSURE_COST_MULTIPLIER[snapshot.pressure.tier];
    const overlayCostModifier = normalizedOverlay.costModifier;
    const resolvedCost = roundCurrency(
      definition.baseCost * overlayCostModifier * pressureMultiplier,
    );

    const effectModifier =
      normalizedOverlay.effectModifier *
      computeModeEffectModifier(definition, snapshot);

    const resolvedEffect = multiplyEffect(definition.baseEffect, effectModifier);
    const resourceType = deriveResourceType(definition, snapshot.mode);
    const targeting = deriveTargeting(definition, snapshot.mode, overlay);

    const timingLocks = deriveTimingLocks(overlay);
    const resolvedTimingClass = uniqueTimingClasses([
      ...definition.timingClass,
      ...timingLocks,
    ]);

    const tagWeights = this.computeTagWeights(definition, snapshot, overlay);
    const tags = uniqueStrings(definition.tags);
    const autoResolve =
      definition.autoResolve ||
      (definition.deckType === 'FUBAR' && snapshot.mode !== 'pvp');

    const base = {
      definitionId: definition.id,
      mode: snapshot.mode,
      legal: legalityReasons.length === 0,
      legalityReasons,
      resourceType,
      cost: resolvedCost,
      effect: resolvedEffect,
      targeting,
      timingClass: resolvedTimingClass,
      timingLocks,
      tags,
      tagWeights,
      autoResolve,
      decisionTimerMs: defaultDecisionTimerMs(
        definition,
        snapshot,
        resolvedTimingClass,
      ),
      decayTicksRemaining: defaultDecayTicks(definition, snapshot),
      divergencePotential: deriveDivergencePotential(definition, snapshot, overlay),
    };

    const mlScore = buildMLScore(definition, base, snapshot);
    const dlInputVector = buildDLInputVector(definition, base, snapshot);
    const playRecommendation = buildPlayRecommendation(definition, base, mlScore, snapshot);

    return {
      ...base,
      mlScore,
      dlInputVector,
      playRecommendation,
    };
  }

  public resolveInstanceForPlay(
    instance: CardInstance,
    snapshot: RunStateSnapshot,
  ): ResolvedCardView {
    const base = this.resolveDefinition(instance.card, snapshot);

    return {
      ...base,
      cost: instance.cost,
      targeting: instance.targeting,
      timingClass: uniqueTimingClasses(instance.timingClass),
      tags: uniqueStrings(instance.tags),
      decayTicksRemaining: instance.decayTicksRemaining,
      divergencePotential: instance.divergencePotential,
    };
  }

  public createInstance(
    definition: CardDefinition,
    snapshot: RunStateSnapshot,
  ): CardInstance | null {
    const resolved = this.resolveDefinition(definition, snapshot);

    if (!resolved.legal) {
      return null;
    }

    const instanceId = createDeterministicId(
      'card-instance',
      snapshot.seed,
      snapshot.runId,
      snapshot.tick,
      definition.id,
      snapshot.cards.hand.length,
      snapshot.cards.drawHistory.length,
    );

    return createCardInstance(definition, {
      instanceId,
      mode: snapshot.mode,
      cost: resolved.cost,
      tags: resolved.tags,
      timingClass: resolved.timingClass,
      targeting: resolved.targeting,
      decayTicksRemaining: resolved.decayTicksRemaining,
      divergencePotential: resolved.divergencePotential,
    });
  }

  public validateCardPlay(
    input: ValidateCardPlayInput,
  ): CardPlayValidationResult {
    const validationStartMs = Date.now();

    const resolved =
      'instanceId' in input.card
        ? this.resolveInstanceForPlay(input.card, input.snapshot)
        : this.resolveDefinition(input.card, input.snapshot);

    const reasons = [...resolved.legalityReasons];
    const availableTimingClasses = Array.from(
      new Set(input.availableTimingClasses ?? ['ANY']),
    ) as TimingClass[];

    const chosen = selectedTimingClass(
      resolved.timingClass,
      input.requestedTimingClass,
      availableTimingClasses,
    );

    const timingWindowOpen = chosen !== null && availableTimingClasses.includes(chosen);
    const resourceSufficient = this.hasSufficientResources(input.snapshot, resolved);
    const modeLegalityPassed = !resolved.legalityReasons.some((r) => r.includes('not legal in mode'));
    const deckLegalityPassed = !resolved.legalityReasons.some((r) => r.includes('not permitted in mode'));
    const modeOverlayBlocked = overlay_blocked(resolved);
    const ghostMarkerRequired = resolved.timingClass.includes('GBM');
    const phaseBoundaryRequired = resolved.timingClass.includes('PHZ');
    const counterWindowRequired = resolved.timingClass.includes('CTR');
    const aidWindowRequired = resolved.timingClass.includes('AID') || resolved.timingClass.includes('RES');

    if (!resolved.legal) {
      return {
        legal: false,
        chosenTimingClass: chosen,
        reasons,
        resolved,
        diagnostics: buildDiagnostics(
          timingWindowOpen, resourceSufficient, modeLegalityPassed, deckLegalityPassed,
          modeOverlayBlocked, ghostMarkerRequired, phaseBoundaryRequired,
          counterWindowRequired, aidWindowRequired, validationStartMs, input.snapshot,
        ),
      };
    }

    if (chosen === null) {
      reasons.push(
        `No valid timing class open for card ${resolved.definitionId}. Available: ${availableTimingClasses.join(', ')}`,
      );

      return {
        legal: false,
        chosenTimingClass: null,
        reasons,
        resolved,
        diagnostics: buildDiagnostics(
          false, resourceSufficient, modeLegalityPassed, deckLegalityPassed,
          modeOverlayBlocked, ghostMarkerRequired, phaseBoundaryRequired,
          counterWindowRequired, aidWindowRequired, validationStartMs, input.snapshot,
        ),
      };
    }

    if (
      !resolved.timingClass.includes('ANY') &&
      !resolved.timingClass.includes(chosen)
    ) {
      reasons.push(
        `Requested timing class ${chosen} is not legal for ${resolved.definitionId}.`,
      );
    }

    if (
      input.requestedTimingClass &&
      !availableTimingClasses.includes(input.requestedTimingClass)
    ) {
      reasons.push(
        `Requested timing class ${input.requestedTimingClass} is not currently open.`,
      );
    }

    if (resolved.timingLocks.length > 0) {
      const lockSatisfied = resolved.timingLocks.some((timingClass) =>
        availableTimingClasses.includes(timingClass),
      );

      if (!lockSatisfied) {
        reasons.push(
          `Card ${resolved.definitionId} requires one of the locked timing windows: ${resolved.timingLocks.join(', ')}`,
        );
      }
    }

    if (!resourceSufficient) {
      const currentBalance = this.getResourceBalance(input.snapshot, resolved.resourceType);
      reasons.push(
        `Insufficient ${resolved.resourceType}. Need ${resolved.cost}, have ${currentBalance}.`,
      );
    }

    if (chosen === 'GBM' && !isNearGhostMarker(input.snapshot)) {
      reasons.push('GBM card played without a nearby legend marker.');
    }

    if (chosen === 'PHZ' && !phaseBoundaryWindowOpen(input.snapshot)) {
      reasons.push('PHZ card played without an active phase boundary window.');
    }

    if (chosen === 'CTR' && input.snapshot.mode !== 'pvp') {
      reasons.push('Counter Window exists only in PvP mode.');
    }

    if ((chosen === 'RES' || chosen === 'AID') && input.snapshot.mode !== 'coop') {
      reasons.push(`${chosen} timing exists only in co-op mode.`);
    }

    return {
      legal: reasons.length === 0,
      chosenTimingClass: chosen,
      reasons,
      resolved,
      diagnostics: buildDiagnostics(
        timingWindowOpen, resourceSufficient, modeLegalityPassed, deckLegalityPassed,
        modeOverlayBlocked, ghostMarkerRequired, phaseBoundaryRequired,
        counterWindowRequired, aidWindowRequired, validationStartMs, input.snapshot,
      ),
    };
  }

  // ============================================================================
  // MARK: Tag Weight Computation
  // ============================================================================

  public computeTagWeights(
    definition: CardDefinition,
    snapshot: RunStateSnapshot,
    overlay?: Partial<ModeOverlay> | null,
  ): Record<string, number> {
    const baseWeights = {
      ...MODE_TAG_WEIGHTS[snapshot.mode],
    };

    for (const tag of definition.tags) {
      if (baseWeights[tag] === undefined) {
        baseWeights[tag] = 1;
      }
    }

    if (overlay?.tagWeights) {
      for (const [tag, weight] of Object.entries(overlay.tagWeights)) {
        baseWeights[tag] = weight;
      }
    }

    const phaseMultiplier = this.computePhaseTagMultiplier(snapshot);
    for (const tag of Object.keys(baseWeights)) {
      baseWeights[tag] = roundThousandths(baseWeights[tag] * phaseMultiplier);
    }

    return baseWeights;
  }

  private computePhaseTagMultiplier(snapshot: RunStateSnapshot): number {
    if (snapshot.phase === 'SOVEREIGNTY') return 1.15;
    if (snapshot.phase === 'ESCALATION') return 1.05;
    return 1.0;
  }

  // ============================================================================
  // MARK: Resource Access
  // ============================================================================

  public hasSufficientResources(
    snapshot: RunStateSnapshot,
    resolved: ResolvedCardView,
  ): boolean {
    if (resolved.resourceType === 'free') {
      return true;
    }

    return this.getResourceBalance(snapshot, resolved.resourceType) >= resolved.cost;
  }

  public getResourceBalance(
    snapshot: RunStateSnapshot,
    resourceType: ResourceType,
  ): number {
    switch (resourceType) {
      case 'cash':
        return snapshot.economy.cash;
      case 'battle_budget':
        return snapshot.battle.battleBudget;
      case 'shared_treasury':
        return snapshot.modeState.sharedTreasuryBalance;
      case 'free':
        return Number.POSITIVE_INFINITY;
      default:
        return 0;
    }
  }

  // ============================================================================
  // MARK: Hand Analysis
  // ============================================================================

  /**
   * Analyze the full hand and produce structured ML-ready insights.
   */
  public analyzeHand(
    instances: readonly CardInstance[],
    snapshot: RunStateSnapshot,
  ): HandAnalysis {
    const resolvedCards: ResolvedCardView[] = instances.map((instance) =>
      this.resolveInstanceForPlay(instance, snapshot),
    );

    const playable = resolvedCards.filter((c) => c.legal);
    const totalExpectedValue = playable.reduce((sum, c) => sum + c.mlScore.playValue, 0);

    const topCard = playable.length === 0 ? null :
      playable.reduce((best, c) => c.mlScore.urgencyScore > best.mlScore.urgencyScore ? c : best, playable[0]);

    const combos = this.computeCombos(instances, snapshot);
    const deckEntropyEstimate = this.estimateDeckEntropy(snapshot);
    const diversityScore = this.computeHandDiversity(resolvedCards);
    const timingCoverage = this.computeTimingCoverage(resolvedCards);
    const tagDistribution = this.computeTagDistribution(resolvedCards);
    const mlVector = this.buildHandMLVector(resolvedCards, snapshot);

    return {
      handSize: instances.length,
      playableCount: playable.length,
      totalExpectedValue: roundThousandths(totalExpectedValue),
      topCard,
      combos,
      deckEntropyEstimate,
      diversityScore,
      timingCoverage,
      tagDistribution,
      mlVector,
    };
  }

  private computeCombos(
    instances: readonly CardInstance[],
    snapshot: RunStateSnapshot,
  ): CardComboScore[] {
    const combos: CardComboScore[] = [];

    for (let i = 0; i < instances.length; i++) {
      for (let j = i + 1; j < instances.length; j++) {
        const a = instances[i];
        const b = instances[j];
        const combo = this.scoreCardCombo(a, b, snapshot);
        if (combo.synergyScore > 0.3) {
          combos.push(combo);
        }
      }
    }

    return combos.sort((x, y) => y.synergyScore - x.synergyScore).slice(0, 5);
  }

  private scoreCardCombo(
    a: CardInstance,
    b: CardInstance,
    snapshot: RunStateSnapshot,
  ): CardComboScore {
    const sharedTags = a.tags.filter((t) => b.tags.includes(t));
    let synergyScore = 0;
    let cascadeAmplification = 0;

    for (const tag of a.tags) {
      const comboRow = TAG_COMBO_MATRIX[tag];
      if (comboRow) {
        for (const bTag of b.tags) {
          if (comboRow[bTag] !== undefined) {
            synergyScore += comboRow[bTag];
          }
        }
      }
    }

    synergyScore = clamp01(synergyScore / 3);

    if (a.tags.includes('cascade') || b.tags.includes('cascade')) {
      cascadeAmplification = 0.3 + snapshot.cascade.activeChains.length * 0.05;
    }

    const pressureDoubling =
      (a.tags.includes('resilience') && b.tags.includes('discipline')) ||
      (a.tags.includes('counter') && b.tags.includes('sabotage'));

    const timingAlignment =
      a.timingClass.some((t) => b.timingClass.includes(t) && t !== 'ANY');

    const description = sharedTags.length > 0
      ? `Synergy via shared tags: ${sharedTags.join(', ')}.`
      : `Combo via tag interaction.`;

    return {
      cardAId: a.instanceId,
      cardBId: b.instanceId,
      synergyScore: roundThousandths(synergyScore),
      sharedTags,
      cascadeAmplification: roundThousandths(cascadeAmplification),
      pressureDoubling,
      timingAlignment,
      description,
    };
  }

  private estimateDeckEntropy(snapshot: RunStateSnapshot): number {
    const drawPileSize = snapshot.cards.drawPileSize;
    const handSize = snapshot.cards.hand.length;
    if (drawPileSize + handSize === 0) return 0;

    const ratio = handSize / Math.max(1, drawPileSize + handSize);
    return roundThousandths(snapshot.cards.deckEntropy * (1 - ratio * 0.2));
  }

  private computeHandDiversity(resolvedCards: readonly ResolvedCardView[]): number {
    if (resolvedCards.length === 0) return 0;

    const uniqueDecks = new Set(resolvedCards.map((c) => {
      const inst = c as unknown as { card?: { deckType?: string } };
      return inst.card?.deckType ?? 'UNKNOWN';
    }));

    const uniqueTimings = new Set(resolvedCards.flatMap((c) => c.timingClass));
    const uniqueTags = new Set(resolvedCards.flatMap((c) => c.tags));

    const deckDiversity = uniqueDecks.size / Math.max(1, DECK_TYPES.length);
    const timingDiversity = uniqueTimings.size / TIMING_CLASSES.length;
    const tagDiversity = Math.min(1, uniqueTags.size / 10);

    return roundThousandths((deckDiversity + timingDiversity + tagDiversity) / 3);
  }

  private computeTimingCoverage(resolvedCards: readonly ResolvedCardView[]): TimingClass[] {
    const coverage = new Set<TimingClass>();
    for (const card of resolvedCards) {
      for (const t of card.timingClass) {
        if (isTimingClass(t)) coverage.add(t);
      }
    }
    return Array.from(coverage);
  }

  private computeTagDistribution(resolvedCards: readonly ResolvedCardView[]): Record<string, number> {
    const dist: Record<string, number> = {};
    for (const card of resolvedCards) {
      for (const tag of card.tags) {
        dist[tag] = (dist[tag] ?? 0) + 1;
      }
    }
    return dist;
  }

  private buildHandMLVector(
    resolvedCards: readonly ResolvedCardView[],
    snapshot: RunStateSnapshot,
  ): number[] {
    const playable = resolvedCards.filter((c) => c.legal);
    const avgPlayValue = playable.length === 0 ? 0 :
      playable.reduce((s, c) => s + c.mlScore.playValue, 0) / playable.length;
    const avgUrgency = playable.length === 0 ? 0 :
      playable.reduce((s, c) => s + c.mlScore.urgencyScore, 0) / playable.length;

    return [
      resolvedCards.length / 8,
      playable.length / Math.max(1, resolvedCards.length),
      avgPlayValue,
      avgUrgency,
      this.computeHandDiversity(resolvedCards),
      this.estimateDeckEntropy(snapshot),
      snapshot.pressure.score,
      snapshot.tension.score,
    ];
  }

  // ============================================================================
  // MARK: Bulk Resolution
  // ============================================================================

  /**
   * Resolve a batch of card definitions in one pass.
   * Optimized for deck composition scanning.
   */
  public resolveBatch(
    definitions: readonly CardDefinition[],
    snapshot: RunStateSnapshot,
  ): ResolvedCardView[] {
    return definitions.map((def) => this.resolveDefinition(def, snapshot));
  }

  /**
   * Resolve all hand instances and sort by ML urgency descending.
   */
  public resolveHandByPriority(
    instances: readonly CardInstance[],
    snapshot: RunStateSnapshot,
  ): ResolvedCardView[] {
    return instances
      .map((instance) => this.resolveInstanceForPlay(instance, snapshot))
      .sort((a, b) => b.mlScore.urgencyScore - a.mlScore.urgencyScore);
  }

  /**
   * Filter hand to only playable cards.
   */
  public filterPlayable(
    instances: readonly CardInstance[],
    snapshot: RunStateSnapshot,
    availableTimingClasses: readonly TimingClass[] = ['ANY'],
  ): Array<{ instance: CardInstance; resolved: ResolvedCardView }> {
    return instances
      .map((instance) => ({
        instance,
        resolved: this.resolveInstanceForPlay(instance, snapshot),
      }))
      .filter(({ resolved }) => {
        if (!resolved.legal) return false;
        return resolved.timingClass.some((t) => availableTimingClasses.includes(t) || t === 'ANY');
      });
  }

  // ============================================================================
  // MARK: Checksum / Proof Support
  // ============================================================================

  /**
   * Compute a deterministic checksum of the resolved card view for proof chain inclusion.
   */
  public checksumResolvedView(view: ResolvedCardView): string {
    return checksumSnapshot({
      definitionId: view.definitionId,
      mode: view.mode,
      legal: view.legal,
      cost: view.cost,
      timingClass: view.timingClass,
      tags: view.tags,
      divergencePotential: view.divergencePotential,
    });
  }

  /**
   * Compute a stable parts checksum for multi-card validation batches.
   */
  public checksumValidationBatch(results: readonly CardPlayValidationResult[]): string {
    return checksumParts(
      ...results.map((r) => ({
        definitionId: r.resolved.definitionId,
        legal: r.legal,
        chosenTimingClass: r.chosenTimingClass,
      })),
    );
  }

  /**
   * Serialize a resolved view to a stable string (used by proof sealer).
   */
  public serializeView(view: ResolvedCardView): string {
    return stableStringify({
      definitionId: view.definitionId,
      mode: view.mode,
      legal: view.legal,
      cost: view.cost,
      resourceType: view.resourceType,
      timingClass: view.timingClass,
      tags: view.tags,
    });
  }

  // ============================================================================
  // MARK: Mode Rule Surface
  // ============================================================================

  /**
   * Check if a deck type is legal in the given mode.
   * Uses the canonical DECK_MODE_LEGALITY table.
   */
  public static isDeckTypeLegalForMode(deckType: DeckType, mode: ModeCode): boolean {
    if (!isDeckType(deckType) || !isModeCode(mode)) return false;
    return (DECK_MODE_LEGALITY[deckType] ?? []).includes(mode);
  }

  /**
   * Get the legal modes for a deck type.
   */
  public static getLegalModesForDeckType(deckType: DeckType): readonly ModeCode[] {
    return DECK_MODE_LEGALITY[deckType] ?? [];
  }

  /**
   * Get the resource type for a deck type in a given mode.
   * Used by the economy engine for pre-play budget checks.
   */
  public static getResourceTypeForDeckType(deckType: DeckType, mode: ModeCode): ResourceType {
    if (mode === 'pvp' && (deckType === 'SABOTAGE' || deckType === 'COUNTER')) {
      return 'battle_budget';
    }
    if (mode === 'coop' && (deckType === 'AID' || deckType === 'RESCUE' || deckType === 'TRUST')) {
      return 'shared_treasury';
    }
    return 'cash';
  }

  /**
   * Get the full pressure cost multiplier table.
   * Consumed by economy surfaces and ML pricing models.
   */
  public static getPressureCostMultiplierTable(): Readonly<Record<PressureTier, number>> {
    return Object.freeze({ ...PRESSURE_COST_MULTIPLIER });
  }

  /**
   * Get mode tag weights for a given mode.
   * Read surface for ML feature extraction.
   */
  public static getModeTagWeights(mode: ModeCode): Readonly<Record<string, number>> {
    return Object.freeze({ ...MODE_TAG_WEIGHTS[mode] });
  }

  /**
   * Get all known timing classes (from canonical GamePrimitives constant).
   */
  public static getAllTimingClasses(): readonly TimingClass[] {
    return TIMING_CLASSES as unknown as TimingClass[];
  }

  /**
   * Get all known pressure tiers (from canonical GamePrimitives constant).
   */
  public static getAllPressureTiers(): readonly PressureTier[] {
    return PRESSURE_TIERS as unknown as PressureTier[];
  }

  /**
   * Get all known mode codes.
   */
  public static getAllModeCodes(): readonly ModeCode[] {
    return MODE_CODES as unknown as ModeCode[];
  }

  /**
   * Get the shield layer label for a shield layer ID.
   * Exposes SHIELD_LAYER_LABEL_BY_ID via the overlay surface.
   */
  public static getShieldLayerLabel(layerId: string): string {
    if (SHIELD_LAYER_IDS.includes(layerId as ReturnType<typeof SHIELD_LAYER_IDS[number]>)) {
      return SHIELD_LAYER_LABEL_BY_ID[layerId as keyof typeof SHIELD_LAYER_LABEL_BY_ID];
    }
    return layerId;
  }

  /**
   * Surface the mergeEffectPayload utility for external callers.
   */
  public static mergeEffects(base: EffectPayload, delta: EffectPayload): EffectPayload {
    return mergeEffectPayload(base, delta);
  }

  /**
   * Surface the resolveModeOverlay utility for external callers.
   */
  public static resolveOverlay(definition: CardDefinition, mode: ModeCode): ModeOverlay {
    return resolveModeOverlay(definition, mode);
  }

  /**
   * Surface the DEFAULT_MODE_OVERLAY for callers that need the fallback.
   */
  public static getDefaultOverlay(): Readonly<ModeOverlay> {
    return DEFAULT_MODE_OVERLAY;
  }

  /**
   * Surface the getShieldLayerLabel primitive via the overlay surface.
   */
  public static shieldLayerLabel = getShieldLayerLabel;
}

// ============================================================================
// MARK: Diagnostics Builder (module-private)
// ============================================================================

function overlay_blocked(resolved: Omit<ResolvedCardView, 'mlScore' | 'dlInputVector' | 'playRecommendation'>): boolean {
  return resolved.legalityReasons.some((r) => r.includes('overlay explicitly marks'));
}

function buildDiagnostics(
  timingWindowOpen: boolean,
  resourceSufficient: boolean,
  modeLegalityPassed: boolean,
  deckLegalityPassed: boolean,
  modeOverlayBlocked: boolean,
  ghostMarkerRequired: boolean,
  phaseBoundaryRequired: boolean,
  counterWindowRequired: boolean,
  aidWindowRequired: boolean,
  validationStartMs: number,
  snapshot: RunStateSnapshot,
): CardPlayDiagnostics {
  return {
    timingWindowOpen,
    resourceSufficient,
    modeLegalityPassed,
    deckLegalityPassed,
    modeOverlayBlocked,
    ghostMarkerRequired,
    phaseBoundaryRequired,
    counterWindowRequired,
    aidWindowRequired,
    validationDurationMs: Date.now() - validationStartMs,
    checksumAtValidation: checksumSnapshot({
      runId: snapshot.runId,
      tick: snapshot.tick,
      pressureTier: snapshot.pressure.tier,
    }),
  };
}

// ---------------------------------------------------------------------------
// CardOverlayRollingStats — tracks validation throughput over 60 ticks
// ---------------------------------------------------------------------------

export interface CardOverlayTickStats {
  readonly tick: number;
  readonly validations: number;
  readonly playableCount: number;
  readonly blockedCount: number;
  readonly avgValidationMs: number;
}

export class CardOverlayRollingStats {
  private readonly capacity: number;
  private readonly snapshots: CardOverlayTickStats[] = [];

  public constructor(capacity = 60) { this.capacity = capacity; }

  public record(snap: CardOverlayTickStats): void {
    if (this.snapshots.length >= this.capacity) this.snapshots.shift();
    this.snapshots.push(Object.freeze(snap));
  }

  public avgPlayableRate(): number {
    if (this.snapshots.length === 0) return 1;
    const total = this.snapshots.reduce((s, r) => s + r.validations, 0);
    const playable = this.snapshots.reduce((s, r) => s + r.playableCount, 0);
    return total > 0 ? playable / total : 1;
  }

  public avgValidationMs(): number {
    if (this.snapshots.length === 0) return 0;
    return this.snapshots.reduce((s, r) => s + r.avgValidationMs, 0) / this.snapshots.length;
  }

  public totalValidations(): number {
    return this.snapshots.reduce((s, r) => s + r.validations, 0);
  }

  public peakValidationsPerTick(): number {
    if (this.snapshots.length === 0) return 0;
    return Math.max(...this.snapshots.map(s => s.validations));
  }

  public clear(): void { this.snapshots.length = 0; }
  public size(): number { return this.snapshots.length; }
}

// ---------------------------------------------------------------------------
// CardOverlayHealthGrader
// ---------------------------------------------------------------------------

export type CardOverlayHealthGrade = 'S' | 'A' | 'B' | 'C' | 'D' | 'F';

export function gradeCardOverlayHealth(
  avgPlayableRate: number,
  avgValidationMs: number,
): CardOverlayHealthGrade {
  const timeScore = Math.max(0, 1 - avgValidationMs / 50);
  const composite = avgPlayableRate * 0.7 + timeScore * 0.3;
  if (composite >= 0.93) return 'S';
  if (composite >= 0.82) return 'A';
  if (composite >= 0.68) return 'B';
  if (composite >= 0.50) return 'C';
  if (composite >= 0.32) return 'D';
  return 'F';
}

export interface CardOverlayHealthSummary {
  readonly grade: CardOverlayHealthGrade;
  readonly avgPlayableRate: number;
  readonly avgValidationMs: number;
  readonly totalValidations: number;
  readonly peakValidationsPerTick: number;
  readonly isHealthy: boolean;
}

export function buildCardOverlayHealthSummary(
  stats: CardOverlayRollingStats,
): CardOverlayHealthSummary {
  const avgPlayableRate = stats.avgPlayableRate();
  const avgValidationMs = stats.avgValidationMs();
  const grade = gradeCardOverlayHealth(avgPlayableRate, avgValidationMs);
  return Object.freeze({
    grade, avgPlayableRate, avgValidationMs,
    totalValidations: stats.totalValidations(),
    peakValidationsPerTick: stats.peakValidationsPerTick(),
    isHealthy: grade === 'S' || grade === 'A' || grade === 'B',
  });
}

// ---------------------------------------------------------------------------
// Module constants
// ---------------------------------------------------------------------------

export const CARD_OVERLAY_MODULE_VERSION = '2.0.0' as const;
export const CARD_OVERLAY_MODULE_READY = true;
export const CARD_OVERLAY_ROLLING_CAPACITY = 60 as const;
export const CARD_OVERLAY_COMPLETE = true;
