- A user management system with authentication (login/register functionality)
- A Redux store containing a `userSlice` and a `contentRestrictionsSlice` for managing user data and content restrictions respectively
- An `AgeGateModal` component for handling the age gating functionality
