- `checkAge()` checks if the user's age is over 13 based on the provided birthdate. If not, it redirects them to an age-gating page.
- `getAgeVerification()` verifies the user's age with a mock API. The actual implementation would involve sending the user's birthday to a COPPA-compliant age verification service and storing the response.
- `setBirthday(birthday: string)` sets the user's birthdate in local storage.
