- `generateHash()`: Generates a SHA256 hash of a given file.
- `authenticateToken()`: Verifies and authenticates an incoming JWT token.
- `checkFileIntegrity()`: Checks the integrity of a given file by comparing its current hash with the stored one.
- `checkAndStoreFileIntegrity()`: Checks the file's integrity and stores the new hash if needed.
