-- Migration 021: Create webhook_subscriptions
            -- Generated by pzo_curriculum_gateway_generator.py
            -- Date: 2026-03-07T14:32:44Z

            BEGIN;

            CREATE TABLE IF NOT EXISTS webhook_subscriptions (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    institution_id UUID NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
    target_url TEXT NOT NULL,
    secret VARCHAR(255) NOT NULL,
    event_types JSONB NOT NULL DEFAULT '[]',
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    failure_count INTEGER NOT NULL DEFAULT 0,
    last_success_at TIMESTAMPTZ,
    last_failure_at TIMESTAMPTZ,
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE INDEX IF NOT EXISTS idx_webhook_subscriptions_institution_id ON webhook_subscriptions(institution_id);
CREATE INDEX IF NOT EXISTS idx_webhook_subscriptions_status ON webhook_subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_webhook_subscriptions_created_at ON webhook_subscriptions(created_at);

            COMMIT;

            -- ROLLBACK SQL:
            -- DROP TABLE IF EXISTS webhook_subscriptions CASCADE;
