// AUTO-GENERATED by pzo_curriculum_gateway_generator.py — DO NOT EDIT MANUALLY
import { TenantContext } from '../middleware/auth/types';
import { CircuitBreaker } from '../middleware/resilience/circuit_breaker';
import Stripe from 'stripe';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY || '', {
  apiVersion: '2024-12-18.acacia',
  typescript: true,
});

const breaker = new CircuitBreaker('stripe-billing', {
  failureThreshold: 3, resetTimeoutMs: 60_000, halfOpenMaxAttempts: 2,
});

export class StripeBillingAdapter {
  async createCustomer(ctx: TenantContext, email: string, name: string, institutionId: string): Promise<string> {
    return breaker.execute(async () => {
      const customer = await stripe.customers.create({
        email,
        name,
        metadata: {
          institution_id: institutionId,
          actor_id: ctx.actorId,
          source: 'pointzeroonegame.com',
        },
      });
      return customer.id;
    });
  }

  async createSubscription(
    ctx: TenantContext,
    customerId: string,
    priceId: string,
    institutionId: string,
  ): Promise<{ subscriptionId: string; clientSecret: string | null }> {
    return breaker.execute(async () => {
      const subscription = await stripe.subscriptions.create({
        customer: customerId,
        items: [{ price: priceId }],
        payment_behavior: 'default_incomplete',
        expand: ['latest_invoice.payment_intent'],
        metadata: {
          institution_id: institutionId,
          actor_id: ctx.actorId,
        },
      });

      const invoice = subscription.latest_invoice as Stripe.Invoice;
      const paymentIntent = invoice?.payment_intent as Stripe.PaymentIntent | null;

      return {
        subscriptionId: subscription.id,
        clientSecret: paymentIntent?.client_secret || null,
      };
    });
  }

  async cancelSubscription(ctx: TenantContext, subscriptionId: string): Promise<void> {
    return breaker.execute(async () => {
      await stripe.subscriptions.cancel(subscriptionId);
    });
  }

  async getSubscription(ctx: TenantContext, subscriptionId: string): Promise<Stripe.Subscription> {
    return breaker.execute(async () => {
      return stripe.subscriptions.retrieve(subscriptionId);
    });
  }

  verifyWebhookSignature(payload: Buffer, signature: string): Stripe.Event {
    const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET;
    if (!webhookSecret) throw new Error('STRIPE_WEBHOOK_SECRET not configured');
    return stripe.webhooks.constructEvent(payload, signature, webhookSecret);
  }
}

export const stripeBillingAdapter = new StripeBillingAdapter();
