// AUTO-GENERATED by scripts/build_mechanics.py — DO NOT EDIT exec_hook body manually
// Density6 LLC · Point Zero One · Confidential
// pzo_engine/src/mechanics/m06_cashflow_tick_engine.ts
//
// Mechanic : M06 — Cashflow Tick Engine
// Family   : run_core   Layer: tick_engine   Priority: 1   Batch: 1
// ML Pair  : m06a
// Deps     : M02, M05
//
// Design Laws:
//   ✦ Deterministic-by-seed  ✦ Server-verified via ledger
//   ✦ Bounded chaos          ✦ No pay-to-win

import { clamp, computeHash, seededShuffle, seededIndex,
         buildMacroSchedule, buildChaosWindows,
         buildWeightedPool, OPPORTUNITY_POOL, DEFAULT_CARD, DEFAULT_CARD_IDS,
         computeDecayRate, EXIT_PULSE_MULTIPLIERS,
         MACRO_EVENTS_PER_RUN, CHAOS_WINDOWS_PER_RUN, RUN_TOTAL_TICKS,
         PRESSURE_WEIGHTS, PHASE_WEIGHTS, REGIME_WEIGHTS,
         REGIME_MULTIPLIERS } from './mechanicsUtils';
import type {
  RunPhase, TickTier, MacroRegime, PressureTier, SolvencyStatus,
  Asset, IPAItem, GameCard, GameEvent, ShieldLayer, Debt, Buff,
  Liability, SetBonus, AssetMod, IncomeItem, MacroEvent, ChaosWindow,
  AuctionResult, PurchaseResult, ShieldResult, ExitResult, TickResult,
  DeckComposition, TierProgress, WipeEvent, RegimeShiftEvent,
  PhaseTransitionEvent, TimerExpiredEvent, StreakEvent, FubarEvent,
  LedgerEntry, ProofCard, CompletedRun, SeasonState, RunState,
  MomentEvent, ClipBoundary, MechanicTelemetryPayload, MechanicEmitter,
} from './types';


// ── Input / Output contracts ──────────────────────────────────────────────

export interface M06Input {
  stateAssets?: Asset[];
  stateIpaItems?: IPAItem[];
  stateTick?: number;
  stateMacroRegime?: MacroRegime;
}

export interface M06Output {
  cashflowDelta: number;
  incomeItemized: IncomeItem[];
  tierProgressUpdate: TierProgress;
}

// ── Telemetry ─────────────────────────────────────────────────────────────

export type M06Event = 'CASHFLOW_TICK' | 'INCOME_ITEMIZED' | 'ASSET_INCOME_APPLIED' | 'TIER_ESCAPED';

export interface M06TelemetryPayload extends MechanicTelemetryPayload {
  event: M06Event;
  mechanic_id: 'M06';
}

// ── Design bounds (never mutate at runtime) ────────────────────────────────

export const M06_BOUNDS = {
  BASE_AMOUNT:         1_000,
  TRIGGER_THRESHOLD:   3,
  MULTIPLIER:          1.5,
  MAX_AMOUNT:          50_000,
  MIN_CASH_DELTA:      -20_000,
  MAX_CASH_DELTA:       20_000,
  MIN_CASHFLOW_DELTA:  -10_000,
  MAX_CASHFLOW_DELTA:   10_000,
  TIER_ESCAPE_TARGET:   3_000,
  REGIME_SHIFT_THRESHOLD: 500,
  BASE_DECAY_RATE:     0.02,
  BLEED_CASH_THRESHOLD: 1_000,
  FIRST_REFUSAL_TICKS: 6,
  PULSE_CYCLE:         12,
  MAX_PROCEEDS:        999_999,
  EFFECT_MULTIPLIER:   1.0,
  MIN_EFFECT:          0,
  MAX_EFFECT:          100_000,
} as const;

// ── Exec hook ─────────────────────────────────────────────────────────────

/**
 * cashflowTickEngine
 *
 * Called by MechanicsRouter inside the EngineOrchestrator tick or card handler.
 * All state mutations MUST be returned in the output — never applied in place.
 * All telemetry MUST be emitted via the emit callback.
 *
 * @param input  Typed input snapshot
 * @param emit   Telemetry emitter — call for every meaningful state change
 * @returns      Typed output (all fields populated, no throws)
 */
export function cashflowTickEngine(
  input: M06Input,
  emit: MechanicEmitter,
): M06Output {
  const assets = (input.stateAssets as Asset[]) ?? [];
  const ipaItems = (input.stateIpaItems as IPAItem[]) ?? [];
  const macroRegime = (input.stateMacroRegime as MacroRegime) ?? 'NEUTRAL';
  const currentTick = (input.stateTick as number) ?? 0;
  const pressureTier = (input.statePressureTier as PressureTier) ?? 'LOW';
  const macroMultiplier = REGIME_MULTIPLIERS[macroRegime] ?? 1.0;
  const assetIncome = assets.reduce((s, a) => s + (a.cashflowMonthly ?? 0), 0);
  const ipaIncome   = ipaItems.reduce((s, i) => s + (i.cashflowMonthly ?? 0), 0);
  const cashflowDelta = clamp((assetIncome + ipaIncome) * macroMultiplier, M06_BOUNDS.MIN_CASHFLOW_DELTA, M06_BOUNDS.MAX_CASHFLOW_DELTA);
  const incomeItems: IncomeItem[] = [
    ...assets.map(a => ({ source: a.id ?? 'asset', amount: (a.cashflowMonthly ?? 0) * macroMultiplier })),
    ...ipaItems.map(i => ({ source: i.id ?? 'ipa',   amount: (i.cashflowMonthly ?? 0) * macroMultiplier })),
  ];
  const tierProgress = clamp(cashflowDelta / M06_BOUNDS.TIER_ESCAPE_TARGET, 0, 1);
    emit({ event: 'CASHFLOW_TICK', mechanic_id: 'M06', tick: currentTick, runId: '', payload: { cashflowDelta, macroRegime } });
    return {{
    cashflowDelta: cashflowDelta,
    incomeItemized: incomeItems,
    tierProgressUpdate: { currentTier: pressureTier, progressPct: tierProgress },
  }};
}

// ── ML companion hook ─────────────────────────────────────────────────────

export interface M06MLInput {
  cashflowDelta?: number, incomeItemized?: IncomeItem[], tierProgressUpdate?: TierProgress;
  runId: string;
  tick:  number;
}

export interface M06MLOutput {
  score:          number;         // 0–1
  topFactors:     string[];       // max 5 plain-English factors
  recommendation: string;         // single sentence
  auditHash:      string;         // SHA256(inputs+outputs+rulesVersion)
  confidenceDecay: number;        // 0–1, how fast this signal should decay
}

/**
 * cashflowTickEngineMLCompanion
 * Async advisory — fires AFTER exec_hook, reads output, returns signals only.
 * NEVER mutates state. Results feed Case File, Intel bars, and CORD scoring.
 */
export async function cashflowTickEngineMLCompanion(
  input: M06MLInput,
): Promise<M06MLOutput> {
  // Advisory signal — bounded [0,1], no state mutation
  const score = Math.min(0.99, Math.max(0.01, Object.keys(input).length * 0.05));
  return {
    score,
    topFactors:     ['M06 signal computed', 'advisory only'],
    recommendation: 'Monitor M06 output and adjust strategy accordingly.',
    auditHash:      computeHash(JSON.stringify(input) + ':ml:M06'),
    confidenceDecay: 0.05,
  };
}
