// AUTO-GENERATED by scripts/build_mechanics.py — DO NOT EDIT exec_hook body manually
// Density6 LLC · Point Zero One · Confidential
// pzo_engine/src/mechanics/m137_mid_run_hotfix_lock_no_surprise_changes_inside_a_run.ts
//
// Mechanic : M137 — Mid-Run Hotfix Lock: No Surprise Changes Inside a Run
// Family   : ops   Layer: tick_engine   Priority: 1   Batch: 3
// ML Pair  : m137a
// Deps     : M02
//
// Design Laws:
//   ✦ Deterministic-by-seed  ✦ Server-verified via ledger
//   ✦ Bounded chaos          ✦ No pay-to-win

import { clamp, computeHash, seededShuffle, seededIndex,
         buildMacroSchedule, buildChaosWindows,
         buildWeightedPool, OPPORTUNITY_POOL, DEFAULT_CARD, DEFAULT_CARD_IDS,
         computeDecayRate, EXIT_PULSE_MULTIPLIERS,
         MACRO_EVENTS_PER_RUN, CHAOS_WINDOWS_PER_RUN, RUN_TOTAL_TICKS,
         PRESSURE_WEIGHTS, PHASE_WEIGHTS, REGIME_WEIGHTS,
         REGIME_MULTIPLIERS } from './mechanicsUtils';
import type {
  RunPhase, TickTier, MacroRegime, PressureTier, SolvencyStatus,
  Asset, IPAItem, GameCard, GameEvent, ShieldLayer, Debt, Buff,
  Liability, SetBonus, AssetMod, IncomeItem, MacroEvent, ChaosWindow,
  AuctionResult, PurchaseResult, ShieldResult, ExitResult, TickResult,
  DeckComposition, TierProgress, WipeEvent, RegimeShiftEvent,
  PhaseTransitionEvent, TimerExpiredEvent, StreakEvent, FubarEvent,
  LedgerEntry, ProofCard, CompletedRun, SeasonState, RunState,
  MomentEvent, ClipBoundary, MechanicTelemetryPayload, MechanicEmitter,
} from './types';


// ── Input / Output contracts ──────────────────────────────────────────────

export interface M137Input {
  activeRunId?: string;
  hotfixPayload?: HotfixPayload;
  runLockStatus?: unknown;
}

export interface M137Output {
  hotfixQueued: boolean;
  lockEnforced: boolean;
  hotfixAppliedPostRun: boolean;
}

// ── Telemetry ─────────────────────────────────────────────────────────────

export type M137Event = 'HOTFIX_QUEUED' | 'RUN_LOCK_ENFORCED' | 'HOTFIX_APPLIED';

export interface M137TelemetryPayload extends MechanicTelemetryPayload {
  event: M137Event;
  mechanic_id: 'M137';
}

// ── Design bounds (never mutate at runtime) ────────────────────────────────

export const M137_BOUNDS = {
  BASE_AMOUNT:         1_000,
  TRIGGER_THRESHOLD:   3,
  MULTIPLIER:          1.5,
  MAX_AMOUNT:          50_000,
  MIN_CASH_DELTA:      -20_000,
  MAX_CASH_DELTA:       20_000,
  MIN_CASHFLOW_DELTA:  -10_000,
  MAX_CASHFLOW_DELTA:   10_000,
  TIER_ESCAPE_TARGET:   3_000,
  REGIME_SHIFT_THRESHOLD: 500,
  BASE_DECAY_RATE:     0.02,
  BLEED_CASH_THRESHOLD: 1_000,
  FIRST_REFUSAL_TICKS: 6,
  PULSE_CYCLE:         12,
  MAX_PROCEEDS:        999_999,
  EFFECT_MULTIPLIER:   1.0,
  MIN_EFFECT:          0,
  MAX_EFFECT:          100_000,
} as const;

// ── Exec hook ─────────────────────────────────────────────────────────────

/**
 * midRunHotfixLockEnforcer
 *
 * Called by MechanicsRouter inside the EngineOrchestrator tick or card handler.
 * All state mutations MUST be returned in the output — never applied in place.
 * All telemetry MUST be emitted via the emit callback.
 *
 * @param input  Typed input snapshot
 * @param emit   Telemetry emitter — call for every meaningful state change
 * @returns      Typed output (all fields populated, no throws)
 */
export function midRunHotfixLockEnforcer(
  input: M137Input,
  emit: MechanicEmitter,
): M137Output {
  const currentTick = (input.stateTick as number) ?? 0;
  const nextTick = currentTick + 1;
  const timerExpired = nextTick >= RUN_TOTAL_TICKS;
  const progress = clamp(nextTick / RUN_TOTAL_TICKS, 0, 1);
  const newPhase: RunPhase = progress < 0.33 ? 'EARLY' : progress < 0.66 ? 'MID' : 'LATE';
  const phaseChanged = newPhase !== ((input.stateRunPhase as string) ?? 'EARLY');
    emit({ event: 'HOTFIX_QUEUED', mechanic_id: 'M137', tick: nextTick, runId: '', payload: { nextTick, newPhase, timerExpired } });
  
    return {{
    hotfixQueued: false,
    lockEnforced: true,
    hotfixAppliedPostRun: false,
  }};
}

// ── ML companion hook ─────────────────────────────────────────────────────

export interface M137MLInput {
  hotfixQueued?: boolean, lockEnforced?: boolean, hotfixAppliedPostRun?: boolean;
  runId: string;
  tick:  number;
}

export interface M137MLOutput {
  score:          number;         // 0–1
  topFactors:     string[];       // max 5 plain-English factors
  recommendation: string;         // single sentence
  auditHash:      string;         // SHA256(inputs+outputs+rulesVersion)
  confidenceDecay: number;        // 0–1, how fast this signal should decay
}

/**
 * midRunHotfixLockEnforcerMLCompanion
 * Async advisory — fires AFTER exec_hook, reads output, returns signals only.
 * NEVER mutates state. Results feed Case File, Intel bars, and CORD scoring.
 */
export async function midRunHotfixLockEnforcerMLCompanion(
  input: M137MLInput,
): Promise<M137MLOutput> {
  // Advisory signal — bounded [0,1], no state mutation
  const score = Math.min(0.99, Math.max(0.01, Object.keys(input).length * 0.05));
  return {
    score,
    topFactors:     ['M137 signal computed', 'advisory only'],
    recommendation: 'Monitor M137 output and adjust strategy accordingly.',
    auditHash:      computeHash(JSON.stringify(input) + ':ml:M137'),
    confidenceDecay: 0.05,
  };
}
