// AUTO-GENERATED by scripts/build_mechanics.py — DO NOT EDIT exec_hook body manually
// Density6 LLC · Point Zero One · Confidential
// pzo_engine/src/mechanics/m138_degraded_mode_server_load_shedding_without_breaking_runs.ts
//
// Mechanic : M138 — Degraded Mode: Server Load Shedding Without Breaking Runs
// Family   : ops   Layer: tick_engine   Priority: 1   Batch: 3
// ML Pair  : m138a
// Deps     : M02, M46
//
// Design Laws:
//   ✦ Deterministic-by-seed  ✦ Server-verified via ledger
//   ✦ Bounded chaos          ✦ No pay-to-win

import { clamp, computeHash, seededShuffle, seededIndex,
         buildMacroSchedule, buildChaosWindows,
         buildWeightedPool, OPPORTUNITY_POOL, DEFAULT_CARD, DEFAULT_CARD_IDS,
         computeDecayRate, EXIT_PULSE_MULTIPLIERS,
         MACRO_EVENTS_PER_RUN, CHAOS_WINDOWS_PER_RUN, RUN_TOTAL_TICKS,
         PRESSURE_WEIGHTS, PHASE_WEIGHTS, REGIME_WEIGHTS,
         REGIME_MULTIPLIERS } from './mechanicsUtils';
import type {
  RunPhase, TickTier, MacroRegime, PressureTier, SolvencyStatus,
  Asset, IPAItem, GameCard, GameEvent, ShieldLayer, Debt, Buff,
  Liability, SetBonus, AssetMod, IncomeItem, MacroEvent, ChaosWindow,
  AuctionResult, PurchaseResult, ShieldResult, ExitResult, TickResult,
  DeckComposition, TierProgress, WipeEvent, RegimeShiftEvent,
  PhaseTransitionEvent, TimerExpiredEvent, StreakEvent, FubarEvent,
  LedgerEntry, ProofCard, CompletedRun, SeasonState, RunState,
  MomentEvent, ClipBoundary, MechanicTelemetryPayload, MechanicEmitter,
} from './types';


// ── Input / Output contracts ──────────────────────────────────────────────

export interface M138Input {
  serverLoadMetric?: number;
  degradedModeConfig?: DegradedModeConfig;
  activeRuns?: boolean;
}

export interface M138Output {
  degradedModeActive: boolean;
  shedFeatures: string[];
  runPreserved: boolean;
}

// ── Telemetry ─────────────────────────────────────────────────────────────

export type M138Event = 'DEGRADED_MODE_ENTERED' | 'FEATURES_SHED' | 'DEGRADED_MODE_EXITED';

export interface M138TelemetryPayload extends MechanicTelemetryPayload {
  event: M138Event;
  mechanic_id: 'M138';
}

// ── Design bounds (never mutate at runtime) ────────────────────────────────

export const M138_BOUNDS = {
  BASE_AMOUNT:         1_000,
  TRIGGER_THRESHOLD:   3,
  MULTIPLIER:          1.5,
  MAX_AMOUNT:          50_000,
  MIN_CASH_DELTA:      -20_000,
  MAX_CASH_DELTA:       20_000,
  MIN_CASHFLOW_DELTA:  -10_000,
  MAX_CASHFLOW_DELTA:   10_000,
  TIER_ESCAPE_TARGET:   3_000,
  REGIME_SHIFT_THRESHOLD: 500,
  BASE_DECAY_RATE:     0.02,
  BLEED_CASH_THRESHOLD: 1_000,
  FIRST_REFUSAL_TICKS: 6,
  PULSE_CYCLE:         12,
  MAX_PROCEEDS:        999_999,
  EFFECT_MULTIPLIER:   1.0,
  MIN_EFFECT:          0,
  MAX_EFFECT:          100_000,
} as const;

// ── Exec hook ─────────────────────────────────────────────────────────────

/**
 * degradedModeLoadShedder
 *
 * Called by MechanicsRouter inside the EngineOrchestrator tick or card handler.
 * All state mutations MUST be returned in the output — never applied in place.
 * All telemetry MUST be emitted via the emit callback.
 *
 * @param input  Typed input snapshot
 * @param emit   Telemetry emitter — call for every meaningful state change
 * @returns      Typed output (all fields populated, no throws)
 */
export function degradedModeLoadShedder(
  input: M138Input,
  emit: MechanicEmitter,
): M138Output {
  const currentTick = (input.stateTick as number) ?? 0;
  const nextTick = currentTick + 1;
  const timerExpired = nextTick >= RUN_TOTAL_TICKS;
  const progress = clamp(nextTick / RUN_TOTAL_TICKS, 0, 1);
  const newPhase: RunPhase = progress < 0.33 ? 'EARLY' : progress < 0.66 ? 'MID' : 'LATE';
  const phaseChanged = newPhase !== ((input.stateRunPhase as string) ?? 'EARLY');
    emit({ event: 'DEGRADED_MODE_ENTERED', mechanic_id: 'M138', tick: nextTick, runId: '', payload: { nextTick, newPhase, timerExpired } });
  
    return {{
    degradedModeActive: (input.serverLoadMetric as number ?? 0) > 0.85,
    shedFeatures: (input.serverLoadMetric as number ?? 0) > 0.85 ? ['spectator','replay'] : [],
    runPreserved: true,
  }};
}

// ── ML companion hook ─────────────────────────────────────────────────────

export interface M138MLInput {
  degradedModeActive?: boolean, shedFeatures?: string[], runPreserved?: boolean;
  runId: string;
  tick:  number;
}

export interface M138MLOutput {
  score:          number;         // 0–1
  topFactors:     string[];       // max 5 plain-English factors
  recommendation: string;         // single sentence
  auditHash:      string;         // SHA256(inputs+outputs+rulesVersion)
  confidenceDecay: number;        // 0–1, how fast this signal should decay
}

/**
 * degradedModeLoadShedderMLCompanion
 * Async advisory — fires AFTER exec_hook, reads output, returns signals only.
 * NEVER mutates state. Results feed Case File, Intel bars, and CORD scoring.
 */
export async function degradedModeLoadShedderMLCompanion(
  input: M138MLInput,
): Promise<M138MLOutput> {
  // Advisory signal — bounded [0,1], no state mutation
  const score = Math.min(0.99, Math.max(0.01, Object.keys(input).length * 0.05));
  return {
    score,
    topFactors:     ['M138 signal computed', 'advisory only'],
    recommendation: 'Monitor M138 output and adjust strategy accordingly.',
    auditHash:      computeHash(JSON.stringify(input) + ':ml:M138'),
    confidenceDecay: 0.05,
  };
}
