// ═══════════════════════════════════════════════════════════════════════════════
// POINT ZERO ONE — src/mechanics/m42_guided_prompts:_opt_in_minimal.ts
// AUTO-GENERATED by scripts/build_mechanics.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/build_mechanics.py --force
//
// Mechanic : M42 — Guided Prompts: Opt-In Minimal
// Family   : onboarding
// Layer    : ui_component
// Priority : 2  Batch: 1
// ML Pair  : m42a
// Deps     : M41
//
// Density6 LLC · Point Zero One · Confidential · All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════════

// import type { M41Types } from './m41_...';

// ── Input contract ────────────────────────────────────────────────────────────
export interface M42Input {
  playeroptin: unknown;  // playerOptIn
  gamestate: unknown;  // gameState
  promptlibrary: unknown;  // promptLibrary
}

// ── Output contract ───────────────────────────────────────────────────────────
export interface M42Output {
  promptdisplayed: unknown;  // promptDisplayed
  promptdismissed: unknown;  // promptDismissed
  overlayconfig: unknown;  // overlayConfig
}

// ── Telemetry events ──────────────────────────────────────────────────────────
export type M42Event = 'PROMPT_SHOWN' | 'PROMPT_DISMISSED' | 'PROMPTS_DISABLED';

export interface M42TelemetryPayload {
  event: M42Event;
  mechanic_id: 'M42';
  tick: number;
  runId: string;
  payload: Record<string, unknown>;
}

// ── Design constants ──────────────────────────────────────────────────────────
export const M42_CONSTANTS = {
  MECHANIC_ID:  'M42',
  TITLE:        'Guided Prompts: Opt-In Minimal',
  FAMILY:       'onboarding',
  LAYER:        'ui_component',
  PRIORITY:      2,
  BATCH:         1,
  ML_PAIR:      'm42a',
  EXEC_HOOK:    'guidedPromptOverlay',
  DESIGN_LAWS: [
    'deterministic-by-seed',
    'server-verified-via-ledger',
    'bounded-chaos',
    'no-pay-to-win',
  ],
} as const;

// ── Exec hook ─────────────────────────────────────────────────────────────────
/**
 * guidedPromptOverlay
 *
 * Called by the EngineOrchestrator (or appropriate engine) on each
 * relevant tick/event. All state mutations MUST be returned in the
 * output — never applied in place. All telemetry MUST be emitted
 * via the EventBus, never fired directly.
 *
 * @param input  - Typed input snapshot (see M42Input)
 * @param emit   - Telemetry emitter — call for every meaningful state change
 * @returns      - Typed output (see M42Output)
 */
export function guidedPromptOverlay(
  input: M42Input,
  emit: (payload: M42TelemetryPayload) => void,
): M42Output {
  // ── TODO: implement M42 — Guided Prompts: Opt-In Minimal ───────────────────────────────
  //
  // Implementation checklist:
  // □ handle: playerOptIn
  // □ handle: gameState
  // □ handle: promptLibrary
  //
  // Emit at minimum: PROMPT_SHOWN
  //
  // Required telemetry shape:
  //   emit({ event: '...', mechanic_id: 'M42', tick: <tick>, runId: <runId>, payload: {} });
  //
  // ─────────────────────────────────────────────────────────────────────────
  throw new Error('M42 (guidedPromptOverlay) is not yet implemented.');
}

// ── ML companion hook ─────────────────────────────────────────────────────────
/**
 * ML companion: m42a
 * Async — fires after exec_hook, reads output, returns advisory signals only.
 * NEVER mutates state. Results feed Case File, Intel bars, and CORD scoring.
 */
export type M42MLInput = M42Output & { runId: string; tick: number };
export interface M42MLOutput {
  score: number;           // 0–1
  topFactors: string[];    // max 5 plain-English factors
  recommendation: string;  // single sentence
  auditHash: string;       // SHA256(inputs + outputs + rulesVersion)
}

export async function guidedPromptOverlayMLCompanion(
  _input: M42MLInput,
): Promise<M42MLOutput> {
  // TODO: call ML inference endpoint for m42a
  throw new Error('M42 ML companion (m42a) is not yet implemented.');
}
