// ═══════════════════════════════════════════════════════════════════════════════
// POINT ZERO ONE — src/mechanics/m80_contract_receipt_cards:_portable_verifia.ts
// AUTO-GENERATED by scripts/build_mechanics.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/build_mechanics.py --force
//
// Mechanic : M80 — Contract Receipt Cards: Portable Verifiable Coop Proofs
// Family   : coop_governance
// Layer    : api_endpoint
// Priority : 2  Batch: 2
// ML Pair  : m80a
// Deps     : M50, M26
//
// Density6 LLC · Point Zero One · Confidential · All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════════

// import type { M50Types } from './m50_...';
// import type { M26Types } from './m26_...';

// ── Input contract ────────────────────────────────────────────────────────────
export interface M80Input {
  contractid: unknown;  // contractId
  contractoutcome: unknown;  // contractOutcome
  proofhash: unknown;  // proofHash
}

// ── Output contract ───────────────────────────────────────────────────────────
export interface M80Output {
  receiptcard: unknown;  // receiptCard
  portableproof: unknown;  // portableProof
  shareablereceipturl: unknown;  // shareableReceiptUrl
}

// ── Telemetry events ──────────────────────────────────────────────────────────
export type M80Event = 'RECEIPT_CARD_ISSUED' | 'RECEIPT_SHARED' | 'RECEIPT_VERIFIED';

export interface M80TelemetryPayload {
  event: M80Event;
  mechanic_id: 'M80';
  tick: number;
  runId: string;
  payload: Record<string, unknown>;
}

// ── Design constants ──────────────────────────────────────────────────────────
export const M80_CONSTANTS = {
  MECHANIC_ID:  'M80',
  TITLE:        'Contract Receipt Cards: Portable Verifiable Coop Proofs',
  FAMILY:       'coop_governance',
  LAYER:        'api_endpoint',
  PRIORITY:      2,
  BATCH:         2,
  ML_PAIR:      'm80a',
  EXEC_HOOK:    'contractReceiptCardIssuer',
  DESIGN_LAWS: [
    'deterministic-by-seed',
    'server-verified-via-ledger',
    'bounded-chaos',
    'no-pay-to-win',
  ],
} as const;

// ── Exec hook ─────────────────────────────────────────────────────────────────
/**
 * contractReceiptCardIssuer
 *
 * Called by the EngineOrchestrator (or appropriate engine) on each
 * relevant tick/event. All state mutations MUST be returned in the
 * output — never applied in place. All telemetry MUST be emitted
 * via the EventBus, never fired directly.
 *
 * @param input  - Typed input snapshot (see M80Input)
 * @param emit   - Telemetry emitter — call for every meaningful state change
 * @returns      - Typed output (see M80Output)
 */
export function contractReceiptCardIssuer(
  input: M80Input,
  emit: (payload: M80TelemetryPayload) => void,
): M80Output {
  // ── TODO: implement M80 — Contract Receipt Cards: Portable Verifiable Coop Proofs ───────────────────────────────
  //
  // Implementation checklist:
  // □ handle: contractId
  // □ handle: contractOutcome
  // □ handle: proofHash
  //
  // Emit at minimum: RECEIPT_CARD_ISSUED
  //
  // Required telemetry shape:
  //   emit({ event: '...', mechanic_id: 'M80', tick: <tick>, runId: <runId>, payload: {} });
  //
  // ─────────────────────────────────────────────────────────────────────────
  throw new Error('M80 (contractReceiptCardIssuer) is not yet implemented.');
}

// ── ML companion hook ─────────────────────────────────────────────────────────
/**
 * ML companion: m80a
 * Async — fires after exec_hook, reads output, returns advisory signals only.
 * NEVER mutates state. Results feed Case File, Intel bars, and CORD scoring.
 */
export type M80MLInput = M80Output & { runId: string; tick: number };
export interface M80MLOutput {
  score: number;           // 0–1
  topFactors: string[];    // max 5 plain-English factors
  recommendation: string;  // single sentence
  auditHash: string;       // SHA256(inputs + outputs + rulesVersion)
}

export async function contractReceiptCardIssuerMLCompanion(
  _input: M80MLInput,
): Promise<M80MLOutput> {
  // TODO: call ML inference endpoint for m80a
  throw new Error('M80 ML companion (m80a) is not yet implemented.');
}
