// ═══════════════════════════════════════════════════════════════════════════════
// POINT ZERO ONE — src/mechanics/m94_inline_glossary_pings:_micro_explain_wit.ts
// AUTO-GENERATED by scripts/build_mechanics.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/build_mechanics.py --force
//
// Mechanic : M94 — Inline Glossary Pings: Micro-Explain Without Handholding
// Family   : onboarding_expert
// Layer    : ui_component
// Priority : 2  Batch: 2
// ML Pair  : m94a
// Deps     : M42
//
// Density6 LLC · Point Zero One · Confidential · All Rights Reserved
// ═══════════════════════════════════════════════════════════════════════════════

// import type { M42Types } from './m42_...';

// ── Input contract ────────────────────────────────────────────────────────────
export interface M94Input {
  termencountered: unknown;  // termEncountered
  playeroptin: unknown;  // playerOptIn
  glossarylibrary: unknown;  // glossaryLibrary
}

// ── Output contract ───────────────────────────────────────────────────────────
export interface M94Output {
  glossaryping: unknown;  // glossaryPing
  explanationshown: unknown;  // explanationShown
  pingdismissed: unknown;  // pingDismissed
}

// ── Telemetry events ──────────────────────────────────────────────────────────
export type M94Event = 'GLOSSARY_PING_SHOWN' | 'GLOSSARY_PING_DISMISSED' | 'TERM_EXPLAINED';

export interface M94TelemetryPayload {
  event: M94Event;
  mechanic_id: 'M94';
  tick: number;
  runId: string;
  payload: Record<string, unknown>;
}

// ── Design constants ──────────────────────────────────────────────────────────
export const M94_CONSTANTS = {
  MECHANIC_ID:  'M94',
  TITLE:        'Inline Glossary Pings: Micro-Explain Without Handholding',
  FAMILY:       'onboarding_expert',
  LAYER:        'ui_component',
  PRIORITY:      2,
  BATCH:         2,
  ML_PAIR:      'm94a',
  EXEC_HOOK:    'inlineGlossaryPing',
  DESIGN_LAWS: [
    'deterministic-by-seed',
    'server-verified-via-ledger',
    'bounded-chaos',
    'no-pay-to-win',
  ],
} as const;

// ── Exec hook ─────────────────────────────────────────────────────────────────
/**
 * inlineGlossaryPing
 *
 * Called by the EngineOrchestrator (or appropriate engine) on each
 * relevant tick/event. All state mutations MUST be returned in the
 * output — never applied in place. All telemetry MUST be emitted
 * via the EventBus, never fired directly.
 *
 * @param input  - Typed input snapshot (see M94Input)
 * @param emit   - Telemetry emitter — call for every meaningful state change
 * @returns      - Typed output (see M94Output)
 */
export function inlineGlossaryPing(
  input: M94Input,
  emit: (payload: M94TelemetryPayload) => void,
): M94Output {
  // ── TODO: implement M94 — Inline Glossary Pings: Micro-Explain Without Handholding ───────────────────────────────
  //
  // Implementation checklist:
  // □ handle: termEncountered
  // □ handle: playerOptIn
  // □ handle: glossaryLibrary
  //
  // Emit at minimum: GLOSSARY_PING_SHOWN
  //
  // Required telemetry shape:
  //   emit({ event: '...', mechanic_id: 'M94', tick: <tick>, runId: <runId>, payload: {} });
  //
  // ─────────────────────────────────────────────────────────────────────────
  throw new Error('M94 (inlineGlossaryPing) is not yet implemented.');
}

// ── ML companion hook ─────────────────────────────────────────────────────────
/**
 * ML companion: m94a
 * Async — fires after exec_hook, reads output, returns advisory signals only.
 * NEVER mutates state. Results feed Case File, Intel bars, and CORD scoring.
 */
export type M94MLInput = M94Output & { runId: string; tick: number };
export interface M94MLOutput {
  score: number;           // 0–1
  topFactors: string[];    // max 5 plain-English factors
  recommendation: string;  // single sentence
  auditHash: string;       // SHA256(inputs + outputs + rulesVersion)
}

export async function inlineGlossaryPingMLCompanion(
  _input: M94MLInput,
): Promise<M94MLOutput> {
  // TODO: call ML inference endpoint for m94a
  throw new Error('M94 ML companion (m94a) is not yet implemented.');
}
