// AUTO-GENERATED by pzo_curriculum_gateway_generator.py — DO NOT EDIT MANUALLY
import { Request, Response, NextFunction } from 'express';

export function withTimeout(ms: number) {
  return (req: Request, res: Response, next: NextFunction): void => {
    const timer = setTimeout(() => {
      if (!res.headersSent) {
        res.status(504).json({
          ok: false,
          requestId: req.tenantContext?.requestId || 'unknown',
          error: { code: 'GATEWAY_TIMEOUT', message: `Request timed out after ${ms}ms` },
        });
      }
    }, ms);

    res.on('finish', () => clearTimeout(timer));
    res.on('close', () => clearTimeout(timer));

    next();
  };
}
