- Creates an HTTP server that listens on port 3000 and serves a single endpoint (/) with a response of "Hello, World!".
- Sets up a test suite with `describe`, `before`, `it`, and `after` functions.
- Sends 100 requests concurrently to the server using the `supertest` library.
- Uses `chai.assert` to check that the responses are all equal to "Hello, World!".
- Closes the server in the `after` function when the tests are complete.
