- Simulate normal traffic by sending 1000 requests with random URLs and methods.
- Simulate stress traffic by sending 10 concurrent requests per second for 10 seconds, testing the app's ability to handle high loads.
- Simulate chaos traffic by adding random delays between requests while still maintaining a high load, testing the app's resilience under unpredictable conditions.
