- A fuzz testing harness using the `fuzzystream` library.
- A simulator for executing actions (represented by the `Simulator` class).
- A set of mutations to be applied during fuzz testing.
- Function to run a test with an input and handle errors.
- Running the fuzzer for a specified number of iterations.
- Calculating the percentage of passed tests based on the number of iterations and errors.
- Asserting that there were no errors during the fuzz testing (optional, removed in CI environments).
