- A Socket.io server with multiple namespaces (one for each active session).
- Client connections, disconnections, and message sending are handled.
- The list of active sessions is kept and updated dynamically as clients join or leave.
